/* Chinese — 简体中文
   Question bank translation. Keyed by question id; options are
   pipe-separated and stay in the English source order.
   UK proper nouns, institutions and official terms are left in
   English, glossed in Simplified Chinese on first use where it helps. */

export default {

  /* ---------- CHAPTER 1-3 (core) ---------- */
  1: ["以下哪一项是英国生活的基本原则？", "法治|义务兵役制|全民统一的国教|政府控制新闻界", "基本原则包括民主、法治、个人自由、对不同信仰和religion的宽容，以及参与社区生活。"],
  2: ["以下哪两项是对UK居民的期望？（请选择两个答案）", "照顾好自己和家人|公平对待他人|每周前往礼拜场所|加入某个政党", "责任包括遵守法律、尊重他人权利、公平待人、照顾自己和家人，以及爱护自己居住的社区。"],
  3: ["Life in the UK考试可以用哪些语言参加？", "英语、Welsh或Scottish Gaelic|仅英语|任何欧盟官方语言|英语或法语", "该考试可用英语、Welsh或Scottish Gaelic参加。"],
  4: ["在公民宣誓仪式上，新公民除宣誓效忠外还要做什么？", "承诺尊重UK的权利、自由与法律|承诺加入武装部队|向慈善机构捐款|正式放弃其他所有国籍", "新公民向君主宣誓效忠，并承诺尊重UK的权利、自由与法律。"],
  5: ["这句话是对还是错？UK保障信仰与宗教自由。", "对|错", "信仰与宗教自由是UK每个人共享的权利与自由之一。"],
  6: ["以下哪一项不是UK每个人共享的权利或自由？", "不缴税的权利|获得公正审判的权利|免受不公正歧视|言论自由", "缴税是一项责任，而非自由。权利包括言论自由、信仰自由、公正审判和免受不公正歧视。"],
  7: ["公民宣誓仪式通常在哪里举行？", "由地方政府（local authority）安排|在Houses of Parliament|在王室宫殿|在申请人家中", "地方政府安排公民宣誓仪式，通常在申请获批后三个月内举行。"],
  8: ["永久居留或入籍申请人通常必须证明哪两点？（请选择两个答案）", "能够说和读英语|对UK生活有良好了解|在UK拥有房产|曾在London居住", "申请人必须证明自己能说能读英语，并对UK生活有良好了解。"],
  9: ["参与社区生活最恰当的描述是什么？", "英国生活的一项基本原则|所有居民的法定义务|只有公民才能做的事|就业的一项条件", "参与社区生活被列为英国生活的基本原则之一。"],
  10: ["这句话是对还是错？UK的每个人都有尊重并遵守法律的义务。", "对|错", "尊重并遵守法律是每位UK居民的基本责任。"],
  11: ["UK是一个民主国家。这意味着什么？", "权力属于人民或其选出的代表|权力仅属于君主|权力属于法院|权力属于军队", "在民主制度中，权力属于人民，或直接行使，或通过选出的代表行使。"],
  12: ["以下哪一项是责任而非权利？", "爱护自己居住地的环境|参与选举政府|免受不公正歧视|获得公正审判", "爱护自己居住的社区和环境是在UK生活的责任之一。"],
  13: ["United Kingdom由几个国家组成？", "四个|两个|三个|五个", "UK由England、Scotland、Wales和Northern Ireland组成。"],
  14: ["哪些国家共同构成Great Britain？", "England、Scotland和Wales|England、Scotland和Northern Ireland|仅England和Wales|UK的全部四个国家", "Great Britain仅指England、Scotland和Wales。UK还包括Northern Ireland。"],
  15: ["以下哪两个是Crown dependencies，并不属于UK？（请选择两个答案）", "The Channel Islands|The Isle of Man|The Isle of Wight|Anglesey", "Channel Islands和Isle of Man拥有自己的政府；它们是Crown dependencies，不属于UK。"],
  16: ["以下哪一个是英国海外领地？", "The Falkland Islands|The Isle of Man|Jersey|Guernsey", "Falkland Islands和St Helena等海外领地与UK相关联，但不属于UK。"],
  17: ["Wales的首府是哪座城市？", "Cardiff|Swansea|Newport|Bangor", "Cardiff是Wales的首府；Senedd（威尔士议会）在Cardiff Bay开会。"],
  18: ["Northern Ireland的首府是哪座城市？", "Belfast|Londonderry|Dublin|Armagh", "Belfast是Northern Ireland的首府。Northern Ireland Assembly在Belfast的Stormont开会。"],
  19: ["这句话是对还是错？Northern Ireland是Great Britain的一部分。", "错|对", "Northern Ireland是UK的一部分，但Great Britain只指England、Scotland和Wales。"],
  20: ["UK的哪三个地区设有权力下放（devolved）的行政机构？", "Scotland、Wales和Northern Ireland|England、Scotland和Wales|Scotland、England和Northern Ireland|Wales、England和Northern Ireland", "Scotland、Wales和Northern Ireland各有一个权力下放的政府，部分权力由Westminster移交。"],
  21: ["最早居住在Britain的人是什么人？", "狩猎采集者|农民|商人|士兵", "Britain最早的居民是狩猎采集者，他们随气候变化而来去。"],
  22: ["连接Britain与欧洲大陆的陆桥大约在多久以前被淹没？", "约10,000年前|约1,000年前|约100,000年前|约500年前", "约10,000年前通往大陆的陆桥被海水淹没，Britain从此永久成为岛屿。"],
  23: ["Orkney的哪处史前遗址是北欧保存最完好的石器时代村落之一？", "Skara Brae|Stonehenge|Maiden Castle|Sutton Hoo", "Orkney的Skara Brae为考古学家提供了石器时代生活的详尽图景。"],
  24: ["Dorset的Maiden Castle是哪类遗址的实例？", "铁器时代的山丘堡垒|罗马别墅|诺曼城堡|维京定居点", "Maiden Castle是一座大型铁器时代山丘堡垒。青铜时代的人们还建造圆形房屋和墓丘。"],
  25: ["Julius Caesar在哪一年对Britain发动了一次失败的入侵？", "55 BC|AD 43|AD 122|AD 410", "Caesar在55 BC的突袭失败了。成功的罗马入侵发生在AD 43，由皇帝Claudius发动。"],
  26: ["哪位部落首领领导了反抗罗马人的起义，并在Westminster Bridge上立有雕像？", "Boudicca|Caratacus|Kenneth MacAlpin|Alfred the Great", "England东部Iceni部落的女王Boudicca发动了一场著名的反罗马统治起义。"],
  27: ["Hadrian's Wall为何而建？", "为抵御北方的Picts等部落|为标示与Wales的边界|为抵御维京人的袭击|为保护London", "皇帝Hadrian于AD 122下令修筑此墙，以守护罗马不列颠的北部边疆。"],
  28: ["罗马军队在哪一年撤离Britain？", "AD 410|AD 43|AD 789|AD 1066", "罗马人于AD 410撤退，以保卫帝国的其他地区。"],
  29: ["罗马人离开后，哪些民族入侵了Britain？", "Jutes、Angles和Saxons|Normans和Franks|仅Picts和Scots|西班牙人和葡萄牙人", "Anglo-Saxons——Jutes、Angles和Saxons——来自北欧，在Britain定居。"],
  30: ["East Anglia的Sutton Hoo是谁的墓葬地？", "一位Anglo-Saxon国王|一位罗马将军|一位维京首领|一位诺曼骑士", "Sutton Hoo的船葬被认为属于一位Anglo-Saxon国王或伟大战士。"],
  31: ["谁率领来自罗马的传教团使Anglo-Saxons皈依基督教，并成为首任Archbishop of Canterbury？", "St Augustine|St Columba|St Patrick|St David", "St Augustine于597年抵达，成为首任Archbishop of Canterbury。St Columba则在Iona创建了一座修道院。"],
  32: ["维京人首次袭击Britain是在哪一年？", "AD 789|AD 410|AD 1066|AD 1215", "维京人于AD 789首次前来劫掠沿海城镇，后来在Britain部分地区定居。"],
  33: ["哪位Anglo-Saxon国王击败了维京人并统一了盎格鲁-撒克逊各王国？", "Alfred the Great|Harold|Cnut|Ethelred", "国王Alfred the Great击败了维京人，尽管他们仍控制着东部和北部的Danelaw。"],
  34: ["谁统一了苏格兰各王国并成为Scotland的第一位国王？", "Kenneth MacAlpin|Robert the Bruce|William Wallace|Macbeth", "Kenneth MacAlpin将Picts和Scots统一为一个王国。"],

  /* ---------- CHAPTER 3 (core, continued) ---------- */
  35: ["哪场战役发生在1066年？", "The Battle of Hastings|The Battle of Bosworth Field|The Battle of Bannockburn|The Battle of Agincourt", "1066年在Hastings，Normandy公爵William击败了国王Harold——这是England最后一次被外敌成功入侵。"],
  36: ["Bayeux Tapestry是什么？", "一幅描绘诺曼征服England的刺绣|一份土地所有权记录|一份王室权利宪章|一幅中世纪Britain地图", "Bayeux Tapestry至今仍在France展出，纪念Battle of Hastings和诺曼征服。"],
  37: ["Domesday Book是什么？", "对England城镇、村庄与土地产业的普查|一部宗教法典|英格兰国王名录|一部诗集", "William于1086年下令编纂Domesday Book，记录England各地土地与牲畜的归属。"],
  38: ["哪位英格兰国王征服了Wales，并修建了Conwy和Caernarfon等城堡？", "Edward I|Henry V|William I|Richard III", "到1284年，Edward I通过Statute of Rhuddlan吞并了Wales，并修建了一圈宏伟城堡。"],
  39: ["Robert the Bruce在1314年的哪场战役中击败了英格兰人？", "Bannockburn|Culloden|Agincourt|Naseby", "1314年，Robert the Bruce率领的苏格兰人在Bannockburn获胜，使Scotland数百年保持独立。"],
  40: ["哪位英格兰国王在1415年赢得了Battle of Agincourt？", "Henry V|Henry VIII|Edward III|Richard II", "Henry V在Agincourt的胜利发生在对France的Hundred Years War期间。"],
  41: ["与France的Hundred Years War于1453年结束，England保留了哪座城镇？", "Calais|Paris|Rouen|Bordeaux", "England失去了除Calais港以外的全部法国领地；Calais本身也于1558年失守。"],
  42: ["1348年的Black Death中，England大约多少人口死亡？", "三分之一|十分之一|一半|四分之三", "Black Death夺去了England约三分之一人口的生命，也重创了Scotland和Wales。"],
  43: ["Magna Carta是什么？", "1215年达成的、限制国王权力的宪章|第一部英文圣经|与France的条约|土地产业记录", "国王John于1215年被迫接受Magna Carta（《大宪章》），确立了国王同样受法律约束。"],
  44: ["Wars of the Roses在哪两个家族之间展开？", "Lancaster与York|Tudor与Stuart|Normandy与Anjou|Wessex与Mercia", "Lancaster家族（红玫瑰）与York家族（白玫瑰）自1455年至1485年争夺王位。"],
  45: ["1485年的哪场战役结束了Wars of the Roses？", "The Battle of Bosworth Field|The Battle of Hastings|The Battle of the Boyne|The Battle of Marston Moor", "Richard III在Bosworth Field阵亡，Henry Tudor成为Henry VII，开创了Tudor王朝。"],
  46: ["谁在1476年于England建立了第一家印刷所？", "William Caxton|Geoffrey Chaucer|Thomas Cromwell|Robert Burns", "William Caxton将印刷术带到England，使书籍得以广泛流传。"],
  47: ["The Canterbury Tales是谁写的？", "Geoffrey Chaucer|William Shakespeare|John Milton|Robert Burns", "Chaucer的Canterbury Tales是一部描写一群前往Canterbury的朝圣者的诗集。"],
  48: ["Henry VIII有几位妻子？", "六位|四位|两位|八位", "Catherine of Aragon、Anne Boleyn、Jane Seymour、Anne of Cleves、Catherine Howard和Catherine Parr——离婚、斩首、去世、离婚、斩首、幸存。"],
  49: ["Henry VIII为何脱离罗马教会？", "教皇拒绝废除他与Catherine of Aragon的婚姻|他想入侵France|他想提高税收|他皈依了犹太教", "Henry创立Church of England并自任首领，以便再婚，由此开启了英格兰宗教改革。"],
  50: ["哪位女王因迫害新教徒而被称为'Bloody Mary'？", "Mary I|Mary Queen of Scots|Elizabeth I|Queen Anne", "Henry VIII之女Mary I是虔诚的天主教徒，处决了许多新教徒。"],
  51: ["Spanish Armada在哪一年被击败？", "1588|1485|1666|1215", "1588年，英格兰舰队击败了Philip II派来入侵England的Spanish Armada。"],
  52: ["William Shakespeare出生在哪里？", "Stratford-upon-Avon|London|Canterbury|Edinburgh", "Shakespeare出生于Stratford-upon-Avon，后来在London的Globe剧院工作。"],
  53: ["谁在1603年成为England、Wales和Ireland的国王，同时还是Scotland的国王？", "Scotland的James VI（England的James I）|Charles I|Henry VII|William III", "1603年的Union of the Crowns使England和Scotland同属一位君主，但两国仍各自独立。"],
  54: ["在English Civil War中，国王的支持者被称为什么？", "Cavaliers|Roundheads|Jacobites|Whigs", "保王派Cavaliers自1642年起与议会派Roundheads交战。"],
  55: ["Charles I在哪一年被处决？", "1649|1660|1666|1688", "Charles I于1649年被处决，England成为称作Commonwealth的共和国。"],
  56: ["Oliver Cromwell采用了什么头衔？", "Lord Protector|England国王|Lord Chancellor|Prime Minister", "Cromwell以Lord Protector的身份统治，直至1658年去世；其子Richard无力治理。"],
  57: ["君主制在哪一年随Charles II而恢复？", "1660|1649|1688|1707", "议会于1660年邀请Charles II回国，这一事件被称为Restoration。"],
  58: ["1660年代哪两场灾难袭击了London？（请选择两个答案）", "The Great Plague|The Great Fire|The Black Death|The Spanish Armada", "Great Plague发生于1665年，Great Fire of London发生于1666年。"],
  59: ["1688年的Glorious Revolution使哪位统治者登上王位？", "William of Orange|Charles II|George I|Oliver Cromwell", "William of Orange与其妻Mary（James II之女）在England未经战事便登上王位。"],
  60: ["1689年的Bill of Rights确立了什么？", "对君主权力的限制以及定期召开议会的必要|所有成年人的选举权|免于纳税|The Church of England", "Bill of Rights确认君主须获议会同意，并要求定期召开议会。"],
  61: ["1707年的Act of Union创建了哪个王国？", "The Kingdom of Great Britain|The United Kingdom of Great Britain and Ireland|The Commonwealth|England与Wales王国", "Scotland和England在同一个议会下联合，组成Kingdom of Great Britain。"],
  62: ["谁通常被视为Great Britain的第一位Prime Minister？", "Sir Robert Walpole|William Pitt|Winston Churchill|The Duke of Wellington", "Sir Robert Walpole自1721年任职至1742年，被视为第一位Prime Minister。"],
  63: ["Jacobites在1746年的哪场战役中被击败？", "Culloden|Bannockburn|Naseby|Bosworth Field", "Bonnie Prince Charlie的军队在Culloden被击溃；他随后逃往欧洲。"],
  64: ["Adam Smith和David Hume是什么运动的代表人物？", "The Scottish Enlightenment|工业革命|宗教改革|The Restoration", "启蒙运动在政治、哲学与科学上产生了新思想，其中许多来自苏格兰思想家。"],
  65: ["谁改良了为工业革命提供动力的蒸汽机？", "James Watt|Richard Arkwright|Isaac Newton|George Stephenson", "苏格兰人James Watt改良了蒸汽机，使其能够驱动工厂和矿井中的机械。"],
  66: ["议会在哪一年废除了英国船只上的奴隶贸易？", "1807|1833|1776|1215", "这项贸易于1807年废除；1833年的Emancipation Act则废除了整个British Empire的奴隶制。"],
  67: ["哪位议员成功地推动了反对奴隶贸易的运动？", "William Wilberforce|Robert Walpole|William Gladstone|Isambard Kingdom Brunel", "福音派基督徒William Wilberforce领导了议会中的反奴隶制运动。"],
  68: ["Admiral Nelson在1805年的哪场海战中阵亡？", "Trafalgar|Jutland|The Nile|Dunkirk", "Nelson在Trafalgar阵亡；其旗舰HMS Victory保存于Portsmouth，其纪念柱矗立在Trafalgar Square。"],

  /* ---------- CHAPTER 3/4 (core) ---------- */
  69: ["谁指挥了1815年在Waterloo击败Napoleon的英军？", "The Duke of Wellington|Admiral Nelson|Sir Robert Walpole|Oliver Cromwell", "后来出任Prime Minister的Duke of Wellington被称为铁公爵。"],
  70: ["女王Victoria在位多久？", "从1837年到1901年|从1801年到1837年|从1901年到1936年|从1760年到1820年", "Victoria于1837年18岁登基，在位64年，这是工业与帝国大扩张的时期。"],
  71: ["Florence Nightingale因在哪场战争中的工作而闻名？", "The Crimean War|The First World War|The Boer War|The Hundred Years War", "她在Crimean War期间于Scutari护理伤员，后来在London的St Thomas' Hospital创办了护士学校。"],
  72: ["谁在1889年创立了Women's Franchise League，后来领导了suffragettes？", "Emmeline Pankhurst|Florence Nightingale|Mary Seacole|Elizabeth Fry", "Emmeline Pankhurst为女性选举权而奔走；该运动采取了日益激进的手段。"],
  73: ["女性在哪一年获得与男性同龄的选举权？", "1928|1918|1945|1969", "拥有财产的30岁以上女性于1918年获得选举权；1928年起女性可在21岁投票，与男性相同。"],
  74: ["哪一事件引发了First World War？", "Archduke Franz Ferdinand遇刺|入侵波兰|Lusitania号沉没|俄国革命", "奥匈帝国的Archduke于1914年在Sarajevo遇刺。"],
  75: ["1916年Battle of the Somme首日，英军伤亡约为多少？", "60,000|6,000|600|600,000", "Somme是First World War中最血腥的战役之一。"],
  76: ["First World War在哪一天上午11时结束？", "11 November 1918|8 May 1945|1 September 1939|6 June 1944", "停战协定在第十一个月第十一天的第十一小时生效。"],
  77: ["1922年Ireland被分割。南部成立了什么？", "The Irish Free State|The Republic of Ulster|The Kingdom of Ireland|The Irish Commonwealth", "北部六郡留在UK，国家因此更名为United Kingdom of Great Britain and Northern Ireland。"],
  78: ["谁在1940年出任Prime Minister，并领导英国度过Second World War的大部分时期？", "Winston Churchill|Neville Chamberlain|Clement Attlee|David Lloyd George", "Churchill于1940年成为Prime Minister，以战时演说闻名。"],
  79: ["1940年在Dunkirk发生了什么？", "逾300,000名士兵从France撤离，许多人靠小船获救|赢得了一场大规模海战|英军在Normandy登陆|RAF击败了德国空军", "数百艘民用船只协助从Dunkirk海滩救出英法士兵。"],
  80: ["1940年的Battle of Britain主要由哪支部队进行？", "The Royal Air Force|The Royal Navy|陆军|The Home Guard", "RAF的Spitfire和Hurricane战斗机击败了德国空军，阻止了入侵。"],
  81: ["盟军在D-Day于哪一天在Normandy登陆？", "6 June 1944|8 May 1945|3 September 1939|11 November 1918", "D-Day登陆开启了将西欧从纳粹占领中解放的进程。"],
  82: ["标志欧洲胜利的VE Day在哪一天纪念？", "8 May 1945|6 June 1944|11 November 1918|1 January 1945", "欧洲战事于8 May 1945结束；日本于1945年August投降。"],
  83: ["谁在1928年发现了penicillin？", "Sir Alexander Fleming|Sir Frank Whittle|Alan Turing|Sir Isaac Newton", "苏格兰科学家Alexander Fleming发现了penicillin，后被开发为抗生素。"],
  84: ["促成现代福利国家的报告是谁撰写的？", "William Beveridge|Clement Attlee|Aneurin Bevan|Winston Churchill", "1942年的Beveridge Report提出了'从摇篮到坟墓'的社会保障方案。"],
  85: ["谁在1948年主导创建了National Health Service？", "Aneurin Bevan|William Beveridge|Winston Churchill|Margaret Thatcher", "卫生大臣Aneurin Bevan启动了NHS，为所有人提供在使用时免费的医疗服务。"],
  86: ["1948年抵达的Empire Windrush号载来了何处的工人？", "The West Indies|India|Ireland|波兰", "战后劳动力短缺促使英国邀请来自West Indies、后来还有India和Pakistan的工人。"],
  87: ["India、Pakistan和Ceylon（Sri Lanka）在哪一年独立？", "1947|1922|1966|1973", "这些国家的独立开启了British Empire的快速非殖民化。"],
  88: ["UK在哪一年加入欧洲经济共同体？", "1973|1957|1969|1992", "UK于1973年加入EEC，并于31 January 2020退出欧盟。"],
  89: ["UK的第一位女性Prime Minister是谁？", "Margaret Thatcher|Theresa May|Emmeline Pankhurst|Barbara Castle", "Margaret Thatcher自1979年至1990年任Prime Minister，是20世纪任期最长的首相。"],
  90: ["1998年在Northern Ireland签署了什么？", "The Belfast (Good Friday) Agreement|The Act of Union|The Treaty of Rome|The Bill of Rights", "该协议促成了在Stormont成立权力分享的Northern Ireland Assembly。"],
  91: ["Scottish Parliament和Welsh Assembly在哪一年首次开会？", "1999|1979|1989|2007", "1997年的公投促成了权力下放机构，它们于1999年首次开会。"],
  92: ["Alan Turing最为人所知的是什么？", "协助破译德军密码并开创现代计算机科学|发明喷气发动机|发现penicillin|研发雷达", "Turing在Bletchley Park的工作有助于缩短Second World War，他也是现代计算的奠基者之一。"],
  93: ["谁发明了喷气发动机？", "Sir Frank Whittle|Sir Christopher Cockerell|John Logie Baird|Sir Bernard Lovell", "RAF工程师Sir Frank Whittle在1930年代为涡轮喷气发动机申请了专利。"],
  94: ["1690年William III在Ireland的哪场战役中击败了James II？", "The Battle of the Boyne|The Battle of Culloden|The Battle of Naseby|The Battle of Bannockburn", "Battle of the Boyne至今仍有人在Northern Ireland纪念。"],
  95: ["1679年的Habeas Corpus Act保障了什么？", "任何人不得未经审判被非法羁押|选举权|新闻自由|免费教育", "Habeas corpus是防止非法监禁的关键保障。"],
  96: ["Highland Clearances是什么？", "地主为改养绵羊而驱逐佃户|苏格兰沼泽的排水工程|一项植树造林计划|清除罗马遗迹", "许多苏格兰人被逐出Highlands的家园，移民到美洲及其他地方。"],
  97: ["United Kingdom在哪一年退出欧盟？", "2020|2016|2019|2021", "公投于2016年举行，UK于31 January 2020正式退出欧盟。"],
  98: ["女王Elizabeth II在哪一年登基？", "1952|1936|1945|1960", "Elizabeth II自1952年在位至2022年，是英国在位时间最长的君主。"],
  99: ["UK哪个国家的人口远多于其他国家？", "England|Scotland|Wales|Northern Ireland", "England约占UK人口的84%。"],
  100: ["UK多久进行一次人口普查？", "每10年|每5年|每年|每20年", "全国人口普查每十年进行一次。"],
  101: ["哪一面旗是St George十字旗？", "白底红十字|蓝底白色斜十字|白底红色斜十字|黑底黄十字", "St George是England的主保圣人；其旗为白底红十字。"],
  102: ["St Andrew旗是什么样子？", "蓝底白色斜十字|白底红十字|绿白底红龙|黑底黄十字", "St Andrew是Scotland的主保圣人；saltire为蓝底白色斜十字。"],

  /* ---------- CHAPTER 4 (core) ---------- */
  103: ["哪位主保圣人的旗帜没有出现在Union Flag中？", "St David|St George|St Andrew|St Patrick", "Union Flag融合了St George、St Andrew和St Patrick的十字。Wales未获体现。"],
  104: ["St David's Day是哪一天？", "1 March|17 March|23 April|30 November", "St David（Wales）1 March，St Patrick（NI）17 March，St George（England）23 April，St Andrew（Scotland）30 November。"],
  105: ["St Andrew's Day是哪一天？", "30 November|23 April|17 March|1 March", "St Andrew's Day，30 November，是Scotland的国庆日。"],
  106: ["11月5日的Bonfire Night纪念什么？", "1605年炸毁议会的失败阴谋|First World War的结束|The Great Fire of London|Spanish Armada的失败", "Guy Fawkes与其他同谋企图炸毁议会以杀死新教国王。"],
  107: ["人们在11 November的Remembrance Day佩戴什么？", "罂粟花|玫瑰|蓟花|水仙花", "罂粟花用以纪念在两次世界大战及其后冲突中阵亡的人。"],
  108: ["Hogmanay庆祝的是什么？", "Scotland的除夕|Wales的仲夏|Northern Ireland的丰收|England的五月节", "Hogmanay是苏格兰的重要庆典；2 January在Scotland也是公共假日。"],
  109: ["25 January的Burns Night纪念谁的一生？", "Robert Burns|Robert the Bruce|Rabbie MacAlpin|Robert Louis Stevenson", "Burns Night晚宴纪念写下Auld Lang Syne的苏格兰诗人Robert Burns。"],
  110: ["以下哪两项是全UK的公共假日（bank holidays）？（请选择两个答案）", "Christmas Day|Good Friday|Halloween|Valentine's Day", "Christmas Day、Boxing Day、New Year's Day、Good Friday、Easter Monday等公共假日均属bank holidays。"],
  111: ["The Ashes是England与哪个国家之间的板球赛事？", "Australia|India|South Africa|New Zealand", "England与Australia之间的Ashes系列赛自1882年起举行。"],
  112: ["Wimbledon网球锦标赛在哪里举行？", "London|Manchester|Edinburgh|Birmingham", "Wimbledon的All England Lawn Tennis Championships是世界上历史最悠久的网球赛事。"],
  113: ["Grand National赛马在哪个赛马场举行？", "Aintree|Epsom|Ascot|Ayr", "Grand National在Liverpool附近的Aintree举行；Derby则在Epsom。"],
  114: ["哪座苏格兰城镇被称为高尔夫的故乡？", "St Andrews|Aberdeen|Stirling|Perth", "现代高尔夫在Scotland发展起来，St Andrews是其历史发源地。"],
  115: ["Sir Roger Bannister是第一位做到什么的人？", "在四分钟内跑完一英里|赢得五枚奥运金牌|单人环球航行|赢得Tour de France", "Bannister于1954年打破了四分钟一英里的纪录。"],
  116: ["Sir Steve Redgrave在哪个项目上赢得五枚金牌？", "赛艇|自行车|田径|帆船", "Redgrave在连续五届奥运会上夺金。"],
  117: ["谁是赢得1966年世界杯的England足球队队长？", "Bobby Moore|Bobby Charlton|Ian Botham|Jackie Stewart", "England在Wembley击败West Germany后，Bobby Moore高举世界杯。"],
  118: ["London举办过几次奥运会？", "三次|一次|两次|四次", "London在1908年、1948年和2012年举办过奥运会。"],
  119: ["The Planets是谁创作的？", "Gustav Holst|Edward Elgar|Benjamin Britten|Henry Purcell", "Gustav Holst的组曲The Planets于1918年首演。"],
  120: ["BBC Proms音乐会在哪里举行？", "The Royal Albert Hall|The Globe Theatre|The National Gallery|Wembley Stadium", "Proms是为期八周的夏季古典音乐季，以Last Night of the Proms收尾。"],
  121: ["哪位画家创作了The Hay Wain？", "John Constable|J M W Turner|David Hockney|Thomas Gainsborough", "Constable以描绘英格兰乡村风景而闻名。"],
  122: ["在Tate Britain颁发的当代艺术奖项是什么？", "The Turner Prize|The Booker Prize|The Mercury Prize|The Laurence Olivier Award", "以J M W Turner命名的Turner Prize表彰英国当代艺术。"],
  123: ["St Paul's Cathedral是谁设计的？", "Sir Christopher Wren|Inigo Jones|Robert Adam|Sir Norman Foster", "Wren在1666年Great Fire of London之后重建了St Paul's。"],
  124: ["'Capability' Brown以设计什么而闻名？", "园林景观与公园|大教堂|蒸汽机|家具", "Lancelot 'Capability' Brown在乡间宅邸周围设计了开阔而自然的园林。"],
  125: ["哪个奖项每年颁给来自Commonwealth或Ireland作家的最佳小说？", "The Booker Prize|The Turner Prize|The Mercury Prize|The BAFTA", "Man Booker Prize for Fiction自1968年起颁发。"],
  126: ["Pride and Prejudice是谁写的？", "Jane Austen|Charlotte Bronte|George Eliot|Mary Shelley", "Jane Austen的小说探讨19世纪初England的婚姻与社会阶层。"],
  127: ["Poets' Corner在哪里？", "Westminster Abbey|St Paul's Cathedral|The Tower of London|Canterbury Cathedral", "许多著名诗人安葬或被纪念于Westminster Abbey的Poets' Corner。"],
  128: ["谁发明了World Wide Web？", "Sir Tim Berners-Lee|Alan Turing|John Logie Baird|Sir Clive Sinclair", "英国科学家Berners-Lee在1989-1990年发明了World Wide Web。"],
  129: ["John Logie Baird以开创什么而闻名？", "电视|电话|雷达|气垫船", "Baird于1926年完成首次电视传输，1928年完成首次跨大西洋电视传输。"],
  130: ["1996年克隆的绵羊Dolly是第一只由什么克隆而来的哺乳动物？", "一个成年细胞|一个胚胎|一个植物细胞|一枚冷冻卵子", "Sir Ian Wilmut和Keith Campbell在Edinburgh的Roslin Institute克隆了Dolly。"],
  131: ["Northern Ireland的哪处地貌与巨人Finn McCool的传说相关？", "The Giant's Causeway|The Eden Project|Snowdonia|Loch Lomond", "The Giant's Causeway是Northern Ireland东北海岸的一处天然岩石构造。"],
  132: ["UK最高的山是哪座？", "Ben Nevis|Snowdon|Scafell Pike|Slieve Donard", "Scotland的Ben Nevis是UK最高的山；Snowdon是Wales最高的山。"],
  133: ["Crown Jewels存放在哪里？", "The Tower of London|Buckingham Palace|Windsor Castle|Edinburgh Castle", "Tower of London由被称为Beefeaters的Yeoman Warders守卫。"],
  134: ["UK的货币是什么？", "英镑（pound sterling）|欧元|美元|几尼", "英镑（£）分为100 pence。"],
  135: ["England的国教会是哪一个？", "The Church of England|The Church of Scotland|罗马天主教会|卫理公会", "Church of England属圣公会；君主是其首领，Archbishop of Canterbury是其精神领袖。"],
  136: ["Scotland的国家教会是哪一个？", "The Church of Scotland，一个长老会教会|The Church of England|罗马天主教会|没有国家教会", "Church of Scotland由其General Assembly治理，由Moderator主持。"],

  /* ---------- CHAPTER 5 (core) ---------- */
  137: ["在UK，多大年龄才能合法在pub购买酒精饮料？", "18|16|21|17", "购买酒类须年满18岁。在某些情形下未满18岁者可由成人陪同进入pub，但通常不得饮酒。"],
  138: ["除英语外，UK部分地区还使用哪两种语言？（请选择两个答案）", "Welsh|Gaelic|拉丁语|Cornish Norse", "Welsh在Wales广泛使用；Gaelic在Scotland和Northern Ireland的部分地区使用。"],
  139: ["UK实行何种政体？", "议会民主制下的君主立宪制|绝对君主制|联邦共和制|一党制国家", "君主是国家元首，但由民选政府治理国家。"],
  140: ["House of Commons有多少名议员（MPs）？", "650|600|129|450", "每位MP代表一个选区，共有650位。"],
  141: ["谁主持House of Commons的辩论？", "The Speaker|The Prime Minister|The Lord Chancellor|君主", "Speaker是由其他议员以无记名投票选出的议员，必须保持政治中立。"],
  142: ["House of Lords的成员通常被称为什么？", "Peers|MPs|议员（地方）|大臣", "如今多数是终身贵族（life peers）；Lords中还有若干主教和部分世袭贵族。"],
  143: ["大选最少必须每隔多久举行一次？", "至少每五年一次|至少每三年一次|至少每七年一次|每两年一次", "大选必须至少每五年举行一次。"],
  144: ["UK大选采用的选举制度叫什么？", "First past the post|比例代表制|单一可转移票制|排序复选制", "在每个选区得票最多的候选人成为MP。"],
  145: ["Prime Minister的官邸在哪里？", "10 Downing Street|11 Downing Street|Buckingham Palace|Chequers", "PM住在10 Downing Street，另有一处名为Chequers的乡间宅邸。"],
  146: ["哪位大臣负责经济事务？", "The Chancellor of the Exchequer|The Home Secretary|The Foreign Secretary|The Lord Chancellor", "Chancellor of the Exchequer住在11 Downing Street。"],
  147: ["哪位大臣负责犯罪、警务与移民？", "The Home Secretary|The Foreign Secretary|The Chancellor of the Exchequer|The Defence Secretary", "Home Secretary领导Home Office。"],
  148: ["什么是'反对党'？", "House of Commons中的第二大党|一群公务员|The House of Lords|仅指独立议员", "Leader of the Opposition领导本党，并任命影子内阁以制衡政府。"],
  149: ["公务员体系（civil service）必须做到什么？", "政治中立并按能力任用|由公众选举产生|由君主任命|由执政党成员组成", "无论个人政治观点如何，公务员都为当届政府服务。"],
  150: ["Scottish Parliament有多少名议员？", "129|650|90|60", "Scottish Parliament有129名议员（MSPs），设于Edinburgh的Holyrood。"],
  151: ["Northern Ireland Assembly在哪里开会？", "Belfast的Stormont|Edinburgh的Holyrood|Cardiff Bay|Westminster", "Northern Ireland Assembly有90名议员（MLAs），以权力分享的方式运作。"],
  152: ["议会辩论的记录叫什么？", "Hansard|The Domesday Book|The Gazette|The Register", "Hansard每日出版，可在大型图书馆和网上查阅。"],
  153: ["以下哪项陈述是正确的？", "君主保持政治中立，不在政治上偏袒任何一方|君主决定议会通过哪些法律|君主任命所有议员|君主领导最大的政党", "君主是国家元首，但超然于党派政治之上，定期会见Prime Minister以提出建议与告诫。"],
  154: ["每年的State Opening of Parliament会发生什么？", "君主宣读阐述政府施政方针的演说|议员选出新的Speaker|公布预算|册封新的贵族", "君主的演说由政府撰写，概述其来年的施政计划。"],
  155: ["多大年龄才能在UK大选中投票？", "18|16|21|17", "须年满18岁并登记在electoral register上，方可在大选中投票。"],
  156: ["选举日当天，投票站的开放时间是从几点到几点？", "上午7点至晚上10点|上午9点至下午5点|上午8点至晚上8点|上午6点至午夜", "投票站上午7点开放，晚上10点关闭。"],
  157: ["Commonwealth有多少个成员国？", "54|27|15|100", "Commonwealth是由54个国家组成的自愿联合体；君主是其首脑，对成员国没有权力。"],
  158: ["UK是UN Security Council几个常任理事国之一？", "五个|三个|十个|十五个", "UK是五个常任理事国之一，可以否决提案。"],
  159: ["NATO的主要宗旨是什么？", "为成员国提供集体防御|制定贸易规则|管理欧元|保护欧洲的人权", "NATO成员国约定，若遭到攻击则彼此援助。"],
  160: ["Council of Europe做什么？", "保护成员国的人权|制定欧盟预算|指挥欧洲军队|签发护照", "Council of Europe负责European Convention on Human Rights，并无立法权。"],
  161: ["在England和Wales，哪个法院审理轻微刑事案件？", "The Magistrates' Court|The Crown Court|The County Court|The High Court", "magistrates（又称Justices of the Peace）是无薪志愿者，在没有陪审团的情况下审理轻微案件。"],
  162: ["在Scotland，轻微刑事案件通常由哪个法院审理？", "The Justice of the Peace Court|The Magistrates' Court|The County Court|The Crown Court", "Scotland有自己的法律体系，设有Justice of the Peace Courts和Sheriff Courts。"],
  163: ["在England、Wales和Northern Ireland，Crown Court的陪审团由多少人组成？", "12|15|10|8", "陪审团在England、Wales和Northern Ireland为12人，在Scotland为15人。"],
  164: ["在England、Wales和Northern Ireland，刑事责任年龄是多少？", "10|12|16|18", "在England、Wales和Northern Ireland为10岁，在Scotland为12岁。"],
  165: ["在England和Wales，哪个法院处理小额索赔等轻微民事纠纷？", "The County Court|The Crown Court|The Magistrates' Court|The Youth Court", "County Courts处理债务、人身伤害和违约等民事事务。"],
  166: ["哪个机构就法律与财务问题提供免费、独立的咨询？", "Citizens Advice|The Home Office|仅Law Society|The Crown Prosecution Service", "Citizens Advice是提供免费保密咨询的全国性慈善机构网络。"],
  167: ["以下哪两项在UK是违法的？（请选择两个答案）", "强迫婚姻|女性生殖器切割|双方自愿的包办婚姻|穿着宗教服饰", "强迫婚姻和FGM是严重刑事犯罪。双方均同意的包办婚姻则是合法的。"],
  168: ["National Insurance用于什么？", "支付国家福利和国家养老金|为住房投保|缴纳council tax|承保车祸损失", "几乎所有工作的人都缴纳National Insurance，并需要一个National Insurance号码。"],
  169: ["在PAYE制度下，谁从你的工资中代扣所得税？", "你的雇主|你自己，通过self-assessment|你所在的地方议会|你的银行", "PAYE意为Pay As You Earn；自雇者通常通过self-assessment纳税。"],
  170: ["网上self-assessment报税表必须在哪一天之前提交？", "31 January|31 October|5 April|1 January", "纸质报税表须在31 October前提交，网上报税表须在31 January前提交。"],

  /* ---------- CHAPTER 5 / EXTRA (core) ---------- */
  171: ["在UK，多大年龄可以驾驶汽车？", "17|16|18|21", "17岁可驾驶汽车或摩托车，16岁可骑轻便摩托车。"],
  172: ["汽车何时需要首次MOT检验？", "车龄满三年时|车龄满一年时|车龄满五年时|购车后立即", "车龄超过三年的车辆须每年通过MOT检验，方可上路。"],
  173: ["以下哪两项是参与社区的方式？（请选择两个答案）", "担任school governor|为慈善机构做志愿者|拒绝jury service|不参加地方选举", "你也可以加入neighbourhood watch、成为magistrate或special constable，或在当地医院帮忙。"],
  174: ["谁可能被传召担任陪审员？", "electoral register上18至70岁的任何人|仅律师|仅25岁以上者|仅在英国出生的公民", "jury service是一项义务，人员从electoral register中随机抽选。"],
  175: ["UK的所有驾驶者必须具备什么？", "机动车保险|大学学位|居留许可|停车许可", "无保险驾驶属刑事犯罪；还须持有有效驾照并缴纳road tax。"],
  176: ["如果被警方拦下并认为受到不公正对待，你可以怎么做？", "向警队或独立机构投诉|无计可施|只能向本选区议员投诉|从此拒绝服从任何指示", "警方必须守法，若未守法则有正式投诉程序可循。"],
  177: ["Police and Crime Commissioner是什么？", "由民众选出、监督地方警务优先事项的官员|一名高级警官|Home Office的一名公务员|刑事法院的一名法官", "PCC由England和Wales的民众选出，负责监督地方警队。"],
  178: ["以下哪项陈述是正确的？", "地方议会的经费来自中央政府和地方council tax|地方议会仅靠捐款维持|地方议会不获得政府拨款|地方议会由君主提供经费", "议会提供垃圾收集、图书馆和学校等服务。"],
  201: ["以下哪一项不属于英国生活的基本原则？", "对某个政党的忠诚|个人自由|对不同信仰者的宽容|民主", "这些原则是民主、法治、个人自由、对不同信仰和宗教的宽容，以及参与社区生活。"],
  202: ["申请永久居留或入籍之前必须做什么？", "通过Life in the UK考试并满足英语语言要求|在UK购置房产|在武装部队服役|加入注册政党", "除非获得豁免，通常两项要求都必须满足。"],
  203: ["这句话是对还是错？UK是一个多元社会，长期以来一直欢迎新来者。", "对|错", "从Anglo-Saxons和维京人到近年的移民，移民数百年来塑造了英国社会。"],
  204: ["以下哪两件事有助于保护你居住地的环境？（请选择两个答案）", "回收家庭垃圾|短途出行时步行或骑车|在公共公园乱丢垃圾|在花园里焚烧垃圾", "爱护自己居住的社区是在UK生活的责任之一。"],
  205: ["Scotland的首府是哪座城市？", "Edinburgh|Glasgow|Aberdeen|Dundee", "Edinburgh是首府；Scottish Parliament在当地的Holyrood开会。"],
  206: ["这句话是对还是错？Isle of Man是United Kingdom的一部分。", "错|对", "Isle of Man是拥有自己政府的Crown dependency，不属于UK。"],
  207: ["UK最长的河流是哪一条？", "The Severn|The Thames|The Tyne|The Clyde", "Severn全长约220英里；其次Thames是England最长的河流。"],
  208: ["以下哪一个是Northern Ireland的大城市？", "Londonderry|Swansea|Leeds|Dundee", "Belfast和Londonderry是Northern Ireland的主要城市。"],
  209: ["Stonehenge是由什么人建造的？", "石器时代与青铜时代的人们|罗马人|维京人|诺曼人", "Wiltshire的Stonehenge很可能是举行仪式的场所，建于石器时代与青铜时代。"],
  210: ["Celts使用什么语言？", "凯尔特语，Welsh和Gaelic的祖先|拉丁语|Old English|古诺斯语", "凯尔特语今天以Welsh、Gaelic和Cornish的形式留存。"],
  211: ["Britain的哪些地区从未被罗马人征服？", "Scotland和Ireland|Wales和Cornwall|Kent和Sussex|East Anglia", "罗马统治涵盖England和Wales；Scotland和Ireland始终在帝国之外。"],
  212: ["谁在Iona岛上创建了一座修道院？", "St Columba|St Augustine|St Patrick|St Andrew", "St Columba的传教工作自Iona将基督教传遍Scotland。"],
  213: ["哪位国王在Battle of Hastings中率领英格兰人？", "Harold|Alfred|Cnut|Edward", "国王Harold于1066年在Hastings阵亡，William of Normandy登上王位。"],
  214: ["国王John在Runnymede盖印的是哪份文件？", "Magna Carta|The Bill of Rights|The Domesday Book|The Act of Union", "男爵们迫使国王John在1215年接受Magna Carta。"],
  215: ["Black Death在哪个世纪传入Britain？", "14世纪|12世纪|16世纪|17世纪", "瘟疫于1348年抵达England，夺去约三分之一人口的生命。"],
  216: ["以下哪两项是Black Death的后果？（请选择两个答案）", "劳动力短缺|更富裕的中产阶级兴起|诺曼征服|印刷术的发明", "劳动力减少意味着幸存者可以要求更高的工资，这削弱了旧有的封建制度。"],
  217: ["最后一位统治England的天主教君主是谁？", "James II|Charles II|Henry VIII|Elizabeth I", "James II于1688年在Glorious Revolution期间出逃。"],
  218: ["Reformation是什么？", "一场反对教皇权威的运动|一场反抗税收的起义|法律制度的一次变革|议会的创立", "新教思想传遍欧洲；Henry VIII与罗马决裂将其带入England。"],
  219: ["哪位女王统治Scotland并于1587年被处决？", "Mary, Queen of Scots|Mary I|Elizabeth I|Anne", "Mary逃往England，被囚禁20年，最终因涉嫌密谋反对Elizabeth I而被处决。"],
  220: ["Gunpowder Plot是什么？", "1605年一场炸毁Houses of Parliament的天主教阴谋|一项焚烧London的计划|刺杀Cromwell的阴谋|一场苏格兰起义", "Guy Fawkes在议会大厦地下看守炸药时被捕；这一失败在5 November被纪念。"],
  221: ["议会与国王Charles I之间爆发的是哪场战争？", "The English Civil War|The Wars of the Roses|The Hundred Years War|The Crimean War", "内战于1642年爆发，并导致国王于1649年被处决。"],
  222: ["Great Fire之后重建St Paul's Cathedral的建筑师是谁？", "Sir Christopher Wren|Inigo Jones|Robert Adam|John Nash", "1666年的Great Fire摧毁了London大部分地区，包括那座古老的大教堂。"],
  223: ["与Ireland的Act of Union在哪一年创建了United Kingdom of Great Britain and Ireland？", "1801|1707|1922|1689", "Ireland于1801年加入联合；其大部分于1922年退出。"],
  224: ["Richard Arkwright的哪项发明对工业革命至关重要？", "高效且获利的纺纱机械|蒸汽机车|电话|电灯", "Arkwright的工厂改变了纺织品的生产方式。"],
  225: ["Isambard Kingdom Brunel以什么闻名？", "建造桥梁、铁路和船舶|发现penicillin|创建NHS|撰写小说", "Brunel建造了Great Western Railway以及包括SS Great Britain在内的船舶。"],
  226: ["1851年的Great Exhibition是为庆祝什么而举办的？", "来自英国和世界各地的工业与文化|拿破仑战争的结束|女王Victoria的加冕|帝国的建立", "展览在Hyde Park的Crystal Palace举行。"],
  227: ["Mary Seacole是谁？", "一位在Crimea救治伤兵的牙买加护士|英国第一位女医生|一位suffragette领袖|一位战时首相", "她为病伤士兵设立了一处住所，如今在London立有雕像以示纪念。"],
  228: ["Emmeline Pankhurst的支持者通常被称为什么？", "Suffragettes|Chartists|Levellers|Jacobites", "suffragettes为女性选举权而奔走，在First World War之前采取了日益激进的手段。"],
  229: ["First World War中英国的主要盟友是哪些国家？", "France、Russia以及后来的United States|Germany和Austria|仅Italy和Japan|Spain和Portugal", "英国与France、Russia并肩作战，后来还有Italy、Japan和United States。"],
  230: ["Blitz是什么？", "德国飞机对英国城市的猛烈轰炸|Dunkirk撤退|Normandy登陆|Malta保卫战", "自1940年起，London、Coventry等城市遭到猛烈轰炸。"],
  231: ["英国在Second World War中与哪位德国领导人作战？", "Adolf Hitler|Kaiser Wilhelm|Otto von Bismarck|Erich Ludendorff", "德国入侵波兰后，英国于1939年宣战。"],
  232: ["以下哪两项是在Second World War之后不久设立的？（请选择两个答案）", "The National Health Service|福利国家的补助体系|欧盟|The Bank of England", "NHS于1948年创立，Beveridge Report则塑造了现代福利国家。"],
  233: ["哪些英国科学家协助发现了DNA的结构？", "Francis Crick和Maurice Wilkins|Alexander Fleming和Howard Florey|Charles Darwin和Alfred Wallace|Isaac Newton和Robert Hooke", "这一发现于1953年在Cambridge完成，并与James Watson合作。"],
  234: ["谁发明了气垫船？", "Sir Christopher Cockerell|Sir Frank Whittle|John Logie Baird|Sir Tim Berners-Lee", "英国发明家Cockerell在1950年代研制出气垫船。"],

  /* ---------- EXTRA (core, completing 253) ---------- */
  235: ["以下哪位是Second World War期间著名的英国Prime Minister？", "Winston Churchill|Harold Wilson|Stanley Baldwin|Anthony Eden", "Churchill自1940年起领导战时联合政府，并于1951年再度出任首相。"],
  236: ["Commonwealth最初由什么演变而来？", "曾属于British Empire的国家|欧盟成员国|联合国创始成员国|NATO成员国", "多数Commonwealth成员是前英国殖民地，不过成员资格是自愿的。"],
  237: ["以下哪两种传统食物与Wales和Scotland相关？（请选择两个答案）", "Welsh cakes|Haggis|Ulster fry|Cornish pasty", "Welsh cakes来自Wales，haggis来自Scotland；Ulster fry则来自Northern Ireland。"],
  238: ["United Kingdom的国旗通常被称为什么？", "The Union Flag或Union Jack|The Royal Standard|The Red Ensign|The Saltire", "它融合了St George、St Andrew和St Patrick的十字。"],
  239: ["Christmas Day在哪一天庆祝？", "25 December|24 December|26 December|1 January", "26 December的Boxing Day也是公共假日。"],
  240: ["UK的印度教徒和锡克教徒庆祝哪个光明节？", "Diwali|Eid al-Fitr|Hanukkah|Vaisakhi", "Diwali通常在October或November，持续五天。"],
  241: ["Eid al-Fitr是什么？", "标志Ramadan结束的穆斯林节日|印度教新年节日|锡克教丰收节|犹太光明节", "穆斯林感谢真主赐予他们完成斋月的力量。"],
  242: ["Lord's球场进行的是哪项运动？", "板球|橄榄球|网球|足球", "位于London的Lord's是世界上最著名的板球场之一。"],
  243: ["各国橄榄球联合会代表队参加的是哪项赛事？", "The Six Nations Championship|The Ashes|The Ryder Cup|The Grand National", "England、Scotland、Wales和Ireland每年与France和Italy比赛。"],
  244: ["Sir Ian Botham在哪项运动上享有盛名？", "板球|足球|赛艇|赛车", "Botham曾保持England在板球测试赛中夺取三柱门数的纪录。"],
  245: ["哪位赛车手在1960和70年代三度赢得Formula 1世界冠军？", "Sir Jackie Stewart|Damon Hill|Lewis Hamilton|Stirling Moss", "苏格兰车手Jackie Stewart三度赢得世界冠军。"],
  246: ["什么是'bank holiday'？", "多数企业停业的公共假日|银行不收取费用的日子|只有银行停业的日子|一个宗教节日", "bank holidays包括Christmas Day、Boxing Day、New Year's Day和Easter Monday。"],
  247: ["以下哪位是著名的英国电影导演？", "Sir Alfred Hitchcock|Steven Spielberg|Martin Scorsese|Ang Lee", "Hitchcock执导了Psycho和The Birds；英国电影奖项是BAFTAs。"],
  248: ["哪个年度花卉展在London举办？", "The Chelsea Flower Show|The Edinburgh Festival|The Notting Hill Carnival|The Eisteddfod", "Chelsea Flower Show展示来自世界各地的园林设计。"],
  249: ["Eisteddfod是什么？", "一个以文学、音乐和表演为主的威尔士节庆|苏格兰高地运动会|爱尔兰舞蹈比赛|英格兰乡村集市", "Wales每年举办National Eisteddfod，主要以威尔士语进行。"],
  250: ["以下哪处UK地标是位于Wiltshire的史前遗迹？", "Stonehenge|The Eden Project|The Tower of London|Snowdonia", "Stonehenge是World Heritage Site，也是世界上最著名的史前遗迹之一。"],
  251: ["Eden Project在哪里？", "Cornwall|Kent|Fife|Antrim", "位于Cornwall的Eden Project生物穹顶收藏着来自世界各地的植物。"],
  252: ["UK最大的国家公园是哪一个？", "The Cairngorms|Snowdonia|The Lake District|The Peak District", "位于Scotland的Cairngorms National Park是UK最大的国家公园。"],
  253: ["在UK观看或录制直播电视之前必须做什么？", "购买TV licence|在地方议会登记|加入BBC|向Ofcom申请", "每个观看直播电视或使用BBC iPlayer的家庭都需要TV licence。"],
  254: ["多大年龄可以购买National Lottery彩票？", "18|16|21|14", "National Lottery产品的最低年龄为18岁。"],
  255: ["以下哪两项是UK民众参与慈善的方式？（请选择两个答案）", "在慈善商店做志愿者|向募捐活动捐款|拒绝纳税|无视地方选举", "National Trust和Comic Relief等慈善机构高度依赖志愿者和捐款。"],
  256: ["UK的国家元首是谁？", "君主|The Prime Minister|The Speaker|The Lord Chancellor", "君主是国家元首；Prime Minister是政府首脑。"],
  257: ["constituency是什么？", "一位MP所代表的地区|一个政党|一个政府部门|一类法院", "共有650个选区，每个选区选出一位MP。"],
  258: ["by-election是什么？", "在两次大选之间某位MP席位出缺时举行的选举|大选的第二轮|地方议员的选举|一次公投", "当某位MP辞职或去世时会举行by-election。"],
  259: ["压力团体（pressure group）的作用是什么？", "就某一特定议题影响政府政策|组织选举|征收税款|任命法官", "压力团体就特定议题代表英国公民的意见。"],
  260: ["UK法律的两个主要来源是什么？", "Acts of Parliament和case law|王室敕令和教会法|仅欧洲条约|地方议会规章", "法官也会解释法律，其判决逐渐积累成common law。"],
  261: ["如果你被控严重刑事罪行却无力聘请律师，谁来为你辩护？", "由legal aid支付费用的solicitor或barrister|一名警官|一名magistrate|一名公务员", "视你的情况与案件而定，你可能可以获得legal aid。"],
  262: ["在Scotland，哪个法院审理严重刑事案件？", "The High Court of Justiciary或Sheriff Court|The Crown Court|The Magistrates' Court|The County Court", "Scotland拥有自己的法律体系，与England、Wales和Northern Ireland相区别。"],
  263: ["如果你为已付款的商品或服务遇到问题，可以怎么做？", "向County Court起诉或使用小额索赔程序|向警方报案|向议会申诉|联系Crown Court", "小额索赔在England、Wales和Northern Ireland由County Courts处理，在Scotland由Sheriff Courts处理。"],
  264: ["以下哪两项属于职场上的非法歧视？（请选择两个答案）", "基于种族的歧视|基于残疾的歧视|不聘用缺乏相应资格的人|因经验更丰富而给予更高薪酬", "Equality Act保护人们免受基于年龄、残疾、种族、宗教、性别和性取向等理由的歧视。"],
  265: ["UK报警、火警和救护车的紧急电话号码是什么？", "999或112|911|101|111", "紧急情况请拨999或112；101用于非紧急警务事项，111用于非紧急医疗咨询。"],
  266: ["在England，非紧急医疗咨询应拨打哪个号码？", "111|999|101|112", "在情况没有生命危险时，NHS 111提供医疗咨询。"],
  267: ["如何登记注册家庭医生？", "在当地的GP surgery登记|向Home Office申请|请雇主代办|只能在医院登记", "对于非紧急的健康问题，GP通常是第一联系人。"],
  268: ["谁可以参选成为MP？", "多数年满18岁、拥有UK、爱尔兰或符合条件的Commonwealth公民身份的人|仅25岁以上者|仅两大政党成员|仅在UK出生者", "部分人不具备资格，例如武装部队成员、公务员和在押囚犯。"],
  269: ["school governor是什么？", "协助管理学校的志愿者|领薪的校长|地方议会雇员|政府督学", "成为school governor是参与社区的一种方式。"],
  270: ["如果被传召担任陪审员，你必须怎么做？", "除非有正当理由获准免除，否则必须出席|缴费才能参加|自行挑选要审理的案件|服务整整一年", "jury service是一项公共义务，人员从electoral register中随机抽选。"],
  271: ["Speaker的选区工作有何意义？", "Speaker仍以MP身份代表其选民|Speaker没有选区|Speaker代表政府|Speaker只主持辩论", "Speaker仍是选区议员，但在Commons议事厅内必须保持政治中立。"],
  272: ["哪个机构审查并可对House of Commons通过的法律提出修正？", "The House of Lords|The Supreme Court|公务员体系|王室机构", "Lords审议法案，不过Commons最终可以否决其意见。"],
  273: ["如果不缴纳council tax会怎样？", "你可能被起诉并承担额外费用|不会怎样，缴纳是自愿的|护照会被吊销|会被驱逐出境", "council tax用于支付垃圾收集、图书馆和警务等地方服务。"],
  274: ["'devolved power'一词是什么意思？", "由中央政府移交给某个国家或地区机构的权力|授予君主的权力|授予法院的权力|授予地方慈善机构的权力", "Scotland、Wales和Northern Ireland设有权力下放的行政机构，在卫生和教育等领域拥有权力。"],
  275: ["以下哪一项是每位在UK工作的居民的责任？", "缴纳所得税和National Insurance|加入工会|每次选举都投票|担任magistrate", "税款用于支付道路、学校、武装部队和NHS等公共服务。"],

  /* ---------- DOUBLES — CHAPTER 1-3 ---------- */
  1000: ["以下哪一项被视为Britain生活的核心原则？", "法治|所有成年人的义务兵役|唯一的官方宗教|政府对新闻界的控制", "基本原则包括民主、法治、个人自由、对不同信仰和宗教的宽容，以及参与社区生活。"],
  1004: ["以下哪两项是对UK居民的期望？（请选择两个答案）", "公平对待他人|照顾好自己和家人|每周前往礼拜场所|成为某个政党的成员", "责任包括遵守法律、尊重他人权利、公平待人、照顾自己和家人，以及爱护自己居住的社区。"],
  1008: ["在以下哪种语言选项中可以参加Life in the UK考试？", "英语、Welsh或Scottish Gaelic|仅英语|任何欧盟官方语言|英语或法语", "该考试可用英语、Welsh或Scottish Gaelic参加。"],
  1012: ["在公民宣誓仪式上，除宣誓或确认效忠外，新公民还要做什么？", "承诺尊重UK的权利、自由与法律|承诺加入武装部队|向慈善机构捐款|正式放弃其他所有国籍", "新公民向君主宣誓效忠，并承诺尊重UK的权利、自由与法律。"],
  1016: ["以下哪项权利为UK所有人共享？", "信仰与宗教自由|不缴税的权利|获得免费住房的权利|任何年龄领取国家养老金的权利", "信仰与宗教自由是UK每个人共享的权利与自由之一。"],
  1020: ["在UK，以下哪一项是责任而非权利或自由？", "缴税|公正审判|免受不公正歧视|言论自由", "缴税是一项责任，而非自由。权利包括言论自由、信仰自由、公正审判和免受不公正歧视。"],
  1024: ["通常由谁安排公民宣誓仪式？", "地方政府|Houses of Parliament|王室|直接由Home Office办理，无地方参与", "地方政府安排公民宣誓仪式，通常在申请获批后三个月内举行。"],
  1028: ["多数永久居留或入籍申请人必须证明哪两点？（请选择两个答案）", "能够说和读英语|对UK生活了解良好|在UK拥有房产|曾在London居住", "申请人必须证明自己能说能读英语，并对UK生活有良好了解。"],
  1032: ["'参与社区生活'最恰当的描述是什么？", "英国生活的一项基本原则|所有居民的法定义务|只有公民才能做的事|就业的一项条件", "参与社区生活被列为英国生活的基本原则之一。"],
  1036: ["在法律方面，对UK每个人的期望是什么？", "尊重并遵守法律|只遵守自己认同的法律|把不喜欢的法律报告给议会|成为公民后才遵守", "尊重并遵守法律是每位UK居民的基本责任。"],
  1040: ["UK被描述为民主国家。这在实践中意味着什么？", "权力属于人民或其选出的代表|权力仅属于君主|权力属于法院|权力属于军队", "在民主制度中，权力属于人民，或直接行使，或通过选出的代表行使。"],
  1044: ["爱护自己居住地的环境是什么的例子？", "一项责任|一项权利|专属公民的法律特权|一种可选的礼节", "爱护自己居住的社区和环境是在UK生活的责任之一。"],
  1048: ["以下哪一项不属于英国生活的基本原则？", "对某个特定政党的忠诚|个人自由|民主|对不同信仰和宗教的宽容", "这些原则是民主、法治、个人自由、对不同信仰和宗教的宽容，以及参与社区生活。支持某个特定政党不在其列。"],
  1052: ["在申请永久居留或入籍之前，多数申请人必须已经做到什么？", "通过Life in the UK考试并满足英语语言要求|在UK购置房产|完成一段军队服役|加入注册政党", "除非获得豁免，通常两项要求都必须满足。"],
  1056: ["UK的移民史最恰当的描述是什么？", "长期在多元社会中接纳新来者的历史|抑制一切移民的历史|一种史无前例的近期现象|完全局限于过去二十年", "从Anglo-Saxons和维京人到近年的移民，移民数百年来塑造了英国社会。"],
  1060: ["以下哪两项行动有助于保护你居住地的环境？（请选择两个答案）", "回收家庭垃圾|短途出行时步行或骑车|在公共公园乱丢垃圾|在花园里焚烧垃圾", "爱护自己居住的社区是在UK生活的责任之一。"],
  1064: ["United Kingdom由多少个国家组成？", "四个|两个|三个|五个", "UK由England、Scotland、Wales和Northern Ireland组成。"],
  1068: ["哪三个国家共同组成Great Britain？", "England、Scotland和Wales|England、Scotland和Northern Ireland|仅England和Wales|UK的全部四个国家", "Great Britain仅指England、Scotland和Wales。UK还包括Northern Ireland。"],
  1072: ["以下哪两个是Crown dependencies，不属于UK？（请选择两个答案）", "The Channel Islands|The Isle of Man|The Isle of Wight|Anglesey", "Channel Islands和Isle of Man拥有自己的政府；它们是Crown dependencies，不属于UK。"],
  1076: ["以下哪一个是英国海外领地而非UK的一部分？", "The Falkland Islands|The Isle of Man|Jersey|Guernsey", "Falkland Islands和St Helena等海外领地与UK相关联，但不属于UK。"],
  1080: ["Cardiff是UK哪个国家的首府？", "Wales|Scotland|Northern Ireland|England", "Cardiff是Wales的首府；Senedd（威尔士议会）在Cardiff Bay开会。"],
  1084: ["Belfast是UK哪个国家的首府？", "Northern Ireland|Scotland|Wales|England", "Belfast是Northern Ireland的首府。Northern Ireland Assembly在Belfast的Stormont开会。"],
  1088: ["以下哪一项最恰当地描述了Northern Ireland的地位？", "属于UK，但不属于Great Britain|属于Great Britain|完全不属于UK|一个Crown dependency", "Northern Ireland是UK的一部分，但Great Britain只指England、Scotland和Wales。"],
  1092: ["UK的哪三个地区各自拥有权力下放的行政机构？", "Scotland、Wales和Northern Ireland|England、Scotland和Wales|Scotland、England和Northern Ireland|Wales、England和Northern Ireland", "Scotland、Wales和Northern Ireland各有一个权力下放的政府，部分权力由Westminster移交。"],
  1096: ["Edinburgh是UK哪个国家的首府？", "Scotland|England|Wales|Northern Ireland", "Edinburgh是首府；Scottish Parliament在当地的Holyrood开会。"],
  1100: ["Isle of Man的地位是什么？", "一个Crown dependency，不属于UK|属于UK|属于Scotland|一个英国海外领地", "Isle of Man是拥有自己政府的Crown dependency，不属于UK。"],
  1104: ["UK最长的河流是哪一条？", "The Severn|The Thames|The Tyne|The Clyde", "Severn全长约220英里；其次Thames是England最长的河流。"],
  1111: ["以下哪一个不是Northern Ireland的城市？", "Leeds|Belfast|Londonderry|Armagh", "Belfast、Londonderry和Armagh都是Northern Ireland的城市。Leeds是England的城市。"],
  1112: ["最早居住在Britain的人最恰当的描述是什么？", "狩猎采集者|农民|商人|士兵", "Britain最早的居民是狩猎采集者，他们随气候变化而来去。"],
  1116: ["连接Britain与欧洲大陆的陆桥大约在多久以前被海水淹没？", "约10,000年前|约1,000年前|约100,000年前|约500年前", "约10,000年前通往大陆的陆桥被海水淹没，Britain从此永久成为岛屿。"],
  1122: ["一位对考古感兴趣的朋友问，Orkney的哪处遗址展现了石器时代的生活面貌。你会怎么说？", "Skara Brae|Stonehenge|Maiden Castle|Hadrian's Wall", "Orkney的Skara Brae为考古学家提供了石器时代生活的详尽图景。"],
  1124: ["Dorset的Maiden Castle是哪类遗址的例子？", "铁器时代的山丘堡垒|罗马别墅|诺曼城堡|维京定居点", "Maiden Castle是一座大型铁器时代山丘堡垒。青铜时代的人们还建造圆形房屋和墓丘。"],

  /* ---------- DOUBLES — CHAPTER 3 (History) ---------- */
  1128: ["Julius Caesar在哪一年试图入侵Britain却以失败告终？", "55 BC|AD 43|AD 122|AD 410", "Caesar在55 BC的突袭失败了。成功的罗马入侵发生在AD 43，由皇帝Claudius发动。"],
  1135: ["在Britain的早期历史中，以下哪一位没有领导起义或统一王国？", "Julius Caesar|Boudicca|Alfred the Great|Kenneth MacAlpin", "Boudicca领导了反抗罗马的起义，Alfred击败了维京人，Kenneth MacAlpin统一了Scotland。Julius Caesar是罗马入侵者，而非不列颠领袖。"],
  1136: ["Hadrian's Wall的主要用途是什么？", "抵御北方的Picts等部落|标示与Wales的边界|抵御维京人的袭击|保护London", "皇帝Hadrian于AD 122下令修筑此墙，以守护罗马不列颠的北部边疆。"],
  1143: ["以下哪一项不是罗马人于AD 410撤离Britain的相关原因？", "他们被维京人击败|他们需要保卫帝国的其他地区|罗马帝国其他地方的压力日益增大|罗马在Britain的统治正式结束", "罗马人于AD 410撤退以保卫帝国其他地区——维京人直到AD 789才袭击Britain，那已是罗马撤离很久之后。"],
  1144: ["罗马人离开后，哪些民族入侵Britain并在此定居？", "Jutes、Angles和Saxons|Normans和Franks|仅Picts和Scots|西班牙人和葡萄牙人", "Anglo-Saxons——Jutes、Angles和Saxons——来自北欧，在Britain定居。"],
  1148: ["East Anglia的Sutton Hoo是谁的墓葬地？", "一位Anglo-Saxon国王|一位罗马将军|一位维京首领|一位诺曼骑士", "Sutton Hoo的船葬被认为属于一位Anglo-Saxon国王或伟大战士。"],
  1154: ["一位朋友问，597年谁被从罗马派来使Anglo-Saxons皈依基督教。那是谁？", "St Augustine|St Columba|St Patrick|St Andrew", "St Augustine于597年抵达，成为首任Archbishop of Canterbury。"],
  1159: ["以下哪个年份与Britain的维京人无关？", "AD 1215|AD 789|东部与北部的Danelaw时期|国王Alfred后来对他们的胜利", "维京人于AD 789首次袭击，后来控制Danelaw，直到Alfred the Great将其击败。AD 1215是Magna Carta之年，与维京人无关。"],
  1162: ["一位朋友问，哪位Anglo-Saxon国王因击败维京人而为人铭记。那是谁？", "Alfred the Great|Harold|Cnut|William of Normandy", "国王Alfred the Great击败了维京人，尽管他们仍控制着东部和北部的Danelaw。"],
  1167: ["在Britain的早期历史中，以下哪一位没有统一王国或率众取胜？", "Macbeth|Kenneth MacAlpin|Alfred the Great|Robert the Bruce", "Kenneth MacAlpin统一了Picts和Scots，Alfred the Great击败了维京人，Robert the Bruce在Bannockburn获胜。Macbeth是后来的苏格兰国王，统一王国之功并不属于他。"],
  1170: ["一位朋友问1066年发生了哪场著名战役。答案是什么？", "The Battle of Hastings|The Battle of Bosworth Field|The Battle of Bannockburn|The Battle of Agincourt", "1066年在Hastings，Normandy公爵William击败了国王Harold——这是England最后一次被外敌成功入侵。"],
  1175: ["关于Bayeux Tapestry，以下哪一项不正确？", "它是一份书面法律文件|它是一幅刺绣|它描绘了诺曼征服|它至今仍在France展出", "Bayeux Tapestry是一幅刺绣，而非书面法律文件——这一时期的书面土地普查是Domesday Book。"],
  1178: ["一位朋友问William为何在1086年下令对England进行大规模普查。那是为了什么？", "为记录England各地土地与牲畜的归属|为统计有多少人支持他的统治|为规划新的道路网|为评估各城镇能提供多少士兵", "William于1086年下令编纂Domesday Book，记录England各地土地与牲畜的归属。"],
  1183: ["以下哪座城堡不属于Edward I在Wales修建的城堡环带？", "Bosworth Castle|Conwy Castle|Caernarfon Castle|Harlech Castle", "Edward I征服Wales后修建了Conwy、Caernarfon和Harlech等城堡。Bosworth并非城堡——它是1485年那场结束Wars of the Roses的战役的发生地。"],
  1186: ["一位朋友问，在Robert the Bruce率领下哪场战役为Scotland赢得了数百年的独立。是哪一场？", "Bannockburn|Culloden|Agincourt|Naseby", "1314年，Robert the Bruce率领的苏格兰人在Bannockburn获胜，使Scotland数百年保持独立。"],
  1191: ["以下哪位国王没有在Hundred Years War期间在位？", "Henry VIII|Henry V|Edward III|Richard II", "Henry V、Edward III和Richard II都在Hundred Years War（1337-1453）期间在位。Henry VIII在16世纪在位，远在战争结束之后。"],
  1194: ["一位朋友问，England输掉Hundred Years War后仍保有哪座法国城镇。是哪一座？", "Calais|Paris|Rouen|Bordeaux", "England失去了除Calais港以外的全部法国领地；Calais本身也于1558年失守。"],
  1199: ["以下哪一项不是1348年Black Death的后果？", "劳动力突然过剩、工资下跌|劳动力短缺|更富裕的中产阶级兴起|约三分之一人口死亡", "Black Death造成的是劳动力短缺而非过剩——工人减少意味着幸存者可以要求更高工资，这促成了更富裕的中产阶级出现。"],
  1202: ["一位朋友问国王John在1215年被迫同意了什么。那是什么，又起了什么作用？", "Magna Carta，它限制了他作为国王的权力|一份结束与Scotland战争的条约|第一部英文圣经|一套新的货币制度", "国王John于1215年被迫接受Magna Carta（《大宪章》），确立了国王同样受法律约束。"],
  1207: ["以下哪个家族没有卷入Wars of the Roses？", "Tudor，在战争开始之前|Lancaster|York|红玫瑰与白玫瑰两派", "Wars of the Roses在Lancaster与York之间展开。Tudor王朝是此后才开始的，当时Henry Tudor于1485年在Bosworth Field获胜。"],
  1210: ["一位朋友问哪场战役使Henry Tudor成为国王Henry VII。是哪一场？", "The Battle of Bosworth Field|The Battle of Hastings|The Battle of the Boyne|The Battle of Agincourt", "Richard III于1485年在Bosworth Field阵亡，Henry Tudor成为Henry VII，开创了Tudor王朝。"],
  1215: ["关于William Caxton，以下哪一项不正确？", "他写了The Canterbury Tales|他在England建立了第一家印刷所|他在1476年从业|他的工作使书籍更广泛流传", "William Caxton将印刷术带到England——The Canterbury Tales由更早的作家Geoffrey Chaucer所写，Caxton后来印行了他的作品。"],
  1218: ["一位朋友问，谁写了一部关于前往Canterbury朝圣者的著名诗集。那是谁？", "Geoffrey Chaucer|William Shakespeare|John Milton|William Caxton", "Chaucer的Canterbury Tales是一部描写一群前往Canterbury的朝圣者的诗集。"],
  1223: ["以下哪一位不是Henry VIII的六位妻子之一？", "Mary I|Catherine of Aragon|Anne Boleyn|Catherine Parr", "Henry VIII的六位妻子是Catherine of Aragon、Anne Boleyn、Jane Seymour、Anne of Cleves、Catherine Howard和Catherine Parr。Mary I是他的女儿，而非妻子。"],
  1226: ["一位朋友问Henry VIII为何创立Church of England。正确的原因是什么？", "教皇拒绝废除他与Catherine of Aragon的婚姻|他想入侵France|他不喜欢礼拜中使用的拉丁语|他想废除税收", "Henry创立Church of England并自任首领，以便再婚，由此开启了英格兰宗教改革。"],
  1231: ["关于Mary I，以下哪一项不正确？", "她是坚定的新教徒|她是Henry VIII的女儿|她迫害新教徒|她被称为'Bloody Mary'", "Mary I是虔诚的天主教徒而非新教徒——正因如此，她在位期间迫害新教徒。"],
  1234: ["一位朋友问England在哪一年击败了Philip II派来的西班牙入侵舰队。是哪一年？", "1588|1485|1666|1707", "1588年，英格兰舰队击败了Philip II派来入侵England的Spanish Armada。"],
  1239: ["关于William Shakespeare，以下哪一项不正确？", "他出生在London|他出生在Stratford-upon-Avon|他在Globe剧院工作|他在London担任剧作家", "Shakespeare出生于Stratford-upon-Avon而非London——尽管他后来在London的Globe剧院工作。"],
  1242: ["一位朋友问，1603年后哪位国王同时统治Scotland和England，而两国并未正式合并。那是谁？", "Scotland的James VI（England的James I）|Charles I|Henry VII|William III", "1603年的Union of the Crowns使England和Scotland同属一位君主，但两国仍各自独立。"],
  1247: ["以下哪个称谓不是English Civil War中的一方？", "Jacobites|Cavaliers|Roundheads|Royalists", "内战中，Cavaliers（保王派）与Roundheads（议会派）交战。Jacobites是流亡的James II及其后嗣的支持者，属于后来的冲突。"],

  /* ---------- DOUBLES — CHAPTER 3 (continued) ---------- */
  1250: ["一位朋友问Charles I在哪一年被处决，使England成为共和国。是哪一年？", "1649|1660|1666|1688", "Charles I于1649年被处决，England成为称作Commonwealth的共和国。"],
  1255: ["关于Oliver Cromwell，以下哪一项不正确？", "他被加冕为England国王|他以Lord Protector的头衔统治|他于1658年去世|其子Richard继任但无力有效治理", "Cromwell以Lord Protector而非国王的身份统治——这一时期England是没有君主的共和国。"],
  1258: ["一位朋友问，在Cromwell的共和国之后，君主制在哪一年随Charles II恢复。是哪一年？", "1660|1649|1688|1707", "议会于1660年邀请Charles II回国，这一事件被称为Restoration。"],
  1263: ["以下哪一项没有在1660年代袭击London？", "The Black Death|The Great Plague|The Great Fire|需要重建（包括St Paul's）的大范围破坏", "Great Plague（1665）和Great Fire（1666）在1660年代袭击了London。Black Death是更早的疫情，发生在1348年。"],
  1266: ["一位朋友问，1688年Glorious Revolution的结果是谁成为国王。那是谁？", "William of Orange|Charles II|George I|James II，他保住了王位", "William of Orange与其妻Mary（James II之女）在England未经战事便登上王位。"],
  1271: ["以下哪一项不是1689年Bill of Rights所确立的？", "全体成年人的普选权|君主须获议会同意|定期召开议会的要求|对王权的限制", "Bill of Rights限制了王权并要求定期召开议会——全体成年人的普选权要到很久以后的20世纪才出现。"],
  1274: ["一位朋友问1707年的Act of Union联合了什么、创建了什么。答案是什么？", "它将Scotland与England置于同一议会之下，创建了Kingdom of Great Britain|它联合England与Ireland，创建了United Kingdom|它创建了Commonwealth|它只联合了England与Wales", "Scotland和England在同一个议会下联合，于1707年组成Kingdom of Great Britain。"],
  1279: ["以下哪一位没有担任过UK的Prime Minister？", "Oliver Cromwell|Sir Robert Walpole|Winston Churchill|Margaret Thatcher", "Walpole、Churchill和Thatcher都曾担任Prime Minister。Oliver Cromwell在更早的共和国时期以Lord Protector身份统治，那时Prime Minister一职尚不存在。"],
  1282: ["一位朋友问哪场战役在1746年结束了Bonnie Prince Charlie的征战。是哪一场？", "Culloden|Bannockburn|Naseby|Bosworth Field", "Bonnie Prince Charlie的军队于1746年在Culloden被击溃；他随后逃往欧洲。"],
  1287: ["以下哪一项与Scottish Enlightenment无关？", "James Watt的蒸汽机|Adam Smith|David Hume|哲学与科学上的新思想", "Adam Smith和David Hume是启蒙运动的主要思想家。James Watt的蒸汽机属于后来的工业革命，尽管两者都是苏格兰人的成就。"],
  1290: ["一位朋友问，为工业革命提供动力的蒸汽机改良归功于谁。那是谁？", "James Watt|Richard Arkwright|Isaac Newton|Isambard Kingdom Brunel", "苏格兰人James Watt改良了蒸汽机，使其能够驱动工厂和矿井中的机械。"],
  1295: ["关于British Empire废除奴隶制与奴隶贸易，以下哪一项不正确？", "奴隶贸易与奴隶制本身都在1807年被废除|奴隶贸易于1807年被废除|整个帝国的奴隶制于1833年被废除|William Wilberforce曾推动反对奴隶贸易的运动", "奴隶贸易于1807年废除，但奴隶制本身在帝国内一直延续到1833年的Emancipation Act——这是两个不同的年份。"],
  1298: ["一位朋友问，哪位议员与终结英国参与奴隶贸易的关系最为密切。那是谁？", "William Wilberforce|Robert Walpole|William Gladstone|Robert Peel", "福音派基督徒William Wilberforce领导了议会中的反奴隶制运动。"],
  1303: ["关于Admiral Nelson，以下哪一项不正确？", "他在Waterloo指挥英国陆军|他在Battle of Trafalgar中阵亡|他的旗舰是HMS Victory|Trafalgar Square部分是为纪念他而命名", "Nelson是海军统帅，于1805年在Trafalgar阵亡——1815年的陆上战役Waterloo由Duke of Wellington指挥。"],
  1306: ["一位朋友问，1815年是谁率领英国在Waterloo战胜Napoleon。那是谁？", "The Duke of Wellington|Admiral Nelson|Sir Robert Walpole|William Pitt", "后来出任Prime Minister的Duke of Wellington被称为铁公爵，并在Waterloo指挥作战。"],
  1311: ["关于女王Victoria的统治，以下哪一项不正确？", "它持续了不到20年|它始于1837年|它结束于1901年|它持续了64年", "女王Victoria自1837年至1901年在位64年——远超20年。"],
  1314: ["一位朋友问Florence Nightingale与哪场战争关系最密切。是哪一场？", "The Crimean War|The First World War|The Boer War|The Napoleonic Wars", "Florence Nightingale在Crimean War期间于Scutari护理伤员，后来在London创办了护士学校。"],
  1319: ["关于Emmeline Pankhurst，以下哪一项不正确？", "她是Crimean War的护士|她于1889年创立了Women's Franchise League|她领导了suffragette运动|她的运动采取了日益激进的手段", "Emmeline Pankhurst领导了争取女性选举权的suffragette运动。在Crimean War中护理伤员是更早一代的Florence Nightingale的功绩。"],
  1322: ["一位朋友问女性最终在什么时候获得了与男性完全相同条件的选举权。是哪一年？", "1928|1918|1945|1969", "拥有财产的30岁以上女性于1918年获得选举权；投票年龄的完全平等则在1928年实现。"],
  1327: ["以下哪一事件与First World War的爆发无关？", "1939年入侵波兰|Archduke Franz Ferdinand遇刺|1914年Sarajevo的事件|将欧洲列强卷入战争的一连串同盟", "First World War在Franz Ferdinand遇刺后于1914年爆发。1939年入侵波兰引发的则是Second World War。"],
  1330: ["一位朋友问1916年Somme首日英军伤亡大约多少。最接近的数字是哪个？", "约60,000|约6,000|约600|约600,000", "Somme是First World War中最血腥的战役之一，仅首日英军伤亡就约60,000人。"],
  1335: ["以下哪个日期与First World War无关？", "8 May 1945|11 November 1918|1914年，战争爆发之时|'第十一个月第十一天的第十一小时'", "First World War于11 November 1918结束。8 May 1945是VE Day，标志Second World War在欧洲结束。"],
  1338: ["一位朋友问，1922年国家被分割时，Ireland南部成立了什么。它叫什么？", "The Irish Free State|The Republic of Ulster|The Kingdom of Ireland|The Irish Commonwealth", "Irish Free State于1922年在南部成立；北部六郡留在UK。"],
  1343: ["关于Winston Churchill，以下哪一项不正确？", "他创立了National Health Service|他于1940年成为Prime Minister|他因战时演说而为人铭记|他领导英国度过Second World War的大部分时期", "Churchill以Prime Minister身份领导英国度过Second World War。NHS由卫生大臣Aneurin Bevan在另一届政府下于1948年创立。"],
  1346: ["一位朋友问，1940年在Dunkirk发生了什么，有数百艘小型民用船只参与其中。那是什么？", "从海滩撤离逾300,000名士兵|一次成功入侵France|对德国舰队的海上胜利|签署一项和平条约", "1940年，数百艘民用船只协助从Dunkirk海滩救出英法士兵。"],
  1351: ["以下哪种飞机在Battle of Britain中没有为RAF发挥主要作用？", "Lancaster轰炸机|The Spitfire|The Hurricane|守卫英国天空的战斗机", "赢得Battle of Britain的是RAF的Spitfire和Hurricane战斗机。Lancaster是重型轰炸机，在战争后期才投入使用。"],
  1354: ["一位朋友问盟军在哪一天登陆Normandy、开始解放西欧。是哪一天？", "6 June 1944|8 May 1945|3 September 1939|11 November 1918", "6 June 1944的D-Day登陆开启了将西欧从纳粹占领中解放的进程。"],
  1359: ["关于VE Day，以下哪一项不正确？", "它标志日本投降|它是8 May 1945|它标志欧洲的胜利|在此之后对日战争仍在继续", "VE Day标志的是8 May 1945欧洲的胜利——日本直到1945年August才投降。"],
  1362: ["一位朋友问哪位苏格兰科学家发现了penicillin。那是谁？", "Sir Alexander Fleming|Sir Frank Whittle|Alan Turing|James Watt", "苏格兰科学家Alexander Fleming于1928年发现了penicillin，后被开发为抗生素。"],
  1367: ["关于Beveridge Report，以下哪一项不正确？", "它由Aneurin Bevan撰写|它于1942年发表|它由William Beveridge撰写|它提出了现代福利国家构想", "报告由William Beveridge撰写；Aneurin Bevan另有其人，他后来在1948年主导创建了NHS。"],

  /* ---------- DOUBLES — CHAPTER 3 (continued) ---------- */
  1370: ["一位朋友问，1948年NHS的启动归功于哪位大臣。那是谁？", "Aneurin Bevan|William Beveridge|Winston Churchill|Clement Attlee，尽管由Bevan直接主导", "卫生大臣Aneurin Bevan于1948年启动了NHS，为所有人提供在使用时免费的医疗服务。"],
  1375: ["关于Empire Windrush号，以下哪一项不正确？", "它于1948年自India驶来|它载来了West Indies的工人|它于1948年抵达|战后劳动力短缺促成了前来的邀请", "Empire Windrush号于1948年从West Indies载来工人，以缓解战后劳动力短缺——并非来自India，尽管来自India和Pakistan的工人稍后也陆续抵达。"],
  1378: ["一位朋友问India、Pakistan和Ceylon在哪一年脱离Britain独立。是哪一年？", "1947|1922|1966|1973", "India、Pakistan和Ceylon于1947年独立，开启了British Empire的快速非殖民化。"],
  1383: ["关于UK与EEC/欧盟，以下哪一项不正确？", "UK在加入EEC之前就已退出欧盟|UK于1973年加入EEC|UK于2020年退出欧盟|EEC后来发展为欧盟", "UK于1973年加入EEC，直到很久之后的2020年才退出欧盟——并非在加入之前就退出。"],
  1386: ["一位朋友问，1979年谁成为UK第一位女性Prime Minister。那是谁？", "Margaret Thatcher|Theresa May|Emmeline Pankhurst|Indira Gandhi", "Margaret Thatcher自1979年至1990年任Prime Minister，是20世纪任期最长的首相。"],
  1391: ["关于Belfast (Good Friday) Agreement，以下哪一项不正确？", "它于1801年签署|它于1998年签署|它促成了Stormont的权力分享Assembly|它涉及Northern Ireland", "Belfast (Good Friday) Agreement于1998年签署——1801年则是早先与Ireland签订Act of Union的年份。"],
  1394: ["一位朋友问，1997年公投之后，权力下放的Scottish Parliament和Welsh Assembly在哪一年首次开会。是哪一年？", "1999|1979|1989|2007", "1997年的公投促成了权力下放机构，它们于1999年首次开会。"],
  1399: ["以下哪一项不是Alan Turing的成就？", "发明喷气发动机|在Bletchley Park协助破译德军密码|开创现代计算机科学|通过破译工作缩短了Second World War", "Turing的成就在密码破译与计算领域。喷气发动机由另一位英国人Sir Frank Whittle发明。"],
  1402: ["一位朋友问，1930年代哪位RAF工程师为涡轮喷气发动机申请了专利。那是谁？", "Sir Frank Whittle|Sir Christopher Cockerell|John Logie Baird|Alan Turing", "RAF工程师Sir Frank Whittle在1930年代为涡轮喷气发动机申请了专利。"],
  1407: ["关于Battle of the Boyne，以下哪一项不正确？", "它发生在Scotland|它发生在1690年|William III在那里击败了James II|它在Northern Ireland至今仍被纪念", "Battle of the Boyne于1690年在Ireland而非Scotland打响，当时William III击败了James II。"],
  1410: ["一位朋友问1679年的Habeas Corpus Act提供了什么保障。正确答案是什么？", "防止未经审判被非法羁押的保障|选举投票权|新闻自由|人人享有免费教育", "Habeas corpus是防止非法监禁的关键保障，由1679年的法案确立。"],
  1415: ["以下哪一项不是Highland Clearances的特征？", "地主邀请佃户免费留下|佃户被逐出家园|土地改作养羊之用|许多苏格兰人因此移民", "Highland Clearances中地主驱逐佃户，而非邀请他们留下——许多被逐出的家庭移民到美洲及其他地方。"],
  1418: ["一位朋友把欧盟公投与UK实际退出混为一谈。UK在哪一年正式退出欧盟？", "2020|2016|2019|2021", "公投于2016年举行，但UK直到31 January 2020才正式退出欧盟。"],
  1423: ["关于女王Elizabeth II的统治，以下哪一项不正确？", "它比女王Victoria的统治更短|它始于1952年|它持续到2022年|它是英国历史上最长的统治", "Elizabeth II自1952年至2022年的统治是英国历史上最长的——比女王Victoria的64年更长，而非更短。"],
  1426: ["一位在Wiltshire游览的朋友问，Stonehenge的石阵是谁建造的。那是谁？", "石器时代与青铜时代的人们|罗马人|维京人|诺曼人", "Wiltshire的Stonehenge很可能是举行仪式的场所，建于石器时代与青铜时代。"],
  1431: ["以下哪种语言不是源自古不列颠人所说的凯尔特语？", "Old English|Welsh|Gaelic|Cornish", "Welsh、Gaelic和Cornish都源自凯尔特语。Old English随Anglo-Saxon移民而来，属于完全不同的语系。"],
  1432: ["Britain和Ireland的哪些地区从未被罗马人征服？", "Scotland和Ireland|Wales和Cornwall|Kent和Sussex|East Anglia", "罗马统治涵盖England和Wales；Scotland和Ireland始终在帝国之外。"],
  1439: ["关于St Columba，以下哪一项不正确？", "他成为首任Archbishop of Canterbury|他在Iona创建了一座修道院|他的传教使基督教传遍Scotland|他与Britain的早期基督教有关", "St Columba创建了Iona的修道院。成为首任Archbishop of Canterbury的是St Augustine，而非Columba。"],
  1442: ["一位朋友问1066年在Battle of Hastings中哪位英格兰国王阵亡。那是谁？", "Harold|Alfred|Cnut|Edward the Confessor", "国王Harold于1066年在Hastings阵亡，William of Normandy登上王位。"],
  1447: ["关于Runnymede的Magna Carta，以下哪一项不正确？", "国王John在毫无压力的情况下自愿盖印|它于1215年盖印|男爵们迫使国王接受它|它限制了王权", "Magna Carta是在压力下盖印的——男爵们于1215年迫使国王John接受，这并非自愿之举。"],
  1450: ["一位朋友问Black Death在哪个世纪袭击Britain。是哪个世纪？", "14世纪|12世纪|16世纪|17世纪", "瘟疫于1348年、即14世纪抵达England，夺去约三分之一人口的生命。"],
  1455: ["以下哪一项不是Black Death的后果？", "England的诺曼征服|劳动力短缺|幸存的工人得以要求更高工资|旧有封建制度被削弱", "Black Death造成的劳动力短缺削弱了封建制度，并促成更富裕的中产阶级出现。诺曼征服发生在数百年前的1066年。"],
  1458: ["一位朋友问，在Glorious Revolution中被废黜的England最后一位天主教国王是谁。那是谁？", "James II|Charles II|Henry VIII|Charles I", "James II是最后一位统治England的天主教君主；他于1688年在Glorious Revolution期间出逃。"],
  1463: ["关于Reformation，以下哪一项不正确？", "它强化了教皇在全欧洲的权威|它是一场反对教皇权威的运动|新教思想因此传遍欧洲|Henry VIII与罗马决裂与之相关", "Reformation挑战并削弱了教皇的权威，传播了新教思想——并未强化教皇的地位。"],
  1466: ["一位朋友问，哪位苏格兰女王在被处决前曾在England被囚禁20年。那是谁？", "Mary, Queen of Scots|Mary I|Elizabeth I|Lady Jane Grey", "Mary, Queen of Scots逃往England，被囚禁20年，最终因涉嫌密谋反对Elizabeth I而被处决。"],
  1471: ["关于Gunpowder Plot，以下哪一项不正确？", "它成功炸毁了议会|Guy Fawkes参与其中|它是一场天主教阴谋|它发生在1605年", "Gunpowder Plot失败了——Guy Fawkes在炸药被引爆前看守时就被捕，议会并未被摧毁。"],
  1474: ["一位朋友问，1642年开始的哪场冲突是议会与国王之间的战争。是哪一场？", "The English Civil War|The Wars of the Roses|The Hundred Years War|The Jacobite rebellions", "English Civil War于1642年在议会与国王Charles I之间爆发，并导致国王于1649年被处决。"],
  1479: ["关于Sir Christopher Wren，以下哪一项不正确？", "他设计了最初那座中世纪的St Paul's Cathedral|他在Great Fire之后重建了St Paul's|他的工作发生在1666年大火之后|他是著名的英国建筑师", "Great Fire摧毁那座古老的中世纪大教堂后，Christopher Wren重建了St Paul's——他并未设计最初那一座。"],
  1482: ["一位朋友问Ireland在哪一年正式加入与Great Britain的联合。是哪一年？", "1801|1707|1922|1689", "Ireland于1801年加入联合；其大部分于1922年退出。"],
  1487: ["关于Richard Arkwright，以下哪一项不正确？", "他建造了桥梁、铁路和船舶|他研制了用于纺织的纺纱机械|他的工厂改变了纺织品生产|他是工业革命的关键人物", "Arkwright以纺纱机械和工厂闻名。建造桥梁、铁路和船舶是Isambard Kingdom Brunel的成就。"],

  /* ---------- DOUBLES — CHAPTER 3/4 ---------- */
  1490: ["一位朋友问Great Western Railway和SS Great Britain是谁建造的。那是谁？", "Isambard Kingdom Brunel|Richard Arkwright|James Watt|George Stephenson", "Brunel建造了Great Western Railway以及包括SS Great Britain在内的船舶。"],
  1495: ["关于1851年的Great Exhibition，以下哪一项不正确？", "它是为庆祝Crimean War结束而举办|它在Crystal Palace举行|它展示了工业与文化|它在Hyde Park举行", "1851年的Great Exhibition展示了来自世界各地的工业与文化——Crimean War（1853-56）当时甚至尚未开始。"],
  1498: ["一位朋友问起一位因在Crimean War中的工作而在London立像纪念的牙买加护士。她是谁？", "Mary Seacole|Florence Nightingale|Elizabeth Fry|Emmeline Pankhurst", "Mary Seacole是来自Jamaica的护士，她在Crimea救治伤兵，并为病伤士兵设立了住所。"],
  1503: ["关于suffragettes，以下哪一项不正确？", "她们在17世纪内战期间开展运动|她们为女性选举权而奔走|她们采取了日益激进的方法|她们在First World War之前十分活跃", "suffragettes在First World War之前的20世纪初开展运动——而非17世纪的内战期间。"],
  1506: ["一位朋友问，First World War中哪些主要国家与英国并肩作战。是哪些？", "France、Russia以及后来的United States|Germany和Austria|仅Italy和Japan|Spain和Portugal", "英国与France、Russia并肩作战，后来还有Italy、Japan和United States。"],
  1511: ["关于Blitz，以下哪一项不正确？", "它是盟军对Germany的轰炸行动|它包括对英国城市的猛烈轰炸|它由德国飞机执行|它始于1940年", "Blitz是Germany对英国城市的轰炸，而非盟军对Germany的行动——London和Coventry都在受袭城市之列。"],
  1514: ["一位朋友问，1939年入侵波兰之后英国向哪位德国领导人宣战。那是谁？", "Adolf Hitler|Kaiser Wilhelm|Otto von Bismarck|Erich Ludendorff", "在Adolf Hitler领导的德国入侵波兰后，英国于1939年宣战。"],
  1519: ["以下哪一项不是在Second World War之后不久设立的？", "The Bank of England，它在数百年前就已成立|The National Health Service|现代福利国家的补助体系|在使用时免费的医疗服务", "NHS与现代福利国家是在Second World War之后的1948年设立的。而Bank of England在那时已存在数百年。"],
  1522: ["一位朋友问，哪些英国科学家与James Watson合作，于1953年发现了DNA的结构。是哪些人？", "Francis Crick和Maurice Wilkins|Alexander Fleming和Howard Florey|Charles Darwin和Alfred Wallace|Isaac Newton和Robert Hooke", "Francis Crick和Maurice Wilkins于1953年在Cambridge与James Watson合作，协助发现了DNA的结构。"],
  1527: ["关于Sir Christopher Cockerell，以下哪一项不正确？", "他发明了喷气发动机|他发明了气垫船|他在1950年代研制出它|他是英国发明家", "Cockerell发明了气垫船。喷气发动机由另一位英国发明家Sir Frank Whittle发明。"],
  1530: ["一位朋友问，谁在Second World War的大部分时期领导英国联合政府，后来又重任首相。那是谁？", "Winston Churchill|Harold Wilson|Stanley Baldwin|Neville Chamberlain，他于1951年回任", "Churchill自1940年起领导战时联合政府，并于1951年再度出任Prime Minister。"],
  1535: ["关于Commonwealth，以下哪一项不正确？", "前英国殖民地必须加入|多数成员曾属于British Empire|如今成员资格是自愿的|它由昔日的British Empire演变而来", "Commonwealth的成员资格是自愿的而非强制的——各国虽已完全独立，仍选择继续留任成员。"],
  1538: ["一位朋友问UK哪个国家的人口占比最大。是哪一个？", "England|Scotland|Wales|Northern Ireland", "England约占UK人口的84%。"],
  1543: ["关于UK的人口普查，以下哪一项不正确？", "它每年进行一次|它统计全部人口|它每10年进行一次|它是全国范围的统计", "UK的人口普查每十年进行一次，而非每年一次。"],
  1546: ["一位朋友问England主保圣人的旗帜是什么样子。你会怎么描述？", "白底红十字|蓝底白色斜十字|白底红色斜十字|绿白底上的一条龙", "St George是England的主保圣人；其旗为白底红十字。"],
  1551: ["关于St Andrew旗，以下哪一项不正确？", "它被称为Union Jack|它被称为saltire|它代表Scotland|它是蓝底白色", "St Andrew旗称为saltire，代表Scotland。Union Jack则是整个UK的合并旗帜。"],
  1554: ["一位朋友问为何Wales没有体现在Union Flag的设计中。其中缺少哪位圣人的十字？", "St David的|St George的|St Andrew的|St Patrick的", "Union Flag融合了St George、St Andrew和St Patrick的十字。Wales和St David的十字未获体现。"],
  1559: ["以下哪一项与其主保圣人纪念日的搭配不正确？", "St David's Day — 23 April|St David's Day — 1 March|St Patrick's Day — 17 March|St George's Day — 23 April", "St David's Day是1 March而非23 April——23 April是England的St George's Day。"],
  1562: ["一位在Scotland的朋友问他们的国庆日St Andrew's Day是哪一天。是哪一天？", "30 November|23 April|17 March|1 March", "St Andrew's Day，30 November，是Scotland的国庆日。"],
  1567: ["关于Bonfire Night，以下哪一项不正确？", "它纪念一场成功炸毁议会的阴谋|它在5 November|它纪念1605年的一场阴谋|Guy Fawkes参与了它所纪念的那场阴谋", "Bonfire Night所纪念的Gunpowder Plot失败了——议会并未被摧毁，Guy Fawkes在计划得以实施前就被捕。"],
  1570: ["一位朋友问每年November佩戴哪种花以纪念战争中阵亡者。是哪种花？", "罂粟花|玫瑰|蓟花|水仙花", "罂粟花纪念在两次世界大战及其后冲突中阵亡的人，在11 November的Remembrance Day前后佩戴。"],
  1575: ["关于Hogmanay，以下哪一项不正确？", "它在Wales作为丰收节庆祝|它是苏格兰的庆典|它标志除夕|因为它，2 January在Scotland也是公共假日", "Hogmanay是Scotland的除夕庆典——并非威尔士的丰收节。"],
  1578: ["一位朋友问每年25 January的Burns Night晚宴纪念的是谁。那是谁？", "Robert Burns|Robert the Bruce|Robert Louis Stevenson|Walter Scott", "Burns Night晚宴纪念写下Auld Lang Syne的苏格兰诗人Robert Burns。"],
  1583: ["以下哪一项不是UK的公共假日（bank holiday）？", "Halloween|Christmas Day|Good Friday|New Year's Day", "Christmas Day、Good Friday和New Year's Day都是公共假日。Halloween广受庆祝，但并非官方公共假日。"],
  1586: ["一位朋友问，在历史悠久的Ashes系列赛中England与哪个国家进行板球比赛。是哪个国家？", "Australia|India|South Africa|New Zealand", "England与Australia之间的Ashes系列赛自1882年起举行。"],
  1591: ["关于Wimbledon锦标赛，以下哪一项不正确？", "它是世界上最新的网球赛事|它在London举行|它也称作All England Lawn Tennis Championships|它是世界上历史最悠久的网球赛事", "Wimbledon是世界上历史最悠久的网球赛事，而非最新的。"],
  1594: ["一位朋友问Liverpool附近哪个赛马场举办Grand National。是哪一个？", "Aintree|Epsom|Ascot|Ayr", "Grand National在Liverpool附近的Aintree举行；Derby则在Epsom。"],
  1599: ["关于高尔夫与Scotland的渊源，以下哪一项不正确？", "现代高尔夫在England发展起来|现代高尔夫在Scotland发展起来|St Andrews被视为其历史发源地|高尔夫与苏格兰历史关系密切", "现代高尔夫在Scotland而非England发展起来——St Andrews是其历史发源地。"],
  1602: ["一位朋友问1954年谁第一个在四分钟内跑完一英里。那是谁？", "Sir Roger Bannister|Sir Steve Redgrave|Bobby Moore|Sir Jackie Stewart", "Bannister于1954年打破了四分钟一英里的纪录。"],
  1607: ["关于Sir Steve Redgrave，以下哪一项不正确？", "他的金牌是在田径项目上获得的|他在赛艇项目上获得金牌|他在连续五届奥运会上夺冠|他是英国最成功的奥运选手之一", "Steve Redgrave的五枚金牌是在赛艇而非田径项目上获得的。"],

  /* ---------- DOUBLES — CHAPTER 4 ---------- */
  1610: ["一位朋友问，1966年谁以England队长身份高举世界杯。那是谁？", "Bobby Moore|Bobby Charlton|Ian Botham|Bobby Robson", "1966年England在Wembley击败West Germany后，Bobby Moore高举世界杯。"],
  1615: ["以下哪一年London没有举办奥运会？", "1984|1908|1948|2012", "London在1908、1948和2012年举办过奥运会——1984年并未举办，那一年由Los Angeles主办。"],
  1618: ["一位朋友问，1918年首演的管弦乐组曲The Planets是谁创作的。那是谁？", "Gustav Holst|Edward Elgar|Benjamin Britten|Ralph Vaughan Williams", "Gustav Holst的组曲The Planets于1918年首演。"],
  1623: ["关于BBC Proms，以下哪一项不正确？", "它们是一季足球比赛|它们在Royal Albert Hall举行|它们持续约八周|它们以Last Night of the Proms收尾", "Proms是古典音乐会的演出季而非足球比赛，在Royal Albert Hall举行。"],
  1626: ["一位朋友问，著名的英格兰乡村风景画The Hay Wain是谁画的。那是谁？", "John Constable|J M W Turner|David Hockney|Thomas Gainsborough", "Constable以描绘英格兰乡村风景而闻名，其中就包括The Hay Wain。"],
  1631: ["关于Turner Prize，以下哪一项不正确？", "它授予年度最佳小说|它以J M W Turner命名|它表彰英国当代艺术|它与Tate Britain相关", "Turner Prize表彰当代艺术而非小说——最佳小说的奖项是Booker Prize。"],
  1634: ["一位朋友问，1666年旧教堂焚毁后，如今的St Paul's Cathedral是谁设计的。那是谁？", "Sir Christopher Wren|Inigo Jones|Robert Adam|Sir Norman Foster", "Wren在1666年Great Fire of London之后设计并重建了St Paul's。"],
  1639: ["关于'Capability' Brown，以下哪一项不正确？", "他设计了St Paul's Cathedral|他设计了园林景观|他的全名是Lancelot Brown|他的园林围绕乡间宅邸而设计", "'Capability' Brown设计的是园林景观而非大教堂——St Paul's Cathedral由Sir Christopher Wren设计。"],
  1642: ["一位朋友问，自1968年起颁发的哪个文学奖每年表彰最佳小说。它叫什么？", "The Booker Prize|The Turner Prize|The Mercury Prize|The Costa Book Award", "Man Booker Prize for Fiction自1968年起颁发。"],
  1647: ["关于Jane Austen，以下哪一项不正确？", "她写了Frankenstein|她写了Pride and Prejudice|她的小说探讨婚姻与社会阶层|她在19世纪初的England写作", "Jane Austen写的是Pride and Prejudice。Frankenstein由另一位小说家Mary Shelley所写。"],
  1650: ["一位朋友问，在London许多著名诗人安葬或被纪念于何处。是哪里？", "Westminster Abbey的Poets' Corner|St Paul's Cathedral|The Tower of London|The British Museum", "许多著名诗人安葬或被纪念于Westminster Abbey的Poets' Corner。"],
  1655: ["关于Sir Tim Berners-Lee，以下哪一项不正确？", "他发明了电视|他发明了World Wide Web|他的发明约在1989-1990年|他是英国科学家", "Tim Berners-Lee发明了World Wide Web。电视由另一位英国先驱John Logie Baird发明。"],
  1658: ["一位朋友问1926年谁完成了首次电视传输。那是谁？", "John Logie Baird|Sir Tim Berners-Lee|Alan Turing|Sir Frank Whittle", "Baird于1926年完成首次电视传输，1928年完成首次跨大西洋电视传输。"],
  1663: ["关于绵羊Dolly，以下哪一项不正确？", "它由一个植物细胞克隆而来|它于1996年被克隆|它由一个成年细胞克隆而来|它在Edinburgh的Roslin Institute被克隆", "Dolly由成年动物细胞而非植物细胞克隆而来——它是一只绵羊，1996年在Roslin Institute培育。"],
  1666: ["一位游览Northern Ireland东北海岸的朋友问起一处与传说中巨人相关的岩石构造。它叫什么？", "The Giant's Causeway|The Eden Project|Snowdonia|Loch Lomond", "The Giant's Causeway是Northern Ireland东北海岸的一处天然岩石构造，与Finn McCool的传说相关。"],
  1671: ["以下哪座山不是其所在UK国家的最高点？", "Scafell Pike是Wales最高的山|Ben Nevis是整个UK最高的山|Snowdon是Wales最高的山|Scafell Pike是England最高的山", "Scafell Pike是England而非Wales最高的山——在Wales，这一头衔属于Snowdon。"],
  1674: ["一位游览London的朋友问，由Beefeaters守卫的Crown Jewels在哪里可以看到。他该去哪里？", "The Tower of London|Buckingham Palace|Windsor Castle|Westminster Abbey", "Crown Jewels存放在Tower of London，由被称为Beefeaters的Yeoman Warders守卫。"],
  1679: ["关于英镑，以下哪一项不正确？", "它分为1,000 pence|它是UK的货币|它分为100 pence|它的符号是£", "英镑分为100 pence，而非1,000。"],
  1682: ["一位朋友问，England以君主为首领的国教会是哪一个。是哪个教会？", "The Church of England|The Church of Scotland|罗马天主教会|卫理公会", "Church of England属圣公会；君主是其首领，Archbishop of Canterbury是其精神领袖。"],
  1687: ["关于Church of Scotland，以下哪一项不正确？", "君主是其精神领袖|它是长老会教会|它由General Assembly治理|它由Moderator主持", "Church of Scotland由其自身的General Assembly和Moderator治理，君主并非其首领——那一安排适用于Church of England。"],
  1690: ["一位即将年满17岁的朋友问，他现在能否合法在pub买酒。你会怎么说？", "不能——他必须等到年满18岁|能——17岁就是法定年龄|能，但须有家长在场|不能——法定年龄是21岁", "在UK购买酒类须年满18岁，因此17岁的人还得再等一年。"],
  1695: ["以下哪一种语言如今在UK部分地区并未广泛使用？", "拉丁语|Welsh|Gaelic|英语", "Welsh、Gaelic和英语如今都在UK部分地区使用。拉丁语并非活的社区语言，尽管仍留存于部分正式与学术场合。"],
  1698: ["一位同时游览Wales和Scotland的朋友问，在两地各该尝试哪些传统食物。以下哪两项搭配正确？（请选择两个答案）", "Wales的Welsh cakes|Scotland的Haggis|Wales的Ulster fry|Scotland的Cornish pasty", "Welsh cakes来自Wales，haggis来自Scotland；Ulster fry来自Northern Ireland，Cornish pasty则来自England的Cornwall。"],
  1703: ["以下哪一项不是UK国旗的别称？", "The Saltire|The Union Flag|The Union Jack|一面融合三位圣人十字的旗帜", "Union Flag也称作Union Jack。Saltire特指St Andrew旗，仅代表Scotland。"],
  1706: ["一位初到UK的朋友问Christmas Day是哪一天，次日则是Boxing Day。是哪一天？", "25 December|24 December|26 December|1 January", "Christmas Day是25 December；26 December的Boxing Day也是公共假日。"],
  1711: ["关于Diwali，以下哪一项不正确？", "它是犹太节日|它由印度教徒和锡克教徒庆祝|它是光明节|它通常在October或November", "Diwali是印度教徒与锡克教徒的光明节——Hanukkah才是犹太人的光明节。"],
  1714: ["一位朋友问，在斋月结束时庆祝的Eid al-Fitr标志着什么。那是什么？", "Ramadan的结束|印度教新年|锡克教丰收节|犹太光明节", "Eid al-Fitr是标志Ramadan结束的穆斯林节日，穆斯林感谢真主赐予他们完成斋月的力量。"],
  1719: ["关于Lord's，以下哪一项不正确？", "它是著名的网球场地|它是著名的板球场|它位于London|它是世界上该项运动最著名的场地之一", "Lord's是著名的板球场而非网球场地——London著名的网球场地是Wimbledon。"],
  1722: ["一位朋友问，哪项年度赛事让England、Scotland、Wales和Ireland与France和Italy进行橄榄球比赛。它叫什么？", "The Six Nations Championship|The Ashes|The Ryder Cup|The World Cup", "在Six Nations Championship中，England、Scotland、Wales和Ireland每年与France和Italy进行rugby union比赛。"],
  1727: ["关于Sir Ian Botham，以下哪一项不正确？", "他是赛艇冠军|他是著名的板球运动员|他曾保持England在测试赛中夺取三柱门数的纪录|他的成就在板球领域", "Ian Botham以板球运动员闻名。赛艇金牌是另一位运动员Sir Steve Redgrave的成就。"],

  /* ---------- DOUBLES — CHAPTER 4/5 ---------- */
  1730: ["一位朋友问，1960和70年代哪位苏格兰车手三度赢得Formula 1世界冠军。那是谁？", "Sir Jackie Stewart|Damon Hill|Lewis Hamilton|Nigel Mansell", "苏格兰车手Jackie Stewart三度赢得Formula 1世界冠军。"],
  1735: ["关于UK的bank holiday，以下哪一项不正确？", "只有银行受影响，其他所有企业照常营业|多数企业停业|Christmas Day就是一例|Easter Monday就是一例", "bank holiday影响的是多数企业而不只是银行——它是面向所有人的公共假日。"],
  1738: ["一位朋友问哪位英国导演拍摄了Psycho和The Birds。那是谁？", "Sir Alfred Hitchcock|Steven Spielberg|Martin Scorsese|David Lean", "Hitchcock执导了Psycho和The Birds；英国电影奖项是BAFTAs。"],
  1743: ["关于Chelsea Flower Show，以下哪一项不正确？", "它在Edinburgh举办|它在London举办|它每年举办|它展示来自世界各地的园林设计", "Chelsea Flower Show在London而非Edinburgh举办——Edinburgh Festival是另一项互不相关的活动。"],
  1746: ["一位朋友问起一个以威尔士语为主、涵盖文学、音乐与表演的威尔士节庆。它叫什么？", "The Eisteddfod|The Highland Games|The Chelsea Flower Show|The Notting Hill Carnival", "National Eisteddfod是每年举办的威尔士文学、音乐与表演节庆，主要以威尔士语进行。"],
  1751: ["关于Stonehenge，以下哪一项不正确？", "它位于Cornwall|它位于Wiltshire|它是World Heritage Site|它是史前遗迹", "Stonehenge位于Wiltshire而非Cornwall——Cornwall有的是Eden Project。"],
  1754: ["一位朋友问，收藏世界各地植物的Eden Project巨型生物穹顶位于哪个郡。是哪个郡？", "Cornwall|Kent|Fife|Antrim", "位于Cornwall的Eden Project生物穹顶收藏着来自世界各地的植物。"],
  1759: ["以下哪一个不是UK最大的国家公园？", "Snowdonia|The Cairngorms|一个位于Scotland的国家公园|按面积计UK最大的国家公园", "位于Scotland的Cairngorms是UK最大的国家公园——位于Wales的Snowdonia并非最大。"],
  1762: ["一位朋友刚搬进他在UK的第一个住所，打算观看直播电视。他必须先办理什么？", "一张TV licence|在地方议会登记|加入BBC|获得Ofcom批准", "每个观看直播电视或使用BBC iPlayer的家庭都需要TV licence。"],
  1767: ["以下哪一项不是购买National Lottery彩票的正确最低年龄？", "16|18|与购买酒类相同的年龄|与在betting shop投注相同的年龄", "National Lottery产品的最低年龄是18岁，与购买酒类或投注相同——并非16岁。"],
  1770: ["一位朋友想参与慈善工作。以下哪两项真的能帮助慈善机构？（请选择两个答案）", "在慈善商店做志愿者|向募捐活动捐款|拒绝缴纳任何税款|在选举日待在家里", "National Trust和Comic Relief等慈善机构高度依赖志愿者和捐款。"],
  1774: ["一位朋友问，君主是国家元首但不治理国家的UK政体该如何称呼。它叫什么？", "议会民主制下的君主立宪制|绝对君主制|联邦共和制|一党制国家", "UK是议会民主制下的君主立宪制——君主是国家元首，但由民选政府治理国家。"],
  1779: ["关于House of Commons的议员，以下哪一项不正确？", "他们有129人|他们有650人|每人代表一个选区|他们在House of Commons就座", "House of Commons共有650位议员——129则是Scottish Parliament的议员人数。"],
  1782: ["一位朋友问，谁主持House of Commons的辩论并必须保持政治中立。那是谁？", "The Speaker|The Prime Minister|The Lord Chancellor|The Leader of the Opposition", "Speaker是由其他议员以无记名投票选出的议员，必须保持政治中立。"],
  1787: ["关于House of Lords的成员，以下哪一项不正确？", "他们全部由公众选举产生|多数是终身贵族|Lords中还有若干主教|Lords中还有部分世袭贵族", "House of Lords的成员并非由公众选举产生——多数被任命为终身贵族，此外还有主教和部分世袭贵族。"],
  1790: ["一位朋友问UK最少必须每隔多久举行一次大选。答案是什么？", "至少每五年一次|至少每三年一次|至少每七年一次|每两年一次", "大选必须至少每五年举行一次。"],
  1795: ["关于UK大选所用的first past the post制度，以下哪一项不正确？", "席位严格按全国得票比例分配|在某选区得票最多的候选人胜出|它用于UK大选|每个选区选出一位议员", "first past the post并不按全国得票比例分配席位——在每个选区得票最多的候选人直接赢得该席位。"],
  1798: ["一位朋友问Prime Minister在London的官邸是哪个地址。是哪个地址？", "10 Downing Street|11 Downing Street|Buckingham Palace|Chequers", "Prime Minister住在10 Downing Street，另有一处名为Chequers的乡间宅邸。"],
  1803: ["以下哪一项不是Chancellor of the Exchequer的职责？", "警务与移民|经济|住在11 Downing Street|财政与预算事务", "Chancellor of the Exchequer主管经济——警务与移民则是Home Secretary的职责。"],
  1806: ["一位朋友问，哪位大臣领导负责犯罪、警务与移民的Home Office。那是谁？", "The Home Secretary|The Foreign Secretary|The Chancellor of the Exchequer|The Justice Secretary", "Home Secretary领导Home Office，负责犯罪、警务与移民事务。"],
  1811: ["关于House of Commons中的反对党，以下哪一项不正确？", "其领袖完全没有任何正式角色|它是第二大党|其领袖任命影子内阁|其职责是制衡政府", "Leader of the Opposition拥有正式且受认可的角色——任命影子内阁以制衡政府——而非毫无角色。"],
  1814: ["一位朋友问公务员是否必须隶属执政党。正确答案是什么？", "不必——他们必须政治中立，并按能力任用|必须——他们必须隶属执政党|必须，但仅限高级公务员|不必——但他们由公众选举产生", "公务员必须政治中立并按能力任用——无论个人观点如何，他们都为当届政府服务。"],
  1819: ["关于Scottish Parliament，以下哪一项不正确？", "它有90名议员|它有129名议员|其议员称为MSPs|它设于Edinburgh的Holyrood", "Scottish Parliament有129名议员——90则是Northern Ireland Assembly的议员（MLAs）人数。"],
  1822: ["一位朋友问，拥有90名MLAs的Northern Ireland Assembly设在哪里。它在哪里？", "Belfast的Stormont|Edinburgh的Holyrood|Cardiff Bay|Westminster", "设于Belfast Stormont的Northern Ireland Assembly有90名议员（MLAs），以权力分享的方式运作。"],
  1827: ["关于Hansard，以下哪一项不正确？", "它记录中世纪的土地所有权|它记录议会辩论|它每日出版|它可在网上查阅", "Hansard记录议会辩论——记录中世纪土地所有权则是更为古老的Domesday Book的用途。"],
  1828: ["以下关于君主的哪项陈述是正确的？", "君主保持政治中立，不在政治上偏袒任何一方|君主决定议会通过哪些法律|君主任命所有议员|君主领导最大的政党", "君主是国家元首，但超然于党派政治之上，定期会见Prime Minister以提出建议与告诫。"],
  1835: ["关于君主在State Opening of Parliament宣读的演说，以下哪一项不正确？", "君主亲自撰写|由政府撰写|它阐述政府来年的施政方针|它在State Opening上宣读", "君主在State Opening宣读的演说由政府撰写，而非君主本人。"],
  1838: ["一位即将年满17岁的朋友问他能否在下次大选中投票。你会怎么说？", "不能——他必须等到年满18岁|能——投票年龄是17岁|能，但只能参加地方选举|不能——投票年龄是21岁", "须年满18岁并登记在electoral register上，方可在大选中投票。"],
  1843: ["关于UK投票站的开放时间，以下哪一项不正确？", "它们下午5点关闭|它们上午7点开放|它们晚上10点关闭|选举日当天开放15小时", "投票站晚上10点关闭而非下午5点——从上午7点开放到晚上10点，共15小时。"],
  1846: ["一位朋友问，由君主担任首脑的自愿联合体Commonwealth有多少个国家。有多少？", "54|27|15|100", "Commonwealth是由54个国家组成的自愿联合体；君主是其首脑，对成员国没有权力。"],
  1851: ["关于UK在UN Security Council中的地位，以下哪一项不正确？", "UK只是轮值的临时成员|UK是常任理事国|UK可以否决提案|常任理事国共有五个", "UK是UN Security Council的常任理事国，而非轮值的临时成员，并可以否决提案。"],
  1854: ["一位朋友问，若NATO某成员遭到攻击，其他成员承诺怎么做。答案是什么？", "作为集体防御的一部分彼此援助|制定共同的贸易规则|管理共同货币|什么也不做——NATO没有防御职能", "NATO的主要宗旨是集体防御——成员国约定，若遭到攻击则彼此援助。"],
  1859: ["关于Council of Europe，以下哪一项不正确？", "它有权为成员国制定具约束力的法律|它保护人权|它监督European Convention on Human Rights|它没有立法权", "Council of Europe明确没有立法权——它通过European Convention on Human Rights保护人权。"],
  1862: ["一位朋友问，在England和Wales，由无薪志愿者在没有陪审团的情况下审理轻微刑事案件的是哪个法院。是哪个法院？", "The Magistrates' Court|The Crown Court|The County Court|The High Court", "Magistrates' Court在England和Wales审理轻微刑事案件；magistrates是无薪志愿者，在没有陪审团的情况下审案。"],
  1867: ["关于Scotland的轻微刑事案件，以下哪一项不正确？", "与England和Wales一样在Magistrates' Court审理|通常在Justice of the Peace Court审理|Scotland有自己独立的法律体系|Sheriff Courts也是苏格兰体系的一部分", "Scotland不设Magistrates' Courts——那是England和Wales的制度。Scotland改用Justice of the Peace Courts和Sheriff Courts。"],
  1870: ["一位朋友问，在England、Wales或Northern Ireland的Crown Court案件中有多少名陪审员。有多少？", "12|15|10|8", "陪审团在England、Wales和Northern Ireland为12人，在Scotland为15人。"],

  /* ---------- DOUBLES — CHAPTER 5 ---------- */
  1875: ["关于UK的刑事责任年龄，以下哪一项不正确？", "它在UK各地都相同|在England、Wales和Northern Ireland为10岁|在Scotland为12岁|它在Scotland与UK其他地区不同", "刑事责任年龄在UK各地并不一致——England、Wales和Northern Ireland为10岁，Scotland则为12岁。"],
  1878: ["一位朋友因一笔未偿债务而有小额索赔纠纷。在England或Wales应由哪个法院处理？", "The County Court|The Crown Court|The Magistrates' Court|The High Court", "County Courts处理债务、人身伤害和违约等民事事务。"],
  1883: ["关于Citizens Advice，以下哪一项不正确？", "它是一个政府部门|它是一个慈善机构网络|它提供免费咨询|它是保密的", "Citizens Advice是一个慈善机构网络，而非政府部门。"],
  1886: ["一位朋友把强迫婚姻与包办婚姻混为一谈。以下哪两项在UK确实违法？（请选择两个答案）", "强迫婚姻|女性生殖器切割|双方完全同意的包办婚姻|穿着宗教服饰", "强迫婚姻和FGM是严重刑事犯罪。双方均同意的包办婚姻则是合法的。"],
  1891: ["以下哪一项不是National Insurance所资助的？", "车祸保险理赔|国家福利|国家养老金|几乎每位劳动者都缴款的项目", "National Insurance用于国家福利和国家养老金——车祸保障属于机动车保险的范畴，是另一回事，且属私人事务。"],
  1894: ["一位刚开始受雇工作的朋友问，在PAYE制度下由谁负责代扣其所得税。是谁？", "他的雇主|他自己，通过self-assessment|他所在的地方议会|他的银行", "在PAYE（Pay As You Earn）制度下，由雇主从工资中代扣所得税；自雇者通常通过self-assessment纳税。"],
  1899: ["关于self-assessment报税截止日期，以下哪一项不正确？", "纸质截止日期晚于网上截止日期|网上截止日期是31 January|纸质截止日期是31 October|纸质报税表须比网上更早提交", "纸质截止日期（31 October）早于网上截止日期（31 January），而非更晚。"],
  1902: ["一位即将年满17岁的朋友问他现在能否合法驾车。你会怎么说？", "能——17岁是驾驶汽车的法定年龄|不能——法定年龄是18岁|不能——法定年龄是21岁|能，但须已持有完整驾照", "在UK，17岁可驾驶汽车或摩托车，16岁可骑轻便摩托车。"],
  1907: ["关于MOT检验，以下哪一项不正确？", "全新汽车在购车当天就需要检验|汽车首次检验是在车龄满三年时|此后MOT检验每年进行|检验用以确认车辆适合上路", "全新汽车无须立即接受MOT——首次检验要到车龄满三年时才需要。"],
  1910: ["一位朋友想更多参与本地事务。以下哪两项确实算作参与社区？（请选择两个答案）", "成为school governor|为慈善机构做志愿者|被传召时拒绝jury service|不参加地方选举", "你也可以加入neighbourhood watch、成为magistrate或special constable，或在当地医院帮忙。"],
  1915: ["关于担任陪审员的资格，以下哪一项不正确？", "只有受过训练的律师才能担任陪审员|人员从electoral register中随机抽选|合资格年龄大致为18至70岁|jury service是一项公民义务", "陪审员是从electoral register中随机抽选的普通民众——律师并非特殊或必需的群体。"],
  1918: ["一位朋友问，除驾照和road tax外，在UK道路上驾车前法律上还需要什么。还需要什么？", "机动车保险|大学学位|居留许可|停车许可", "所有驾驶者都必须有机动车保险；无保险驾驶属刑事犯罪，此外还须持有效驾照并缴纳road tax。"],
  1923: ["如果你认为自己受到警方不公正对待，以下哪一项不是正当的回应？", "从此拒绝服从警方的合法指示|向警队提出正式投诉|向独立机构提出投诉|使用正式投诉程序", "拒绝服从合法指示并非正当回应——正确途径是向警队或独立机构提出正式投诉。"],
  1926: ["一位朋友问，在England和Wales由民众选出、负责监督地方警队的是什么职务。它叫什么？", "一位Police and Crime Commissioner|一名高级警官|一名Home Office公务员|一名magistrate", "Police and Crime Commissioners（PCCs）由England和Wales的民众选出，负责监督地方警队。"],
  1928: ["以下关于地方议会经费的哪项陈述是正确的？", "地方议会的经费来自中央政府和地方council tax|地方议会仅靠捐款维持|地方议会不获得政府拨款|地方议会由君主提供经费", "议会提供垃圾收集、图书馆和学校等服务。"],
  1935: ["关于UK的国家元首与政府首脑，以下哪一项不正确？", "Prime Minister是国家元首|君主是国家元首|Prime Minister是政府首脑|这是两个不同的职位", "国家元首是君主而非Prime Minister——Prime Minister则是政府首脑。"],
  1938: ["一位朋友问，描述单一议员所代表地理区域的术语是什么。是哪个术语？", "选区（constituency）|政党|政府部门|议会分区（ward）", "选区是议员所代表的区域；共有650个选区，每个选出一位议员。"],
  1943: ["关于by-election，以下哪一项不正确？", "它像大选一样每五年固定举行|它在某个席位出缺时举行|它可能因议员辞职而举行|它可能因议员去世而举行", "by-election并非按固定周期举行——只要有席位意外出缺就会举行，与大选固定的五年周期不同。"],
  1946: ["一位朋友问，就环境等单一议题开展运动的团体通常叫什么、又做些什么。答案是什么？", "压力团体，致力于影响政府政策|选举委员会，负责组织选举|税务机关，负责征税|司法小组，负责任命法官", "压力团体致力于就某一特定议题影响政府政策，代表英国公民在该议题上的意见。"],
  1951: ["以下哪一项不是UK法律的两大主要来源之一？", "君主亲自颁布的王室敕令|Acts of Parliament|Case law|法官的解释逐渐积累而成的common law", "UK的法律来自Acts of Parliament和case law——如今君主并不亲自颁布具约束力、可创制法律的敕令。"],
  1954: ["一位面临严重刑事指控的朋友无力聘请律师。他可能获得什么支持？", "Legal aid，用以支付solicitor或barrister的费用|一名警官将为他辩护|一名magistrate将为他辩护|没有任何支持", "视你的情况与案件而定，Legal aid可能会支付solicitor或barrister的费用。"],
  1959: ["关于Scotland的严重刑事案件，以下哪一项不正确？", "与England一样在Crown Court审理|在High Court of Justiciary或Sheriff Court审理|Scotland有自己独立的法律体系|Scotland的法院与England和Wales不同", "Scotland不设Crown Court——那是England、Wales和Northern Ireland采用的制度。Scotland另有自己独立的法院。"],
  1962: ["一位朋友因已付款的缺陷商品与某公司发生纠纷。正确的处理途径是什么？", "County Court或小额索赔程序|向警方报案|直接向议会申诉|The Crown Court", "针对已付款商品或服务的小额索赔，在England、Wales和Northern Ireland由County Courts处理，在Scotland由Sheriff Courts处理。"],
  1967: ["根据Equality Act，以下哪一项不属于非法歧视？", "向经验更丰富的员工支付更高薪酬|基于种族的歧视|基于残疾的歧视|基于宗教的歧视", "因经验更丰富而给予更高薪酬是正当的薪酬决定，而非歧视——Equality Act保护的是免受基于种族、残疾和宗教等理由的歧视。"],
  1970: ["一位初到UK的朋友问，在确需警察、消防或救护车的紧急情况下该拨打哪个号码。是哪个号码？", "999或112|911|101|111", "999或112是UK的紧急电话号码；101和111则用于非紧急事项。"],
  1975: ["在England，以下哪一个不是非紧急医疗咨询的正确号码？", "999|111|NHS帮助热线号码|情况没有生命危险时拨打的号码", "999用于真正的紧急情况——非紧急医疗咨询应通过NHS 111获取。"],
  1978: ["一位刚搬到新地区的朋友问，在那里如何登记注册家庭医生。他该怎么做？", "在当地的GP surgery登记|向Home Office申请|请雇主代为登记|等到需要住院治疗时再说", "在当地GP surgery登记即可注册家庭医生；对于非紧急的健康问题，GP通常是第一联系人。"],
  1983: ["以下哪一类人没有被取消参选MP的资格？", "年满18岁、符合条件的Commonwealth公民|现役武装部队成员|在职公务员|正在服刑的囚犯", "年满18岁、符合条件的Commonwealth公民可以参选MP——被取消资格的是武装部队成员、公务员和在押囚犯。"],
  1986: ["一位朋友想以参与社区的方式加入本地学校。他可以担任什么无薪职务？", "School governor|校长|地方议会雇员|政府督学", "成为school governor是以志愿方式协助管理学校并参与社区的一条途径。"],
  1991: ["关于jury service，以下哪一项不正确？", "只要缴费就可以免于出席|它是一项公共义务|有正当理由可获豁免|陪审员从electoral register中随机抽选", "不能仅靠缴费免于jury service——它是一项公共义务，只有正当理由才能免除出席。"],
  1994: ["一位朋友问，House of Commons的Speaker当选后是否就不再代表其选区。答案是什么？", "不是——Speaker仍以MP身份代表其选民|是——Speaker完全放弃其选区|是——Speaker转而代表政府|不是——但Speaker只主持辩论，别无其他", "Speaker仍是选区议员，继续代表其选民，但在Commons议事厅内必须保持政治中立。"],
  1999: ["关于House of Lords在审议法案中的作用，以下哪一项不正确？", "其决定永远不能被Commons推翻|它可对法案提出修正建议|它审议来自Commons的法案|Commons最终可以推翻它", "Commons最终可以推翻House of Lords——Lords对法案的决定并非终局且不可动摇。"],
  2002: ["一位朋友打算干脆不缴council tax账单。他可能因此面临什么后果？", "可能被起诉并承担额外费用|什么也不会——它完全是自愿的|护照可能被吊销|可能被驱逐出境", "不缴council tax可能导致被起诉并承担额外费用——它并非自愿缴纳的款项。"],
  2007: ["以下哪一项不是权力下放（devolved power）的例子？", "君主亲自掌握的权力|Scotland对卫生等领域的管理权|Wales对教育等领域的管理权|Northern Ireland权力下放行政机构的权力", "权力下放是指中央政府将权力移交给Scottish Parliament等机构——它们并非君主亲自掌握的权力。"],
  2010: ["一位在UK开始第一份工作的朋友问，作为劳动者他现在负有什么财务责任。是什么？", "缴纳所得税和National Insurance|加入工会|每次选举都投票|担任magistrate", "每位在UK工作的居民都有责任缴纳所得税和National Insurance，用以支付道路、学校和NHS等公共服务。"],
};
