/* ============================================================
   QUESTION VARIANTS — Chapter 3h (History: the 1801 Act of Union
   through the origins of the Commonwealth, base i:223-236 — the
   second half of EXTRA_Q's chapter 3 questions, and the last of
   chapter 3). See chapter1.js for format notes.
   ============================================================ */

export default [
  // ---- base i:223 — 1801: Act of Union with Ireland ----
  { i: 1480, base: 223, variant: "rephrase", c: 3, q: "In which year did the Act of Union with Ireland create the United Kingdom of Great Britain and Ireland?", o: ["1801", "1707", "1922", "1689"], a: [0], e: "Ireland joined the union in 1801; most of it left in 1922." },
  { i: 1481, base: 223, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? The Act of Union with Ireland took effect in 1801.", o: ["True", "False"], a: [0], e: "Ireland joined the union in 1801; most of it left in 1922." },
  { i: 1482, base: 223, variant: "scenario", c: 3, q: "A friend asks in which year Ireland formally joined the union with Great Britain. Which year is it?", o: ["1801", "1707", "1922", "1689"], a: [0], e: "Ireland joined the union in 1801; most of it left in 1922." },
  { i: 1483, base: 223, variant: "exception", c: 3, q: "Which of these is NOT true about the Act of Union with Ireland?", o: ["It happened in the same year as the Union with Scotland", "It took effect in 1801", "It created the United Kingdom of Great Britain and Ireland", "Most of Ireland later left the union in 1922"], a: [0], e: "The Union with Ireland was in 1801, almost a century after the 1707 Union with Scotland — they were not in the same year." },

  // ---- base i:224 — Richard Arkwright: spinning machinery ----
  { i: 1484, base: 224, variant: "rephrase", c: 3, q: "Which invention by Richard Arkwright was important to the Industrial Revolution?", o: ["Efficient and profitable spinning machinery for cloth", "The steam locomotive", "The telephone", "The electric light"], a: [0], e: "Arkwright's factories transformed the production of textiles." },
  { i: 1485, base: 224, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? Richard Arkwright developed efficient spinning machinery for cloth production.", o: ["True", "False"], a: [0], e: "Arkwright's factories transformed the production of textiles." },
  { i: 1486, base: 224, variant: "scenario", c: 3, q: "A friend asks what invention Richard Arkwright is known for, which transformed textile production. What was it?", o: ["Efficient spinning machinery for cloth", "The steam locomotive", "The telephone", "James Watt's steam engine"], a: [0], e: "Arkwright's spinning machinery and factories transformed the production of textiles." },
  { i: 1487, base: 224, variant: "exception", c: 3, q: "Which of these is NOT true about Richard Arkwright?", o: ["He built bridges, railways and ships", "He developed spinning machinery for cloth", "His factories transformed textile production", "He was a key figure in the Industrial Revolution"], a: [0], e: "Arkwright is known for spinning machinery and factories. Building bridges, railways and ships was Isambard Kingdom Brunel's achievement." },

  // ---- base i:225 — Isambard Kingdom Brunel ----
  { i: 1488, base: 225, variant: "rephrase", c: 3, q: "Isambard Kingdom Brunel is famous for what?", o: ["Building bridges, railways and ships", "Discovering penicillin", "Founding the NHS", "Writing novels"], a: [0], e: "Brunel built the Great Western Railway and ships including the SS Great Britain." },
  { i: 1489, base: 225, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? Isambard Kingdom Brunel is famous for building bridges, railways and ships.", o: ["True", "False"], a: [0], e: "Brunel built the Great Western Railway and ships including the SS Great Britain." },
  { i: 1490, base: 225, variant: "scenario", c: 3, q: "A friend asks who built the Great Western Railway and the SS Great Britain. Who was it?", o: ["Isambard Kingdom Brunel", "Richard Arkwright", "James Watt", "George Stephenson"], a: [0], e: "Brunel built the Great Western Railway and ships including the SS Great Britain." },
  { i: 1491, base: 225, variant: "exception", c: 3, q: "Which of these did Isambard Kingdom Brunel NOT build?", o: ["A national health system", "The Great Western Railway", "The SS Great Britain", "Famous bridges"], a: [0], e: "Brunel built railways, bridges and ships. The NHS was founded much later, in 1948, by Aneurin Bevan." },

  // ---- base i:226 — the Great Exhibition of 1851 ----
  { i: 1492, base: 226, variant: "rephrase", c: 3, q: "What was the Great Exhibition of 1851 held to celebrate?", o: ["Industry and culture from Britain and around the world", "The end of the Napoleonic Wars", "Queen Victoria's coronation", "The founding of the Empire"], a: [0], e: "It was held in the Crystal Palace in Hyde Park." },
  { i: 1493, base: 226, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? The Great Exhibition of 1851 celebrated industry and culture from around the world.", o: ["True", "False"], a: [0], e: "It was held in the Crystal Palace in Hyde Park." },
  { i: 1494, base: 226, variant: "scenario", c: 3, q: "A friend asks what the Great Exhibition, held in the Crystal Palace in 1851, was celebrating. What was it?", o: ["Industry and culture from Britain and around the world", "The end of the Napoleonic Wars", "Queen Victoria's coronation", "Victory in the Crimean War"], a: [0], e: "The Great Exhibition of 1851, held in the Crystal Palace in Hyde Park, celebrated industry and culture from Britain and around the world." },
  { i: 1495, base: 226, variant: "exception", c: 3, q: "Which of these is NOT true about the Great Exhibition of 1851?", o: ["It was held to mark the end of the Crimean War", "It was held in the Crystal Palace", "It celebrated industry and culture", "It took place in Hyde Park"], a: [0], e: "The Great Exhibition of 1851 celebrated industry and culture from around the world — the Crimean War (1853-56) had not yet even begun." },

  // ---- base i:227 — Mary Seacole ----
  { i: 1496, base: 227, variant: "rephrase", c: 3, q: "Who was Mary Seacole?", o: ["A nurse from Jamaica who treated wounded soldiers in the Crimea", "The first woman doctor in Britain", "A suffragette leader", "A wartime prime minister"], a: [0], e: "She set up a hotel for sick and wounded soldiers and is now honoured with a statue in London." },
  { i: 1497, base: 227, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? Mary Seacole was a nurse from Jamaica who treated wounded soldiers in the Crimea.", o: ["True", "False"], a: [0], e: "She set up a hotel for sick and wounded soldiers and is now honoured with a statue in London." },
  { i: 1498, base: 227, variant: "scenario", c: 3, q: "A friend asks about a Jamaican nurse honoured with a statue in London for her Crimean War work. Who was she?", o: ["Mary Seacole", "Florence Nightingale", "Elizabeth Fry", "Emmeline Pankhurst"], a: [0], e: "Mary Seacole was a nurse from Jamaica who treated wounded soldiers in the Crimea and set up a hotel for the sick and wounded." },
  { i: 1499, base: 227, variant: "exception", c: 3, q: "Which of these is NOT true about Mary Seacole?", o: ["She led the suffragette movement", "She was from Jamaica", "She treated wounded soldiers in the Crimea", "She is honoured with a statue in London"], a: [0], e: "Mary Seacole was a nurse in the Crimean War. The suffragette movement was led by Emmeline Pankhurst, in a later era." },

  // ---- base i:228 — Emmeline Pankhurst's campaigners: the suffragettes ----
  { i: 1500, base: 228, variant: "rephrase", c: 3, q: "Emmeline Pankhurst's campaigners were commonly known as what?", o: ["Suffragettes", "Chartists", "Levellers", "Jacobites"], a: [0], e: "The suffragettes campaigned for votes for women, using increasingly militant methods before the First World War." },
  { i: 1501, base: 228, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? Emmeline Pankhurst's campaigners were known as suffragettes.", o: ["True", "False"], a: [0], e: "The suffragettes campaigned for votes for women, using increasingly militant methods before the First World War." },
  { i: 1502, base: 228, variant: "scenario", c: 3, q: "A friend asks what name is given to Emmeline Pankhurst's campaigners for women's votes. What is it?", o: ["Suffragettes", "Chartists", "Levellers", "Roundheads"], a: [0], e: "The suffragettes campaigned for votes for women, using increasingly militant methods before the First World War." },
  { i: 1503, base: 228, variant: "exception", c: 3, q: "Which of these is NOT true about the suffragettes?", o: ["They campaigned in the 17th century, during the Civil War", "They campaigned for votes for women", "They used increasingly militant methods", "They were active before the First World War"], a: [0], e: "The suffragettes campaigned before the First World War, in the early 20th century — not during the 17th-century Civil War." },

  // ---- base i:229 — Britain's WWI allies: France, Russia, later the US ----
  { i: 1504, base: 229, variant: "rephrase", c: 3, q: "Which countries were Britain's main allies in the First World War?", o: ["France, Russia and later the United States", "Germany and Austria", "Italy and Japan only", "Spain and Portugal"], a: [0], e: "Britain fought alongside France, Russia, and later Italy, Japan and the United States." },
  { i: 1505, base: 229, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? Britain's main First World War allies included France, Russia and later the United States.", o: ["True", "False"], a: [0], e: "Britain fought alongside France, Russia, and later Italy, Japan and the United States." },
  { i: 1506, base: 229, variant: "scenario", c: 3, q: "A friend asks which major countries fought alongside Britain in the First World War. Which were they?", o: ["France, Russia and later the United States", "Germany and Austria", "Italy and Japan only", "Spain and Portugal"], a: [0], e: "Britain fought alongside France, Russia, and later Italy, Japan and the United States." },
  { i: 1507, base: 229, variant: "exception", c: 3, q: "Which of these was NOT one of Britain's allies in the First World War?", o: ["Germany", "France", "Russia", "The United States, later in the war"], a: [0], e: "Britain's allies included France, Russia and later the United States. Germany was Britain's enemy in the First World War, not an ally." },

  // ---- base i:230 — the Blitz: bombing of British cities ----
  { i: 1508, base: 230, variant: "rephrase", c: 3, q: "What was the Blitz?", o: ["Heavy bombing of British cities by German aircraft", "The evacuation of Dunkirk", "The invasion of Normandy", "The defence of Malta"], a: [0], e: "London, Coventry and other cities were bombed heavily from 1940." },
  { i: 1509, base: 230, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? The Blitz was heavy bombing of British cities by German aircraft.", o: ["True", "False"], a: [0], e: "London, Coventry and other cities were bombed heavily from 1940." },
  { i: 1510, base: 230, variant: "scenario", c: 3, q: "A friend asks what name is given to the heavy German bombing of London, Coventry and other cities from 1940. What is it called?", o: ["The Blitz", "D-Day", "The Battle of the Somme", "Operation Dynamo"], a: [0], e: "The Blitz was heavy bombing of British cities by German aircraft; London, Coventry and other cities were bombed heavily from 1940." },
  { i: 1511, base: 230, variant: "exception", c: 3, q: "Which of these is NOT true about the Blitz?", o: ["It was an Allied bombing campaign against Germany", "It involved heavy bombing of British cities", "German aircraft carried it out", "It began in 1940"], a: [0], e: "The Blitz was Germany bombing British cities, not an Allied campaign against Germany — London and Coventry were among the cities hit." },

  // ---- base i:231 — Adolf Hitler: the German leader Britain fought ----
  { i: 1512, base: 231, variant: "rephrase", c: 3, q: "Which German leader did Britain fight in the Second World War?", o: ["Adolf Hitler", "Kaiser Wilhelm", "Otto von Bismarck", "Erich Ludendorff"], a: [0], e: "Britain declared war in 1939 after Germany invaded Poland." },
  { i: 1513, base: 231, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? Britain fought against Adolf Hitler's Germany in the Second World War.", o: ["True", "False"], a: [0], e: "Britain declared war in 1939 after Germany invaded Poland." },
  { i: 1514, base: 231, variant: "scenario", c: 3, q: "A friend asks which German leader Britain declared war on in 1939 after the invasion of Poland. Who was it?", o: ["Adolf Hitler", "Kaiser Wilhelm", "Otto von Bismarck", "Erich Ludendorff"], a: [0], e: "Britain declared war in 1939 after Germany, led by Adolf Hitler, invaded Poland." },
  { i: 1515, base: 231, variant: "exception", c: 3, q: "Which of these did NOT lead Germany during either world war fought against Britain?", o: ["Otto von Bismarck", "Adolf Hitler", "Kaiser Wilhelm", "The German government in 1914 and 1939 respectively"], a: [0], e: "Kaiser Wilhelm led Germany in the First World War and Hitler in the Second. Otto von Bismarck was an earlier 19th-century German chancellor, before either war." },

  // ---- base i:232 — the NHS and the welfare state (choose two) ----
  { i: 1516, base: 232, variant: "rephrase", c: 3, q: "Which TWO were established shortly after the Second World War? (Choose two answers)", o: ["The National Health Service", "The welfare state benefit system", "The European Union", "The Bank of England"], a: [0, 1], e: "The NHS began in 1948, and the Beveridge Report shaped the modern welfare state." },
  { i: 1517, base: 232, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? The National Health Service was established shortly after the Second World War.", o: ["True", "False"], a: [0], e: "The NHS began in 1948, and the Beveridge Report shaped the modern welfare state." },
  { i: 1518, base: 232, variant: "scenario", c: 3, q: "A friend asks what TWO major changes to British society followed shortly after the Second World War. Which were they? (Choose two answers)", o: ["The founding of the NHS", "The creation of the modern welfare state", "The UK joining the European Union", "The founding of the Bank of England"], a: [0, 1], e: "The NHS began in 1948, and the Beveridge Report shaped the modern welfare state, both shortly after the Second World War." },
  { i: 1519, base: 232, variant: "exception", c: 3, q: "Which of these was NOT established shortly after the Second World War?", o: ["The Bank of England, founded centuries earlier", "The National Health Service", "The modern welfare state benefit system", "Free healthcare at the point of use"], a: [0], e: "The NHS and modern welfare state were established after the Second World War in 1948. The Bank of England had already existed for centuries by then." },

  // ---- base i:233 — Crick and Wilkins: the structure of DNA ----
  { i: 1520, base: 233, variant: "rephrase", c: 3, q: "Which British scientists helped discover the structure of DNA?", o: ["Francis Crick and Maurice Wilkins", "Alexander Fleming and Howard Florey", "Charles Darwin and Alfred Wallace", "Isaac Newton and Robert Hooke"], a: [0], e: "The discovery was made in 1953 at Cambridge, working with James Watson." },
  { i: 1521, base: 233, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? Francis Crick and Maurice Wilkins helped discover the structure of DNA.", o: ["True", "False"], a: [0], e: "The discovery was made in 1953 at Cambridge, working with James Watson." },
  { i: 1522, base: 233, variant: "scenario", c: 3, q: "A friend asks which British scientists, working with James Watson, discovered the structure of DNA in 1953. Who were they?", o: ["Francis Crick and Maurice Wilkins", "Alexander Fleming and Howard Florey", "Charles Darwin and Alfred Wallace", "Isaac Newton and Robert Hooke"], a: [0], e: "Francis Crick and Maurice Wilkins helped discover the structure of DNA in 1953 at Cambridge, working with James Watson." },
  { i: 1523, base: 233, variant: "exception", c: 3, q: "Which of these did NOT contribute to the discovery of the structure of DNA?", o: ["Alexander Fleming", "Francis Crick", "Maurice Wilkins", "James Watson"], a: [0], e: "Crick, Wilkins and Watson discovered the structure of DNA in 1953. Alexander Fleming is known instead for discovering penicillin." },

  // ---- base i:234 — Christopher Cockerell invents the hovercraft ----
  { i: 1524, base: 234, variant: "rephrase", c: 3, q: "Who invented the hovercraft?", o: ["Sir Christopher Cockerell", "Sir Frank Whittle", "John Logie Baird", "Sir Tim Berners-Lee"], a: [0], e: "Cockerell, a British inventor, developed the hovercraft in the 1950s." },
  { i: 1525, base: 234, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? Sir Christopher Cockerell invented the hovercraft.", o: ["True", "False"], a: [0], e: "Cockerell, a British inventor, developed the hovercraft in the 1950s." },
  { i: 1526, base: 234, variant: "scenario", c: 3, q: "A friend asks who developed the hovercraft in the 1950s. Who was it?", o: ["Sir Christopher Cockerell", "Sir Frank Whittle", "John Logie Baird", "Alan Turing"], a: [0], e: "Cockerell, a British inventor, developed the hovercraft in the 1950s." },
  { i: 1527, base: 234, variant: "exception", c: 3, q: "Which of these is NOT true about Sir Christopher Cockerell?", o: ["He invented the jet engine", "He invented the hovercraft", "He developed it in the 1950s", "He was a British inventor"], a: [0], e: "Cockerell invented the hovercraft. The jet engine was invented by a different British inventor, Sir Frank Whittle." },

  // ---- base i:235 — Winston Churchill, wartime Prime Minister ----
  { i: 1528, base: 235, variant: "rephrase", c: 3, q: "Which of these was a famous British Prime Minister during the Second World War?", o: ["Winston Churchill", "Harold Wilson", "Stanley Baldwin", "Anthony Eden"], a: [0], e: "Churchill led the wartime coalition government from 1940 and returned as PM in 1951." },
  { i: 1529, base: 235, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? Winston Churchill led Britain's wartime coalition government during the Second World War.", o: ["True", "False"], a: [0], e: "Churchill led the wartime coalition government from 1940 and returned as PM in 1951." },
  { i: 1530, base: 235, variant: "scenario", c: 3, q: "A friend asks who led Britain's coalition government for most of the Second World War, and later returned as PM. Who was it?", o: ["Winston Churchill", "Harold Wilson", "Stanley Baldwin", "Neville Chamberlain, who returned in 1951"], a: [0], e: "Churchill led the wartime coalition government from 1940 and returned as Prime Minister again in 1951." },
  { i: 1531, base: 235, variant: "exception", c: 3, q: "Which of these is NOT true about Winston Churchill?", o: ["He never served as Prime Minister a second time", "He led the wartime coalition government from 1940", "He returned as Prime Minister in 1951", "He is remembered as a famous wartime leader"], a: [0], e: "Churchill served as Prime Minister twice: during the war from 1940, and again from 1951 — he did serve a second time." },

  // ---- base i:236 — the Commonwealth's origins: the former British Empire ----
  { i: 1532, base: 236, variant: "rephrase", c: 3, q: "What was the Commonwealth originally formed from?", o: ["Countries that were once part of the British Empire", "Members of the European Union", "Founding members of the United Nations", "NATO member states"], a: [0], e: "Most Commonwealth members are former British colonies, though membership is voluntary." },
  { i: 1533, base: 236, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? The Commonwealth was originally formed from countries that were once part of the British Empire.", o: ["True", "False"], a: [0], e: "Most Commonwealth members are former British colonies, though membership is voluntary." },
  { i: 1534, base: 236, variant: "scenario", c: 3, q: "A friend asks what most Commonwealth member countries have in common historically. What is the connection?", o: ["They were once part of the British Empire", "They are all members of the European Union", "They are all founding members of the United Nations", "They are all NATO member states"], a: [0], e: "Most Commonwealth members are former British colonies, though membership today is entirely voluntary." },
  { i: 1535, base: 236, variant: "exception", c: 3, q: "Which of these is NOT true about the Commonwealth?", o: ["Membership is compulsory for former British colonies", "Most members were once part of the British Empire", "Membership today is voluntary", "It grew out of the former British Empire"], a: [0], e: "Commonwealth membership is voluntary, not compulsory — countries choose to remain members even though they are fully independent." },
];
