/* ============================================================
   QUESTION VARIANTS — Chapter 5c (Government and law: the County
   Court through local council funding, base i:165-178 — the last of
   BASE_Q's chapter 5 questions). See chapter1.js for format notes.
   ============================================================ */

export default [
  // ---- base i:165 — the County Court: minor civil disputes ----
  { i: 1876, base: 165, variant: "rephrase", c: 5, q: "Which court handles minor civil disputes such as small claims in England and Wales?", o: ["The County Court", "The Crown Court", "The Magistrates' Court", "The Youth Court"], a: [0], e: "County Courts deal with civil matters such as debt, personal injury and breach of contract." },
  { i: 1877, base: 165, variant: "truefalse", c: 5, q: "Is this statement TRUE or FALSE? The County Court handles minor civil disputes in England and Wales.", o: ["True", "False"], a: [0], e: "County Courts deal with civil matters such as debt, personal injury and breach of contract." },
  { i: 1878, base: 165, variant: "scenario", c: 5, q: "A friend has a small claims dispute over an unpaid debt. Which court in England or Wales should handle it?", o: ["The County Court", "The Crown Court", "The Magistrates' Court", "The High Court"], a: [0], e: "County Courts deal with civil matters such as debt, personal injury and breach of contract." },
  { i: 1879, base: 165, variant: "exception", c: 5, q: "Which of these is NOT a type of case the County Court deals with?", o: ["Serious criminal trials with a jury", "Debt disputes", "Personal injury claims", "Breach of contract"], a: [0], e: "The County Court handles civil matters like debt and contract disputes — serious criminal trials with a jury are heard in the Crown Court instead." },

  // ---- base i:166 — Citizens Advice: free, independent advice ----
  { i: 1880, base: 166, variant: "rephrase", c: 5, q: "Which organisation gives free, independent advice on legal and money problems?", o: ["Citizens Advice", "The Home Office", "The Law Society only", "The Crown Prosecution Service"], a: [0], e: "Citizens Advice is a national network of charities offering free confidential advice." },
  { i: 1881, base: 166, variant: "truefalse", c: 5, q: "Is this statement TRUE or FALSE? Citizens Advice offers free, independent advice on legal and money problems.", o: ["True", "False"], a: [0], e: "Citizens Advice is a national network of charities offering free confidential advice." },
  { i: 1882, base: 166, variant: "scenario", c: 5, q: "A friend needs free, confidential advice about a legal or money problem. Which organisation should they contact?", o: ["Citizens Advice", "The Home Office", "The Law Society", "The Crown Prosecution Service"], a: [0], e: "Citizens Advice is a national network of charities offering free confidential advice on legal and money problems." },
  { i: 1883, base: 166, variant: "exception", c: 5, q: "Which of these is NOT true about Citizens Advice?", o: ["It is a government department", "It is a network of charities", "It offers free advice", "It is confidential"], a: [0], e: "Citizens Advice is a network of charities, not a government department." },

  // ---- base i:167 — two illegal practices: forced marriage and FGM (choose two) ----
  { i: 1884, base: 167, variant: "rephrase", c: 5, q: "Which TWO are illegal in the UK? (Choose two answers)", o: ["Forced marriage", "Female genital mutilation", "Arranged marriage between consenting adults", "Wearing religious dress"], a: [0, 1], e: "Forced marriage and FGM are serious criminal offences. Arranged marriage, where both people consent, is lawful." },
  { i: 1885, base: 167, variant: "truefalse", c: 5, q: "Is this statement TRUE or FALSE? Forced marriage is a criminal offence in the UK.", o: ["True", "False"], a: [0], e: "Forced marriage and FGM are serious criminal offences. Arranged marriage, where both people consent, is lawful." },
  { i: 1886, base: 167, variant: "scenario", c: 5, q: "A friend confuses forced marriage with arranged marriage. Which TWO of these are actually illegal in the UK? (Choose two answers)", o: ["Forced marriage", "Female genital mutilation", "Arranged marriage with full consent", "Wearing religious dress"], a: [0, 1], e: "Forced marriage and FGM are serious criminal offences. Arranged marriage, where both people consent, is lawful." },
  { i: 1887, base: 167, variant: "exception", c: 5, q: "Which of these is NOT illegal in the UK?", o: ["Arranged marriage between consenting adults", "Forced marriage", "Female genital mutilation", "Coercing someone into marriage"], a: [0], e: "Arranged marriage is lawful when both people freely consent — forced marriage and FGM, by contrast, are serious criminal offences." },

  // ---- base i:168 — National Insurance: funds benefits and the state pension ----
  { i: 1888, base: 168, variant: "rephrase", c: 5, q: "What is National Insurance used for?", o: ["Funding state benefits and the state pension", "Insuring your home", "Paying council tax", "Covering car accidents"], a: [0], e: "Almost everybody who works pays National Insurance contributions and needs a National Insurance number." },
  { i: 1889, base: 168, variant: "truefalse", c: 5, q: "Is this statement TRUE or FALSE? National Insurance funds state benefits and the state pension.", o: ["True", "False"], a: [0], e: "Almost everybody who works pays National Insurance contributions and needs a National Insurance number." },
  { i: 1890, base: 168, variant: "scenario", c: 5, q: "A friend starting their first job asks what their National Insurance contributions actually pay for. What is the answer?", o: ["State benefits and the state pension", "Home insurance", "Council tax", "Car accident cover"], a: [0], e: "National Insurance funds state benefits and the state pension; almost everyone who works pays contributions." },
  { i: 1891, base: 168, variant: "exception", c: 5, q: "Which of these is NOT what National Insurance funds?", o: ["Car accident insurance claims", "State benefits", "The state pension", "Programmes almost every worker contributes to"], a: [0], e: "National Insurance funds state benefits and the state pension — car accident cover is a separate, private matter of motor insurance." },

  // ---- base i:169 — PAYE: your employer deducts income tax ----
  { i: 1892, base: 169, variant: "rephrase", c: 5, q: "Under the PAYE system, who deducts income tax from your wages?", o: ["Your employer", "You, through self-assessment", "Your local council", "Your bank"], a: [0], e: "PAYE stands for Pay As You Earn; self-employed people usually pay tax through self-assessment." },
  { i: 1893, base: 169, variant: "truefalse", c: 5, q: "Is this statement TRUE or FALSE? Under PAYE, your employer deducts income tax from your wages.", o: ["True", "False"], a: [0], e: "PAYE stands for Pay As You Earn; self-employed people usually pay tax through self-assessment." },
  { i: 1894, base: 169, variant: "scenario", c: 5, q: "A friend starting an employed job asks who takes care of deducting their income tax under the PAYE system. Who does it?", o: ["Their employer", "They must do it themselves through self-assessment", "Their local council", "Their bank"], a: [0], e: "Under PAYE (Pay As You Earn), the employer deducts income tax from wages; self-employed people usually pay through self-assessment instead." },
  { i: 1895, base: 169, variant: "exception", c: 5, q: "Which of these is NOT true about the PAYE system?", o: ["It applies to self-employed people, who must always use it", "It stands for Pay As You Earn", "It is used by employers to deduct income tax", "Self-employed people usually use self-assessment instead"], a: [0], e: "PAYE is used by employers for employed workers — self-employed people usually pay tax through self-assessment, not PAYE." },

  // ---- base i:170 — online self-assessment deadline: 31 January ----
  { i: 1896, base: 170, variant: "rephrase", c: 5, q: "By what date must an online self-assessment tax return be filed?", o: ["31 January", "31 October", "5 April", "1 January"], a: [0], e: "Paper returns are due by 31 October and online returns by 31 January." },
  { i: 1897, base: 170, variant: "truefalse", c: 5, q: "Is this statement TRUE or FALSE? An online self-assessment tax return must be filed by 31 January.", o: ["True", "False"], a: [0], e: "Paper returns are due by 31 October and online returns by 31 January." },
  { i: 1898, base: 170, variant: "scenario", c: 5, q: "A friend plans to file their tax return online, rather than on paper. By what date must they file it?", o: ["31 January", "31 October", "5 April", "1 January"], a: [0], e: "Online self-assessment tax returns are due by 31 January; paper returns are due earlier, by 31 October." },
  { i: 1899, base: 170, variant: "exception", c: 5, q: "Which of these is NOT true about self-assessment tax return deadlines?", o: ["The paper deadline is later than the online deadline", "The online deadline is 31 January", "The paper deadline is 31 October", "Paper returns must be filed earlier than online ones"], a: [0], e: "The paper deadline (31 October) comes earlier than the online deadline (31 January), not later." },

  // ---- base i:171 — the driving age: 17 ----
  { i: 1900, base: 171, variant: "rephrase", c: 5, q: "At what age can you drive a car in the UK?", o: ["17", "16", "18", "21"], a: [0], e: "You can drive a car or motorcycle at 17, and ride a moped at 16." },
  { i: 1901, base: 171, variant: "truefalse", c: 5, q: "Is this statement TRUE or FALSE? You can drive a car in the UK from age 17.", o: ["True", "False"], a: [0], e: "You can drive a car or motorcycle at 17, and ride a moped at 16." },
  { i: 1902, base: 171, variant: "scenario", c: 5, q: "A friend turning 17 asks if they can now legally drive a car. What do you tell them?", o: ["Yes — 17 is the legal age to drive a car", "No — the legal age is 18", "No — the legal age is 21", "Yes, but only with a full licence already held"], a: [0], e: "You can drive a car or motorcycle at 17 in the UK, and ride a moped at 16." },
  { i: 1903, base: 171, variant: "exception", c: 5, q: "Which of these is NOT the correct legal driving age for a car in the UK?", o: ["16", "17", "The same age you can also ride a motorcycle", "One year older than the moped riding age"], a: [0], e: "The legal age to drive a car is 17, not 16 — 16 is instead the age at which you can ride a moped." },

  // ---- base i:172 — the first MOT test: when a car is three years old ----
  { i: 1904, base: 172, variant: "rephrase", c: 5, q: "When does a car need its first MOT test?", o: ["When it is three years old", "When it is one year old", "When it is five years old", "Immediately when bought"], a: [0], e: "Vehicles over three years old must pass an annual MOT test to be roadworthy." },
  { i: 1905, base: 172, variant: "truefalse", c: 5, q: "Is this statement TRUE or FALSE? A car needs its first MOT test when it is three years old.", o: ["True", "False"], a: [0], e: "Vehicles over three years old must pass an annual MOT test to be roadworthy." },
  { i: 1906, base: 172, variant: "scenario", c: 5, q: "A friend has just bought a brand new car. When will it first need an MOT test?", o: ["When it turns three years old", "When it turns one year old", "When it turns five years old", "Immediately, before it can be driven"], a: [0], e: "Vehicles over three years old must pass an annual MOT test — a brand new car does not need one immediately." },
  { i: 1907, base: 172, variant: "exception", c: 5, q: "Which of these is NOT true about the MOT test?", o: ["Brand new cars need one on the day of purchase", "Cars need their first one at three years old", "MOT tests are required annually after that", "The test checks that a vehicle is roadworthy"], a: [0], e: "A brand new car does not need an MOT immediately — the first test is due only once the car reaches three years old." },

  // ---- base i:173 — two ways of taking part in the community (choose two) ----
  { i: 1908, base: 173, variant: "rephrase", c: 5, q: "Which TWO are ways of taking part in your community? (Choose two answers)", o: ["Serving as a school governor", "Volunteering for a charity", "Refusing jury service", "Avoiding local elections"], a: [0, 1], e: "You can also join a neighbourhood watch, become a magistrate or special constable, or help at a local hospital." },
  { i: 1909, base: 173, variant: "truefalse", c: 5, q: "Is this statement TRUE or FALSE? Serving as a school governor is a way of taking part in your community.", o: ["True", "False"], a: [0], e: "You can also join a neighbourhood watch, become a magistrate or special constable, or help at a local hospital." },
  { i: 1910, base: 173, variant: "scenario", c: 5, q: "A friend wants to get more involved locally. Which TWO of these would genuinely count as community participation? (Choose two answers)", o: ["Becoming a school governor", "Volunteering for a charity", "Refusing jury service when called", "Skipping local elections"], a: [0, 1], e: "You can also join a neighbourhood watch, become a magistrate or special constable, or help at a local hospital." },
  { i: 1911, base: 173, variant: "exception", c: 5, q: "Which of these is NOT a way of taking part in your community?", o: ["Refusing jury service when called", "Serving as a school governor", "Volunteering for a charity", "Becoming a special constable"], a: [0], e: "Refusing jury service is not a form of community participation — jury service itself, if attended, is one of the recognised ways to take part." },

  // ---- base i:174 — jury service: from the electoral register, 18-70 ----
  { i: 1912, base: 174, variant: "rephrase", c: 5, q: "Who can be called for jury service?", o: ["Anyone on the electoral register aged 18 to 70", "Only lawyers", "Only people over 25", "Only British-born citizens"], a: [0], e: "Jury service is a duty, and people are chosen at random from the electoral register." },
  { i: 1913, base: 174, variant: "truefalse", c: 5, q: "Is this statement TRUE or FALSE? Anyone on the electoral register aged 18 to 70 can be called for jury service.", o: ["True", "False"], a: [0], e: "Jury service is a duty, and people are chosen at random from the electoral register." },
  { i: 1914, base: 174, variant: "scenario", c: 5, q: "A friend asks who is eligible to be randomly selected for jury service. Who is it?", o: ["Anyone on the electoral register aged 18 to 70", "Only qualified lawyers", "Only people over 25", "Only British-born citizens"], a: [0], e: "Jury service is a duty, and people are chosen at random from the electoral register — anyone aged 18 to 70 who is registered." },
  { i: 1915, base: 174, variant: "exception", c: 5, q: "Which of these is NOT true about eligibility for jury service?", o: ["Only trained lawyers can serve on a jury", "People are chosen at random from the electoral register", "The eligible age range is roughly 18 to 70", "Jury service is a civic duty"], a: [0], e: "Jurors are ordinary members of the public chosen at random from the electoral register — lawyers are not a special or required category." },

  // ---- base i:175 — drivers must have motor insurance ----
  { i: 1916, base: 175, variant: "rephrase", c: 5, q: "What must all drivers in the UK have?", o: ["Motor insurance", "A university degree", "A resident permit", "A parking permit"], a: [0], e: "Driving without insurance is a criminal offence; you also need a valid licence and road tax." },
  { i: 1917, base: 175, variant: "truefalse", c: 5, q: "Is this statement TRUE or FALSE? All drivers in the UK must have motor insurance.", o: ["True", "False"], a: [0], e: "Driving without insurance is a criminal offence; you also need a valid licence and road tax." },
  { i: 1918, base: 175, variant: "scenario", c: 5, q: "A friend asks what they legally need before driving a car on UK roads, besides a licence and road tax. What else is required?", o: ["Motor insurance", "A university degree", "A resident permit", "A parking permit"], a: [0], e: "All drivers must have motor insurance; driving without it is a criminal offence, alongside needing a valid licence and road tax." },
  { i: 1919, base: 175, variant: "exception", c: 5, q: "Which of these is NOT required of every UK driver?", o: ["A university degree", "Motor insurance", "A valid driving licence", "Road tax"], a: [0], e: "Drivers need motor insurance, a valid licence and road tax — a university degree has nothing to do with the legal requirements to drive." },

  // ---- base i:176 — complaining about the police ----
  { i: 1920, base: 176, variant: "rephrase", c: 5, q: "If you are stopped by the police and feel you have been treated unfairly, what can you do?", o: ["Make a complaint to the police force or an independent body", "Nothing can be done", "Only complain to your MP", "Refuse to obey any future instructions"], a: [0], e: "The police must obey the law, and there are formal complaints procedures if they do not." },
  { i: 1921, base: 176, variant: "truefalse", c: 5, q: "Is this statement TRUE or FALSE? You can make a formal complaint to the police force or an independent body if treated unfairly by police.", o: ["True", "False"], a: [0], e: "The police must obey the law, and there are formal complaints procedures if they do not." },
  { i: 1922, base: 176, variant: "scenario", c: 5, q: "A friend feels they were treated unfairly during a police stop. What is the correct way to raise this?", o: ["Make a formal complaint to the police force or an independent body", "Accept it, as nothing can be done", "Only raise it with their MP", "Refuse to cooperate with police from then on"], a: [0], e: "There are formal complaints procedures for raising concerns about police conduct, through the police force itself or an independent body." },
  { i: 1923, base: 176, variant: "exception", c: 5, q: "Which of these is NOT a legitimate response if you feel unfairly treated by the police?", o: ["Refusing to obey lawful police instructions from then on", "Making a formal complaint to the police force", "Making a complaint to an independent body", "Using the formal complaints procedure"], a: [0], e: "Refusing to obey lawful instructions is not a legitimate response — the proper route is a formal complaint to the police force or an independent body." },

  // ---- base i:177 — the Police and Crime Commissioner ----
  { i: 1924, base: 177, variant: "rephrase", c: 5, q: "What is a Police and Crime Commissioner?", o: ["An elected official who oversees local policing priorities", "A senior police officer", "A civil servant in the Home Office", "A judge in a criminal court"], a: [0], e: "PCCs are elected by the public in England and Wales to hold local police forces to account." },
  { i: 1925, base: 177, variant: "truefalse", c: 5, q: "Is this statement TRUE or FALSE? A Police and Crime Commissioner is an elected official overseeing local policing priorities.", o: ["True", "False"], a: [0], e: "PCCs are elected by the public in England and Wales to hold local police forces to account." },
  { i: 1926, base: 177, variant: "scenario", c: 5, q: "A friend asks who is elected by the public to hold local police forces to account in England and Wales. What is that role called?", o: ["A Police and Crime Commissioner", "A senior police officer", "A Home Office civil servant", "A magistrate"], a: [0], e: "Police and Crime Commissioners (PCCs) are elected by the public in England and Wales to hold local police forces to account." },
  { i: 1927, base: 177, variant: "exception", c: 5, q: "Which of these is NOT true about a Police and Crime Commissioner?", o: ["They are appointed by the Home Office, not elected", "They are elected by the public", "They oversee local policing priorities", "They operate in England and Wales"], a: [0], e: "Police and Crime Commissioners are elected by the public, not appointed by the Home Office." },

  // ---- base i:178 — local councils: funded by government and council tax ----
  { i: 1928, base: 178, variant: "rephrase", c: 5, q: "Which of these statements about local council funding is correct?", o: ["Local councils are funded by central government and local council tax", "Local councils are funded only by donations", "Local councils receive no government money", "Local councils are funded by the monarch"], a: [0], e: "Councils provide services such as rubbish collection, libraries and schools." },
  { i: 1929, base: 178, variant: "truefalse", c: 5, q: "Is this statement TRUE or FALSE? Local councils are funded by central government and local council tax.", o: ["True", "False"], a: [0], e: "Councils provide services such as rubbish collection, libraries and schools." },
  { i: 1930, base: 178, variant: "scenario", c: 5, q: "A friend asks where a local council gets the money it uses for services like rubbish collection and libraries. Where does it come from?", o: ["Central government and local council tax", "Donations only", "No government money at all", "The monarch"], a: [0], e: "Local councils are funded by central government and local council tax, and use this to provide services such as rubbish collection, libraries and schools." },
  { i: 1931, base: 178, variant: "exception", c: 5, q: "Which of these is NOT a source of funding for local councils?", o: ["Direct funding from the monarch", "Central government funding", "Local council tax", "A combination of government funding and council tax"], a: [0], e: "Local councils are funded by central government and local council tax — not by the monarch personally." },
];
