/* ============================================================
   QUESTION VARIANTS — Chapter 3f (History: Empire Windrush through
   Elizabeth II's accession, base i:86-98 — the last of BASE_Q's
   chapter 3 questions). See chapter1.js for format notes.
   ============================================================ */

export default [
  // ---- base i:86 — Empire Windrush, from the West Indies ----
  { i: 1372, base: 86, variant: "rephrase", c: 3, q: "The ship Empire Windrush, which arrived in 1948, carried workers from where?", o: ["The West Indies", "India", "Ireland", "Poland"], a: [0], e: "Post-war labour shortages led Britain to invite workers from the West Indies and later from India and Pakistan." },
  { i: 1373, base: 86, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? The Empire Windrush brought workers from the West Indies to Britain in 1948.", o: ["True", "False"], a: [0], e: "Post-war labour shortages led Britain to invite workers from the West Indies and later from India and Pakistan." },
  { i: 1374, base: 86, variant: "scenario", c: 3, q: "A friend asks where the passengers on the Empire Windrush travelled from in 1948. Where was it?", o: ["The West Indies", "India", "Ireland", "Poland"], a: [0], e: "Post-war labour shortages led Britain to invite workers from the West Indies, who arrived on the Empire Windrush in 1948." },
  { i: 1375, base: 86, variant: "exception", c: 3, q: "Which of these is NOT true about the Empire Windrush?", o: ["It arrived from India in 1948", "It carried workers from the West Indies", "It arrived in 1948", "Post-war labour shortages prompted the invitation to travel"], a: [0], e: "The Empire Windrush brought workers from the West Indies in 1948, addressing post-war labour shortages — not from India, though workers from India and Pakistan came somewhat later." },

  // ---- base i:87 — 1947: India, Pakistan and Ceylon become independent ----
  { i: 1376, base: 87, variant: "rephrase", c: 3, q: "In which year did India, Pakistan and Ceylon (Sri Lanka) become independent?", o: ["1947", "1922", "1966", "1973"], a: [0], e: "Independence for these countries began the rapid decolonisation of the British Empire." },
  { i: 1377, base: 87, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? India, Pakistan and Ceylon became independent in 1947.", o: ["True", "False"], a: [0], e: "Independence for these countries began the rapid decolonisation of the British Empire." },
  { i: 1378, base: 87, variant: "scenario", c: 3, q: "A friend asks in which year India, Pakistan and Ceylon gained independence from Britain. Which year is it?", o: ["1947", "1922", "1966", "1973"], a: [0], e: "India, Pakistan and Ceylon became independent in 1947, beginning the rapid decolonisation of the British Empire." },
  { i: 1379, base: 87, variant: "exception", c: 3, q: "Which of these events did NOT happen in 1947?", o: ["Ireland was divided into the Irish Free State and Northern Ireland", "India became independent", "Pakistan became independent", "Ceylon (Sri Lanka) became independent"], a: [0], e: "India, Pakistan and Ceylon became independent in 1947. Ireland was divided much earlier, in 1922." },

  // ---- base i:88 — 1973: the UK joins the EEC ----
  { i: 1380, base: 88, variant: "rephrase", c: 3, q: "In which year did the UK join the European Economic Community?", o: ["1973", "1957", "1969", "1992"], a: [0], e: "The UK joined the EEC in 1973 and left the European Union on 31 January 2020." },
  { i: 1381, base: 88, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? The UK joined the European Economic Community in 1973.", o: ["True", "False"], a: [0], e: "The UK joined the EEC in 1973 and left the European Union on 31 January 2020." },
  { i: 1382, base: 88, variant: "scenario", c: 3, q: "A friend asks in which year the UK joined the EEC, decades before it later left the EU. Which year is it?", o: ["1973", "1957", "1969", "1992"], a: [0], e: "The UK joined the EEC in 1973 and left the European Union on 31 January 2020." },
  { i: 1383, base: 88, variant: "exception", c: 3, q: "Which of these is NOT true about the UK and the EEC/EU?", o: ["The UK left the EU before it ever joined the EEC", "The UK joined the EEC in 1973", "The UK left the European Union in 2020", "The EEC later became the European Union"], a: [0], e: "The UK joined the EEC in 1973 and only left the European Union much later, in 2020 — it did not leave before joining." },

  // ---- base i:89 — Margaret Thatcher, first woman Prime Minister ----
  { i: 1384, base: 89, variant: "rephrase", c: 3, q: "Who was the first woman Prime Minister of the UK?", o: ["Margaret Thatcher", "Theresa May", "Emmeline Pankhurst", "Barbara Castle"], a: [0], e: "Margaret Thatcher was Prime Minister from 1979 to 1990, the longest-serving PM of the 20th century." },
  { i: 1385, base: 89, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? Margaret Thatcher was the UK's first woman Prime Minister.", o: ["True", "False"], a: [0], e: "Margaret Thatcher was Prime Minister from 1979 to 1990, the longest-serving PM of the 20th century." },
  { i: 1386, base: 89, variant: "scenario", c: 3, q: "A friend asks who became the UK's first female Prime Minister in 1979. Who was it?", o: ["Margaret Thatcher", "Theresa May", "Emmeline Pankhurst", "Indira Gandhi"], a: [0], e: "Margaret Thatcher was Prime Minister from 1979 to 1990, the longest-serving PM of the 20th century." },
  { i: 1387, base: 89, variant: "exception", c: 3, q: "Which of these is NOT true about Margaret Thatcher?", o: ["She led the suffragette movement", "She was the UK's first woman Prime Minister", "She served from 1979 to 1990", "She was the longest-serving PM of the 20th century"], a: [0], e: "Margaret Thatcher was the first woman Prime Minister, serving 1979-1990. The suffragette movement was led decades earlier by Emmeline Pankhurst." },

  // ---- base i:90 — 1998: the Belfast (Good Friday) Agreement ----
  { i: 1388, base: 90, variant: "rephrase", c: 3, q: "What was signed in Northern Ireland in 1998?", o: ["The Belfast (Good Friday) Agreement", "The Act of Union", "The Treaty of Rome", "The Bill of Rights"], a: [0], e: "The agreement led to a power-sharing Northern Ireland Assembly at Stormont." },
  { i: 1389, base: 90, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? The Belfast (Good Friday) Agreement was signed in 1998.", o: ["True", "False"], a: [0], e: "The agreement led to a power-sharing Northern Ireland Assembly at Stormont." },
  { i: 1390, base: 90, variant: "scenario", c: 3, q: "A friend asks what agreement, signed in 1998, led to a power-sharing assembly in Northern Ireland. What was it called?", o: ["The Belfast (Good Friday) Agreement", "The Act of Union", "The Treaty of Rome", "The Anglo-Irish Treaty"], a: [0], e: "The Belfast (Good Friday) Agreement of 1998 led to a power-sharing Northern Ireland Assembly at Stormont." },
  { i: 1391, base: 90, variant: "exception", c: 3, q: "Which of these is NOT true about the Belfast (Good Friday) Agreement?", o: ["It was signed in 1801", "It was signed in 1998", "It led to a power-sharing Assembly at Stormont", "It concerned Northern Ireland"], a: [0], e: "The Belfast (Good Friday) Agreement was signed in 1998 — 1801 is instead the year of the earlier Act of Union with Ireland." },

  // ---- base i:91 — 1999: Scottish Parliament and Welsh Assembly first meet ----
  { i: 1392, base: 91, variant: "rephrase", c: 3, q: "In which year did the Scottish Parliament and the Welsh Assembly first meet?", o: ["1999", "1979", "1989", "2007"], a: [0], e: "Referendums in 1997 led to devolved bodies that first met in 1999." },
  { i: 1393, base: 91, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? The Scottish Parliament and Welsh Assembly first met in 1999.", o: ["True", "False"], a: [0], e: "Referendums in 1997 led to devolved bodies that first met in 1999." },
  { i: 1394, base: 91, variant: "scenario", c: 3, q: "A friend asks in which year the devolved Scottish Parliament and Welsh Assembly first sat, following 1997 referendums. Which year is it?", o: ["1999", "1979", "1989", "2007"], a: [0], e: "Referendums in 1997 led to devolved bodies that first met in 1999." },
  { i: 1395, base: 91, variant: "exception", c: 3, q: "Which of these is NOT true about the devolved Scottish Parliament and Welsh Assembly?", o: ["They first met in 1979", "They first met in 1999", "Referendums preceded their creation in 1997", "They resulted from devolution"], a: [0], e: "The Scottish Parliament and Welsh Assembly first met in 1999, following referendums in 1997 — not 1979." },

  // ---- base i:92 — Alan Turing: codebreaking and computing ----
  { i: 1396, base: 92, variant: "rephrase", c: 3, q: "Alan Turing is best known for what?", o: ["Helping to break German codes and pioneering computer science", "Inventing the jet engine", "Discovering penicillin", "Developing radar"], a: [0], e: "Turing's work at Bletchley Park helped shorten the Second World War, and he is a founder of modern computing." },
  { i: 1397, base: 92, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? Alan Turing helped break German codes and pioneered computer science.", o: ["True", "False"], a: [0], e: "Turing's work at Bletchley Park helped shorten the Second World War, and he is a founder of modern computing." },
  { i: 1398, base: 92, variant: "scenario", c: 3, q: "A friend asks what Alan Turing is best remembered for. What is the correct answer?", o: ["Breaking German codes at Bletchley Park and pioneering computing", "Inventing the jet engine", "Discovering penicillin", "Founding the NHS"], a: [0], e: "Turing's work at Bletchley Park helped shorten the Second World War, and he is a founder of modern computing." },
  { i: 1399, base: 92, variant: "exception", c: 3, q: "Which of these is NOT one of Alan Turing's achievements?", o: ["Inventing the jet engine", "Helping break German codes at Bletchley Park", "Pioneering modern computer science", "Shortening the Second World War through his codebreaking work"], a: [0], e: "Turing's achievements were in codebreaking and computing. The jet engine was invented by a different British figure, Sir Frank Whittle." },

  // ---- base i:93 — Frank Whittle: the jet engine ----
  { i: 1400, base: 93, variant: "rephrase", c: 3, q: "Who invented the jet engine?", o: ["Sir Frank Whittle", "Sir Christopher Cockerell", "John Logie Baird", "Sir Bernard Lovell"], a: [0], e: "Sir Frank Whittle, an RAF engineer, patented the turbo jet engine in the 1930s." },
  { i: 1401, base: 93, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? Sir Frank Whittle invented the jet engine.", o: ["True", "False"], a: [0], e: "Sir Frank Whittle, an RAF engineer, patented the turbo jet engine in the 1930s." },
  { i: 1402, base: 93, variant: "scenario", c: 3, q: "A friend asks which RAF engineer patented the turbo jet engine in the 1930s. Who was it?", o: ["Sir Frank Whittle", "Sir Christopher Cockerell", "John Logie Baird", "Alan Turing"], a: [0], e: "Sir Frank Whittle, an RAF engineer, patented the turbo jet engine in the 1930s." },
  { i: 1403, base: 93, variant: "exception", c: 3, q: "Which of these is NOT true about Sir Frank Whittle?", o: ["He invented the hovercraft", "He was an RAF engineer", "He patented the jet engine", "His invention dates from the 1930s"], a: [0], e: "Frank Whittle invented the jet engine. The hovercraft was invented by Sir Christopher Cockerell, a different British inventor." },

  // ---- base i:94 — 1690: the Battle of the Boyne ----
  { i: 1404, base: 94, variant: "rephrase", c: 3, q: "Which battle in 1690 saw William III defeat James II in Ireland?", o: ["The Battle of the Boyne", "The Battle of Culloden", "The Battle of Naseby", "The Battle of Bannockburn"], a: [0], e: "The Battle of the Boyne is still commemorated by some in Northern Ireland today." },
  { i: 1405, base: 94, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? William III defeated James II at the Battle of the Boyne in 1690.", o: ["True", "False"], a: [0], e: "The Battle of the Boyne is still commemorated by some in Northern Ireland today." },
  { i: 1406, base: 94, variant: "scenario", c: 3, q: "A friend asks which 1690 battle in Ireland is still commemorated today, and who won it. What is the answer?", o: ["The Battle of the Boyne, won by William III", "The Battle of Culloden, won by the British government", "The Battle of Naseby, won by Parliament", "The Battle of Bannockburn, won by Robert the Bruce"], a: [0], e: "William III defeated James II at the Battle of the Boyne in 1690; it is still commemorated by some in Northern Ireland today." },
  { i: 1407, base: 94, variant: "exception", c: 3, q: "Which of these is NOT true about the Battle of the Boyne?", o: ["It took place in Scotland", "It took place in 1690", "William III defeated James II there", "It is still commemorated in Northern Ireland"], a: [0], e: "The Battle of the Boyne was fought in Ireland, not Scotland, in 1690, when William III defeated James II." },

  // ---- base i:95 — 1679: the Habeas Corpus Act ----
  { i: 1408, base: 95, variant: "rephrase", c: 3, q: "The Habeas Corpus Act of 1679 guaranteed what?", o: ["That no one could be held unlawfully without trial", "The right to vote", "Freedom of the press", "Free schooling"], a: [0], e: "Habeas corpus is a key protection against unlawful imprisonment." },
  { i: 1409, base: 95, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? The Habeas Corpus Act of 1679 protects against unlawful imprisonment without trial.", o: ["True", "False"], a: [0], e: "Habeas corpus is a key protection against unlawful imprisonment." },
  { i: 1410, base: 95, variant: "scenario", c: 3, q: "A friend asks what protection the 1679 Habeas Corpus Act provides. What is the correct answer?", o: ["Protection against being held unlawfully without trial", "The right to vote in elections", "Freedom of the press", "Free education for all"], a: [0], e: "Habeas corpus is a key protection against unlawful imprisonment, established by the 1679 Act." },
  { i: 1411, base: 95, variant: "exception", c: 3, q: "Which of these is NOT what the Habeas Corpus Act of 1679 guaranteed?", o: ["Free schooling for all children", "Protection against unlawful detention", "That a person could not be held without trial", "A safeguard against arbitrary imprisonment"], a: [0], e: "Habeas corpus is a protection against unlawful imprisonment without trial — it does not concern education." },

  // ---- base i:96 — the Highland Clearances ----
  { i: 1412, base: 96, variant: "rephrase", c: 3, q: "What were the Highland Clearances?", o: ["Landowners evicting tenants to make way for sheep farming", "The draining of Scottish marshland", "A programme of forest planting", "The removal of Roman ruins"], a: [0], e: "Many Scots were evicted from their homes in the Highlands and emigrated to America and elsewhere." },
  { i: 1413, base: 96, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? The Highland Clearances involved landowners evicting tenants for sheep farming.", o: ["True", "False"], a: [0], e: "Many Scots were evicted from their homes in the Highlands and emigrated to America and elsewhere." },
  { i: 1414, base: 96, variant: "scenario", c: 3, q: "A friend asks why many Scottish Highlanders emigrated to America in the 18th and 19th centuries. What is the explanation?", o: ["Landowners evicted them from their homes to make way for sheep farming", "A famine forced them to leave", "They were exiled after the Jacobite rebellions specifically", "The government relocated them for industrial work"], a: [0], e: "The Highland Clearances saw many Scots evicted from their homes by landowners to make way for sheep farming; many then emigrated to America and elsewhere." },
  { i: 1415, base: 96, variant: "exception", c: 3, q: "Which of these was NOT a feature of the Highland Clearances?", o: ["Landowners inviting tenants to stay for free", "Tenants being evicted from their homes", "Land being turned over to sheep farming", "Many Scots emigrating as a result"], a: [0], e: "The Highland Clearances involved landowners evicting tenants, not inviting them to stay — many evicted families emigrated to America and elsewhere." },

  // ---- base i:97 — 2020: the UK leaves the EU ----
  { i: 1416, base: 97, variant: "rephrase", c: 3, q: "In which year did the United Kingdom leave the European Union?", o: ["2020", "2016", "2019", "2021"], a: [0], e: "A referendum was held in 2016 and the UK formally left the EU on 31 January 2020." },
  { i: 1417, base: 97, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? The United Kingdom formally left the European Union in 2020.", o: ["True", "False"], a: [0], e: "A referendum was held in 2016 and the UK formally left the EU on 31 January 2020." },
  { i: 1418, base: 97, variant: "scenario", c: 3, q: "A friend confuses the EU referendum with the UK's actual departure. In which year did the UK formally leave the EU?", o: ["2020", "2016", "2019", "2021"], a: [0], e: "A referendum was held in 2016, but the UK did not formally leave the EU until 31 January 2020." },
  { i: 1419, base: 97, variant: "exception", c: 3, q: "Which of these is NOT true about the UK's departure from the European Union?", o: ["The UK left the EU the same year as the referendum", "A referendum on EU membership was held in 2016", "The UK formally left on 31 January 2020", "There was a gap of several years between the vote and departure"], a: [0], e: "The referendum was held in 2016, but formal departure did not happen until 2020 — a gap of about four years, not the same year." },

  // ---- base i:98 — 1952: Elizabeth II comes to the throne ----
  { i: 1420, base: 98, variant: "rephrase", c: 3, q: "In which year did Queen Elizabeth II come to the throne?", o: ["1952", "1936", "1945", "1960"], a: [0], e: "Elizabeth II reigned from 1952 until 2022 and was the longest-reigning British monarch." },
  { i: 1421, base: 98, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? Queen Elizabeth II came to the throne in 1952.", o: ["True", "False"], a: [0], e: "Elizabeth II reigned from 1952 until 2022 and was the longest-reigning British monarch." },
  { i: 1422, base: 98, variant: "scenario", c: 3, q: "A friend asks in which year Elizabeth II became queen, beginning the longest reign in British history. Which year is it?", o: ["1952", "1936", "1945", "1960"], a: [0], e: "Elizabeth II came to the throne in 1952 and reigned until 2022, the longest reign in British history." },
  { i: 1423, base: 98, variant: "exception", c: 3, q: "Which of these is NOT true about Queen Elizabeth II's reign?", o: ["It was shorter than Queen Victoria's reign", "It began in 1952", "It lasted until 2022", "It was the longest reign in British history"], a: [0], e: "Elizabeth II's reign, from 1952 to 2022, was the longest in British history — longer than Queen Victoria's 64 years, not shorter." },
];
