/* ============================================================
   QUESTION VARIANTS — Chapter 1 (Values and principles of the UK)

   Four variants per base question in this chapter (i:1-12, 201-204):
     rephrase   same fact, different wording
     truefalse  the fact recast as a true/false statement
     scenario   the fact framed as something to apply, not just recall
     exception  "which of these is NOT..." — tests the same topic
                from the opposite direction

   `base` names the original question id; `variant` names the type.
   Neither field is read by quizLogic.js — they exist so a variant's
   origin is traceable by eye, not by re-deriving it from the text.

   Same conventions as BASE_Q/EXTRA_Q: the correct option sits first
   in `o` with `a` pointing at it (randomise() shuffles at render
   time), UK proper nouns are kept exact, and every explanation
   stands on its own rather than assuming the base question was seen.
   ============================================================ */

export default [
  // ---- base i:1 — fundamental principle: the rule of law ----
  { i: 1000, base: 1, variant: "rephrase", c: 1, q: "Which of the following is considered a core principle of life in Britain?", o: ["The rule of law", "Mandatory military service for all adults", "A single official religion", "Government control of the press"], a: [0], e: "The fundamental principles include democracy, the rule of law, individual liberty, tolerance of different faiths and beliefs, and taking part in community life." },
  { i: 1001, base: 1, variant: "truefalse", c: 1, q: "Is this statement TRUE or FALSE? The rule of law is one of the fundamental principles of British life.", o: ["True", "False"], a: [0], e: "The fundamental principles include democracy, the rule of law, individual liberty, tolerance of different faiths and beliefs, and taking part in community life." },
  { i: 1002, base: 1, variant: "scenario", c: 1, q: "A friend studying for the Life in the UK test asks you to name one fundamental principle of British life. Which of these should you tell them?", o: ["The rule of law", "Compulsory military service", "A single national religion for all", "Government control of the press"], a: [0], e: "The fundamental principles include democracy, the rule of law, individual liberty, tolerance of different faiths and beliefs, and taking part in community life." },
  { i: 1003, base: 1, variant: "exception", c: 1, q: "Which of these is NOT a fundamental principle of British life?", o: ["A single national religion for all", "Democracy", "Individual liberty", "Tolerance of different faiths and beliefs"], a: [0], e: "The fundamental principles include democracy, the rule of law, individual liberty, tolerance of different faiths and beliefs, and taking part in community life. Britain has no single state religion." },

  // ---- base i:2 — two responsibilities: look after family, treat fairly ----
  { i: 1004, base: 2, variant: "rephrase", c: 1, q: "Which TWO of these are expected of people living in the UK? (Choose two answers)", o: ["Treating other people fairly", "Taking care of yourself and your family", "Attending a place of worship every week", "Becoming a member of a political party"], a: [0, 1], e: "Responsibilities include obeying the law, respecting the rights of others, treating people fairly, looking after yourself and your family, and looking after the area you live in." },
  { i: 1005, base: 2, variant: "truefalse", c: 1, q: "Is this statement TRUE or FALSE? People living in the UK are expected to look after themselves and their family.", o: ["True", "False"], a: [0], e: "Responsibilities include obeying the law, respecting the rights of others, treating people fairly, looking after yourself and your family, and looking after the area you live in." },
  { i: 1006, base: 2, variant: "scenario", c: 1, q: "Someone new to the UK asks what is expected of them as a resident. Which TWO of these should you mention? (Choose two answers)", o: ["Look after yourself and your family", "Treat others with fairness", "Attend a religious service every week", "Join a political party"], a: [0, 1], e: "Responsibilities include obeying the law, respecting the rights of others, treating people fairly, looking after yourself and your family, and looking after the area you live in." },
  { i: 1007, base: 2, variant: "exception", c: 1, q: "Which of these is NOT something people living in the UK are expected to do?", o: ["Attend a place of worship every week", "Look after their family", "Treat others fairly", "Look after the area they live in"], a: [0], e: "Responsibilities include obeying the law, respecting the rights of others, treating people fairly, looking after yourself and your family, and looking after the area you live in. Attending a place of worship is not a listed responsibility." },

  // ---- base i:3 — languages the test can be taken in ----
  { i: 1008, base: 3, variant: "rephrase", c: 1, q: "In which of these language options may a person sit the Life in the UK test?", o: ["English, Welsh or Scottish Gaelic", "English only", "Any official language of the EU", "English or French"], a: [0], e: "The test may be taken in English, Welsh or Scottish Gaelic." },
  { i: 1009, base: 3, variant: "truefalse", c: 1, q: "Is this statement TRUE or FALSE? The Life in the UK test can only be taken in English.", o: ["False", "True"], a: [0], e: "The test may be taken in English, Welsh or Scottish Gaelic — not English only." },
  { i: 1010, base: 3, variant: "scenario", c: 1, q: "A friend who is more confident in Welsh than in English asks if they can sit the Life in the UK test in Welsh. What do you tell them?", o: ["Yes — the test can be taken in English, Welsh or Scottish Gaelic", "No — the test is only offered in English", "No — they must take it in French instead", "Yes, but only with special permission from the Home Office"], a: [0], e: "The test may be taken in English, Welsh or Scottish Gaelic." },
  { i: 1011, base: 3, variant: "exception", c: 1, q: "Which of these is NOT a language the Life in the UK test can be taken in?", o: ["French", "English", "Welsh", "Scottish Gaelic"], a: [0], e: "The test may be taken in English, Welsh or Scottish Gaelic. French is not an option." },

  // ---- base i:4 — the pledge made at a citizenship ceremony ----
  { i: 1012, base: 4, variant: "rephrase", c: 1, q: "At a citizenship ceremony, alongside the oath or affirmation of allegiance, new citizens also do what?", o: ["Pledge to respect the UK's rights, freedoms and laws", "Promise to join the armed forces", "Make a donation to charity", "Formally give up all other nationalities"], a: [0], e: "New citizens swear or affirm allegiance to the monarch and pledge to respect the UK's rights, freedoms and laws." },
  { i: 1013, base: 4, variant: "truefalse", c: 1, q: "Is this statement TRUE or FALSE? At a citizenship ceremony, new citizens pledge to respect the UK's rights, freedoms and laws.", o: ["True", "False"], a: [0], e: "New citizens swear or affirm allegiance to the monarch and pledge to respect the UK's rights, freedoms and laws." },
  { i: 1014, base: 4, variant: "scenario", c: 1, q: "You are attending your own citizenship ceremony. Besides swearing or affirming allegiance to the King, what else will you be asked to do?", o: ["Pledge to respect the UK's rights, freedoms and laws", "Sign up for a National Insurance number", "Promise to vote in every election", "Agree to serve on a jury if called"], a: [0], e: "New citizens swear or affirm allegiance to the monarch and pledge to respect the UK's rights, freedoms and laws." },
  { i: 1015, base: 4, variant: "exception", c: 1, q: "Which of these is NOT something that happens at a citizenship ceremony?", o: ["A promise to serve in the armed forces", "An oath or affirmation of allegiance to the King", "A pledge to respect the UK's laws", "A pledge to respect the UK's freedoms"], a: [0], e: "New citizens swear or affirm allegiance to the monarch and pledge to respect the UK's rights, freedoms and laws — there is no promise of military service." },

  // ---- base i:5 — TRUE/FALSE: freedom of belief and religion ----
  { i: 1016, base: 5, variant: "rephrase", c: 1, q: "Which of these rights is shared by everyone in the UK?", o: ["Freedom of belief and religion", "The right to avoid paying tax", "The right to free housing", "The right to a state pension at any age"], a: [0], e: "Freedom of belief and religion is one of the rights and freedoms shared by everyone in the UK." },
  { i: 1017, base: 5, variant: "truefalse", c: 1, q: "Is this statement TRUE or FALSE? In the UK, people are free to hold and practise their own religious beliefs.", o: ["True", "False"], a: [0], e: "Freedom of belief and religion is one of the rights and freedoms shared by everyone in the UK." },
  { i: 1018, base: 5, variant: "scenario", c: 1, q: "A new resident is worried they will not be able to practise their religion freely in the UK. What can you tell them?", o: ["The UK guarantees freedom of belief and religion for everyone", "Only the established Church may be practised openly", "Religious freedom applies only to British citizens", "Freedom of religion applies only to Christians"], a: [0], e: "Freedom of belief and religion is one of the rights and freedoms shared by everyone in the UK, regardless of nationality." },
  { i: 1019, base: 5, variant: "exception", c: 1, q: "Which of these is NOT one of the rights and freedoms shared by everyone in the UK?", o: ["Guaranteed free private healthcare", "Freedom of belief and religion", "Freedom of speech", "A right to a fair trial"], a: [0], e: "Rights include freedom of belief and religion, freedom of speech, a fair trial and freedom from unfair discrimination. Free private healthcare is not guaranteed — NHS care is provided instead." },

  // ---- base i:6 — NOT a right or freedom: avoiding tax ----
  { i: 1020, base: 6, variant: "rephrase", c: 1, q: "Which of these is a responsibility rather than a right or freedom in the UK?", o: ["Paying tax", "A fair trial", "Freedom from unfair discrimination", "Freedom of speech"], a: [0], e: "Paying tax is a responsibility, not a freedom. Rights include free speech, freedom of belief, a fair trial and freedom from unfair discrimination." },
  { i: 1021, base: 6, variant: "truefalse", c: 1, q: "Is this statement TRUE or FALSE? Avoiding tax is one of the rights and freedoms shared by everyone in the UK.", o: ["False", "True"], a: [0], e: "Paying tax is a responsibility, not a right. Rights include free speech, freedom of belief, a fair trial and freedom from unfair discrimination." },
  { i: 1022, base: 6, variant: "scenario", c: 1, q: "Someone tells you that paying no tax is one of their rights as a UK resident. Are they correct?", o: ["No — paying tax is a responsibility, not a right", "Yes — everyone may choose whether to pay tax", "Yes, but only for the first year of residence", "No — only citizens are required to pay tax"], a: [0], e: "Paying tax is a responsibility, not a freedom. Rights include free speech, freedom of belief, a fair trial and freedom from unfair discrimination." },
  { i: 1023, base: 6, variant: "exception", c: 1, q: "Which of these is NOT a responsibility of people living in the UK?", o: ["Claiming exemption from all taxation", "Respecting and obeying the law", "Treating others with fairness", "Looking after the area you live in"], a: [0], e: "Responsibilities include obeying the law, respecting others' rights, treating people fairly, and looking after your family and area — not avoiding tax." },

  // ---- base i:7 — where citizenship ceremonies take place ----
  { i: 1024, base: 7, variant: "rephrase", c: 1, q: "Who normally organises citizenship ceremonies?", o: ["The local authority", "The Houses of Parliament", "The royal household", "The Home Office directly, with no local involvement"], a: [0], e: "Local authorities arrange citizenship ceremonies, normally within three months of the application being approved." },
  { i: 1025, base: 7, variant: "truefalse", c: 1, q: "Is this statement TRUE or FALSE? Citizenship ceremonies are arranged by local authorities.", o: ["True", "False"], a: [0], e: "Local authorities arrange citizenship ceremonies, normally within three months of the application being approved." },
  { i: 1026, base: 7, variant: "scenario", c: 1, q: "Your citizenship application has just been approved. Who will contact you to arrange your ceremony?", o: ["Your local authority", "The Houses of Parliament", "Buckingham Palace", "Your local police station"], a: [0], e: "Local authorities arrange citizenship ceremonies, normally within three months of the application being approved." },
  { i: 1027, base: 7, variant: "exception", c: 1, q: "Which of these is NOT true about citizenship ceremonies?", o: ["They are held at the Houses of Parliament", "They are arranged by the local authority", "They normally happen within three months of approval", "New citizens swear or affirm allegiance to the King there"], a: [0], e: "Local authorities arrange citizenship ceremonies, normally within three months of the application being approved — not the Houses of Parliament." },

  // ---- base i:8 — two things applicants must show ----
  { i: 1028, base: 8, variant: "rephrase", c: 1, q: "Which TWO of these must most applicants for permanent residence or citizenship demonstrate? (Choose two answers)", o: ["That they can speak and read English", "That they understand life in the UK well", "That they own property in the UK", "That they have lived in London"], a: [0, 1], e: "Applicants must show they can speak and read English and that they have a good understanding of life in the UK." },
  { i: 1029, base: 8, variant: "truefalse", c: 1, q: "Is this statement TRUE or FALSE? Applicants for citizenship must normally show they can speak and read English.", o: ["True", "False"], a: [0], e: "Applicants must show they can speak and read English and that they have a good understanding of life in the UK." },
  { i: 1030, base: 8, variant: "scenario", c: 1, q: "You are helping someone prepare their citizenship application. Which TWO things will they normally need to demonstrate? (Choose two answers)", o: ["A good understanding of life in the UK", "That they can speak and read English", "That they have lived in the UK for ten years", "That they own a home"], a: [0, 1], e: "Applicants must show they can speak and read English and that they have a good understanding of life in the UK." },
  { i: 1031, base: 8, variant: "exception", c: 1, q: "Which of these is NOT something applicants for permanent residence or citizenship normally need to show?", o: ["That they own property in the UK", "That they can speak and read English", "That they have a good understanding of life in the UK", "That they meet the residence requirements"], a: [0], e: "Applicants must show they can speak and read English and that they have a good understanding of life in the UK — property ownership is not a requirement." },

  // ---- base i:9 — community life as a fundamental principle ----
  { i: 1032, base: 9, variant: "rephrase", c: 1, q: "How is 'taking part in community life' best described?", o: ["A fundamental principle of British life", "A legal requirement for all residents", "Something only citizens may do", "A condition of employment"], a: [0], e: "Participation in community life is listed among the fundamental principles of British life." },
  { i: 1033, base: 9, variant: "truefalse", c: 1, q: "Is this statement TRUE or FALSE? Taking part in community life is one of the fundamental principles of British life.", o: ["True", "False"], a: [0], e: "Participation in community life is listed among the fundamental principles of British life." },
  { i: 1034, base: 9, variant: "scenario", c: 1, q: "A study partner says community involvement is only a legal requirement for citizens, not a wider principle. Are they right?", o: ["No — it is one of the fundamental principles of British life for everyone", "Yes — only citizens must take part", "Yes — it is a condition of employment", "No — it only applies to permanent residents"], a: [0], e: "Participation in community life is listed among the fundamental principles of British life." },
  { i: 1035, base: 9, variant: "exception", c: 1, q: "Which of these is NOT one of the fundamental principles of British life?", o: ["Employment status", "Participation in community life", "The rule of law", "Individual liberty"], a: [0], e: "The fundamental principles include democracy, the rule of law, individual liberty, tolerance of different faiths and beliefs, and taking part in community life — employment status is not among them." },

  // ---- base i:10 — TRUE/FALSE: duty to respect and obey the law ----
  { i: 1036, base: 10, variant: "rephrase", c: 1, q: "What is every person in the UK expected to do regarding the law?", o: ["Respect and obey it", "Only follow the laws they personally agree with", "Report any law they dislike to Parliament", "Obey it only once they become a citizen"], a: [0], e: "Respecting and obeying the law is a core responsibility of everyone living in the UK." },
  { i: 1037, base: 10, variant: "truefalse", c: 1, q: "Is this statement TRUE or FALSE? Only British citizens have a duty to respect and obey the law.", o: ["False", "True"], a: [0], e: "Respecting and obeying the law is a core responsibility of everyone living in the UK, not only citizens." },
  { i: 1038, base: 10, variant: "scenario", c: 1, q: "A new resident asks whether they must follow UK law even though they are not yet a citizen. What do you tell them?", o: ["Yes — everyone in the UK has a duty to respect and obey the law", "No — only citizens must obey the law", "Only once they have lived in the UK for five years", "Only if they plan to apply for citizenship"], a: [0], e: "Respecting and obeying the law is a core responsibility of everyone living in the UK." },
  { i: 1039, base: 10, variant: "exception", c: 1, q: "Which of these is NOT one of the responsibilities expected of everyone living in the UK?", o: ["Ignoring laws you personally disagree with", "Respecting and obeying the law", "Respecting the rights of others", "Treating people fairly"], a: [0], e: "Responsibilities include obeying the law, respecting the rights of others, and treating people fairly — the law applies whether or not you agree with it." },

  // ---- base i:11 — what democracy means ----
  { i: 1040, base: 11, variant: "rephrase", c: 1, q: "The UK is described as a democracy. What does that mean in practice?", o: ["Power is held by the people or their elected representatives", "Power is held by the monarch alone", "Power is held by the courts", "Power is held by the army"], a: [0], e: "In a democracy, the people hold power, either directly or through elected representatives." },
  { i: 1041, base: 11, variant: "truefalse", c: 1, q: "Is this statement TRUE or FALSE? In a democracy, power is held by the people or their elected representatives.", o: ["True", "False"], a: [0], e: "In a democracy, the people hold power, either directly or through elected representatives." },
  { i: 1042, base: 11, variant: "scenario", c: 1, q: "A new resident asks what it means to say the UK is a democracy. Which explanation is correct?", o: ["Power is held by the people or those they elect", "Power is held entirely by the monarch", "Power is held by the armed forces", "Power is held only by the courts"], a: [0], e: "In a democracy, the people hold power, either directly or through elected representatives." },
  { i: 1043, base: 11, variant: "exception", c: 1, q: "Which of these does NOT describe how power works in a democracy like the UK's?", o: ["Power rests permanently with the monarch alone", "The people hold power through elected representatives", "Citizens can vote in elections", "Governments can be voted out of office"], a: [0], e: "In a democracy, the people hold power, either directly or through elected representatives — not the monarch alone." },

  // ---- base i:12 — a responsibility rather than a right: the environment ----
  { i: 1044, base: 12, variant: "rephrase", c: 1, q: "Looking after the environment where you live is an example of what?", o: ["A responsibility", "A right", "A legal privilege reserved for citizens", "An optional courtesy"], a: [0], e: "Caring for the area you live in and the environment is one of the responsibilities of living in the UK." },
  { i: 1045, base: 12, variant: "truefalse", c: 1, q: "Is this statement TRUE or FALSE? Looking after the environment where you live is a right rather than a responsibility.", o: ["False", "True"], a: [0], e: "Caring for the area you live in and the environment is one of the responsibilities, not the rights, of living in the UK." },
  { i: 1046, base: 12, variant: "scenario", c: 1, q: "A neighbour says caring for the local environment is entirely optional. Are they correct?", o: ["No — it is one of the responsibilities of living in the UK", "Yes — it is a right you can choose to exercise", "Yes — it only applies to homeowners", "No — but it only applies to citizens"], a: [0], e: "Caring for the area you live in and the environment is one of the responsibilities of living in the UK." },
  { i: 1047, base: 12, variant: "exception", c: 1, q: "Which of these is a right rather than a responsibility?", o: ["A fair trial", "Looking after the area you live in", "Looking after your family", "Respecting the rights of others"], a: [0], e: "A fair trial is a right. Looking after your area, your family, and respecting others' rights are all responsibilities." },

  // ---- base i:201 — NOT a fundamental principle: loyalty to a political party ----
  { i: 1048, base: 201, variant: "rephrase", c: 1, q: "Which of these is not among the fundamental principles of British life?", o: ["Loyalty to a particular political party", "Individual liberty", "Democracy", "Tolerance of different faiths and beliefs"], a: [0], e: "The principles are democracy, the rule of law, individual liberty, tolerance of different faiths and beliefs, and participation in community life. Supporting a specific party is not among them." },
  { i: 1049, base: 201, variant: "truefalse", c: 1, q: "Is this statement TRUE or FALSE? Loyalty to a particular political party is one of the fundamental principles of British life.", o: ["False", "True"], a: [0], e: "The principles are democracy, the rule of law, individual liberty, tolerance of different faiths and beliefs, and participation in community life — not loyalty to any one party." },
  { i: 1050, base: 201, variant: "scenario", c: 1, q: "Someone claims that being loyal to one political party is a fundamental principle of British life. Are they correct?", o: ["No — that is not one of the fundamental principles", "Yes — every resident must support one party", "Yes, but only for citizens", "No — but voting itself is compulsory"], a: [0], e: "The principles are democracy, the rule of law, individual liberty, tolerance of different faiths and beliefs, and participation in community life." },
  { i: 1051, base: 201, variant: "exception", c: 1, q: "Which of these IS one of the fundamental principles of British life?", o: ["Tolerance of different faiths and beliefs", "Loyalty to a particular political party", "Support for a single newspaper", "Membership of a trade union"], a: [0], e: "The fundamental principles include democracy, the rule of law, individual liberty, tolerance of different faiths and beliefs, and participation in community life." },

  // ---- base i:202 — requirements before applying for citizenship ----
  { i: 1052, base: 202, variant: "rephrase", c: 1, q: "Before applying for permanent residence or citizenship, what must most applicants have done?", o: ["Passed the Life in the UK test and met the English language requirement", "Bought a house in the UK", "Completed a period of military service", "Joined a registered political party"], a: [0], e: "Both requirements must normally be met, unless you are exempt." },
  { i: 1053, base: 202, variant: "truefalse", c: 1, q: "Is this statement TRUE or FALSE? Most applicants must pass the Life in the UK test before they can apply for citizenship.", o: ["True", "False"], a: [0], e: "Both the Life in the UK test and the English language requirement must normally be met, unless you are exempt." },
  { i: 1054, base: 202, variant: "scenario", c: 1, q: "A friend asks what they need to complete before applying for citizenship. What should you tell them?", o: ["Pass the Life in the UK test and meet the English language requirement", "Own a home in the UK", "Serve in the armed forces", "Join a registered political party"], a: [0], e: "Both requirements must normally be met, unless you are exempt." },
  { i: 1055, base: 202, variant: "exception", c: 1, q: "Which of these is NOT normally required before applying for permanent residence or citizenship?", o: ["Owning property in the UK", "Passing the Life in the UK test", "Meeting the English language requirement", "Meeting the residence requirements"], a: [0], e: "Applicants must normally pass the Life in the UK test, meet the English language requirement, and meet residence requirements — property ownership is not required." },

  // ---- base i:203 — TRUE/FALSE: UK is a diverse, welcoming society ----
  { i: 1056, base: 203, variant: "rephrase", c: 1, q: "How would the UK's history of migration best be described?", o: ["A long history of welcoming new arrivals into a diverse society", "A history of discouraging all migration", "A recent phenomenon with no historical precedent", "Limited entirely to the last twenty years"], a: [0], e: "Migration has shaped British society for centuries, from the Anglo-Saxons and Vikings to more recent arrivals." },
  { i: 1057, base: 203, variant: "truefalse", c: 1, q: "Is this statement TRUE or FALSE? Migration is a recent phenomenon with no long history in Britain.", o: ["False", "True"], a: [0], e: "Migration has shaped British society for centuries, from the Anglo-Saxons and Vikings to more recent arrivals." },
  { i: 1058, base: 203, variant: "scenario", c: 1, q: "Someone claims migration to Britain only began in the last few decades. How would you correct them?", o: ["Migration has shaped Britain for centuries, long before recent decades", "They are right — it only began after 2000", "They are right — it only began after the Second World War", "Migration has never significantly shaped British society"], a: [0], e: "Migration has shaped British society for centuries, from the Anglo-Saxons and Vikings to more recent arrivals." },
  { i: 1059, base: 203, variant: "exception", c: 1, q: "Which of these groups is NOT mentioned as part of Britain's long history of migration?", o: ["The ancient Egyptians", "The Anglo-Saxons", "The Vikings", "More recent arrivals from around the world"], a: [0], e: "Migration has shaped British society for centuries, from the Anglo-Saxons and Vikings to more recent arrivals — ancient Egypt is not part of this history." },

  // ---- base i:204 — two ways to protect the local environment ----
  { i: 1060, base: 204, variant: "rephrase", c: 1, q: "Which TWO of these actions help protect the environment where you live? (Choose two answers)", o: ["Recycling your household waste", "Walking or cycling for short journeys", "Leaving rubbish in public parks", "Burning waste in your garden"], a: [0, 1], e: "Looking after the area you live in is one of the responsibilities of living in the UK." },
  { i: 1061, base: 204, variant: "truefalse", c: 1, q: "Is this statement TRUE or FALSE? Recycling your household waste is one way to help protect your local environment.", o: ["True", "False"], a: [0], e: "Looking after the area you live in is one of the responsibilities of living in the UK." },
  { i: 1062, base: 204, variant: "scenario", c: 1, q: "You want to do your part in looking after your local area. Which TWO of these would help? (Choose two answers)", o: ["Recycling household waste", "Walking or cycling for short journeys", "Burning rubbish in the garden", "Leaving litter in the park"], a: [0, 1], e: "Looking after the area you live in is one of the responsibilities of living in the UK." },
  { i: 1063, base: 204, variant: "exception", c: 1, q: "Which of these does NOT help protect the environment where you live?", o: ["Burning waste in your garden", "Recycling household waste", "Walking for short journeys", "Cycling instead of driving"], a: [0], e: "Recycling, walking and cycling all help protect the local environment. Burning waste in the garden does not." },
];
