/* ============================================================
   QUESTION VARIANTS — Chapter 5d (Government and law: head of state
   through unlawful discrimination at work, base i:256-265 — the
   first part of EXTRA_Q's chapter 5 questions). See chapter1.js for
   format notes.
   ============================================================ */

export default [
  // ---- base i:256 — the head of state: the monarch ----
  { i: 1932, base: 256, variant: "rephrase", c: 5, q: "Who is the head of state of the UK?", o: ["The monarch", "The Prime Minister", "The Speaker", "The Lord Chancellor"], a: [0], e: "The monarch is head of state; the Prime Minister is head of government." },
  { i: 1933, base: 256, variant: "truefalse", c: 5, q: "Is this statement TRUE or FALSE? The monarch is the UK's head of state.", o: ["True", "False"], a: [0], e: "The monarch is head of state; the Prime Minister is head of government." },
  { i: 1934, base: 256, variant: "scenario", c: 5, q: "A friend asks who holds the role of head of state in the UK, as distinct from head of government. Who is it?", o: ["The monarch", "The Prime Minister", "The Speaker", "The Lord Chancellor"], a: [0], e: "The monarch is head of state; the Prime Minister is head of government — two separate roles." },
  { i: 1935, base: 256, variant: "exception", c: 5, q: "Which of these is NOT true about the UK's head of state and head of government?", o: ["The Prime Minister is head of state", "The monarch is head of state", "The Prime Minister is head of government", "These are two separate roles"], a: [0], e: "The monarch is head of state, not the Prime Minister — the Prime Minister is head of government instead." },

  // ---- base i:257 — a constituency: the area an MP represents ----
  { i: 1936, base: 257, variant: "rephrase", c: 5, q: "What is a constituency?", o: ["The area an MP represents", "A political party", "A government department", "A type of court"], a: [0], e: "There are 650 constituencies, each electing one MP." },
  { i: 1937, base: 257, variant: "truefalse", c: 5, q: "Is this statement TRUE or FALSE? A constituency is the area that an MP represents.", o: ["True", "False"], a: [0], e: "There are 650 constituencies, each electing one MP." },
  { i: 1938, base: 257, variant: "scenario", c: 5, q: "A friend asks what term describes the geographical area a single MP represents. What is the term?", o: ["A constituency", "A political party", "A government department", "A council ward"], a: [0], e: "A constituency is the area an MP represents; there are 650 constituencies, each electing one MP." },
  { i: 1939, base: 257, variant: "exception", c: 5, q: "Which of these is NOT true about a constituency?", o: ["Each one elects several MPs at once", "It is a geographical area", "Each one elects one MP", "There are 650 of them"], a: [0], e: "Each constituency elects just one MP, not several — there are 650 constituencies in total." },

  // ---- base i:258 — a by-election: held when a seat becomes vacant ----
  { i: 1940, base: 258, variant: "rephrase", c: 5, q: "What is a by-election?", o: ["An election held when an MP's seat becomes vacant between general elections", "A second round of a general election", "An election for local councillors", "A referendum"], a: [0], e: "By-elections happen when an MP resigns or dies." },
  { i: 1941, base: 258, variant: "truefalse", c: 5, q: "Is this statement TRUE or FALSE? A by-election is held when an MP's seat becomes vacant between general elections.", o: ["True", "False"], a: [0], e: "By-elections happen when an MP resigns or dies." },
  { i: 1942, base: 258, variant: "scenario", c: 5, q: "A friend asks what happens if an MP resigns or dies in office, before the next scheduled general election. What is held to fill the seat?", o: ["A by-election", "A second round of the general election", "A local council election", "A referendum"], a: [0], e: "A by-election is held to fill a seat that becomes vacant between general elections, such as when an MP resigns or dies." },
  { i: 1943, base: 258, variant: "exception", c: 5, q: "Which of these is NOT true about a by-election?", o: ["It is scheduled at fixed five-year intervals like a general election", "It is held when a seat becomes vacant", "It can follow an MP's resignation", "It can follow an MP's death"], a: [0], e: "A by-election is not scheduled at fixed intervals — it happens whenever a seat unexpectedly becomes vacant, unlike the regular five-year cycle of general elections." },

  // ---- base i:259 — a pressure group: influences government policy ----
  { i: 1944, base: 259, variant: "rephrase", c: 5, q: "What is the role of a pressure group?", o: ["To influence government policy on a particular issue", "To run elections", "To collect taxes", "To appoint judges"], a: [0], e: "Pressure groups represent the views of British citizens on particular causes." },
  { i: 1945, base: 259, variant: "truefalse", c: 5, q: "Is this statement TRUE or FALSE? The role of a pressure group is to influence government policy on a particular issue.", o: ["True", "False"], a: [0], e: "Pressure groups represent the views of British citizens on particular causes." },
  { i: 1946, base: 259, variant: "scenario", c: 5, q: "A friend asks what a group campaigning on a single issue, such as the environment, is generally called, and what it does. What is the answer?", o: ["A pressure group, which aims to influence government policy", "An election commission, which runs elections", "A tax authority, which collects taxes", "A judicial panel, which appoints judges"], a: [0], e: "A pressure group aims to influence government policy on a particular issue, representing the views of British citizens on that cause." },
  { i: 1947, base: 259, variant: "exception", c: 5, q: "Which of these is NOT a role of a pressure group?", o: ["Collecting taxes on behalf of the government", "Influencing government policy", "Representing citizens' views on an issue", "Campaigning on a particular cause"], a: [0], e: "Pressure groups campaign and influence policy — collecting taxes is a government function, not something pressure groups do." },

  // ---- base i:260 — two sources of UK law: Acts of Parliament and case law ----
  { i: 1948, base: 260, variant: "rephrase", c: 5, q: "What are the two main sources of UK law?", o: ["Acts of Parliament and case law", "Royal decrees and church law", "European treaties only", "Local council rules"], a: [0], e: "Judges also interpret the law, and their decisions build up as common law." },
  { i: 1949, base: 260, variant: "truefalse", c: 5, q: "Is this statement TRUE or FALSE? The two main sources of UK law are Acts of Parliament and case law.", o: ["True", "False"], a: [0], e: "Judges also interpret the law, and their decisions build up as common law." },
  { i: 1950, base: 260, variant: "scenario", c: 5, q: "A friend asks where UK law actually comes from, besides laws passed by Parliament. What is the other main source?", o: ["Case law, built up from judges' decisions", "Royal decrees", "European treaties", "Local council rules"], a: [0], e: "The two main sources of UK law are Acts of Parliament and case law — judges interpret the law, and their decisions build up as common law." },
  { i: 1951, base: 260, variant: "exception", c: 5, q: "Which of these is NOT one of the two main sources of UK law?", o: ["Royal decrees issued personally by the monarch", "Acts of Parliament", "Case law", "Judges' interpretations building up as common law"], a: [0], e: "UK law comes from Acts of Parliament and case law — the monarch does not personally issue binding royal decrees that create law today." },

  // ---- base i:261 — legal aid: a solicitor or barrister for serious criminal charges ----
  { i: 1952, base: 261, variant: "rephrase", c: 5, q: "Who represents you if you are charged with a serious criminal offence and cannot afford a lawyer?", o: ["A solicitor or barrister paid for through legal aid", "A police officer", "A magistrate", "A civil servant"], a: [0], e: "Legal aid may be available depending on your circumstances and the case." },
  { i: 1953, base: 261, variant: "truefalse", c: 5, q: "Is this statement TRUE or FALSE? Legal aid can pay for a solicitor or barrister if you cannot afford one for a serious charge.", o: ["True", "False"], a: [0], e: "Legal aid may be available depending on your circumstances and the case." },
  { i: 1954, base: 261, variant: "scenario", c: 5, q: "A friend facing a serious criminal charge cannot afford a lawyer. What support might be available to them?", o: ["Legal aid, paying for a solicitor or barrister", "A police officer will represent them", "A magistrate will represent them", "No support is available"], a: [0], e: "Legal aid may pay for a solicitor or barrister, depending on your circumstances and the case." },
  { i: 1955, base: 261, variant: "exception", c: 5, q: "Which of these is NOT true about legal aid?", o: ["It is guaranteed to everyone regardless of circumstances", "It can pay for a solicitor or barrister", "Eligibility depends on your circumstances", "Eligibility depends on the case"], a: [0], e: "Legal aid is not automatically guaranteed to everyone — whether it is available depends on your circumstances and the nature of the case." },

  // ---- base i:262 — Scotland: serious crime heard in the High Court of Justiciary or Sheriff Court ----
  { i: 1956, base: 262, variant: "rephrase", c: 5, q: "In Scotland, which court hears serious criminal cases?", o: ["The High Court of Justiciary or Sheriff Court", "The Crown Court", "The Magistrates' Court", "The County Court"], a: [0], e: "Scotland has its own legal system, separate from England, Wales and Northern Ireland." },
  { i: 1957, base: 262, variant: "truefalse", c: 5, q: "Is this statement TRUE or FALSE? Serious criminal cases in Scotland are heard in the High Court of Justiciary or Sheriff Court.", o: ["True", "False"], a: [0], e: "Scotland has its own legal system, separate from England, Wales and Northern Ireland." },
  { i: 1958, base: 262, variant: "scenario", c: 5, q: "A friend asks which Scottish court, part of its own separate legal system, hears serious criminal cases. Which court is it?", o: ["The High Court of Justiciary or Sheriff Court", "The Crown Court", "The Magistrates' Court", "The County Court"], a: [0], e: "Scotland has its own legal system; serious criminal cases are heard in the High Court of Justiciary or Sheriff Court." },
  { i: 1959, base: 262, variant: "exception", c: 5, q: "Which of these is NOT true about serious criminal cases in Scotland?", o: ["They are heard in the Crown Court, as in England", "They are heard in the High Court of Justiciary or Sheriff Court", "Scotland has its own separate legal system", "Scotland's courts differ from those in England and Wales"], a: [0], e: "Scotland does not use the Crown Court — that is the system used in England, Wales and Northern Ireland. Scotland has its own separate courts instead." },

  // ---- base i:263 — problems with a paid-for product or service: the County Court ----
  { i: 1960, base: 263, variant: "rephrase", c: 5, q: "What can you do if you have a problem with a product or service you have paid for?", o: ["Take the case to a County Court or use a small claims procedure", "Report it to the police", "Appeal to Parliament", "Contact the Crown Court"], a: [0], e: "Small claims are handled in County Courts in England, Wales and Northern Ireland and Sheriff Courts in Scotland." },
  { i: 1961, base: 263, variant: "truefalse", c: 5, q: "Is this statement TRUE or FALSE? A dispute over a paid-for product or service can be taken to the County Court or a small claims procedure.", o: ["True", "False"], a: [0], e: "Small claims are handled in County Courts in England, Wales and Northern Ireland and Sheriff Courts in Scotland." },
  { i: 1962, base: 263, variant: "scenario", c: 5, q: "A friend has a dispute with a company over a faulty product they paid for. What is the correct route to pursue it?", o: ["The County Court or a small claims procedure", "Reporting it to the police", "Appealing directly to Parliament", "The Crown Court"], a: [0], e: "Small claims over paid-for products or services are handled in County Courts in England, Wales and Northern Ireland, and Sheriff Courts in Scotland." },
  { i: 1963, base: 263, variant: "exception", c: 5, q: "Which of these is NOT the correct way to resolve a dispute over a paid-for product or service?", o: ["Reporting it as a crime to the police", "Using a small claims procedure", "Taking the case to a County Court", "Using a Sheriff Court in Scotland"], a: [0], e: "A dispute over a faulty product or service is a civil matter for the County Court or small claims procedure, not a police matter." },

  // ---- base i:264 — two unlawful forms of discrimination at work (choose two) ----
  { i: 1964, base: 264, variant: "rephrase", c: 5, q: "Which TWO are unlawful forms of discrimination at work? (Choose two answers)", o: ["Discrimination because of race", "Discrimination because of disability", "Refusing to hire someone without the right qualifications", "Paying more for more experience"], a: [0, 1], e: "The Equality Act protects against discrimination on grounds such as age, disability, race, religion, sex and sexual orientation." },
  { i: 1965, base: 264, variant: "truefalse", c: 5, q: "Is this statement TRUE or FALSE? Discrimination at work because of someone's race is unlawful.", o: ["True", "False"], a: [0], e: "The Equality Act protects against discrimination on grounds such as age, disability, race, religion, sex and sexual orientation." },
  { i: 1966, base: 264, variant: "scenario", c: 5, q: "A friend wants to know which TWO of these employment practices are actually unlawful discrimination. Which are they? (Choose two answers)", o: ["Discriminating on the basis of race", "Discriminating on the basis of disability", "Requiring relevant qualifications for a role", "Paying higher wages for more experience"], a: [0, 1], e: "The Equality Act protects against discrimination on grounds such as age, disability, race, religion, sex and sexual orientation — requiring relevant qualifications is not discrimination." },
  { i: 1967, base: 264, variant: "exception", c: 5, q: "Which of these is NOT unlawful discrimination under the Equality Act?", o: ["Paying more experienced staff a higher wage", "Discrimination because of race", "Discrimination because of disability", "Discrimination because of religion"], a: [0], e: "Paying more for greater experience is a legitimate pay decision, not discrimination — the Equality Act protects against discrimination on grounds like race, disability and religion instead." },

  // ---- base i:265 — the emergency number: 999 or 112 ----
  { i: 1968, base: 265, variant: "rephrase", c: 5, q: "What is the emergency telephone number in the UK for police, fire and ambulance?", o: ["999 or 112", "911", "101", "111"], a: [0], e: "Use 999 or 112 in an emergency; 101 is for non-emergency police matters and 111 for non-emergency medical advice." },
  { i: 1969, base: 265, variant: "truefalse", c: 5, q: "Is this statement TRUE or FALSE? The UK emergency number for police, fire and ambulance is 999 or 112.", o: ["True", "False"], a: [0], e: "Use 999 or 112 in an emergency; 101 is for non-emergency police matters and 111 for non-emergency medical advice." },
  { i: 1970, base: 265, variant: "scenario", c: 5, q: "A friend new to the UK asks which number to call in a genuine emergency needing police, fire or ambulance. Which number is it?", o: ["999 or 112", "911", "101", "111"], a: [0], e: "999 or 112 are the emergency numbers in the UK; 101 and 111 are for non-emergency matters instead." },
  { i: 1971, base: 265, variant: "exception", c: 5, q: "Which of these is NOT a genuine UK emergency number for police, fire or ambulance?", o: ["911", "999", "112", "A number to call when life is at risk"], a: [0], e: "911 is the US emergency number, not the UK's — the UK uses 999 or 112." },
];
