/* ============================================================
   QUESTION VARIANTS — Chapter 3d (History: the Bill of Rights
   through Emmeline Pankhurst, base i:60-72). See chapter1.js for
   format notes.
   ============================================================ */

export default [
  // ---- base i:60 — 1689 Bill of Rights ----
  { i: 1268, base: 60, variant: "rephrase", c: 3, q: "What did the Bill of Rights of 1689 establish?", o: ["Limits on the monarch's power and the need for regular Parliaments", "The right to vote for all adults", "Freedom from taxation", "The Church of England"], a: [0], e: "The Bill of Rights confirmed that the monarch must have Parliament's agreement, and required regular Parliaments." },
  { i: 1269, base: 60, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? The Bill of Rights of 1689 limited the monarch's power and required regular Parliaments.", o: ["True", "False"], a: [0], e: "The Bill of Rights confirmed that the monarch must have Parliament's agreement, and required regular Parliaments." },
  { i: 1270, base: 60, variant: "scenario", c: 3, q: "A friend asks what the 1689 Bill of Rights actually did. What is the correct answer?", o: ["It limited the monarch's power and required regular Parliaments", "It gave every adult the right to vote", "It abolished taxation", "It established the Church of England"], a: [0], e: "The Bill of Rights confirmed that the monarch must have Parliament's agreement, and required regular Parliaments." },
  { i: 1271, base: 60, variant: "exception", c: 3, q: "Which of these was NOT something the 1689 Bill of Rights established?", o: ["Universal adult suffrage", "That the monarch needed Parliament's agreement", "The requirement for regular Parliaments", "Limits on royal power"], a: [0], e: "The Bill of Rights limited royal power and required regular Parliaments — universal adult suffrage came much later, in the 20th century." },

  // ---- base i:61 — 1707 Act of Union: Kingdom of Great Britain ----
  { i: 1272, base: 61, variant: "rephrase", c: 3, q: "The Act of Union of 1707 created which kingdom?", o: ["The Kingdom of Great Britain", "The United Kingdom of Great Britain and Ireland", "The Commonwealth", "The Kingdom of England and Wales"], a: [0], e: "Scotland and England joined under one Parliament to form the Kingdom of Great Britain." },
  { i: 1273, base: 61, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? The Act of Union of 1707 created the Kingdom of Great Britain.", o: ["True", "False"], a: [0], e: "Scotland and England joined under one Parliament to form the Kingdom of Great Britain." },
  { i: 1274, base: 61, variant: "scenario", c: 3, q: "A friend asks what the 1707 Act of Union joined together, and what it created. What is the answer?", o: ["It joined Scotland and England under one Parliament, creating the Kingdom of Great Britain", "It joined England and Ireland, creating the United Kingdom", "It created the Commonwealth", "It joined England and Wales only"], a: [0], e: "Scotland and England joined under one Parliament to form the Kingdom of Great Britain in 1707." },
  { i: 1275, base: 61, variant: "exception", c: 3, q: "Which of these was NOT part of the Kingdom of Great Britain created by the 1707 Act of Union?", o: ["Ireland", "England", "Scotland", "Wales, as part of the Kingdom of England"], a: [0], e: "The 1707 Act of Union joined Scotland with the existing Kingdom of England (which already included Wales) to form Great Britain. Ireland joined later, in 1801." },

  // ---- base i:62 — Robert Walpole, first Prime Minister ----
  { i: 1276, base: 62, variant: "rephrase", c: 3, q: "Who is generally regarded as the first Prime Minister of Great Britain?", o: ["Sir Robert Walpole", "William Pitt", "Winston Churchill", "The Duke of Wellington"], a: [0], e: "Sir Robert Walpole served from 1721 to 1742 and is seen as the first Prime Minister." },
  { i: 1277, base: 62, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? Sir Robert Walpole is generally regarded as Britain's first Prime Minister.", o: ["True", "False"], a: [0], e: "Sir Robert Walpole served from 1721 to 1742 and is seen as the first Prime Minister." },
  { i: 1278, base: 62, variant: "scenario", c: 3, q: "A friend asks who is credited as the first person to hold the office of Prime Minister. Who was it?", o: ["Sir Robert Walpole", "William Pitt", "Winston Churchill", "Oliver Cromwell"], a: [0], e: "Sir Robert Walpole served from 1721 to 1742 and is seen as the first Prime Minister." },
  { i: 1279, base: 62, variant: "exception", c: 3, q: "Which of these did NOT serve as Prime Minister of the UK?", o: ["Oliver Cromwell", "Sir Robert Walpole", "Winston Churchill", "Margaret Thatcher"], a: [0], e: "Walpole, Churchill and Thatcher all served as Prime Minister. Oliver Cromwell ruled as Lord Protector during the earlier republic, before the office of Prime Minister existed." },

  // ---- base i:63 — 1746 Culloden: the Jacobites defeated ----
  { i: 1280, base: 63, variant: "rephrase", c: 3, q: "At which 1746 battle were the Jacobites defeated?", o: ["Culloden", "Bannockburn", "Naseby", "Bosworth Field"], a: [0], e: "Bonnie Prince Charlie's forces were crushed at Culloden; he fled to Europe." },
  { i: 1281, base: 63, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? The Jacobites were defeated at the Battle of Culloden in 1746.", o: ["True", "False"], a: [0], e: "Bonnie Prince Charlie's forces were crushed at Culloden; he fled to Europe." },
  { i: 1282, base: 63, variant: "scenario", c: 3, q: "A friend asks which battle ended Bonnie Prince Charlie's campaign in 1746. Which was it?", o: ["Culloden", "Bannockburn", "Naseby", "Bosworth Field"], a: [0], e: "Bonnie Prince Charlie's forces were crushed at Culloden in 1746; he fled to Europe afterwards." },
  { i: 1283, base: 63, variant: "exception", c: 3, q: "Which of these did NOT follow the Battle of Culloden in 1746?", o: ["Bonnie Prince Charlie was crowned king", "Bonnie Prince Charlie fled to Europe", "The Jacobite cause was crushed", "The Highland Clearances followed in the years after"], a: [0], e: "Bonnie Prince Charlie's forces were defeated at Culloden and he fled to Europe — he was never crowned king." },

  // ---- base i:64 — Adam Smith and David Hume: the Scottish Enlightenment ----
  { i: 1284, base: 64, variant: "rephrase", c: 3, q: "Adam Smith and David Hume were leading figures of what?", o: ["The Scottish Enlightenment", "The Industrial Revolution", "The Reformation", "The Restoration"], a: [0], e: "The Enlightenment produced new ideas in politics, philosophy and science, many from Scottish thinkers." },
  { i: 1285, base: 64, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? Adam Smith and David Hume were leading figures of the Scottish Enlightenment.", o: ["True", "False"], a: [0], e: "The Enlightenment produced new ideas in politics, philosophy and science, many from Scottish thinkers." },
  { i: 1286, base: 64, variant: "scenario", c: 3, q: "A friend asks which movement Adam Smith and David Hume are associated with. What is the answer?", o: ["The Scottish Enlightenment", "The Industrial Revolution", "The Jacobite rebellions", "The Reformation"], a: [0], e: "The Enlightenment produced new ideas in politics, philosophy and science, many from Scottish thinkers such as Adam Smith and David Hume." },
  { i: 1287, base: 64, variant: "exception", c: 3, q: "Which of these is NOT associated with the Scottish Enlightenment?", o: ["James Watt's steam engine", "Adam Smith", "David Hume", "New ideas in philosophy and science"], a: [0], e: "Adam Smith and David Hume were leading Enlightenment thinkers. James Watt's steam engine belongs to the later Industrial Revolution, though both were Scottish achievements." },

  // ---- base i:65 — James Watt and the steam engine ----
  { i: 1288, base: 65, variant: "rephrase", c: 3, q: "Who developed the steam engine that helped power the Industrial Revolution?", o: ["James Watt", "Richard Arkwright", "Isaac Newton", "George Stephenson"], a: [0], e: "James Watt, a Scot, improved the steam engine so it could drive machinery in factories and mines." },
  { i: 1289, base: 65, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? James Watt improved the steam engine so it could power factories and mines.", o: ["True", "False"], a: [0], e: "James Watt, a Scot, improved the steam engine so it could drive machinery in factories and mines." },
  { i: 1290, base: 65, variant: "scenario", c: 3, q: "A friend asks who is credited with improving the steam engine to power the Industrial Revolution. Who was it?", o: ["James Watt", "Richard Arkwright", "Isaac Newton", "Isambard Kingdom Brunel"], a: [0], e: "James Watt, a Scot, improved the steam engine so it could drive machinery in factories and mines." },
  { i: 1291, base: 65, variant: "exception", c: 3, q: "Which of these is NOT correctly matched with their Industrial Revolution achievement?", o: ["James Watt — spinning machinery for cloth", "James Watt — the improved steam engine", "Richard Arkwright — spinning machinery for cloth", "James Watt — power for factories and mines"], a: [0], e: "James Watt is known for improving the steam engine. Efficient spinning machinery for cloth was Richard Arkwright's contribution." },

  // ---- base i:66 — 1807: the slave trade abolished ----
  { i: 1292, base: 66, variant: "rephrase", c: 3, q: "In which year did Parliament abolish the slave trade in British ships?", o: ["1807", "1833", "1776", "1215"], a: [0], e: "The trade was abolished in 1807; the Emancipation Act of 1833 abolished slavery throughout the British Empire." },
  { i: 1293, base: 66, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? Parliament abolished the slave trade in British ships in 1807.", o: ["True", "False"], a: [0], e: "The trade was abolished in 1807; the Emancipation Act of 1833 abolished slavery throughout the British Empire." },
  { i: 1294, base: 66, variant: "scenario", c: 3, q: "A friend confuses the abolition of the slave trade with the abolition of slavery itself. When was the slave trade abolished?", o: ["1807", "1833", "1776", "1215"], a: [0], e: "The slave trade was abolished in 1807; slavery itself throughout the British Empire was abolished later, by the Emancipation Act of 1833." },
  { i: 1295, base: 66, variant: "exception", c: 3, q: "Which of these is NOT correct about the abolition of slavery and the slave trade in the British Empire?", o: ["The slave trade and slavery itself were both abolished in 1807", "The slave trade was abolished in 1807", "Slavery throughout the Empire was abolished in 1833", "William Wilberforce campaigned against the slave trade"], a: [0], e: "The slave trade was abolished in 1807, but slavery itself continued in the Empire until the Emancipation Act of 1833 — the two are different dates." },

  // ---- base i:67 — William Wilberforce ----
  { i: 1296, base: 67, variant: "rephrase", c: 3, q: "Which MP campaigned successfully against the slave trade?", o: ["William Wilberforce", "Robert Walpole", "William Gladstone", "Isambard Kingdom Brunel"], a: [0], e: "William Wilberforce, an evangelical Christian, led the parliamentary campaign against slavery." },
  { i: 1297, base: 67, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? William Wilberforce led the parliamentary campaign against the slave trade.", o: ["True", "False"], a: [0], e: "William Wilberforce, an evangelical Christian, led the parliamentary campaign against slavery." },
  { i: 1298, base: 67, variant: "scenario", c: 3, q: "A friend asks which MP is most closely associated with ending Britain's involvement in the slave trade. Who was it?", o: ["William Wilberforce", "Robert Walpole", "William Gladstone", "Robert Peel"], a: [0], e: "William Wilberforce, an evangelical Christian, led the parliamentary campaign against slavery." },
  { i: 1299, base: 67, variant: "exception", c: 3, q: "Which of these was NOT part of William Wilberforce's legacy?", o: ["Inventing the steam engine", "Campaigning against the slave trade", "Being an evangelical Christian", "Leading a parliamentary campaign for abolition"], a: [0], e: "William Wilberforce is remembered for his campaign against the slave trade, not for any engineering invention — that was James Watt's achievement." },

  // ---- base i:68 — 1805: Nelson dies at Trafalgar ----
  { i: 1300, base: 68, variant: "rephrase", c: 3, q: "Admiral Nelson died at which 1805 sea battle?", o: ["Trafalgar", "Jutland", "The Nile", "Dunkirk"], a: [0], e: "Nelson was killed at Trafalgar; his flagship HMS Victory is preserved in Portsmouth and his column stands in Trafalgar Square." },
  { i: 1301, base: 68, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? Admiral Nelson died at the Battle of Trafalgar in 1805.", o: ["True", "False"], a: [0], e: "Nelson was killed at Trafalgar; his flagship HMS Victory is preserved in Portsmouth and his column stands in Trafalgar Square." },
  { i: 1302, base: 68, variant: "scenario", c: 3, q: "A friend visiting Trafalgar Square asks who the column commemorates and how he died. What is the answer?", o: ["Admiral Nelson, who died at the Battle of Trafalgar", "The Duke of Wellington, who died at Waterloo", "Sir Robert Walpole, who died in office", "Oliver Cromwell, who died as Lord Protector"], a: [0], e: "Nelson was killed at Trafalgar in 1805; his column stands in Trafalgar Square, and his flagship HMS Victory is preserved in Portsmouth." },
  { i: 1303, base: 68, variant: "exception", c: 3, q: "Which of these is NOT true about Admiral Nelson?", o: ["He commanded British land forces at Waterloo", "He died at the Battle of Trafalgar", "His flagship was HMS Victory", "Trafalgar Square is named partly in his honour"], a: [0], e: "Nelson was a naval commander who died at Trafalgar in 1805 — Waterloo, a land battle in 1815, was commanded by the Duke of Wellington." },

  // ---- base i:69 — the Duke of Wellington defeats Napoleon at Waterloo ----
  { i: 1304, base: 69, variant: "rephrase", c: 3, q: "Who commanded the British forces that defeated Napoleon at Waterloo in 1815?", o: ["The Duke of Wellington", "Admiral Nelson", "Sir Robert Walpole", "Oliver Cromwell"], a: [0], e: "The Duke of Wellington, later Prime Minister, was known as the Iron Duke." },
  { i: 1305, base: 69, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? The Duke of Wellington commanded the British forces at the Battle of Waterloo.", o: ["True", "False"], a: [0], e: "The Duke of Wellington, later Prime Minister, was known as the Iron Duke." },
  { i: 1306, base: 69, variant: "scenario", c: 3, q: "A friend asks who led Britain to victory over Napoleon at Waterloo in 1815. Who was it?", o: ["The Duke of Wellington", "Admiral Nelson", "Sir Robert Walpole", "William Pitt"], a: [0], e: "The Duke of Wellington, later Prime Minister, was known as the Iron Duke and commanded at Waterloo." },
  { i: 1307, base: 69, variant: "exception", c: 3, q: "Which of these is NOT true about the Duke of Wellington?", o: ["He was known as the Iron Duke and later became Prime Minister", "He commanded British forces at Waterloo", "He defeated Napoleon in 1815", "He was killed at the Battle of Trafalgar"], a: [0], e: "The Duke of Wellington defeated Napoleon at Waterloo and later became Prime Minister — Admiral Nelson, not Wellington, was killed at Trafalgar." },

  // ---- base i:70 — Queen Victoria's reign, 1837-1901 ----
  { i: 1308, base: 70, variant: "rephrase", c: 3, q: "How long did Queen Victoria reign?", o: ["From 1837 to 1901", "From 1801 to 1837", "From 1901 to 1936", "From 1760 to 1820"], a: [0], e: "Victoria came to the throne aged 18 in 1837 and reigned for 64 years, a period of huge industrial and imperial expansion." },
  { i: 1309, base: 70, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? Queen Victoria reigned from 1837 to 1901.", o: ["True", "False"], a: [0], e: "Victoria came to the throne aged 18 in 1837 and reigned for 64 years, a period of huge industrial and imperial expansion." },
  { i: 1310, base: 70, variant: "scenario", c: 3, q: "A friend asks over what years Queen Victoria reigned. What is the correct span?", o: ["1837 to 1901", "1801 to 1837", "1901 to 1936", "1760 to 1820"], a: [0], e: "Victoria came to the throne aged 18 in 1837 and reigned for 64 years." },
  { i: 1311, base: 70, variant: "exception", c: 3, q: "Which of these is NOT true about Queen Victoria's reign?", o: ["It lasted less than 20 years", "It began in 1837", "It ended in 1901", "It lasted 64 years"], a: [0], e: "Queen Victoria reigned for 64 years, from 1837 to 1901 — far longer than 20 years." },

  // ---- base i:71 — Florence Nightingale and the Crimean War ----
  { i: 1312, base: 71, variant: "rephrase", c: 3, q: "Florence Nightingale is famous for her work in which war?", o: ["The Crimean War", "The First World War", "The Boer War", "The Hundred Years War"], a: [0], e: "She nursed at Scutari during the Crimean War and later founded a nursing school at St Thomas' Hospital in London." },
  { i: 1313, base: 71, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? Florence Nightingale is famous for her nursing work during the Crimean War.", o: ["True", "False"], a: [0], e: "She nursed at Scutari during the Crimean War and later founded a nursing school at St Thomas' Hospital in London." },
  { i: 1314, base: 71, variant: "scenario", c: 3, q: "A friend asks which war Florence Nightingale is most associated with. Which one is it?", o: ["The Crimean War", "The First World War", "The Boer War", "The Napoleonic Wars"], a: [0], e: "Florence Nightingale nursed at Scutari during the Crimean War and later founded a nursing school in London." },
  { i: 1315, base: 71, variant: "exception", c: 3, q: "Which of these is NOT true about Florence Nightingale?", o: ["She nursed soldiers during the First World War", "She nursed at Scutari during the Crimean War", "She founded a nursing school in London", "Her work transformed the nursing profession"], a: [0], e: "Florence Nightingale's famous work was during the Crimean War (1853-56), decades before the First World War began in 1914." },

  // ---- base i:72 — Emmeline Pankhurst founds the Women's Franchise League ----
  { i: 1316, base: 72, variant: "rephrase", c: 3, q: "Who founded the Women's Franchise League in 1889 and later led the suffragettes?", o: ["Emmeline Pankhurst", "Florence Nightingale", "Mary Seacole", "Elizabeth Fry"], a: [0], e: "Emmeline Pankhurst campaigned for votes for women; the movement used increasingly militant tactics." },
  { i: 1317, base: 72, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? Emmeline Pankhurst founded the Women's Franchise League in 1889.", o: ["True", "False"], a: [0], e: "Emmeline Pankhurst campaigned for votes for women; the movement used increasingly militant tactics." },
  { i: 1318, base: 72, variant: "scenario", c: 3, q: "A friend asks who led the suffragette movement campaigning for women's votes. Who was it?", o: ["Emmeline Pankhurst", "Florence Nightingale", "Mary Seacole", "Queen Victoria"], a: [0], e: "Emmeline Pankhurst campaigned for votes for women; the movement used increasingly militant tactics." },
  { i: 1319, base: 72, variant: "exception", c: 3, q: "Which of these is NOT true about Emmeline Pankhurst?", o: ["She was a Crimean War nurse", "She founded the Women's Franchise League in 1889", "She led the suffragette movement", "Her campaign used increasingly militant tactics"], a: [0], e: "Emmeline Pankhurst led the suffragette campaign for women's votes. Nursing in the Crimean War was Florence Nightingale's achievement, in an earlier generation." },
];
