/* ============================================================
   QUESTION VARIANTS — Chapter 5e (Government and law: non-emergency
   medical advice through the responsibilities of every working UK
   resident, base i:266-275 — the last of EXTRA_Q's chapter 5
   questions, and the last file of the whole project). See
   chapter1.js for format notes.
   ============================================================ */

export default [
  // ---- base i:266 — non-emergency medical advice: 111 ----
  { i: 1972, base: 266, variant: "rephrase", c: 5, q: "Which number should you call for non-emergency medical advice in England?", o: ["111", "999", "101", "112"], a: [0], e: "NHS 111 gives medical advice when the situation is not life-threatening." },
  { i: 1973, base: 266, variant: "truefalse", c: 5, q: "Is this statement TRUE or FALSE? You should call 111 for non-emergency medical advice in England.", o: ["True", "False"], a: [0], e: "NHS 111 gives medical advice when the situation is not life-threatening." },
  { i: 1974, base: 266, variant: "scenario", c: 5, q: "A friend feels unwell but it isn't life-threatening, so they don't want to call 999. Which number should they call instead?", o: ["111", "999", "101", "112"], a: [0], e: "NHS 111 gives medical advice when the situation is not life-threatening, unlike 999, which is for genuine emergencies." },
  { i: 1975, base: 266, variant: "exception", c: 5, q: "Which of these is NOT the correct number for non-emergency medical advice in England?", o: ["999", "111", "The NHS helpline number", "The number to call when a situation isn't life-threatening"], a: [0], e: "999 is for genuine emergencies — non-emergency medical advice is available through NHS 111 instead." },

  // ---- base i:267 — registering with a doctor: sign up with a local GP surgery ----
  { i: 1976, base: 267, variant: "rephrase", c: 5, q: "How can you register with a doctor?", o: ["Sign up with a local GP surgery", "Apply to the Home Office", "Ask your employer", "Register at a hospital only"], a: [0], e: "GPs are usually the first point of contact for health problems that are not emergencies." },
  { i: 1977, base: 267, variant: "truefalse", c: 5, q: "Is this statement TRUE or FALSE? You register with a doctor by signing up with a local GP surgery.", o: ["True", "False"], a: [0], e: "GPs are usually the first point of contact for health problems that are not emergencies." },
  { i: 1978, base: 267, variant: "scenario", c: 5, q: "A friend who has just moved to a new area asks how to register with a doctor there. What should they do?", o: ["Sign up with a local GP surgery", "Apply to the Home Office", "Ask their employer to register them", "Wait until they need hospital treatment"], a: [0], e: "You register with a doctor by signing up with a local GP surgery; GPs are usually the first point of contact for non-emergency health problems." },
  { i: 1979, base: 267, variant: "exception", c: 5, q: "Which of these is NOT the correct way to register with a doctor?", o: ["Applying through the Home Office", "Signing up with a local GP surgery", "Registering as a new patient at a GP practice", "Choosing a GP surgery near where you live"], a: [0], e: "Registering with a doctor is done through a local GP surgery, not through the Home Office, which handles immigration matters instead." },

  // ---- base i:268 — standing for MP: most people 18+, UK/Irish/eligible Commonwealth citizens ----
  { i: 1980, base: 268, variant: "rephrase", c: 5, q: "Who can stand for election as an MP?", o: ["Most people aged 18 or over who are UK, Irish or eligible Commonwealth citizens", "Only people over 25", "Only members of the two largest parties", "Only people born in the UK"], a: [0], e: "Some people, such as members of the armed forces, civil servants and prisoners, are disqualified." },
  { i: 1981, base: 268, variant: "truefalse", c: 5, q: "Is this statement TRUE or FALSE? Most people aged 18 or over who are UK, Irish or eligible Commonwealth citizens can stand as an MP.", o: ["True", "False"], a: [0], e: "Some people, such as members of the armed forces, civil servants and prisoners, are disqualified." },
  { i: 1982, base: 268, variant: "scenario", c: 5, q: "A friend, a Commonwealth citizen living in the UK, asks if they could ever stand for election as an MP. What is the correct answer?", o: ["Yes, if they are 18 or over and an eligible Commonwealth citizen", "No — only UK-born citizens can stand", "No — only people over 25 can stand", "Yes, but only if they join one of the two largest parties"], a: [0], e: "Most people aged 18 or over who are UK, Irish or eligible Commonwealth citizens can stand as an MP." },
  { i: 1983, base: 268, variant: "exception", c: 5, q: "Which of these is NOT disqualified from standing as an MP?", o: ["An eligible Commonwealth citizen aged 18 or over", "A serving member of the armed forces", "A serving civil servant", "A serving prisoner"], a: [0], e: "An eligible Commonwealth citizen aged 18 or over may stand as an MP — members of the armed forces, civil servants and prisoners are the ones disqualified." },

  // ---- base i:269 — a school governor: a volunteer who helps run a school ----
  { i: 1984, base: 269, variant: "rephrase", c: 5, q: "What is a school governor?", o: ["A volunteer who helps run a school", "A paid head teacher", "A local council employee", "A government inspector"], a: [0], e: "Becoming a school governor is one way of taking part in your community." },
  { i: 1985, base: 269, variant: "truefalse", c: 5, q: "Is this statement TRUE or FALSE? A school governor is a volunteer who helps run a school.", o: ["True", "False"], a: [0], e: "Becoming a school governor is one way of taking part in your community." },
  { i: 1986, base: 269, variant: "scenario", c: 5, q: "A friend wants to get involved with their local school as a form of community participation. What unpaid role could they take on?", o: ["School governor", "Head teacher", "Local council employee", "Government inspector"], a: [0], e: "Becoming a school governor is a voluntary way of helping run a school and taking part in your community." },
  { i: 1987, base: 269, variant: "exception", c: 5, q: "Which of these is NOT true about school governors?", o: ["They are paid a salary like a head teacher", "They are volunteers", "They help run a school", "Being one is a way to take part in your community"], a: [0], e: "School governors are volunteers, not paid staff — a head teacher, by contrast, is a paid employee of the school." },

  // ---- base i:270 — jury service: attend unless excused for a valid reason ----
  { i: 1988, base: 270, variant: "rephrase", c: 5, q: "Which of these must you do if you are called for jury service?", o: ["Attend unless you have a valid reason to be excused", "Pay a fee to take part", "Choose a case to hear", "Serve for a full year"], a: [0], e: "Jury service is a public duty and people are selected at random from the electoral register." },
  { i: 1989, base: 270, variant: "truefalse", c: 5, q: "Is this statement TRUE or FALSE? If called for jury service, you must attend unless you have a valid reason to be excused.", o: ["True", "False"], a: [0], e: "Jury service is a public duty and people are selected at random from the electoral register." },
  { i: 1990, base: 270, variant: "scenario", c: 5, q: "A friend has just been summoned for jury service and would rather not go. What are they required to do?", o: ["Attend, unless they have a valid reason to be excused", "Pay a fee instead of attending", "Choose which case they'd like to hear", "Serve for a full year regardless"], a: [0], e: "Jury service is a public duty; you must attend unless you have a valid reason to be excused." },
  { i: 1991, base: 270, variant: "exception", c: 5, q: "Which of these is NOT true about jury service?", o: ["You can simply pay a fee to avoid attending", "It is a public duty", "You can be excused for a valid reason", "Jurors are selected at random from the electoral register"], a: [0], e: "You cannot simply pay a fee to avoid jury service — it is a public duty, and only a valid reason can excuse you from attending." },

  // ---- base i:271 — the Speaker's constituency work ----
  { i: 1992, base: 271, variant: "rephrase", c: 5, q: "What is the purpose of the Speaker's constituency work?", o: ["The Speaker still represents their constituents as an MP", "The Speaker has no constituency", "The Speaker represents the government", "The Speaker only chairs debates"], a: [0], e: "The Speaker remains a constituency MP but must be politically neutral in the Commons." },
  { i: 1993, base: 271, variant: "truefalse", c: 5, q: "Is this statement TRUE or FALSE? The Speaker still represents their own constituents as an MP.", o: ["True", "False"], a: [0], e: "The Speaker remains a constituency MP but must be politically neutral in the Commons." },
  { i: 1994, base: 271, variant: "scenario", c: 5, q: "A friend asks whether the Speaker of the House of Commons stops representing their constituency once elected Speaker. What is the answer?", o: ["No — the Speaker still represents their constituents as an MP", "Yes — the Speaker gives up their constituency entirely", "Yes — the Speaker instead represents the government", "No — but the Speaker only chairs debates and nothing more"], a: [0], e: "The Speaker remains a constituency MP, continuing to represent their constituents, but must be politically neutral within the Commons chamber." },
  { i: 1995, base: 271, variant: "exception", c: 5, q: "Which of these is NOT true about the Speaker's role?", o: ["The Speaker gives up their constituency once elected", "The Speaker still represents their constituents", "The Speaker must be politically neutral in the Commons", "The Speaker remains an MP"], a: [0], e: "The Speaker does not give up their constituency — they continue representing it as an MP, while remaining politically neutral in the Commons chamber." },

  // ---- base i:272 — the House of Lords checks and amends Commons legislation ----
  { i: 1996, base: 272, variant: "rephrase", c: 5, q: "Which body checks and can suggest amendments to laws passed by the House of Commons?", o: ["The House of Lords", "The Supreme Court", "The civil service", "The monarch's household"], a: [0], e: "The Lords scrutinises legislation, though the Commons can ultimately overrule it." },
  { i: 1997, base: 272, variant: "truefalse", c: 5, q: "Is this statement TRUE or FALSE? The House of Lords checks and can suggest amendments to laws passed by the Commons.", o: ["True", "False"], a: [0], e: "The Lords scrutinises legislation, though the Commons can ultimately overrule it." },
  { i: 1998, base: 272, variant: "scenario", c: 5, q: "A friend asks which body reviews and can propose changes to bills after the Commons has passed them, though the Commons can ultimately overrule it. Which body is it?", o: ["The House of Lords", "The Supreme Court", "The civil service", "The Privy Council"], a: [0], e: "The House of Lords scrutinises legislation passed by the Commons and can suggest amendments, though the Commons can ultimately overrule it." },
  { i: 1999, base: 272, variant: "exception", c: 5, q: "Which of these is NOT true about the House of Lords' role in scrutinising legislation?", o: ["Its decisions can never be overruled by the Commons", "It can suggest amendments to bills", "It scrutinises legislation from the Commons", "The Commons can ultimately overrule it"], a: [0], e: "The Commons can ultimately overrule the House of Lords — the Lords' decisions on legislation are not final and unchallengeable." },

  // ---- base i:273 — not paying council tax: court action and further costs ----
  { i: 2000, base: 273, variant: "rephrase", c: 5, q: "What happens if you do not pay your council tax?", o: ["You can be taken to court and face further costs", "Nothing, it is voluntary", "Your passport is withdrawn", "You are deported"], a: [0], e: "Council tax pays for local services such as rubbish collection, libraries and policing." },
  { i: 2001, base: 273, variant: "truefalse", c: 5, q: "Is this statement TRUE or FALSE? Failing to pay council tax can result in being taken to court and facing further costs.", o: ["True", "False"], a: [0], e: "Council tax pays for local services such as rubbish collection, libraries and policing." },
  { i: 2002, base: 273, variant: "scenario", c: 5, q: "A friend is thinking of simply not paying their council tax bill. What could happen to them as a result?", o: ["They could be taken to court and face further costs", "Nothing — it is entirely voluntary", "Their passport could be withdrawn", "They could be deported"], a: [0], e: "Failing to pay council tax can lead to being taken to court and facing further costs — it is not a voluntary payment." },
  { i: 2003, base: 273, variant: "exception", c: 5, q: "Which of these is NOT a real consequence of not paying council tax?", o: ["Passport withdrawal", "Being taken to court", "Facing further costs", "Legal action to recover the debt"], a: [0], e: "Not paying council tax can lead to court action and extra costs — passport withdrawal is not a real consequence of this kind of debt." },

  // ---- base i:274 — devolved power: powers transferred to a national or regional body ----
  { i: 2004, base: 274, variant: "rephrase", c: 5, q: "What does the term 'devolved power' mean?", o: ["Powers transferred from central government to a national or regional body", "Powers given to the monarch", "Powers given to the courts", "Powers given to local charities"], a: [0], e: "Scotland, Wales and Northern Ireland have devolved administrations with powers over areas such as health and education." },
  { i: 2005, base: 274, variant: "truefalse", c: 5, q: "Is this statement TRUE or FALSE? 'Devolved power' means powers transferred from central government to a national or regional body.", o: ["True", "False"], a: [0], e: "Scotland, Wales and Northern Ireland have devolved administrations with powers over areas such as health and education." },
  { i: 2006, base: 274, variant: "scenario", c: 5, q: "A friend asks what 'devolved power' means, in relation to Scotland, Wales and Northern Ireland having control over health and education. What is the correct definition?", o: ["Powers transferred from central government to a national or regional body", "Powers given directly to the monarch", "Powers given to the courts", "Powers given to local charities"], a: [0], e: "'Devolved power' means powers transferred from central government to a national or regional body, such as the devolved administrations in Scotland, Wales and Northern Ireland." },
  { i: 2007, base: 274, variant: "exception", c: 5, q: "Which of these is NOT an example of a devolved power?", o: ["Powers held personally by the monarch", "Scotland's control over areas like health", "Wales's control over areas like education", "Northern Ireland's devolved administration powers"], a: [0], e: "Devolved powers are transferred from central government to bodies like the Scottish Parliament — they are not powers held personally by the monarch." },

  // ---- base i:275 — a responsibility of every working UK resident: paying income tax and National Insurance ----
  { i: 2008, base: 275, variant: "rephrase", c: 5, q: "Which of these is a responsibility of every UK resident who works?", o: ["Paying income tax and National Insurance", "Joining a trade union", "Voting in every election", "Serving as a magistrate"], a: [0], e: "Tax pays for public services such as roads, schools, the armed forces and the NHS." },
  { i: 2009, base: 275, variant: "truefalse", c: 5, q: "Is this statement TRUE or FALSE? Every UK resident who works has a responsibility to pay income tax and National Insurance.", o: ["True", "False"], a: [0], e: "Tax pays for public services such as roads, schools, the armed forces and the NHS." },
  { i: 2010, base: 275, variant: "scenario", c: 5, q: "A friend starting their first job in the UK asks what financial responsibility they now have as a worker. What is it?", o: ["Paying income tax and National Insurance", "Joining a trade union", "Voting in every election", "Serving as a magistrate"], a: [0], e: "Every UK resident who works has a responsibility to pay income tax and National Insurance, which fund public services such as roads, schools and the NHS." },
  { i: 2011, base: 275, variant: "exception", c: 5, q: "Which of these is NOT a legal responsibility of every UK resident who works?", o: ["Joining a trade union", "Paying income tax", "Paying National Insurance", "Contributing to public services through tax"], a: [0], e: "Joining a trade union is a personal choice, not a legal requirement — paying income tax and National Insurance, by contrast, is a responsibility for every worker." },
];
