/* ============================================================
   QUESTION VARIANTS — Chapter 4e (Society: Alfred Hitchcock through
   charity, base i:247-255 — the last of EXTRA_Q's chapter 4
   questions, and the last of chapter 4 overall). See chapter1.js for
   format notes.
   ============================================================ */

export default [
  // ---- base i:247 — Alfred Hitchcock: British film director ----
  { i: 1736, base: 247, variant: "rephrase", c: 4, q: "Which of these is a famous British film director?", o: ["Sir Alfred Hitchcock", "Steven Spielberg", "Martin Scorsese", "Ang Lee"], a: [0], e: "Hitchcock directed Psycho and The Birds; British film awards are the BAFTAs." },
  { i: 1737, base: 247, variant: "truefalse", c: 4, q: "Is this statement TRUE or FALSE? Sir Alfred Hitchcock was a famous British film director.", o: ["True", "False"], a: [0], e: "Hitchcock directed Psycho and The Birds; British film awards are the BAFTAs." },
  { i: 1738, base: 247, variant: "scenario", c: 4, q: "A friend asks which British director made Psycho and The Birds. Who was it?", o: ["Sir Alfred Hitchcock", "Steven Spielberg", "Martin Scorsese", "David Lean"], a: [0], e: "Hitchcock directed Psycho and The Birds; British film awards are the BAFTAs." },
  { i: 1739, base: 247, variant: "exception", c: 4, q: "Which of these is NOT true about Sir Alfred Hitchcock?", o: ["He was an American director", "He directed Psycho", "He directed The Birds", "British film awards, the BAFTAs, honour directors like him"], a: [0], e: "Alfred Hitchcock was a British director, not American, though he later worked extensively in Hollywood." },

  // ---- base i:248 — the Chelsea Flower Show: held in London ----
  { i: 1740, base: 248, variant: "rephrase", c: 4, q: "Which annual flower show is held in London?", o: ["The Chelsea Flower Show", "The Edinburgh Festival", "The Notting Hill Carnival", "The Eisteddfod"], a: [0], e: "The Chelsea Flower Show showcases garden design from around the world." },
  { i: 1741, base: 248, variant: "truefalse", c: 4, q: "Is this statement TRUE or FALSE? The Chelsea Flower Show is held annually in London.", o: ["True", "False"], a: [0], e: "The Chelsea Flower Show showcases garden design from around the world." },
  { i: 1742, base: 248, variant: "scenario", c: 4, q: "A friend interested in garden design asks which famous annual flower show is held in London. What is it called?", o: ["The Chelsea Flower Show", "The Edinburgh Festival", "The Notting Hill Carnival", "The Chelsea Flower Show is held in Edinburgh instead"], a: [0], e: "The Chelsea Flower Show, held in London, showcases garden design from around the world." },
  { i: 1743, base: 248, variant: "exception", c: 4, q: "Which of these is NOT true about the Chelsea Flower Show?", o: ["It is held in Edinburgh", "It is held in London", "It is held annually", "It showcases garden design from around the world"], a: [0], e: "The Chelsea Flower Show is held in London, not Edinburgh — the Edinburgh Festival is a separate, unrelated event." },

  // ---- base i:249 — the Eisteddfod: a Welsh festival ----
  { i: 1744, base: 249, variant: "rephrase", c: 4, q: "What is the Eisteddfod?", o: ["A Welsh festival of literature, music and performance", "A Scottish highland games", "An Irish dance competition", "An English village fair"], a: [0], e: "There is an annual National Eisteddfod in Wales, held mainly in Welsh." },
  { i: 1745, base: 249, variant: "truefalse", c: 4, q: "Is this statement TRUE or FALSE? The Eisteddfod is a Welsh festival of literature, music and performance.", o: ["True", "False"], a: [0], e: "There is an annual National Eisteddfod in Wales, held mainly in Welsh." },
  { i: 1746, base: 249, variant: "scenario", c: 4, q: "A friend asks about a Welsh festival of literature, music and performance, held mainly in the Welsh language. What is it called?", o: ["The Eisteddfod", "The Highland Games", "The Chelsea Flower Show", "The Notting Hill Carnival"], a: [0], e: "The National Eisteddfod is an annual Welsh festival of literature, music and performance, held mainly in Welsh." },
  { i: 1747, base: 249, variant: "exception", c: 4, q: "Which of these is NOT true about the Eisteddfod?", o: ["It is a Scottish festival", "It is a Welsh festival", "It celebrates literature, music and performance", "It is held mainly in the Welsh language"], a: [0], e: "The Eisteddfod is a Welsh festival, not Scottish — Scotland's equivalent gathering tradition is the Highland Games." },

  // ---- base i:250 — Stonehenge: a prehistoric monument in Wiltshire ----
  { i: 1748, base: 250, variant: "rephrase", c: 4, q: "Which of these UK landmarks is a prehistoric monument in Wiltshire?", o: ["Stonehenge", "The Eden Project", "The Tower of London", "Snowdonia"], a: [0], e: "Stonehenge is a World Heritage Site and one of the most famous prehistoric monuments in the world." },
  { i: 1749, base: 250, variant: "truefalse", c: 4, q: "Is this statement TRUE or FALSE? Stonehenge, a prehistoric monument, is located in Wiltshire.", o: ["True", "False"], a: [0], e: "Stonehenge is a World Heritage Site and one of the most famous prehistoric monuments in the world." },
  { i: 1750, base: 250, variant: "scenario", c: 4, q: "A friend asks which county holds the famous prehistoric stone circle recognised as a World Heritage Site. Which county is it, and what is the monument?", o: ["Wiltshire, home to Stonehenge", "Cornwall, home to Stonehenge", "Kent, home to Stonehenge", "Fife, home to Stonehenge"], a: [0], e: "Stonehenge, in Wiltshire, is a World Heritage Site and one of the most famous prehistoric monuments in the world." },
  { i: 1751, base: 250, variant: "exception", c: 4, q: "Which of these is NOT true about Stonehenge?", o: ["It is located in Cornwall", "It is located in Wiltshire", "It is a World Heritage Site", "It is a prehistoric monument"], a: [0], e: "Stonehenge is in Wiltshire, not Cornwall — Cornwall is instead home to the Eden Project." },

  // ---- base i:251 — the Eden Project: in Cornwall ----
  { i: 1752, base: 251, variant: "rephrase", c: 4, q: "Where is the Eden Project?", o: ["Cornwall", "Kent", "Fife", "Antrim"], a: [0], e: "The Eden Project's biomes in Cornwall house plants from around the world." },
  { i: 1753, base: 251, variant: "truefalse", c: 4, q: "Is this statement TRUE or FALSE? The Eden Project is located in Cornwall.", o: ["True", "False"], a: [0], e: "The Eden Project's biomes in Cornwall house plants from around the world." },
  { i: 1754, base: 251, variant: "scenario", c: 4, q: "A friend asks which county is home to the Eden Project's giant biomes housing plants from around the world. Which county is it?", o: ["Cornwall", "Kent", "Fife", "Antrim"], a: [0], e: "The Eden Project's biomes, in Cornwall, house plants from around the world." },
  { i: 1755, base: 251, variant: "exception", c: 4, q: "Which of these is NOT true about the Eden Project?", o: ["It is located in Scotland", "It is located in Cornwall", "It has biomes housing plants from around the world", "It is a well-known visitor attraction"], a: [0], e: "The Eden Project is in Cornwall, in England, not Scotland." },

  // ---- base i:252 — the largest national park: the Cairngorms ----
  { i: 1756, base: 252, variant: "rephrase", c: 4, q: "Which is the largest national park in the UK?", o: ["The Cairngorms", "Snowdonia", "The Lake District", "The Peak District"], a: [0], e: "The Cairngorms National Park in Scotland is the largest in the UK." },
  { i: 1757, base: 252, variant: "truefalse", c: 4, q: "Is this statement TRUE or FALSE? The Cairngorms is the largest national park in the UK.", o: ["True", "False"], a: [0], e: "The Cairngorms National Park in Scotland is the largest in the UK." },
  { i: 1758, base: 252, variant: "scenario", c: 4, q: "A friend asks which Scottish national park is the largest in the whole UK. Which one is it?", o: ["The Cairngorms", "Snowdonia", "The Lake District", "Loch Lomond"], a: [0], e: "The Cairngorms National Park in Scotland is the largest national park in the UK." },
  { i: 1759, base: 252, variant: "exception", c: 4, q: "Which of these is NOT the largest national park in the UK?", o: ["Snowdonia", "The Cairngorms", "A national park located in Scotland", "The UK's largest national park by area"], a: [0], e: "The Cairngorms in Scotland is the UK's largest national park — Snowdonia, in Wales, is not the largest." },

  // ---- base i:253 — a TV licence is needed to watch or record live TV ----
  { i: 1760, base: 253, variant: "rephrase", c: 4, q: "What must you do before you can watch or record live television in the UK?", o: ["Buy a TV licence", "Register with your local council", "Join the BBC", "Apply to Ofcom"], a: [0], e: "A TV licence is needed for each household watching live television or using BBC iPlayer." },
  { i: 1761, base: 253, variant: "truefalse", c: 4, q: "Is this statement TRUE or FALSE? You must buy a TV licence to watch or record live television in the UK.", o: ["True", "False"], a: [0], e: "A TV licence is needed for each household watching live television or using BBC iPlayer." },
  { i: 1762, base: 253, variant: "scenario", c: 4, q: "A friend just moved into their first UK home and plans to watch live TV. What must they arrange first?", o: ["A TV licence", "Registration with the local council", "Membership of the BBC", "Approval from Ofcom"], a: [0], e: "A TV licence is needed for each household watching live television or using BBC iPlayer." },
  { i: 1763, base: 253, variant: "exception", c: 4, q: "Which of these is NOT true about the TV licence?", o: ["It is optional and only recommended", "It is needed to watch live television", "It is needed to use BBC iPlayer", "It applies per household"], a: [0], e: "A TV licence is required by law for watching live television or using BBC iPlayer — it is not merely optional or recommended." },

  // ---- base i:254 — National Lottery minimum age: 18 ----
  { i: 1764, base: 254, variant: "rephrase", c: 4, q: "At what age can you buy a National Lottery ticket?", o: ["18", "16", "21", "14"], a: [0], e: "The minimum age for National Lottery products is 18." },
  { i: 1765, base: 254, variant: "truefalse", c: 4, q: "Is this statement TRUE or FALSE? You must be 18 to buy a National Lottery ticket.", o: ["True", "False"], a: [0], e: "The minimum age for National Lottery products is 18." },
  { i: 1766, base: 254, variant: "scenario", c: 4, q: "A friend turning 16 asks if they can now buy a National Lottery ticket. What do you tell them?", o: ["No — the minimum age is 18", "Yes — 16 is the minimum age", "Yes, but only with a parent present", "No — the minimum age is 21"], a: [0], e: "The minimum age for National Lottery products is 18, so a 16-year-old cannot yet buy a ticket." },
  { i: 1767, base: 254, variant: "exception", c: 4, q: "Which of these is NOT the correct minimum age for buying a National Lottery ticket?", o: ["16", "18", "The same age as buying alcohol", "The same age as betting in a betting shop"], a: [0], e: "The minimum age for National Lottery products is 18, the same as buying alcohol or betting — not 16." },

  // ---- base i:255 — two ways to take part in charity (choose two) ----
  { i: 1768, base: 255, variant: "rephrase", c: 4, q: "Which TWO of these are ways people take part in charity in the UK? (Choose two answers)", o: ["Volunteering for a charity shop", "Giving to a fundraising appeal", "Refusing to pay tax", "Ignoring local elections"], a: [0, 1], e: "Charities such as the National Trust and Comic Relief rely heavily on volunteers and donations." },
  { i: 1769, base: 255, variant: "truefalse", c: 4, q: "Is this statement TRUE or FALSE? Volunteering for a charity shop is a way of taking part in charity in the UK.", o: ["True", "False"], a: [0], e: "Charities such as the National Trust and Comic Relief rely heavily on volunteers and donations." },
  { i: 1770, base: 255, variant: "scenario", c: 4, q: "A friend wants to get involved in charitable work. Which TWO of these would actually help a charity? (Choose two answers)", o: ["Volunteering in a charity shop", "Donating to a fundraising appeal", "Refusing to pay any tax", "Staying home on election day"], a: [0, 1], e: "Charities such as the National Trust and Comic Relief rely heavily on volunteers and donations." },
  { i: 1771, base: 255, variant: "exception", c: 4, q: "Which of these is NOT a way of taking part in charity in the UK?", o: ["Refusing to pay tax", "Volunteering for a charity shop", "Giving to a fundraising appeal", "Donating your time to a good cause"], a: [0], e: "Volunteering and donating are genuine ways to support charities — refusing to pay tax is unrelated to charitable giving, and is a legal obligation, not a choice." },
];
