/* ============================================================
   QUESTION VARIANTS — Chapter 4a (Society: population through Burns
   Night, base i:99-111). See chapter1.js for format notes.
   ============================================================ */

export default [
  // ---- base i:99 — England has the largest population ----
  { i: 1536, base: 99, variant: "rephrase", c: 4, q: "Which country of the UK has by far the largest population?", o: ["England", "Scotland", "Wales", "Northern Ireland"], a: [0], e: "England has around 84% of the UK's population." },
  { i: 1537, base: 99, variant: "truefalse", c: 4, q: "Is this statement TRUE or FALSE? England has by far the largest population of the UK's four countries.", o: ["True", "False"], a: [0], e: "England has around 84% of the UK's population." },
  { i: 1538, base: 99, variant: "scenario", c: 4, q: "A friend asks which UK country has the largest share of the population. Which one is it?", o: ["England", "Scotland", "Wales", "Northern Ireland"], a: [0], e: "England has around 84% of the UK's population." },
  { i: 1539, base: 99, variant: "exception", c: 4, q: "Which of these does NOT have the largest population among the UK's four countries?", o: ["Scotland", "England, which does have the largest population", "This option intentionally names England as correct", "England has around 84% of the population"], a: [0], e: "England has around 84% of the UK's population — the largest share by far, well ahead of Scotland, Wales or Northern Ireland." },

  // ---- base i:100 — a census every 10 years ----
  { i: 1540, base: 100, variant: "rephrase", c: 4, q: "How often is a census carried out in the UK?", o: ["Every 10 years", "Every 5 years", "Every year", "Every 20 years"], a: [0], e: "A census of the whole population is taken every ten years." },
  { i: 1541, base: 100, variant: "truefalse", c: 4, q: "Is this statement TRUE or FALSE? A UK census is carried out every 10 years.", o: ["True", "False"], a: [0], e: "A census of the whole population is taken every ten years." },
  { i: 1542, base: 100, variant: "scenario", c: 4, q: "A friend asks how frequently the UK counts its whole population in a census. How often is that?", o: ["Every 10 years", "Every 5 years", "Every year", "Every 20 years"], a: [0], e: "A census of the whole population is taken every ten years." },
  { i: 1543, base: 100, variant: "exception", c: 4, q: "Which of these is NOT true about the UK census?", o: ["It is carried out every year", "It counts the whole population", "It is carried out every 10 years", "It is a nationwide count"], a: [0], e: "The UK census is carried out every ten years, not every year." },

  // ---- base i:101 — the flag of St George: red cross on white ----
  { i: 1544, base: 101, variant: "rephrase", c: 4, q: "Which flag is the cross of St George?", o: ["A red cross on a white background", "A white diagonal cross on a blue background", "A red diagonal cross on a white background", "A yellow cross on a black background"], a: [0], e: "St George is the patron saint of England; his flag is a red cross on white." },
  { i: 1545, base: 101, variant: "truefalse", c: 4, q: "Is this statement TRUE or FALSE? The flag of St George is a red cross on a white background.", o: ["True", "False"], a: [0], e: "St George is the patron saint of England; his flag is a red cross on white." },
  { i: 1546, base: 101, variant: "scenario", c: 4, q: "A friend asks what England's patron saint's flag looks like. How would you describe it?", o: ["A red cross on a white background", "A white diagonal cross on a blue background", "A red diagonal cross on a white background", "A dragon on a green and white field"], a: [0], e: "St George is the patron saint of England; his flag is a red cross on white." },
  { i: 1547, base: 101, variant: "exception", c: 4, q: "Which of these is NOT true about the flag of St George?", o: ["It represents Scotland", "It is a red cross on white", "It represents England", "St George is England's patron saint"], a: [0], e: "St George's flag, a red cross on white, represents England — St Andrew's flag represents Scotland instead." },

  // ---- base i:102 — the flag of St Andrew: white diagonal cross on blue ----
  { i: 1548, base: 102, variant: "rephrase", c: 4, q: "What does the flag of St Andrew look like?", o: ["A white diagonal cross on a blue background", "A red cross on white", "A red dragon on green and white", "A yellow cross on black"], a: [0], e: "St Andrew is the patron saint of Scotland; the saltire is white on blue." },
  { i: 1549, base: 102, variant: "truefalse", c: 4, q: "Is this statement TRUE or FALSE? The flag of St Andrew is a white diagonal cross on a blue background.", o: ["True", "False"], a: [0], e: "St Andrew is the patron saint of Scotland; the saltire is white on blue." },
  { i: 1550, base: 102, variant: "scenario", c: 4, q: "A friend asks what Scotland's patron saint's flag, the saltire, looks like. How would you describe it?", o: ["A white diagonal cross on a blue background", "A red cross on white", "A red dragon on green and white", "A yellow cross on black"], a: [0], e: "St Andrew is the patron saint of Scotland; the saltire is white on blue." },
  { i: 1551, base: 102, variant: "exception", c: 4, q: "Which of these is NOT true about the flag of St Andrew?", o: ["It is called the Union Jack", "It is called the saltire", "It represents Scotland", "It is white on a blue background"], a: [0], e: "St Andrew's flag is called the saltire, representing Scotland. The Union Jack is the combined flag of the whole UK." },

  // ---- base i:103 — which patron saint's flag is NOT in the Union Flag: St David ----
  { i: 1552, base: 103, variant: "rephrase", c: 4, q: "Which patron saint's flag does NOT appear in the Union Flag?", o: ["St David", "St George", "St Andrew", "St Patrick"], a: [0], e: "The Union Flag combines the crosses of St George, St Andrew and St Patrick. Wales is not represented." },
  { i: 1553, base: 103, variant: "truefalse", c: 4, q: "Is this statement TRUE or FALSE? St David's flag does not appear in the Union Flag.", o: ["True", "False"], a: [0], e: "The Union Flag combines the crosses of St George, St Andrew and St Patrick. Wales is not represented." },
  { i: 1554, base: 103, variant: "scenario", c: 4, q: "A friend asks why Wales isn't represented in the Union Flag design. Whose cross is missing from it?", o: ["St David's", "St George's", "St Andrew's", "St Patrick's"], a: [0], e: "The Union Flag combines the crosses of St George, St Andrew and St Patrick. Wales, and St David's cross, are not represented." },
  { i: 1555, base: 103, variant: "exception", c: 4, q: "Which of these is NOT one of the three patron saints represented in the Union Flag?", o: ["St David", "St George", "St Andrew", "St Patrick"], a: [0], e: "The Union Flag combines the crosses of St George, St Andrew and St Patrick — St David's cross, representing Wales, is the one left out." },

  // ---- base i:104 — St David's Day, 1 March ----
  { i: 1556, base: 104, variant: "rephrase", c: 4, q: "When is St David's Day?", o: ["1 March", "17 March", "23 April", "30 November"], a: [0], e: "St David (Wales) 1 March, St Patrick (NI) 17 March, St George (England) 23 April, St Andrew (Scotland) 30 November." },
  { i: 1557, base: 104, variant: "truefalse", c: 4, q: "Is this statement TRUE or FALSE? St David's Day falls on 1 March.", o: ["True", "False"], a: [0], e: "St David (Wales) 1 March, St Patrick (NI) 17 March, St George (England) 23 April, St Andrew (Scotland) 30 November." },
  { i: 1558, base: 104, variant: "scenario", c: 4, q: "A friend in Wales asks on which date their patron saint's day falls. Which date is it?", o: ["1 March", "17 March", "23 April", "30 November"], a: [0], e: "St David's Day, Wales's patron saint day, falls on 1 March." },
  { i: 1559, base: 104, variant: "exception", c: 4, q: "Which of these is NOT correctly matched with its patron saint's day?", o: ["St David's Day — 23 April", "St David's Day — 1 March", "St Patrick's Day — 17 March", "St George's Day — 23 April"], a: [0], e: "St David's Day falls on 1 March, not 23 April — 23 April is St George's Day for England." },

  // ---- base i:105 — St Andrew's Day, 30 November ----
  { i: 1560, base: 105, variant: "rephrase", c: 4, q: "When is St Andrew's Day?", o: ["30 November", "23 April", "17 March", "1 March"], a: [0], e: "St Andrew's Day, 30 November, is a national day in Scotland." },
  { i: 1561, base: 105, variant: "truefalse", c: 4, q: "Is this statement TRUE or FALSE? St Andrew's Day falls on 30 November.", o: ["True", "False"], a: [0], e: "St Andrew's Day, 30 November, is a national day in Scotland." },
  { i: 1562, base: 105, variant: "scenario", c: 4, q: "A friend in Scotland asks on which date their national day, St Andrew's Day, falls. Which date is it?", o: ["30 November", "23 April", "17 March", "1 March"], a: [0], e: "St Andrew's Day, 30 November, is a national day in Scotland." },
  { i: 1563, base: 105, variant: "exception", c: 4, q: "Which of these is NOT correctly matched with its patron saint's day?", o: ["St Andrew's Day — 17 March", "St Andrew's Day — 30 November", "St Patrick's Day — 17 March", "St George's Day — 23 April"], a: [0], e: "St Andrew's Day falls on 30 November, not 17 March — 17 March is St Patrick's Day for Northern Ireland." },

  // ---- base i:106 — Bonfire Night, 5 November: the 1605 plot ----
  { i: 1564, base: 106, variant: "rephrase", c: 4, q: "Bonfire Night on 5 November commemorates what?", o: ["The failed plot to blow up Parliament in 1605", "The end of the First World War", "The Great Fire of London", "The defeat of the Spanish Armada"], a: [0], e: "Guy Fawkes and other conspirators tried to kill the Protestant king by blowing up Parliament." },
  { i: 1565, base: 106, variant: "truefalse", c: 4, q: "Is this statement TRUE or FALSE? Bonfire Night on 5 November commemorates the failed 1605 plot to blow up Parliament.", o: ["True", "False"], a: [0], e: "Guy Fawkes and other conspirators tried to kill the Protestant king by blowing up Parliament." },
  { i: 1566, base: 106, variant: "scenario", c: 4, q: "A friend new to the UK asks why bonfires and fireworks are set off on 5 November. What is the explanation?", o: ["It marks the failed 1605 plot to blow up Parliament", "It marks the end of the First World War", "It marks the Great Fire of London", "It marks the defeat of the Spanish Armada"], a: [0], e: "Bonfire Night marks Guy Fawkes and other conspirators' failed 1605 plot to blow up Parliament." },
  { i: 1567, base: 106, variant: "exception", c: 4, q: "Which of these is NOT true about Bonfire Night?", o: ["It commemorates a plot that succeeded in destroying Parliament", "It falls on 5 November", "It commemorates a plot from 1605", "Guy Fawkes was involved in the plot it commemorates"], a: [0], e: "The Gunpowder Plot that Bonfire Night commemorates failed — Parliament was not destroyed, and Guy Fawkes was caught before it could be carried out." },

  // ---- base i:107 — Remembrance Day, 11 November: the poppy ----
  { i: 1568, base: 107, variant: "rephrase", c: 4, q: "What do people wear on Remembrance Day, 11 November?", o: ["A poppy", "A rose", "A thistle", "A daffodil"], a: [0], e: "Poppies commemorate those who died in the two world wars and later conflicts." },
  { i: 1569, base: 107, variant: "truefalse", c: 4, q: "Is this statement TRUE or FALSE? People wear a poppy on Remembrance Day.", o: ["True", "False"], a: [0], e: "Poppies commemorate those who died in the two world wars and later conflicts." },
  { i: 1570, base: 107, variant: "scenario", c: 4, q: "A friend asks what flower is worn every November to remember those who died in war. Which flower is it?", o: ["A poppy", "A rose", "A thistle", "A daffodil"], a: [0], e: "Poppies commemorate those who died in the two world wars and later conflicts, worn around Remembrance Day, 11 November." },
  { i: 1571, base: 107, variant: "exception", c: 4, q: "Which of these is NOT true about the poppy worn on Remembrance Day?", o: ["It represents Wales specifically", "It is worn on and around 11 November", "It commemorates those who died in the world wars", "It also commemorates those who died in later conflicts"], a: [0], e: "The poppy commemorates those who died in the world wars and later conflicts across the whole UK — it is not a symbol specific to Wales, whose national symbol is the daffodil." },

  // ---- base i:108 — Hogmanay: Scottish New Year's Eve ----
  { i: 1572, base: 108, variant: "rephrase", c: 4, q: "Hogmanay is the celebration of what?", o: ["New Year's Eve in Scotland", "Midsummer in Wales", "Harvest in Northern Ireland", "May Day in England"], a: [0], e: "Hogmanay is a major Scottish celebration; 2 January is also a bank holiday in Scotland." },
  { i: 1573, base: 108, variant: "truefalse", c: 4, q: "Is this statement TRUE or FALSE? Hogmanay is the Scottish celebration of New Year's Eve.", o: ["True", "False"], a: [0], e: "Hogmanay is a major Scottish celebration; 2 January is also a bank holiday in Scotland." },
  { i: 1574, base: 108, variant: "scenario", c: 4, q: "A friend visiting Scotland over New Year asks about the major local celebration on 31 December. What is it called?", o: ["Hogmanay", "Burns Night", "St Andrew's Day", "The Eisteddfod"], a: [0], e: "Hogmanay is the Scottish celebration of New Year's Eve, a major event; 2 January is also a bank holiday there." },
  { i: 1575, base: 108, variant: "exception", c: 4, q: "Which of these is NOT true about Hogmanay?", o: ["It is celebrated in Wales as a harvest festival", "It is a Scottish celebration", "It marks New Year's Eve", "2 January is also a bank holiday in Scotland because of it"], a: [0], e: "Hogmanay is Scotland's New Year's Eve celebration — it is not a Welsh harvest festival." },

  // ---- base i:109 — Burns Night: the poet Robert Burns ----
  { i: 1576, base: 109, variant: "rephrase", c: 4, q: "Whose life is celebrated on Burns Night, 25 January?", o: ["Robert Burns", "Robert the Bruce", "Rabbie MacAlpin", "Robert Louis Stevenson"], a: [0], e: "Burns Night suppers celebrate the Scottish poet Robert Burns, who wrote Auld Lang Syne." },
  { i: 1577, base: 109, variant: "truefalse", c: 4, q: "Is this statement TRUE or FALSE? Burns Night, 25 January, celebrates the poet Robert Burns.", o: ["True", "False"], a: [0], e: "Burns Night suppers celebrate the Scottish poet Robert Burns, who wrote Auld Lang Syne." },
  { i: 1578, base: 109, variant: "scenario", c: 4, q: "A friend asks who is honoured at a Burns Night supper each 25 January. Who is it?", o: ["Robert Burns", "Robert the Bruce", "Robert Louis Stevenson", "Walter Scott"], a: [0], e: "Burns Night suppers celebrate the Scottish poet Robert Burns, who wrote Auld Lang Syne." },
  { i: 1579, base: 109, variant: "exception", c: 4, q: "Which of these is NOT true about Burns Night?", o: ["It celebrates a Scottish king, not a poet", "It falls on 25 January", "It celebrates the poet Robert Burns", "Burns wrote Auld Lang Syne"], a: [0], e: "Burns Night celebrates the poet Robert Burns, not a king — Robert the Bruce, a Scottish king, is a different historical figure entirely." },

  // ---- base i:110 — two UK-wide bank holidays (choose two) ----
  { i: 1580, base: 110, variant: "rephrase", c: 4, q: "Which TWO are bank holidays across the UK? (Choose two answers)", o: ["Christmas Day", "Good Friday", "Halloween", "Valentine's Day"], a: [0, 1], e: "Christmas Day, Boxing Day, New Year's Day, Good Friday, Easter Monday and other public holidays are bank holidays." },
  { i: 1581, base: 110, variant: "truefalse", c: 4, q: "Is this statement TRUE or FALSE? Good Friday is a bank holiday across the UK.", o: ["True", "False"], a: [0], e: "Christmas Day, Boxing Day, New Year's Day, Good Friday, Easter Monday and other public holidays are bank holidays." },
  { i: 1582, base: 110, variant: "scenario", c: 4, q: "A friend asks which TWO of these days are official bank holidays across the UK. Which are they? (Choose two answers)", o: ["Christmas Day", "Good Friday", "Valentine's Day", "Halloween"], a: [0, 1], e: "Christmas Day, Boxing Day, New Year's Day, Good Friday, Easter Monday and other public holidays are bank holidays." },
  { i: 1583, base: 110, variant: "exception", c: 4, q: "Which of these is NOT a UK bank holiday?", o: ["Halloween", "Christmas Day", "Good Friday", "New Year's Day"], a: [0], e: "Christmas Day, Good Friday and New Year's Day are all bank holidays. Halloween is widely celebrated but is not an official bank holiday." },

  // ---- base i:111 — the Ashes: cricket against Australia ----
  { i: 1584, base: 111, variant: "rephrase", c: 4, q: "The Ashes is a cricket competition between England and which country?", o: ["Australia", "India", "South Africa", "New Zealand"], a: [0], e: "The Ashes series between England and Australia has been played since 1882." },
  { i: 1585, base: 111, variant: "truefalse", c: 4, q: "Is this statement TRUE or FALSE? The Ashes is a cricket competition between England and Australia.", o: ["True", "False"], a: [0], e: "The Ashes series between England and Australia has been played since 1882." },
  { i: 1586, base: 111, variant: "scenario", c: 4, q: "A friend asks which country England plays cricket against in the historic Ashes series. Which country is it?", o: ["Australia", "India", "South Africa", "New Zealand"], a: [0], e: "The Ashes series between England and Australia has been played since 1882." },
  { i: 1587, base: 111, variant: "exception", c: 4, q: "Which of these is NOT true about the Ashes?", o: ["It has been played since the 21st century only", "It is a cricket competition", "It is played between England and Australia", "It has been played since 1882"], a: [0], e: "The Ashes has been played since 1882, in the 19th century, not only since the 21st century." },
];
