/* ============================================================
   QUESTION VARIANTS — Chapter 3b (History: Kenneth MacAlpin through
   Caxton's printing press, base i:34-46). See chapter1.js for
   format notes.
   ============================================================ */

export default [
  // ---- base i:34 — Kenneth MacAlpin unites Scotland ----
  { i: 1164, base: 34, variant: "rephrase", c: 3, q: "Who united the Scottish kingdoms and became the first king of Scotland?", o: ["Kenneth MacAlpin", "Robert the Bruce", "William Wallace", "Macbeth"], a: [0], e: "Kenneth MacAlpin united the Picts and Scots into a single kingdom." },
  { i: 1165, base: 34, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? Kenneth MacAlpin united the Picts and Scots into a single kingdom.", o: ["True", "False"], a: [0], e: "Kenneth MacAlpin united the Picts and Scots into a single kingdom." },
  { i: 1166, base: 34, variant: "scenario", c: 3, q: "A friend asks who first united the Picts and Scots into one kingdom. Who was it?", o: ["Kenneth MacAlpin", "Robert the Bruce", "William Wallace", "Alfred the Great"], a: [0], e: "Kenneth MacAlpin united the Picts and Scots into a single kingdom." },
  { i: 1167, base: 34, variant: "exception", c: 3, q: "Which of these did NOT unite kingdoms or lead a people to victory in early British history?", o: ["Macbeth", "Kenneth MacAlpin", "Alfred the Great", "Robert the Bruce"], a: [0], e: "Kenneth MacAlpin united the Picts and Scots, Alfred the Great defeated the Vikings, and Robert the Bruce won at Bannockburn. Macbeth was a later Scottish king, not credited with uniting the kingdom." },

  // ---- base i:35 — 1066: the Battle of Hastings ----
  { i: 1168, base: 35, variant: "rephrase", c: 3, q: "Which battle took place in 1066?", o: ["The Battle of Hastings", "The Battle of Bosworth Field", "The Battle of Bannockburn", "The Battle of Agincourt"], a: [0], e: "At Hastings in 1066 William, Duke of Normandy, defeated King Harold — the last successful foreign invasion of England." },
  { i: 1169, base: 35, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? The Battle of Hastings took place in 1066.", o: ["True", "False"], a: [0], e: "At Hastings in 1066 William, Duke of Normandy, defeated King Harold — the last successful foreign invasion of England." },
  { i: 1170, base: 35, variant: "scenario", c: 3, q: "A friend asks which famous battle happened in 1066. What is the answer?", o: ["The Battle of Hastings", "The Battle of Bosworth Field", "The Battle of Bannockburn", "The Battle of Agincourt"], a: [0], e: "At Hastings in 1066 William, Duke of Normandy, defeated King Harold — the last successful foreign invasion of England." },
  { i: 1171, base: 35, variant: "exception", c: 3, q: "Which of these is NOT true about the Battle of Hastings?", o: ["It was won by King Harold", "It happened in 1066", "William, Duke of Normandy, won it", "It was the last successful foreign invasion of England"], a: [0], e: "William, Duke of Normandy, defeated King Harold at Hastings in 1066 — Harold lost, and was killed in the battle." },

  // ---- base i:36 — the Bayeux Tapestry ----
  { i: 1172, base: 36, variant: "rephrase", c: 3, q: "What is the Bayeux Tapestry?", o: ["An embroidery showing the Norman conquest of England", "A record of land ownership", "A royal charter of rights", "A map of medieval Britain"], a: [0], e: "The Bayeux Tapestry, still on display in France, commemorates the Battle of Hastings and the Norman conquest." },
  { i: 1173, base: 36, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? The Bayeux Tapestry is an embroidery depicting the Norman conquest of England.", o: ["True", "False"], a: [0], e: "The Bayeux Tapestry, still on display in France, commemorates the Battle of Hastings and the Norman conquest." },
  { i: 1174, base: 36, variant: "scenario", c: 3, q: "A museum guide describes a famous embroidery that shows the events of 1066. What is it called?", o: ["The Bayeux Tapestry", "The Domesday Book", "Magna Carta", "The Book of Kells"], a: [0], e: "The Bayeux Tapestry, still on display in France, commemorates the Battle of Hastings and the Norman conquest." },
  { i: 1175, base: 36, variant: "exception", c: 3, q: "Which of these is NOT true about the Bayeux Tapestry?", o: ["It is a written legal document", "It is an embroidery", "It depicts the Norman conquest", "It is still on display in France"], a: [0], e: "The Bayeux Tapestry is an embroidery, not a written legal document — the Domesday Book is the written land survey from this period." },

  // ---- base i:37 — the Domesday Book ----
  { i: 1176, base: 37, variant: "rephrase", c: 3, q: "What was the Domesday Book?", o: ["A survey of the towns, villages and landholdings of England", "A book of religious law", "A list of English kings", "A collection of poetry"], a: [0], e: "William ordered the Domesday Book in 1086 to record who owned land and livestock across England." },
  { i: 1177, base: 37, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? The Domesday Book was a survey of land and livestock ordered by William.", o: ["True", "False"], a: [0], e: "William ordered the Domesday Book in 1086 to record who owned land and livestock across England." },
  { i: 1178, base: 37, variant: "scenario", c: 3, q: "A friend asks why William ordered a huge survey of England in 1086. What was it for?", o: ["To record who owned land and livestock across England", "To count how many people supported his rule", "To plan a new road network", "To assess how many soldiers each town could provide"], a: [0], e: "William ordered the Domesday Book in 1086 to record who owned land and livestock across England." },
  { i: 1179, base: 37, variant: "exception", c: 3, q: "Which of these is NOT true about the Domesday Book?", o: ["It was a collection of poetry", "It recorded landholdings", "It was ordered by William", "It dates from 1086"], a: [0], e: "The Domesday Book was a survey of towns, villages and landholdings — not a collection of poetry." },

  // ---- base i:38 — Edward I conquers Wales ----
  { i: 1180, base: 38, variant: "rephrase", c: 3, q: "Which English king conquered Wales, building castles such as Conwy and Caernarfon?", o: ["Edward I", "Henry V", "William I", "Richard III"], a: [0], e: "By 1284 Edward I had annexed Wales under the Statute of Rhuddlan and built a ring of great castles." },
  { i: 1181, base: 38, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? Edward I conquered Wales and built castles such as Conwy and Caernarfon.", o: ["True", "False"], a: [0], e: "By 1284 Edward I had annexed Wales under the Statute of Rhuddlan and built a ring of great castles." },
  { i: 1182, base: 38, variant: "scenario", c: 3, q: "A visitor to Conwy Castle asks which English king ordered it built. Who was it?", o: ["Edward I", "Henry V", "William I", "Richard III"], a: [0], e: "By 1284 Edward I had annexed Wales under the Statute of Rhuddlan and built a ring of great castles, including Conwy." },
  { i: 1183, base: 38, variant: "exception", c: 3, q: "Which of these castles is NOT part of Edward I's ring of Welsh castles?", o: ["Bosworth Castle", "Conwy Castle", "Caernarfon Castle", "Harlech Castle"], a: [0], e: "Edward I built castles including Conwy, Caernarfon and Harlech after conquering Wales. Bosworth is not a castle — it is the site of the 1485 battle that ended the Wars of the Roses." },

  // ---- base i:39 — 1314: the Battle of Bannockburn ----
  { i: 1184, base: 39, variant: "rephrase", c: 3, q: "At which 1314 battle did Robert the Bruce defeat the English?", o: ["Bannockburn", "Culloden", "Agincourt", "Naseby"], a: [0], e: "The Scots under Robert the Bruce won at Bannockburn in 1314, keeping Scotland independent for centuries." },
  { i: 1185, base: 39, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? Robert the Bruce defeated the English at the Battle of Bannockburn in 1314.", o: ["True", "False"], a: [0], e: "The Scots under Robert the Bruce won at Bannockburn in 1314, keeping Scotland independent for centuries." },
  { i: 1186, base: 39, variant: "scenario", c: 3, q: "A friend asks which battle secured Scottish independence for centuries under Robert the Bruce. Which was it?", o: ["Bannockburn", "Culloden", "Agincourt", "Naseby"], a: [0], e: "The Scots under Robert the Bruce won at Bannockburn in 1314, keeping Scotland independent for centuries." },
  { i: 1187, base: 39, variant: "exception", c: 3, q: "Which of these statements about Robert the Bruce and Bannockburn is NOT true?", o: ["Culloden was also a victory for Robert the Bruce", "Robert the Bruce defeated the English at Bannockburn", "The battle took place in 1314", "The victory helped keep Scotland independent for centuries"], a: [0], e: "Robert the Bruce won at Bannockburn in 1314, keeping Scotland independent for centuries. Culloden (1746) was a later, unconnected battle — a defeat for the Jacobites, not a victory for Robert the Bruce." },

  // ---- base i:40 — 1415: the Battle of Agincourt ----
  { i: 1188, base: 40, variant: "rephrase", c: 3, q: "Which English king won the Battle of Agincourt in 1415?", o: ["Henry V", "Henry VIII", "Edward III", "Richard II"], a: [0], e: "Henry V's victory at Agincourt came during the Hundred Years War against France." },
  { i: 1189, base: 40, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? Henry V won the Battle of Agincourt in 1415.", o: ["True", "False"], a: [0], e: "Henry V's victory at Agincourt came during the Hundred Years War against France." },
  { i: 1190, base: 40, variant: "scenario", c: 3, q: "A friend asks which king led England to victory at Agincourt. Who was it?", o: ["Henry V", "Henry VIII", "Edward III", "Richard II"], a: [0], e: "Henry V's victory at Agincourt in 1415 came during the Hundred Years War against France." },
  { i: 1191, base: 40, variant: "exception", c: 3, q: "Which of these kings did NOT reign during the Hundred Years War?", o: ["Henry VIII", "Henry V", "Edward III", "Richard II"], a: [0], e: "Henry V, Edward III and Richard II all reigned during the Hundred Years War (1337-1453). Henry VIII reigned in the 16th century, long after it ended." },

  // ---- base i:41 — 1453: the Hundred Years War ends, England keeps Calais ----
  { i: 1192, base: 41, variant: "rephrase", c: 3, q: "The Hundred Years War with France ended in 1453 with England keeping which town?", o: ["Calais", "Paris", "Rouen", "Bordeaux"], a: [0], e: "England lost all its French territories except the port of Calais, itself lost in 1558." },
  { i: 1193, base: 41, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? England kept Calais when the Hundred Years War ended in 1453.", o: ["True", "False"], a: [0], e: "England lost all its French territories except the port of Calais, itself lost in 1558." },
  { i: 1194, base: 41, variant: "scenario", c: 3, q: "A friend asks which French town England still held after losing the Hundred Years War. Which was it?", o: ["Calais", "Paris", "Rouen", "Bordeaux"], a: [0], e: "England lost all its French territories except the port of Calais, itself lost in 1558." },
  { i: 1195, base: 41, variant: "exception", c: 3, q: "Which of these was NOT a French territory England lost by the end of the Hundred Years War?", o: ["Calais", "Bordeaux", "Rouen", "Paris"], a: [0], e: "England lost all its French territories except Calais, which it kept until 1558 — Bordeaux, Rouen and Paris were all lost." },

  // ---- base i:42 — Black Death: about one third of the population died ----
  { i: 1196, base: 42, variant: "rephrase", c: 3, q: "Roughly what proportion of the population of England died in the Black Death of 1348?", o: ["One third", "One tenth", "One half", "Three quarters"], a: [0], e: "The Black Death killed around a third of England's population and also devastated Scotland and Wales." },
  { i: 1197, base: 42, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? Roughly a third of England's population died in the Black Death of 1348.", o: ["True", "False"], a: [0], e: "The Black Death killed around a third of England's population and also devastated Scotland and Wales." },
  { i: 1198, base: 42, variant: "scenario", c: 3, q: "A friend asks how much of the population the Black Death killed in 1348. What is the closest answer?", o: ["About a third", "About a tenth", "About a half", "About three quarters"], a: [0], e: "The Black Death killed around a third of England's population and also devastated Scotland and Wales." },
  { i: 1199, base: 42, variant: "exception", c: 3, q: "Which of these was NOT a consequence of the Black Death of 1348?", o: ["A sudden surplus of workers and falling wages", "A shortage of labour", "The growth of a wealthier middle class", "Around a third of the population dying"], a: [0], e: "The Black Death caused a labour shortage, not a surplus — fewer workers meant survivors could demand higher wages, which helped a wealthier middle class emerge." },

  // ---- base i:43 — Magna Carta, 1215 ----
  { i: 1200, base: 43, variant: "rephrase", c: 3, q: "What was Magna Carta?", o: ["A charter limiting the king's power, agreed in 1215", "The first English Bible", "A treaty with France", "A record of landholdings"], a: [0], e: "King John was forced to agree Magna Carta ('the Great Charter') in 1215, establishing that the king was subject to law." },
  { i: 1201, base: 43, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? Magna Carta, agreed in 1215, limited the power of the king.", o: ["True", "False"], a: [0], e: "King John was forced to agree Magna Carta ('the Great Charter') in 1215, establishing that the king was subject to law." },
  { i: 1202, base: 43, variant: "scenario", c: 3, q: "A friend asks what King John was forced to agree to in 1215. What was it, and what did it do?", o: ["Magna Carta, which limited his power as king", "A treaty ending war with Scotland", "The first English Bible", "A new system of coinage"], a: [0], e: "King John was forced to agree Magna Carta ('the Great Charter') in 1215, establishing that the king was subject to law." },
  { i: 1203, base: 43, variant: "exception", c: 3, q: "Which of these is NOT true about Magna Carta?", o: ["It was agreed by Henry VIII", "It was agreed in 1215", "It limited the king's power", "It established that the king was subject to law"], a: [0], e: "Magna Carta was agreed by King John in 1215, more than 300 years before Henry VIII's reign." },

  // ---- base i:44 — Wars of the Roses: Lancaster vs York ----
  { i: 1204, base: 44, variant: "rephrase", c: 3, q: "The Wars of the Roses were fought between which two houses?", o: ["Lancaster and York", "Tudor and Stuart", "Normandy and Anjou", "Wessex and Mercia"], a: [0], e: "The House of Lancaster (red rose) fought the House of York (white rose) for the throne from 1455 to 1485." },
  { i: 1205, base: 44, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? The Wars of the Roses were fought between the houses of Lancaster and York.", o: ["True", "False"], a: [0], e: "The House of Lancaster (red rose) fought the House of York (white rose) for the throne from 1455 to 1485." },
  { i: 1206, base: 44, variant: "scenario", c: 3, q: "A friend asks which two royal houses fought the Wars of the Roses. Which were they?", o: ["Lancaster and York", "Tudor and Stuart", "Normandy and Anjou", "Wessex and Mercia"], a: [0], e: "The House of Lancaster (red rose) fought the House of York (white rose) for the throne from 1455 to 1485." },
  { i: 1207, base: 44, variant: "exception", c: 3, q: "Which of these houses was NOT involved in the Wars of the Roses?", o: ["Tudor, before the war began", "Lancaster", "York", "The red rose and white rose factions"], a: [0], e: "The Wars of the Roses were fought between Lancaster and York. The Tudor dynasty only began afterwards, when Henry Tudor won at Bosworth Field in 1485." },

  // ---- base i:45 — 1485: the Battle of Bosworth Field ----
  { i: 1208, base: 45, variant: "rephrase", c: 3, q: "Which battle in 1485 ended the Wars of the Roses?", o: ["The Battle of Bosworth Field", "The Battle of Hastings", "The Battle of the Boyne", "The Battle of Marston Moor"], a: [0], e: "Richard III was killed at Bosworth Field and Henry Tudor became Henry VII, founding the Tudor dynasty." },
  { i: 1209, base: 45, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? The Battle of Bosworth Field in 1485 ended the Wars of the Roses.", o: ["True", "False"], a: [0], e: "Richard III was killed at Bosworth Field and Henry Tudor became Henry VII, founding the Tudor dynasty." },
  { i: 1210, base: 45, variant: "scenario", c: 3, q: "A friend asks which battle led to Henry Tudor becoming King Henry VII. Which was it?", o: ["The Battle of Bosworth Field", "The Battle of Hastings", "The Battle of the Boyne", "The Battle of Agincourt"], a: [0], e: "Richard III was killed at Bosworth Field in 1485 and Henry Tudor became Henry VII, founding the Tudor dynasty." },
  { i: 1211, base: 45, variant: "exception", c: 3, q: "Which of these did NOT happen as a result of the Battle of Bosworth Field?", o: ["Richard III became king", "Richard III was killed", "Henry Tudor became King Henry VII", "The Tudor dynasty began"], a: [0], e: "Richard III was killed AT Bosworth Field, not made king by it — the battle ended his reign and began the Tudor dynasty under Henry VII." },

  // ---- base i:46 — 1476: William Caxton's printing press ----
  { i: 1212, base: 46, variant: "rephrase", c: 3, q: "Who set up the first printing press in England, in 1476?", o: ["William Caxton", "Geoffrey Chaucer", "Thomas Cromwell", "Robert Burns"], a: [0], e: "William Caxton brought printing to England, making books far more widely available." },
  { i: 1213, base: 46, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? William Caxton set up the first printing press in England in 1476.", o: ["True", "False"], a: [0], e: "William Caxton brought printing to England, making books far more widely available." },
  { i: 1214, base: 46, variant: "scenario", c: 3, q: "A friend asks who is credited with bringing printing to England. Who was it?", o: ["William Caxton", "Geoffrey Chaucer", "Thomas Cromwell", "Isaac Newton"], a: [0], e: "William Caxton brought printing to England in 1476, making books far more widely available." },
  { i: 1215, base: 46, variant: "exception", c: 3, q: "Which of these is NOT true about William Caxton?", o: ["He wrote The Canterbury Tales", "He set up the first printing press in England", "He worked in 1476", "His work made books more widely available"], a: [0], e: "William Caxton brought printing to England — The Canterbury Tales was written by Geoffrey Chaucer, an earlier writer whose work Caxton later printed." },
];
