/* ============================================================
   QUESTION VARIANTS — Chapter 3g (History: Stonehenge through the
   rebuilding of St Paul's, base i:209-222 — the first half of
   EXTRA_Q's chapter 3 questions). See chapter1.js for format notes.
   ============================================================ */

export default [
  // ---- base i:209 — Stonehenge: Stone and Bronze Age people ----
  { i: 1424, base: 209, variant: "rephrase", c: 3, q: "Which people built Stonehenge?", o: ["Stone Age and Bronze Age people", "The Romans", "The Vikings", "The Normans"], a: [0], e: "Stonehenge in Wiltshire was probably a place of ceremony, built during the Stone and Bronze Ages." },
  { i: 1425, base: 209, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? Stonehenge was built by Stone Age and Bronze Age people.", o: ["True", "False"], a: [0], e: "Stonehenge in Wiltshire was probably a place of ceremony, built during the Stone and Bronze Ages." },
  { i: 1426, base: 209, variant: "scenario", c: 3, q: "A friend visiting Wiltshire asks who built the stone circle at Stonehenge. Who was it?", o: ["Stone Age and Bronze Age people", "The Romans", "The Vikings", "The Normans"], a: [0], e: "Stonehenge in Wiltshire was probably a place of ceremony, built during the Stone and Bronze Ages." },
  { i: 1427, base: 209, variant: "exception", c: 3, q: "Which of these is NOT true about Stonehenge?", o: ["It was built by the Romans", "It is in Wiltshire", "It was probably a place of ceremony", "It was built during the Stone and Bronze Ages"], a: [0], e: "Stonehenge was built by Stone Age and Bronze Age people, long before the Romans arrived in Britain in AD 43." },

  // ---- base i:210 — the Celts and their language ----
  { i: 1428, base: 210, variant: "rephrase", c: 3, q: "What language did the Celts speak?", o: ["Celtic languages, ancestors of Welsh and Gaelic", "Latin", "Old English", "Norse"], a: [0], e: "Celtic languages survive today as Welsh, Gaelic and Cornish." },
  { i: 1429, base: 210, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? Celtic languages are the ancestors of modern Welsh and Gaelic.", o: ["True", "False"], a: [0], e: "Celtic languages survive today as Welsh, Gaelic and Cornish." },
  { i: 1430, base: 210, variant: "scenario", c: 3, q: "A friend asks which ancient language family modern Welsh and Gaelic descend from. What is the answer?", o: ["Celtic languages", "Latin", "Old English", "Norse"], a: [0], e: "Celtic languages survive today as Welsh, Gaelic and Cornish." },
  { i: 1431, base: 210, variant: "exception", c: 3, q: "Which of these languages does NOT descend from the Celtic languages spoken by ancient Britons?", o: ["Old English", "Welsh", "Gaelic", "Cornish"], a: [0], e: "Welsh, Gaelic and Cornish are all descended from the Celtic languages. Old English came from the Anglo-Saxon settlers, a completely different language family." },

  // ---- base i:211 — Scotland and Ireland were never conquered by the Romans ----
  { i: 1432, base: 211, variant: "rephrase", c: 3, q: "Which parts of Britain and Ireland were never conquered by the Romans?", o: ["Scotland and Ireland", "Wales and Cornwall", "Kent and Sussex", "East Anglia"], a: [0], e: "Roman rule covered England and Wales; Scotland and Ireland remained outside the empire." },
  { i: 1433, base: 211, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? Scotland and Ireland were never conquered by the Romans.", o: ["True", "False"], a: [0], e: "Roman rule covered England and Wales; Scotland and Ireland remained outside the empire." },
  { i: 1434, base: 211, variant: "scenario", c: 3, q: "A friend asks which parts of Britain and Ireland stayed outside Roman control. Which were they?", o: ["Scotland and Ireland", "Wales and Cornwall", "Kent and Sussex", "England as a whole"], a: [0], e: "Roman rule covered England and Wales; Scotland and Ireland remained outside the empire." },
  { i: 1435, base: 211, variant: "exception", c: 3, q: "Which of these WAS under Roman rule, unlike Scotland and Ireland?", o: ["Wales", "Scotland", "Ireland", "The area north of Hadrian's Wall"], a: [0], e: "Roman rule covered England and Wales. Scotland, Ireland and the area beyond Hadrian's Wall remained outside the empire." },

  // ---- base i:212 — St Columba founds a monastery on Iona ----
  { i: 1436, base: 212, variant: "rephrase", c: 3, q: "Who founded a monastery on the island of Iona?", o: ["St Columba", "St Augustine", "St Patrick", "St Andrew"], a: [0], e: "St Columba's mission spread Christianity through Scotland from Iona." },
  { i: 1437, base: 212, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? St Columba founded a monastery on the island of Iona.", o: ["True", "False"], a: [0], e: "St Columba's mission spread Christianity through Scotland from Iona." },
  { i: 1438, base: 212, variant: "scenario", c: 3, q: "A friend asks who founded the monastery on Iona that helped spread Christianity through Scotland. Who was it?", o: ["St Columba", "St Augustine", "St Patrick", "St David"], a: [0], e: "St Columba's mission spread Christianity through Scotland from Iona." },
  { i: 1439, base: 212, variant: "exception", c: 3, q: "Which of these is NOT true about St Columba?", o: ["He became the first Archbishop of Canterbury", "He founded a monastery on Iona", "His mission spread Christianity through Scotland", "He is linked with early Christianity in Britain"], a: [0], e: "St Columba founded the monastery on Iona. It was St Augustine, not Columba, who became the first Archbishop of Canterbury." },

  // ---- base i:213 — King Harold led the English at Hastings ----
  { i: 1440, base: 213, variant: "rephrase", c: 3, q: "Which king led the English at the Battle of Hastings?", o: ["Harold", "Alfred", "Cnut", "Edward"], a: [0], e: "King Harold was killed at Hastings in 1066, and William of Normandy took the throne." },
  { i: 1441, base: 213, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? King Harold led the English at the Battle of Hastings in 1066.", o: ["True", "False"], a: [0], e: "King Harold was killed at Hastings in 1066, and William of Normandy took the throne." },
  { i: 1442, base: 213, variant: "scenario", c: 3, q: "A friend asks which English king was killed at the Battle of Hastings in 1066. Who was it?", o: ["Harold", "Alfred", "Cnut", "Edward the Confessor"], a: [0], e: "King Harold was killed at Hastings in 1066, and William of Normandy took the throne." },
  { i: 1443, base: 213, variant: "exception", c: 3, q: "Which of these is NOT true about the Battle of Hastings?", o: ["King Harold won the battle and kept his throne", "King Harold was killed in the battle", "William of Normandy took the throne afterwards", "The battle happened in 1066"], a: [0], e: "King Harold was killed at Hastings, and William of Normandy took the throne — Harold did not win or keep his throne." },

  // ---- base i:214 — Magna Carta sealed at Runnymede ----
  { i: 1444, base: 214, variant: "rephrase", c: 3, q: "Which document did King John seal at Runnymede?", o: ["Magna Carta", "The Bill of Rights", "The Domesday Book", "The Act of Union"], a: [0], e: "The barons forced King John to agree Magna Carta in 1215." },
  { i: 1445, base: 214, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? King John sealed Magna Carta at Runnymede.", o: ["True", "False"], a: [0], e: "The barons forced King John to agree Magna Carta in 1215." },
  { i: 1446, base: 214, variant: "scenario", c: 3, q: "A friend asks what document the barons forced King John to seal at Runnymede in 1215. What was it?", o: ["Magna Carta", "The Bill of Rights", "The Domesday Book", "The Treaty of Rome"], a: [0], e: "The barons forced King John to agree Magna Carta at Runnymede in 1215." },
  { i: 1447, base: 214, variant: "exception", c: 3, q: "Which of these is NOT true about Magna Carta at Runnymede?", o: ["It was sealed voluntarily by King John with no pressure", "It was sealed in 1215", "The barons forced the king to agree to it", "It limited royal power"], a: [0], e: "Magna Carta was sealed under pressure — the barons forced King John to agree to it in 1215, it was not a voluntary act." },

  // ---- base i:215 — the Black Death arrived in the 14th century ----
  { i: 1448, base: 215, variant: "rephrase", c: 3, q: "The Black Death arrived in Britain in which century?", o: ["The 14th century", "The 12th century", "The 16th century", "The 17th century"], a: [0], e: "The plague reached England in 1348 and killed about a third of the population." },
  { i: 1449, base: 215, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? The Black Death arrived in Britain in the 14th century.", o: ["True", "False"], a: [0], e: "The plague reached England in 1348 and killed about a third of the population." },
  { i: 1450, base: 215, variant: "scenario", c: 3, q: "A friend asks in which century the Black Death struck Britain. Which century is it?", o: ["The 14th century", "The 12th century", "The 16th century", "The 17th century"], a: [0], e: "The plague reached England in 1348, in the 14th century, and killed about a third of the population." },
  { i: 1451, base: 215, variant: "exception", c: 3, q: "Which of these is NOT true about when the Black Death arrived in Britain?", o: ["It arrived in the 17th century, the same time as the Great Plague of London", "It arrived in 1348", "It arrived in the 14th century", "It killed about a third of the population"], a: [0], e: "The Black Death reached England in 1348, in the 14th century — the later Great Plague of London (1665) was a separate, later outbreak in the 17th century." },

  // ---- base i:216 — two consequences of the Black Death (choose two) ----
  { i: 1452, base: 216, variant: "rephrase", c: 3, q: "Which TWO were consequences of the Black Death? (Choose two answers)", o: ["A shortage of labour", "The growth of a wealthier middle class", "The Norman conquest", "The invention of printing"], a: [0, 1], e: "Fewer workers meant those who survived could demand better pay, weakening the old feudal system." },
  { i: 1453, base: 216, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? The Black Death led to a shortage of labour in England.", o: ["True", "False"], a: [0], e: "Fewer workers meant those who survived could demand better pay, weakening the old feudal system." },
  { i: 1454, base: 216, variant: "scenario", c: 3, q: "A friend asks how the Black Death changed the economy for surviving workers. Which TWO of these are correct? (Choose two answers)", o: ["Labour became scarce", "A wealthier middle class began to grow", "Printing was invented as a result", "The Normans invaded as a result"], a: [0, 1], e: "Fewer workers meant those who survived could demand better pay, weakening the old feudal system and helping a wealthier middle class emerge." },
  { i: 1455, base: 216, variant: "exception", c: 3, q: "Which of these was NOT a consequence of the Black Death?", o: ["The Norman conquest of England", "A shortage of labour", "Surviving workers being able to demand better pay", "The weakening of the old feudal system"], a: [0], e: "The Black Death caused a labour shortage that weakened feudalism and helped a wealthier middle class emerge. The Norman conquest happened centuries earlier, in 1066." },

  // ---- base i:217 — James II: the last Catholic monarch ----
  { i: 1456, base: 217, variant: "rephrase", c: 3, q: "Who was the last Catholic monarch to rule England?", o: ["James II", "Charles II", "Henry VIII", "Elizabeth I"], a: [0], e: "James II fled in 1688 during the Glorious Revolution." },
  { i: 1457, base: 217, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? James II was the last Catholic monarch to rule England.", o: ["True", "False"], a: [0], e: "James II fled in 1688 during the Glorious Revolution." },
  { i: 1458, base: 217, variant: "scenario", c: 3, q: "A friend asks who was England's last Catholic king, deposed in the Glorious Revolution. Who was it?", o: ["James II", "Charles II", "Henry VIII", "Charles I"], a: [0], e: "James II was the last Catholic monarch to rule England; he fled in 1688 during the Glorious Revolution." },
  { i: 1459, base: 217, variant: "exception", c: 3, q: "Which of these is NOT true about James II?", o: ["He remained king until his natural death", "He was the last Catholic monarch of England", "He fled during the Glorious Revolution", "He fled in 1688"], a: [0], e: "James II fled the country during the Glorious Revolution of 1688 — he did not remain king until his natural death." },

  // ---- base i:218 — the Reformation: a movement against the Pope's authority ----
  { i: 1460, base: 218, variant: "rephrase", c: 3, q: "What was the Reformation?", o: ["A movement against the authority of the Pope", "A rebellion against taxation", "A change to the legal system", "The founding of Parliament"], a: [0], e: "Protestant ideas spread across Europe; Henry VIII's break with Rome brought them to England." },
  { i: 1461, base: 218, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? The Reformation was a movement against the authority of the Pope.", o: ["True", "False"], a: [0], e: "Protestant ideas spread across Europe; Henry VIII's break with Rome brought them to England." },
  { i: 1462, base: 218, variant: "scenario", c: 3, q: "A friend asks what the Reformation, which reached England through Henry VIII, was actually about. What was it?", o: ["A movement against the Pope's authority", "A rebellion against taxation", "A reform of the legal system", "The founding of Parliament"], a: [0], e: "The Reformation was a movement against the Pope's authority; Protestant ideas spread across Europe, and Henry VIII's break with Rome brought them to England." },
  { i: 1463, base: 218, variant: "exception", c: 3, q: "Which of these is NOT true about the Reformation?", o: ["It strengthened the Pope's authority across Europe", "It was a movement against the Pope's authority", "Protestant ideas spread across Europe because of it", "Henry VIII's break with Rome was linked to it"], a: [0], e: "The Reformation challenged and weakened the Pope's authority, spreading Protestant ideas — it did not strengthen the Pope's position." },

  // ---- base i:219 — Mary, Queen of Scots ----
  { i: 1464, base: 219, variant: "rephrase", c: 3, q: "Which queen ruled Scotland and was executed in 1587?", o: ["Mary, Queen of Scots", "Mary I", "Elizabeth I", "Anne"], a: [0], e: "Mary fled to England, was imprisoned for 20 years and was eventually executed on suspicion of plotting against Elizabeth I." },
  { i: 1465, base: 219, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? Mary, Queen of Scots was executed in 1587.", o: ["True", "False"], a: [0], e: "Mary fled to England, was imprisoned for 20 years and was eventually executed on suspicion of plotting against Elizabeth I." },
  { i: 1466, base: 219, variant: "scenario", c: 3, q: "A friend asks which Scottish queen was imprisoned for 20 years in England before being executed. Who was it?", o: ["Mary, Queen of Scots", "Mary I", "Elizabeth I", "Lady Jane Grey"], a: [0], e: "Mary, Queen of Scots fled to England, was imprisoned for 20 years and was eventually executed on suspicion of plotting against Elizabeth I." },
  { i: 1467, base: 219, variant: "exception", c: 3, q: "Which of these is NOT true about Mary, Queen of Scots?", o: ["She was executed by order of the Pope", "She fled to England", "She was imprisoned for 20 years", "She was executed on suspicion of plotting against Elizabeth I"], a: [0], e: "Mary, Queen of Scots was executed on the order of Elizabeth I's government, on suspicion of plotting against her — not by order of the Pope." },

  // ---- base i:220 — the Gunpowder Plot, 1605 ----
  { i: 1468, base: 220, variant: "rephrase", c: 3, q: "What was the Gunpowder Plot?", o: ["A Catholic plan to blow up the Houses of Parliament in 1605", "A plan to burn London", "A plot to assassinate Cromwell", "A Scottish rebellion"], a: [0], e: "Guy Fawkes was caught guarding explosives beneath Parliament; the failure is marked on 5 November." },
  { i: 1469, base: 220, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? The Gunpowder Plot of 1605 was a plan to blow up the Houses of Parliament.", o: ["True", "False"], a: [0], e: "Guy Fawkes was caught guarding explosives beneath Parliament; the failure is marked on 5 November." },
  { i: 1470, base: 220, variant: "scenario", c: 3, q: "A friend asks what Guy Fawkes was caught doing beneath Parliament in 1605. What was the plan?", o: ["Guarding explosives as part of a plot to blow up Parliament", "Planning to burn down London", "Plotting to assassinate a future Lord Protector", "Organising a Scottish rebellion"], a: [0], e: "Guy Fawkes was caught guarding explosives beneath Parliament as part of the Gunpowder Plot; the failure is marked on 5 November." },
  { i: 1471, base: 220, variant: "exception", c: 3, q: "Which of these is NOT true about the Gunpowder Plot?", o: ["It succeeded in destroying Parliament", "Guy Fawkes was involved", "It was a Catholic plot", "It took place in 1605"], a: [0], e: "The Gunpowder Plot failed — Guy Fawkes was caught guarding the explosives before they could be used, and Parliament was not destroyed." },

  // ---- base i:221 — the English Civil War: Parliament vs Charles I ----
  { i: 1472, base: 221, variant: "rephrase", c: 3, q: "Which war was fought between Parliament and King Charles I?", o: ["The English Civil War", "The Wars of the Roses", "The Hundred Years War", "The Crimean War"], a: [0], e: "The Civil War began in 1642 and led to the king's execution in 1649." },
  { i: 1473, base: 221, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? The English Civil War was fought between Parliament and King Charles I.", o: ["True", "False"], a: [0], e: "The Civil War began in 1642 and led to the king's execution in 1649." },
  { i: 1474, base: 221, variant: "scenario", c: 3, q: "A friend asks which conflict, beginning in 1642, was fought between Parliament and the king. Which conflict was it?", o: ["The English Civil War", "The Wars of the Roses", "The Hundred Years War", "The Jacobite rebellions"], a: [0], e: "The English Civil War began in 1642, fought between Parliament and King Charles I, and led to the king's execution in 1649." },
  { i: 1475, base: 221, variant: "exception", c: 3, q: "Which of these is NOT true about the English Civil War?", o: ["It was fought between two royal houses, Lancaster and York", "It began in 1642", "It was fought between Parliament and the king", "It led to the king's execution in 1649"], a: [0], e: "The English Civil War was fought between Parliament and King Charles I — Lancaster and York fought each other much earlier, in the Wars of the Roses." },

  // ---- base i:222 — Christopher Wren rebuilds St Paul's ----
  { i: 1476, base: 222, variant: "rephrase", c: 3, q: "Who was the architect who rebuilt St Paul's Cathedral after the Great Fire?", o: ["Sir Christopher Wren", "Inigo Jones", "Robert Adam", "John Nash"], a: [0], e: "The Great Fire of 1666 destroyed much of London, including the old cathedral." },
  { i: 1477, base: 222, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? Sir Christopher Wren rebuilt St Paul's Cathedral after the Great Fire of London.", o: ["True", "False"], a: [0], e: "The Great Fire of 1666 destroyed much of London, including the old cathedral." },
  { i: 1478, base: 222, variant: "scenario", c: 3, q: "A friend asks who designed the rebuilt St Paul's Cathedral after the 1666 fire destroyed the old one. Who was it?", o: ["Sir Christopher Wren", "Inigo Jones", "Robert Adam", "Sir Norman Foster"], a: [0], e: "Sir Christopher Wren rebuilt St Paul's Cathedral after the Great Fire of 1666 destroyed the old one." },
  { i: 1479, base: 222, variant: "exception", c: 3, q: "Which of these is NOT true about Sir Christopher Wren?", o: ["He designed the original medieval St Paul's Cathedral", "He rebuilt St Paul's after the Great Fire", "His work followed the fire of 1666", "He is a famous English architect"], a: [0], e: "Christopher Wren rebuilt St Paul's after the Great Fire destroyed the old medieval cathedral — he did not design the original." },
];
