/* ============================================================
   QUESTION VARIANTS — Chapter 5a (Government and law: the
   constitutional monarchy through the Northern Ireland Assembly,
   base i:139-151). See chapter1.js for format notes.
   ============================================================ */

export default [
  // ---- base i:139 — a constitutional monarchy with parliamentary democracy ----
  { i: 1772, base: 139, variant: "rephrase", c: 5, q: "What kind of system of government does the UK have?", o: ["A constitutional monarchy with a parliamentary democracy", "An absolute monarchy", "A federal republic", "A one-party state"], a: [0], e: "The monarch is head of state but the elected government runs the country." },
  { i: 1773, base: 139, variant: "truefalse", c: 5, q: "Is this statement TRUE or FALSE? The UK is a constitutional monarchy with a parliamentary democracy.", o: ["True", "False"], a: [0], e: "The monarch is head of state but the elected government runs the country." },
  { i: 1774, base: 139, variant: "scenario", c: 5, q: "A friend asks how to describe the UK's system of government, where the monarch is head of state but doesn't run the country. What is it called?", o: ["A constitutional monarchy with a parliamentary democracy", "An absolute monarchy", "A federal republic", "A one-party state"], a: [0], e: "The UK is a constitutional monarchy with a parliamentary democracy — the monarch is head of state but the elected government runs the country." },
  { i: 1775, base: 139, variant: "exception", c: 5, q: "Which of these is NOT true about the UK's system of government?", o: ["The monarch personally runs the country day to day", "The UK is a constitutional monarchy", "The UK is a parliamentary democracy", "The elected government runs the country"], a: [0], e: "The monarch is head of state but does not personally run the country — the elected government does." },

  // ---- base i:140 — 650 MPs in the House of Commons ----
  { i: 1776, base: 140, variant: "rephrase", c: 5, q: "How many members of Parliament (MPs) are there in the House of Commons?", o: ["650", "600", "129", "450"], a: [0], e: "Each MP represents a constituency, and there are 650 of them." },
  { i: 1777, base: 140, variant: "truefalse", c: 5, q: "Is this statement TRUE or FALSE? There are 650 MPs in the House of Commons.", o: ["True", "False"], a: [0], e: "Each MP represents a constituency, and there are 650 of them." },
  { i: 1778, base: 140, variant: "scenario", c: 5, q: "A friend asks how many MPs sit in the House of Commons, each representing one constituency. How many is that?", o: ["650", "600", "129", "450"], a: [0], e: "Each MP represents a constituency, and there are 650 of them." },
  { i: 1779, base: 140, variant: "exception", c: 5, q: "Which of these is NOT true about MPs in the House of Commons?", o: ["There are 129 of them", "There are 650 of them", "Each one represents a constituency", "They sit in the House of Commons"], a: [0], e: "There are 650 MPs in the House of Commons — 129 is instead the number of members in the Scottish Parliament." },

  // ---- base i:141 — the Speaker chairs Commons debates ----
  { i: 1780, base: 141, variant: "rephrase", c: 5, q: "Who chairs debates in the House of Commons?", o: ["The Speaker", "The Prime Minister", "The Lord Chancellor", "The monarch"], a: [0], e: "The Speaker is an MP elected by other MPs in a secret ballot and must be politically neutral." },
  { i: 1781, base: 141, variant: "truefalse", c: 5, q: "Is this statement TRUE or FALSE? The Speaker chairs debates in the House of Commons.", o: ["True", "False"], a: [0], e: "The Speaker is an MP elected by other MPs in a secret ballot and must be politically neutral." },
  { i: 1782, base: 141, variant: "scenario", c: 5, q: "A friend asks who is responsible for chairing debates in the House of Commons and must remain politically neutral. Who is it?", o: ["The Speaker", "The Prime Minister", "The Lord Chancellor", "The Leader of the Opposition"], a: [0], e: "The Speaker is an MP elected by other MPs in a secret ballot and must be politically neutral." },
  { i: 1783, base: 141, variant: "exception", c: 5, q: "Which of these is NOT true about the Speaker of the House of Commons?", o: ["The Speaker is appointed directly by the Prime Minister", "The Speaker is an MP", "The Speaker is elected by other MPs", "The Speaker must be politically neutral"], a: [0], e: "The Speaker is elected by fellow MPs in a secret ballot — not appointed by the Prime Minister." },

  // ---- base i:142 — House of Lords members: Peers ----
  { i: 1784, base: 142, variant: "rephrase", c: 5, q: "Members of the House of Lords are usually known as what?", o: ["Peers", "MPs", "Councillors", "Ministers"], a: [0], e: "Most peers today are life peers, appointed for their lifetime; the Lords also includes bishops and some hereditary peers." },
  { i: 1785, base: 142, variant: "truefalse", c: 5, q: "Is this statement TRUE or FALSE? Members of the House of Lords are usually known as Peers.", o: ["True", "False"], a: [0], e: "Most peers today are life peers, appointed for their lifetime; the Lords also includes bishops and some hereditary peers." },
  { i: 1786, base: 142, variant: "scenario", c: 5, q: "A friend asks what members of the House of Lords, mostly appointed for their lifetime, are called. What is the term?", o: ["Peers", "MPs", "Councillors", "Aldermen"], a: [0], e: "Members of the House of Lords are usually known as Peers; most today are life peers, alongside bishops and some hereditary peers." },
  { i: 1787, base: 142, variant: "exception", c: 5, q: "Which of these is NOT true about members of the House of Lords?", o: ["They are all elected by the public", "Most are life peers", "The Lords includes some bishops", "The Lords includes some hereditary peers"], a: [0], e: "Members of the House of Lords are not elected by the public — most are appointed as life peers, alongside bishops and some hereditary peers." },

  // ---- base i:143 — general elections at least every five years ----
  { i: 1788, base: 143, variant: "rephrase", c: 5, q: "How often must a general election be held, at a minimum?", o: ["At least every five years", "At least every three years", "At least every seven years", "Every two years"], a: [0], e: "A general election must be held at least every five years." },
  { i: 1789, base: 143, variant: "truefalse", c: 5, q: "Is this statement TRUE or FALSE? A UK general election must be held at least every five years.", o: ["True", "False"], a: [0], e: "A general election must be held at least every five years." },
  { i: 1790, base: 143, variant: "scenario", c: 5, q: "A friend asks how often, at a minimum, the UK must hold a general election. What is the answer?", o: ["At least every five years", "At least every three years", "At least every seven years", "Every two years"], a: [0], e: "A general election must be held at least every five years." },
  { i: 1791, base: 143, variant: "exception", c: 5, q: "Which of these is NOT true about the timing of UK general elections?", o: ["They can legally be delayed indefinitely with no maximum gap", "They must be held at least every five years", "The gap between them can be shorter than five years", "A five-year gap is the legal maximum"], a: [0], e: "A general election must be held at least every five years — there is a legal maximum gap, not an indefinite delay." },

  // ---- base i:144 — the electoral system: first past the post ----
  { i: 1792, base: 144, variant: "rephrase", c: 5, q: "What is the electoral system used for UK general elections called?", o: ["First past the post", "Proportional representation", "The single transferable vote", "The alternative vote"], a: [0], e: "The candidate with the most votes in each constituency becomes the MP." },
  { i: 1793, base: 144, variant: "truefalse", c: 5, q: "Is this statement TRUE or FALSE? UK general elections use the first past the post system.", o: ["True", "False"], a: [0], e: "The candidate with the most votes in each constituency becomes the MP." },
  { i: 1794, base: 144, variant: "scenario", c: 5, q: "A friend asks what electoral system is used in UK general elections, where the candidate with the most votes in each seat wins. What is it called?", o: ["First past the post", "Proportional representation", "The single transferable vote", "The alternative vote"], a: [0], e: "First past the post is used for UK general elections; the candidate with the most votes in each constituency becomes the MP." },
  { i: 1795, base: 144, variant: "exception", c: 5, q: "Which of these is NOT true about the first past the post system used in UK general elections?", o: ["Seats are allocated strictly in proportion to national vote share", "The candidate with the most votes in a constituency wins", "It is used for UK general elections", "Each constituency elects one MP"], a: [0], e: "First past the post does not allocate seats in proportion to national vote share — the candidate with the most votes in each constituency simply wins that seat." },

  // ---- base i:145 — the PM's official home: 10 Downing Street ----
  { i: 1796, base: 145, variant: "rephrase", c: 5, q: "What is the official home of the Prime Minister?", o: ["10 Downing Street", "11 Downing Street", "Buckingham Palace", "Chequers"], a: [0], e: "The PM lives at 10 Downing Street and also has a country house called Chequers." },
  { i: 1797, base: 145, variant: "truefalse", c: 5, q: "Is this statement TRUE or FALSE? The Prime Minister's official London home is 10 Downing Street.", o: ["True", "False"], a: [0], e: "The PM lives at 10 Downing Street and also has a country house called Chequers." },
  { i: 1798, base: 145, variant: "scenario", c: 5, q: "A friend asks which address is the Prime Minister's official London residence. Which address is it?", o: ["10 Downing Street", "11 Downing Street", "Buckingham Palace", "Chequers"], a: [0], e: "The Prime Minister lives at 10 Downing Street and also has a country house called Chequers." },
  { i: 1799, base: 145, variant: "exception", c: 5, q: "Which of these is NOT true about the Prime Minister's residences?", o: ["11 Downing Street is the PM's main London home", "10 Downing Street is the PM's main London home", "Chequers is the PM's country house", "The PM has both a London and a country residence"], a: [0], e: "The Prime Minister lives at 10 Downing Street — 11 Downing Street is the official residence of the Chancellor of the Exchequer instead." },

  // ---- base i:146 — the Chancellor of the Exchequer: the economy ----
  { i: 1800, base: 146, variant: "rephrase", c: 5, q: "Which minister is responsible for the economy?", o: ["The Chancellor of the Exchequer", "The Home Secretary", "The Foreign Secretary", "The Lord Chancellor"], a: [0], e: "The Chancellor of the Exchequer lives at 11 Downing Street." },
  { i: 1801, base: 146, variant: "truefalse", c: 5, q: "Is this statement TRUE or FALSE? The Chancellor of the Exchequer is responsible for the economy.", o: ["True", "False"], a: [0], e: "The Chancellor of the Exchequer lives at 11 Downing Street." },
  { i: 1802, base: 146, variant: "scenario", c: 5, q: "A friend asks which minister, living at 11 Downing Street, is responsible for the UK economy. Who is it?", o: ["The Chancellor of the Exchequer", "The Home Secretary", "The Foreign Secretary", "The Business Secretary"], a: [0], e: "The Chancellor of the Exchequer, who lives at 11 Downing Street, is responsible for the economy." },
  { i: 1803, base: 146, variant: "exception", c: 5, q: "Which of these is NOT a responsibility of the Chancellor of the Exchequer?", o: ["Policing and immigration", "The economy", "Living at 11 Downing Street", "Financial and budgetary matters"], a: [0], e: "The Chancellor of the Exchequer handles the economy — policing and immigration are the responsibility of the Home Secretary instead." },

  // ---- base i:147 — the Home Secretary: crime, policing and immigration ----
  { i: 1804, base: 147, variant: "rephrase", c: 5, q: "Which minister is responsible for crime, policing and immigration?", o: ["The Home Secretary", "The Foreign Secretary", "The Chancellor of the Exchequer", "The Defence Secretary"], a: [0], e: "The Home Secretary runs the Home Office." },
  { i: 1805, base: 147, variant: "truefalse", c: 5, q: "Is this statement TRUE or FALSE? The Home Secretary is responsible for crime, policing and immigration.", o: ["True", "False"], a: [0], e: "The Home Secretary runs the Home Office." },
  { i: 1806, base: 147, variant: "scenario", c: 5, q: "A friend asks which minister runs the Home Office, covering crime, policing and immigration. Who is it?", o: ["The Home Secretary", "The Foreign Secretary", "The Chancellor of the Exchequer", "The Justice Secretary"], a: [0], e: "The Home Secretary runs the Home Office, responsible for crime, policing and immigration." },
  { i: 1807, base: 147, variant: "exception", c: 5, q: "Which of these is NOT a responsibility of the Home Secretary?", o: ["Relations with other countries", "Crime", "Policing", "Immigration"], a: [0], e: "The Home Secretary is responsible for crime, policing and immigration, not foreign relations — that is the Foreign Secretary's role." },

  // ---- base i:148 — the opposition: the second largest party ----
  { i: 1808, base: 148, variant: "rephrase", c: 5, q: "What is the 'opposition'?", o: ["The second largest party in the House of Commons", "A group of civil servants", "The House of Lords", "Independent MPs only"], a: [0], e: "The Leader of the Opposition leads their party and appoints a shadow cabinet to challenge the government." },
  { i: 1809, base: 148, variant: "truefalse", c: 5, q: "Is this statement TRUE or FALSE? The 'opposition' is the second largest party in the House of Commons.", o: ["True", "False"], a: [0], e: "The Leader of the Opposition leads their party and appoints a shadow cabinet to challenge the government." },
  { i: 1810, base: 148, variant: "scenario", c: 5, q: "A friend asks what is meant by 'the opposition' in the House of Commons. What is the correct definition?", o: ["The second largest party in the Commons", "A group of civil servants", "The House of Lords", "Only MPs with no party"], a: [0], e: "The opposition is the second largest party in the House of Commons; its leader appoints a shadow cabinet to challenge the government." },
  { i: 1811, base: 148, variant: "exception", c: 5, q: "Which of these is NOT true about the opposition in the House of Commons?", o: ["Its leader has no formal role at all", "It is the second largest party", "Its leader appoints a shadow cabinet", "Its role is to challenge the government"], a: [0], e: "The Leader of the Opposition has a formal, recognised role — appointing a shadow cabinet to challenge the government — not no role at all." },

  // ---- base i:149 — the civil service: politically neutral ----
  { i: 1812, base: 149, variant: "rephrase", c: 5, q: "What is the civil service required to be?", o: ["Politically neutral and appointed on merit", "Elected by the public", "Appointed by the monarch", "Members of the governing party"], a: [0], e: "Civil servants support the government of the day whatever their own political views." },
  { i: 1813, base: 149, variant: "truefalse", c: 5, q: "Is this statement TRUE or FALSE? The civil service is required to be politically neutral and appointed on merit.", o: ["True", "False"], a: [0], e: "Civil servants support the government of the day whatever their own political views." },
  { i: 1814, base: 149, variant: "scenario", c: 5, q: "A friend asks whether civil servants must belong to the governing party. What is the correct answer?", o: ["No — they must be politically neutral and appointed on merit", "Yes — they must belong to the governing party", "Yes, but only senior civil servants", "No — but they are elected by the public"], a: [0], e: "Civil servants are required to be politically neutral and appointed on merit — they support the government of the day regardless of their own views." },
  { i: 1815, base: 149, variant: "exception", c: 5, q: "Which of these is NOT true about the civil service?", o: ["Civil servants are elected by the public", "Civil servants are politically neutral", "Civil servants are appointed on merit", "Civil servants support the government of the day regardless of their own views"], a: [0], e: "Civil servants are appointed, not elected by the public — they are meant to be politically neutral and chosen on merit." },

  // ---- base i:150 — the Scottish Parliament: 129 members ----
  { i: 1816, base: 150, variant: "rephrase", c: 5, q: "How many members does the Scottish Parliament have?", o: ["129", "650", "90", "60"], a: [0], e: "There are 129 Members of the Scottish Parliament (MSPs), based at Holyrood in Edinburgh." },
  { i: 1817, base: 150, variant: "truefalse", c: 5, q: "Is this statement TRUE or FALSE? The Scottish Parliament has 129 members.", o: ["True", "False"], a: [0], e: "There are 129 Members of the Scottish Parliament (MSPs), based at Holyrood in Edinburgh." },
  { i: 1818, base: 150, variant: "scenario", c: 5, q: "A friend asks how many MSPs sit in the Scottish Parliament at Holyrood. How many is that?", o: ["129", "650", "90", "60"], a: [0], e: "There are 129 Members of the Scottish Parliament (MSPs), based at Holyrood in Edinburgh." },
  { i: 1819, base: 150, variant: "exception", c: 5, q: "Which of these is NOT true about the Scottish Parliament?", o: ["It has 90 members", "It has 129 members", "Its members are called MSPs", "It is based at Holyrood in Edinburgh"], a: [0], e: "The Scottish Parliament has 129 members — 90 is instead the number of members (MLAs) in the Northern Ireland Assembly." },

  // ---- base i:151 — the Northern Ireland Assembly: Stormont, Belfast ----
  { i: 1820, base: 151, variant: "rephrase", c: 5, q: "Where does the Northern Ireland Assembly meet?", o: ["Stormont, Belfast", "Holyrood, Edinburgh", "Cardiff Bay", "Westminster"], a: [0], e: "The Northern Ireland Assembly has 90 members (MLAs) and works on a power-sharing basis." },
  { i: 1821, base: 151, variant: "truefalse", c: 5, q: "Is this statement TRUE or FALSE? The Northern Ireland Assembly meets at Stormont, Belfast.", o: ["True", "False"], a: [0], e: "The Northern Ireland Assembly has 90 members (MLAs) and works on a power-sharing basis." },
  { i: 1822, base: 151, variant: "scenario", c: 5, q: "A friend asks where the Northern Ireland Assembly, with its 90 MLAs, is based. Where is it?", o: ["Stormont, Belfast", "Holyrood, Edinburgh", "Cardiff Bay", "Westminster"], a: [0], e: "The Northern Ireland Assembly, based at Stormont, Belfast, has 90 members (MLAs) and works on a power-sharing basis." },
  { i: 1823, base: 151, variant: "exception", c: 5, q: "Which of these is NOT true about the Northern Ireland Assembly?", o: ["It meets at Holyrood", "It meets at Stormont", "It has 90 members", "It operates on a power-sharing basis"], a: [0], e: "The Northern Ireland Assembly meets at Stormont, Belfast — Holyrood, in Edinburgh, is instead where the Scottish Parliament meets." },
];
