/* ============================================================
   QUESTION VARIANTS — Chapter 3c (History: Chaucer through the
   Glorious Revolution, base i:47-59). See chapter1.js for format
   notes.
   ============================================================ */

export default [
  // ---- base i:47 — Chaucer wrote The Canterbury Tales ----
  { i: 1216, base: 47, variant: "rephrase", c: 3, q: "Who wrote The Canterbury Tales?", o: ["Geoffrey Chaucer", "William Shakespeare", "John Milton", "Robert Burns"], a: [0], e: "Chaucer's Canterbury Tales is a collection of poems about a group of pilgrims travelling to Canterbury." },
  { i: 1217, base: 47, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? Geoffrey Chaucer wrote The Canterbury Tales.", o: ["True", "False"], a: [0], e: "Chaucer's Canterbury Tales is a collection of poems about a group of pilgrims travelling to Canterbury." },
  { i: 1218, base: 47, variant: "scenario", c: 3, q: "A friend asks who wrote a famous collection of poems about pilgrims travelling to Canterbury. Who was it?", o: ["Geoffrey Chaucer", "William Shakespeare", "John Milton", "William Caxton"], a: [0], e: "Chaucer's Canterbury Tales is a collection of poems about a group of pilgrims travelling to Canterbury." },
  { i: 1219, base: 47, variant: "exception", c: 3, q: "Which of these did NOT write The Canterbury Tales?", o: ["William Caxton", "Geoffrey Chaucer", "The author of the pilgrim poems", "A medieval English writer"], a: [0], e: "The Canterbury Tales was written by Geoffrey Chaucer. William Caxton later printed books, including Chaucer's, but did not write them." },

  // ---- base i:48 — Henry VIII had six wives ----
  { i: 1220, base: 48, variant: "rephrase", c: 3, q: "How many wives did Henry VIII have?", o: ["Six", "Four", "Two", "Eight"], a: [0], e: "Catherine of Aragon, Anne Boleyn, Jane Seymour, Anne of Cleves, Catherine Howard and Catherine Parr — divorced, beheaded, died, divorced, beheaded, survived." },
  { i: 1221, base: 48, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? Henry VIII had six wives.", o: ["True", "False"], a: [0], e: "Catherine of Aragon, Anne Boleyn, Jane Seymour, Anne of Cleves, Catherine Howard and Catherine Parr — divorced, beheaded, died, divorced, beheaded, survived." },
  { i: 1222, base: 48, variant: "scenario", c: 3, q: "A friend is trying to remember how many times Henry VIII married. What is the correct number?", o: ["Six", "Four", "Two", "Eight"], a: [0], e: "Henry VIII had six wives: Catherine of Aragon, Anne Boleyn, Jane Seymour, Anne of Cleves, Catherine Howard and Catherine Parr." },
  { i: 1223, base: 48, variant: "exception", c: 3, q: "Which of these was NOT one of Henry VIII's six wives?", o: ["Mary I", "Catherine of Aragon", "Anne Boleyn", "Catherine Parr"], a: [0], e: "Henry VIII's six wives were Catherine of Aragon, Anne Boleyn, Jane Seymour, Anne of Cleves, Catherine Howard and Catherine Parr. Mary I was his daughter, not a wife." },

  // ---- base i:49 — why Henry VIII broke from Rome ----
  { i: 1224, base: 49, variant: "rephrase", c: 3, q: "Why did Henry VIII break away from the Church of Rome?", o: ["The Pope refused to annul his marriage to Catherine of Aragon", "He wanted to invade France", "He wished to raise taxes", "He converted to Judaism"], a: [0], e: "Henry set up the Church of England with himself as its head so he could remarry, beginning the English Reformation." },
  { i: 1225, base: 49, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? Henry VIII broke from Rome because the Pope would not annul his first marriage.", o: ["True", "False"], a: [0], e: "Henry set up the Church of England with himself as its head so he could remarry, beginning the English Reformation." },
  { i: 1226, base: 49, variant: "scenario", c: 3, q: "A friend asks why Henry VIII created the Church of England. What is the correct reason?", o: ["The Pope refused to annul his marriage to Catherine of Aragon", "He wanted to invade France", "He disliked the Latin language used in church services", "He wanted to abolish taxation"], a: [0], e: "Henry set up the Church of England with himself as its head so he could remarry, beginning the English Reformation." },
  { i: 1227, base: 49, variant: "exception", c: 3, q: "Which of these did NOT result from Henry VIII's break with Rome?", o: ["War with France over religion", "The creation of the Church of England", "Henry becoming head of the new church", "The start of the English Reformation"], a: [0], e: "Henry's break with Rome created the Church of England and began the Reformation, with Henry as its head — it was not caused by or centred on a war with France." },

  // ---- base i:50 — Mary I, 'Bloody Mary' ----
  { i: 1228, base: 50, variant: "rephrase", c: 3, q: "Which queen was known as 'Bloody Mary' for persecuting Protestants?", o: ["Mary I", "Mary Queen of Scots", "Elizabeth I", "Queen Anne"], a: [0], e: "Mary I, Henry VIII's daughter, was a devout Catholic who had many Protestants executed." },
  { i: 1229, base: 50, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? Mary I was known as 'Bloody Mary' for persecuting Protestants.", o: ["True", "False"], a: [0], e: "Mary I, Henry VIII's daughter, was a devout Catholic who had many Protestants executed." },
  { i: 1230, base: 50, variant: "scenario", c: 3, q: "A friend asks which of Henry VIII's daughters became known as 'Bloody Mary'. Who was it?", o: ["Mary I", "Elizabeth I", "Mary Queen of Scots", "Lady Jane Grey"], a: [0], e: "Mary I, Henry VIII's daughter, was a devout Catholic who had many Protestants executed, earning her the nickname 'Bloody Mary'." },
  { i: 1231, base: 50, variant: "exception", c: 3, q: "Which of these is NOT true about Mary I?", o: ["She was a committed Protestant", "She was Henry VIII's daughter", "She persecuted Protestants", "She is known as 'Bloody Mary'"], a: [0], e: "Mary I was a devout Catholic, not a Protestant — this is precisely why she persecuted Protestants during her reign." },

  // ---- base i:51 — 1588: the Spanish Armada is defeated ----
  { i: 1232, base: 51, variant: "rephrase", c: 3, q: "In which year was the Spanish Armada defeated?", o: ["1588", "1485", "1666", "1215"], a: [0], e: "The English fleet defeated the Spanish Armada sent by Philip II to invade England in 1588." },
  { i: 1233, base: 51, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? The Spanish Armada was defeated in 1588.", o: ["True", "False"], a: [0], e: "The English fleet defeated the Spanish Armada sent by Philip II to invade England in 1588." },
  { i: 1234, base: 51, variant: "scenario", c: 3, q: "A friend asks in which year England defeated a Spanish invasion fleet sent by Philip II. Which year is it?", o: ["1588", "1485", "1666", "1707"], a: [0], e: "The English fleet defeated the Spanish Armada sent by Philip II to invade England in 1588." },
  { i: 1235, base: 51, variant: "exception", c: 3, q: "Which of these events did NOT happen in the same century as the defeat of the Spanish Armada?", o: ["The Great Fire of London", "The reign of Elizabeth I", "The defeat of the Spanish Armada itself", "The excommunication tensions between England and Spain"], a: [0], e: "The Spanish Armada was defeated in 1588, during the 16th century. The Great Fire of London happened in 1666, in the 17th century." },

  // ---- base i:52 — Shakespeare born in Stratford-upon-Avon ----
  { i: 1236, base: 52, variant: "rephrase", c: 3, q: "Where was William Shakespeare born?", o: ["Stratford-upon-Avon", "London", "Canterbury", "Edinburgh"], a: [0], e: "Shakespeare was born in Stratford-upon-Avon and later worked at the Globe theatre in London." },
  { i: 1237, base: 52, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? William Shakespeare was born in Stratford-upon-Avon.", o: ["True", "False"], a: [0], e: "Shakespeare was born in Stratford-upon-Avon and later worked at the Globe theatre in London." },
  { i: 1238, base: 52, variant: "scenario", c: 3, q: "A friend visiting Shakespeare's birthplace asks which town it is in. What do you tell them?", o: ["Stratford-upon-Avon", "London", "Canterbury", "Edinburgh"], a: [0], e: "Shakespeare was born in Stratford-upon-Avon and later worked at the Globe theatre in London." },
  { i: 1239, base: 52, variant: "exception", c: 3, q: "Which of these is NOT true about William Shakespeare?", o: ["He was born in London", "He was born in Stratford-upon-Avon", "He worked at the Globe theatre", "He worked in London as a playwright"], a: [0], e: "Shakespeare was born in Stratford-upon-Avon, not London — though he later worked in London at the Globe theatre." },

  // ---- base i:53 — 1603: the Union of the Crowns ----
  { i: 1240, base: 53, variant: "rephrase", c: 3, q: "Who became King of England, Wales and Ireland in 1603 while also King of Scotland?", o: ["James VI of Scotland (James I of England)", "Charles I", "Henry VII", "William III"], a: [0], e: "The Union of the Crowns in 1603 brought England and Scotland under one monarch, though they stayed separate countries." },
  { i: 1241, base: 53, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? James VI of Scotland became James I of England in 1603.", o: ["True", "False"], a: [0], e: "The Union of the Crowns in 1603 brought England and Scotland under one monarch, though they stayed separate countries." },
  { i: 1242, base: 53, variant: "scenario", c: 3, q: "A friend asks which king ruled both Scotland and England after 1603, without the two countries formally merging. Who was it?", o: ["James VI of Scotland (James I of England)", "Charles I", "Henry VII", "William III"], a: [0], e: "The Union of the Crowns in 1603 brought England and Scotland under one monarch, though they stayed separate countries." },
  { i: 1243, base: 53, variant: "exception", c: 3, q: "Which of these did NOT happen as a result of the 1603 Union of the Crowns?", o: ["England and Scotland formally merged into one country immediately", "James VI of Scotland became James I of England", "The two countries shared one monarch", "Scotland kept its own parliament and laws for the time being"], a: [0], e: "The Union of the Crowns in 1603 brought England and Scotland under one monarch, but they stayed separate countries — full political union did not come until the Act of Union in 1707." },

  // ---- base i:54 — Cavaliers: supporters of the king in the Civil War ----
  { i: 1244, base: 54, variant: "rephrase", c: 3, q: "During the English Civil War, supporters of the king were known as what?", o: ["Cavaliers", "Roundheads", "Jacobites", "Whigs"], a: [0], e: "Royalist Cavaliers fought the Parliamentarian Roundheads from 1642." },
  { i: 1245, base: 54, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? Supporters of the king in the English Civil War were known as Cavaliers.", o: ["True", "False"], a: [0], e: "Royalist Cavaliers fought the Parliamentarian Roundheads from 1642." },
  { i: 1246, base: 54, variant: "scenario", c: 3, q: "A friend asks what royalist supporters of Charles I were called during the Civil War. What is the answer?", o: ["Cavaliers", "Roundheads", "Jacobites", "Whigs"], a: [0], e: "Royalist Cavaliers fought the Parliamentarian Roundheads from 1642." },
  { i: 1247, base: 54, variant: "exception", c: 3, q: "Which of these terms does NOT describe a side in the English Civil War?", o: ["Jacobites", "Cavaliers", "Roundheads", "Royalists"], a: [0], e: "Cavaliers (Royalists) fought Roundheads (Parliamentarians) in the Civil War. Jacobites were supporters of the exiled James II and his heirs, in a later conflict." },

  // ---- base i:55 — 1649: Charles I is executed ----
  { i: 1248, base: 55, variant: "rephrase", c: 3, q: "In which year was Charles I executed?", o: ["1649", "1660", "1666", "1688"], a: [0], e: "Charles I was executed in 1649 and England became a republic known as the Commonwealth." },
  { i: 1249, base: 55, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? Charles I was executed in 1649.", o: ["True", "False"], a: [0], e: "Charles I was executed in 1649 and England became a republic known as the Commonwealth." },
  { i: 1250, base: 55, variant: "scenario", c: 3, q: "A friend asks in which year Charles I was executed, making England a republic. Which year is it?", o: ["1649", "1660", "1666", "1688"], a: [0], e: "Charles I was executed in 1649 and England became a republic known as the Commonwealth." },
  { i: 1251, base: 55, variant: "exception", c: 3, q: "Which of these did NOT happen in 1649?", o: ["The monarchy was restored under Charles II", "Charles I was executed", "England became a republic", "The Commonwealth period began"], a: [0], e: "Charles I's execution and the start of the Commonwealth happened in 1649. The monarchy was restored eleven years later, in 1660." },

  // ---- base i:56 — Cromwell's title: Lord Protector ----
  { i: 1252, base: 56, variant: "rephrase", c: 3, q: "What title did Oliver Cromwell take?", o: ["Lord Protector", "King of England", "Lord Chancellor", "Prime Minister"], a: [0], e: "Cromwell ruled as Lord Protector until his death in 1658; his son Richard proved unable to govern." },
  { i: 1253, base: 56, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? Oliver Cromwell took the title Lord Protector.", o: ["True", "False"], a: [0], e: "Cromwell ruled as Lord Protector until his death in 1658; his son Richard proved unable to govern." },
  { i: 1254, base: 56, variant: "scenario", c: 3, q: "A friend asks what title Oliver Cromwell used while ruling England as a republic. What was it?", o: ["Lord Protector", "King of England", "Lord Chancellor", "Prime Minister"], a: [0], e: "Cromwell ruled as Lord Protector until his death in 1658; he never took the title of king." },
  { i: 1255, base: 56, variant: "exception", c: 3, q: "Which of these is NOT true about Oliver Cromwell?", o: ["He was crowned King of England", "He ruled with the title Lord Protector", "He died in 1658", "His son Richard succeeded him but could not govern effectively"], a: [0], e: "Cromwell ruled as Lord Protector, not as king — England was a republic during this period, without a monarch." },

  // ---- base i:57 — 1660: the Restoration, Charles II returns ----
  { i: 1256, base: 57, variant: "rephrase", c: 3, q: "In which year did the monarchy return under Charles II?", o: ["1660", "1649", "1688", "1707"], a: [0], e: "Parliament invited Charles II to return in 1660, an event known as the Restoration." },
  { i: 1257, base: 57, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? Charles II returned to the throne in 1660.", o: ["True", "False"], a: [0], e: "Parliament invited Charles II to return in 1660, an event known as the Restoration." },
  { i: 1258, base: 57, variant: "scenario", c: 3, q: "A friend asks in which year the monarchy was restored under Charles II, following Cromwell's republic. Which year is it?", o: ["1660", "1649", "1688", "1707"], a: [0], e: "Parliament invited Charles II to return in 1660, an event known as the Restoration." },
  { i: 1259, base: 57, variant: "exception", c: 3, q: "Which of these is NOT true about the Restoration of 1660?", o: ["It brought Oliver Cromwell back to power", "It restored the monarchy", "Charles II returned to the throne", "It followed the period of the Commonwealth"], a: [0], e: "The Restoration brought back the monarchy under Charles II in 1660 — Oliver Cromwell had died in 1658 and was not restored to power." },

  // ---- base i:58 — the 1660s: Great Plague and Great Fire of London (choose two) ----
  { i: 1260, base: 58, variant: "rephrase", c: 3, q: "Which TWO disasters struck London in the 1660s? (Choose two answers)", o: ["The Great Plague", "The Great Fire", "The Black Death", "The Spanish Armada"], a: [0, 1], e: "The Great Plague came in 1665 and the Great Fire of London in 1666." },
  { i: 1261, base: 58, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? The Great Fire of London happened in 1666.", o: ["True", "False"], a: [0], e: "The Great Plague came in 1665 and the Great Fire of London in 1666." },
  { i: 1262, base: 58, variant: "scenario", c: 3, q: "A friend asks which TWO major disasters hit London within a year of each other in the 1660s. Which were they? (Choose two answers)", o: ["The Great Plague of 1665", "The Great Fire of 1666", "The Black Death", "The Spanish Armada"], a: [0, 1], e: "The Great Plague came in 1665 and the Great Fire of London in 1666." },
  { i: 1263, base: 58, variant: "exception", c: 3, q: "Which of these did NOT strike London in the 1660s?", o: ["The Black Death", "The Great Plague", "The Great Fire", "Widespread destruction requiring rebuilding, including of St Paul's"], a: [0], e: "The Great Plague (1665) and Great Fire (1666) struck London in the 1660s. The Black Death was a much earlier epidemic, in 1348." },

  // ---- base i:59 — 1688: the Glorious Revolution ----
  { i: 1264, base: 59, variant: "rephrase", c: 3, q: "The Glorious Revolution of 1688 brought which ruler to the throne?", o: ["William of Orange", "Charles II", "George I", "Oliver Cromwell"], a: [0], e: "William of Orange and his wife Mary, James II's daughter, took the throne with no fighting in England." },
  { i: 1265, base: 59, variant: "truefalse", c: 3, q: "Is this statement TRUE or FALSE? The Glorious Revolution of 1688 brought William of Orange to the throne.", o: ["True", "False"], a: [0], e: "William of Orange and his wife Mary, James II's daughter, took the throne with no fighting in England." },
  { i: 1266, base: 59, variant: "scenario", c: 3, q: "A friend asks who became king as a result of the Glorious Revolution of 1688. Who was it?", o: ["William of Orange", "Charles II", "George I", "James II, who kept his throne"], a: [0], e: "William of Orange and his wife Mary, James II's daughter, took the throne with no fighting in England." },
  { i: 1267, base: 59, variant: "exception", c: 3, q: "Which of these is NOT true about the Glorious Revolution of 1688?", o: ["It involved significant fighting across England", "William of Orange took the throne", "Mary, James II's daughter, became joint monarch", "It happened with little bloodshed in England"], a: [0], e: "The Glorious Revolution of 1688 saw William of Orange and Mary take the throne with no fighting in England — hence 'glorious' rather than bloody." },
];
