/* ============================================================
   QUESTION VARIANTS — Chapter 4b (Society: Wimbledon through
   'Capability' Brown's gardens, base i:112-124). See chapter1.js for
   format notes.
   ============================================================ */

export default [
  // ---- base i:112 — Wimbledon: held in London ----
  { i: 1588, base: 112, variant: "rephrase", c: 4, q: "Where is the Wimbledon tennis championship held?", o: ["London", "Manchester", "Edinburgh", "Birmingham"], a: [0], e: "The All England Lawn Tennis Championships at Wimbledon is the oldest tennis tournament in the world." },
  { i: 1589, base: 112, variant: "truefalse", c: 4, q: "Is this statement TRUE or FALSE? The Wimbledon tennis championship is held in London.", o: ["True", "False"], a: [0], e: "The All England Lawn Tennis Championships at Wimbledon is the oldest tennis tournament in the world." },
  { i: 1590, base: 112, variant: "scenario", c: 4, q: "A friend planning to attend the world's oldest tennis tournament asks which city to travel to. Which city is it?", o: ["London", "Manchester", "Edinburgh", "Birmingham"], a: [0], e: "The All England Lawn Tennis Championships at Wimbledon, in London, is the oldest tennis tournament in the world." },
  { i: 1591, base: 112, variant: "exception", c: 4, q: "Which of these is NOT true about the Wimbledon championship?", o: ["It is the newest tennis tournament in the world", "It is held in London", "It is also called the All England Lawn Tennis Championships", "It is the oldest tennis tournament in the world"], a: [0], e: "Wimbledon is the oldest tennis tournament in the world, not the newest." },

  // ---- base i:113 — the Grand National: run at Aintree ----
  { i: 1592, base: 113, variant: "rephrase", c: 4, q: "The Grand National horse race is held at which course?", o: ["Aintree", "Epsom", "Ascot", "Ayr"], a: [0], e: "The Grand National is run at Aintree near Liverpool; the Derby is at Epsom." },
  { i: 1593, base: 113, variant: "truefalse", c: 4, q: "Is this statement TRUE or FALSE? The Grand National is run at Aintree.", o: ["True", "False"], a: [0], e: "The Grand National is run at Aintree near Liverpool; the Derby is at Epsom." },
  { i: 1594, base: 113, variant: "scenario", c: 4, q: "A friend asks which racecourse near Liverpool hosts the Grand National. Which one is it?", o: ["Aintree", "Epsom", "Ascot", "Ayr"], a: [0], e: "The Grand National is run at Aintree near Liverpool; the Derby is at Epsom." },
  { i: 1595, base: 113, variant: "exception", c: 4, q: "Which of these is NOT correctly matched with its horse race?", o: ["The Grand National — Epsom", "The Grand National — Aintree", "The Derby — Epsom", "Royal Ascot — Ascot"], a: [0], e: "The Grand National is run at Aintree, not Epsom — Epsom is instead the home of the Derby." },

  // ---- base i:114 — the home of golf: St Andrews ----
  { i: 1596, base: 114, variant: "rephrase", c: 4, q: "Which Scottish town is known as the home of golf?", o: ["St Andrews", "Aberdeen", "Stirling", "Perth"], a: [0], e: "The modern game developed in Scotland, and St Andrews is its historic home." },
  { i: 1597, base: 114, variant: "truefalse", c: 4, q: "Is this statement TRUE or FALSE? St Andrews is known as the home of golf.", o: ["True", "False"], a: [0], e: "The modern game developed in Scotland, and St Andrews is its historic home." },
  { i: 1598, base: 114, variant: "scenario", c: 4, q: "A friend asks which Scottish town is historically regarded as the home of golf. Which town is it?", o: ["St Andrews", "Aberdeen", "Stirling", "Perth"], a: [0], e: "The modern game of golf developed in Scotland, and St Andrews is its historic home." },
  { i: 1599, base: 114, variant: "exception", c: 4, q: "Which of these is NOT true about golf's connection to Scotland?", o: ["The modern game developed in England", "The modern game developed in Scotland", "St Andrews is regarded as its historic home", "Golf is strongly associated with Scottish history"], a: [0], e: "The modern game of golf developed in Scotland, not England — St Andrews is its historic home." },

  // ---- base i:115 — Roger Bannister: the four-minute mile ----
  { i: 1600, base: 115, variant: "rephrase", c: 4, q: "Sir Roger Bannister was the first man to do what?", o: ["Run a mile in under four minutes", "Win five Olympic gold medals", "Sail solo around the world", "Win the Tour de France"], a: [0], e: "Bannister broke the four-minute mile in 1954." },
  { i: 1601, base: 115, variant: "truefalse", c: 4, q: "Is this statement TRUE or FALSE? Sir Roger Bannister was the first man to run a mile in under four minutes.", o: ["True", "False"], a: [0], e: "Bannister broke the four-minute mile in 1954." },
  { i: 1602, base: 115, variant: "scenario", c: 4, q: "A friend asks who first ran a mile in under four minutes, in 1954. Who was it?", o: ["Sir Roger Bannister", "Sir Steve Redgrave", "Bobby Moore", "Sir Jackie Stewart"], a: [0], e: "Bannister broke the four-minute mile in 1954." },
  { i: 1603, base: 115, variant: "exception", c: 4, q: "Which of these is NOT true about Sir Roger Bannister?", o: ["He won five Olympic gold medals in rowing", "He ran a mile in under four minutes", "His achievement was in 1954", "He is remembered as a pioneering athlete"], a: [0], e: "Roger Bannister is famous for the four-minute mile. Five Olympic rowing golds were won by a different athlete, Sir Steve Redgrave." },

  // ---- base i:116 — Steve Redgrave: rowing ----
  { i: 1604, base: 116, variant: "rephrase", c: 4, q: "Sir Steve Redgrave won five gold medals in which sport?", o: ["Rowing", "Cycling", "Athletics", "Sailing"], a: [0], e: "Redgrave won gold at five consecutive Olympic Games." },
  { i: 1605, base: 116, variant: "truefalse", c: 4, q: "Is this statement TRUE or FALSE? Sir Steve Redgrave won five Olympic gold medals in rowing.", o: ["True", "False"], a: [0], e: "Redgrave won gold at five consecutive Olympic Games." },
  { i: 1606, base: 116, variant: "scenario", c: 4, q: "A friend asks which sport Sir Steve Redgrave won five consecutive Olympic golds in. Which sport is it?", o: ["Rowing", "Cycling", "Athletics", "Sailing"], a: [0], e: "Redgrave won gold in rowing at five consecutive Olympic Games." },
  { i: 1607, base: 116, variant: "exception", c: 4, q: "Which of these is NOT true about Sir Steve Redgrave?", o: ["He won his gold medals in athletics", "He won gold medals in rowing", "He won at five consecutive Olympic Games", "He is one of Britain's most successful Olympians"], a: [0], e: "Steve Redgrave's five gold medals were won in rowing, not athletics." },

  // ---- base i:117 — Bobby Moore: 1966 World Cup captain ----
  { i: 1608, base: 117, variant: "rephrase", c: 4, q: "Who captained the England football team that won the 1966 World Cup?", o: ["Bobby Moore", "Bobby Charlton", "Ian Botham", "Jackie Stewart"], a: [0], e: "Bobby Moore lifted the World Cup after England beat West Germany at Wembley." },
  { i: 1609, base: 117, variant: "truefalse", c: 4, q: "Is this statement TRUE or FALSE? Bobby Moore captained England to victory in the 1966 World Cup.", o: ["True", "False"], a: [0], e: "Bobby Moore lifted the World Cup after England beat West Germany at Wembley." },
  { i: 1610, base: 117, variant: "scenario", c: 4, q: "A friend asks who lifted the World Cup as England's captain in 1966. Who was it?", o: ["Bobby Moore", "Bobby Charlton", "Ian Botham", "Bobby Robson"], a: [0], e: "Bobby Moore lifted the World Cup after England beat West Germany at Wembley in 1966." },
  { i: 1611, base: 117, variant: "exception", c: 4, q: "Which of these is NOT true about the 1966 World Cup?", o: ["England lost the final to West Germany", "Bobby Moore captained the England team", "The final was played at Wembley", "England won the tournament"], a: [0], e: "England beat West Germany in the 1966 World Cup final at Wembley — they won, they did not lose." },

  // ---- base i:118 — London has hosted the Olympics three times ----
  { i: 1612, base: 118, variant: "rephrase", c: 4, q: "How many times has London hosted the Olympic Games?", o: ["Three times", "Once", "Twice", "Four times"], a: [0], e: "London hosted the Games in 1908, 1948 and 2012." },
  { i: 1613, base: 118, variant: "truefalse", c: 4, q: "Is this statement TRUE or FALSE? London has hosted the Olympic Games three times.", o: ["True", "False"], a: [0], e: "London hosted the Games in 1908, 1948 and 2012." },
  { i: 1614, base: 118, variant: "scenario", c: 4, q: "A friend asks how many times London has hosted the Olympics, most recently in 2012. How many times is that in total?", o: ["Three times", "Once", "Twice", "Four times"], a: [0], e: "London hosted the Olympic Games in 1908, 1948 and 2012 — three times in total." },
  { i: 1615, base: 118, variant: "exception", c: 4, q: "Which of these years did London NOT host the Olympic Games?", o: ["1984", "1908", "1948", "2012"], a: [0], e: "London hosted the Olympics in 1908, 1948 and 2012 — not in 1984, when Los Angeles hosted the Games." },

  // ---- base i:119 — Gustav Holst composed The Planets ----
  { i: 1616, base: 119, variant: "rephrase", c: 4, q: "Who composed The Planets?", o: ["Gustav Holst", "Edward Elgar", "Benjamin Britten", "Henry Purcell"], a: [0], e: "Gustav Holst's suite The Planets was first performed in 1918." },
  { i: 1617, base: 119, variant: "truefalse", c: 4, q: "Is this statement TRUE or FALSE? Gustav Holst composed the orchestral suite The Planets.", o: ["True", "False"], a: [0], e: "Gustav Holst's suite The Planets was first performed in 1918." },
  { i: 1618, base: 119, variant: "scenario", c: 4, q: "A friend asks who composed the orchestral suite The Planets, first performed in 1918. Who was it?", o: ["Gustav Holst", "Edward Elgar", "Benjamin Britten", "Ralph Vaughan Williams"], a: [0], e: "Gustav Holst's suite The Planets was first performed in 1918." },
  { i: 1619, base: 119, variant: "exception", c: 4, q: "Which of these composers did NOT write The Planets?", o: ["Edward Elgar", "Gustav Holst", "The composer of a piece first performed in 1918", "The composer of an orchestral suite"], a: [0], e: "The Planets was composed by Gustav Holst, first performed in 1918 — not by Edward Elgar, a different British composer." },

  // ---- base i:120 — the BBC Proms: Royal Albert Hall ----
  { i: 1620, base: 120, variant: "rephrase", c: 4, q: "Where are the BBC Proms concerts held?", o: ["The Royal Albert Hall", "The Globe Theatre", "The National Gallery", "Wembley Stadium"], a: [0], e: "The Proms is an eight-week summer season of classical music, ending with the Last Night of the Proms." },
  { i: 1621, base: 120, variant: "truefalse", c: 4, q: "Is this statement TRUE or FALSE? The BBC Proms concerts are held at the Royal Albert Hall.", o: ["True", "False"], a: [0], e: "The Proms is an eight-week summer season of classical music, ending with the Last Night of the Proms." },
  { i: 1622, base: 120, variant: "scenario", c: 4, q: "A friend asks where the eight-week summer season of classical music known as the Proms takes place. Where is it?", o: ["The Royal Albert Hall", "The Globe Theatre", "The National Gallery", "The Royal Opera House"], a: [0], e: "The BBC Proms are held at the Royal Albert Hall, an eight-week summer season ending with the Last Night of the Proms." },
  { i: 1623, base: 120, variant: "exception", c: 4, q: "Which of these is NOT true about the BBC Proms?", o: ["They are a season of football matches", "They are held at the Royal Albert Hall", "They last around eight weeks", "They end with the Last Night of the Proms"], a: [0], e: "The Proms are a season of classical music concerts, not football matches, held at the Royal Albert Hall." },

  // ---- base i:121 — John Constable painted The Hay Wain ----
  { i: 1624, base: 121, variant: "rephrase", c: 4, q: "Which artist painted The Hay Wain?", o: ["John Constable", "J M W Turner", "David Hockney", "Thomas Gainsborough"], a: [0], e: "Constable was famous for his landscapes of the English countryside." },
  { i: 1625, base: 121, variant: "truefalse", c: 4, q: "Is this statement TRUE or FALSE? John Constable painted The Hay Wain.", o: ["True", "False"], a: [0], e: "Constable was famous for his landscapes of the English countryside." },
  { i: 1626, base: 121, variant: "scenario", c: 4, q: "A friend asks who painted the famous English countryside scene The Hay Wain. Who was it?", o: ["John Constable", "J M W Turner", "David Hockney", "Thomas Gainsborough"], a: [0], e: "Constable was famous for his landscapes of the English countryside, including The Hay Wain." },
  { i: 1627, base: 121, variant: "exception", c: 4, q: "Which of these is NOT true about John Constable?", o: ["The Turner Prize is named after him", "He painted The Hay Wain", "He was famous for English countryside landscapes", "He is a well-known British painter"], a: [0], e: "The Turner Prize is named after J M W Turner, a different British painter — not John Constable." },

  // ---- base i:122 — the Turner Prize at Tate Britain ----
  { i: 1628, base: 122, variant: "rephrase", c: 4, q: "Which prize is awarded for contemporary art at Tate Britain?", o: ["The Turner Prize", "The Booker Prize", "The Mercury Prize", "The Laurence Olivier Award"], a: [0], e: "The Turner Prize, named after J M W Turner, celebrates contemporary British art." },
  { i: 1629, base: 122, variant: "truefalse", c: 4, q: "Is this statement TRUE or FALSE? The Turner Prize is awarded for contemporary art at Tate Britain.", o: ["True", "False"], a: [0], e: "The Turner Prize, named after J M W Turner, celebrates contemporary British art." },
  { i: 1630, base: 122, variant: "scenario", c: 4, q: "A friend asks which prize, named after a famous British painter, celebrates contemporary art at Tate Britain. What is it called?", o: ["The Turner Prize", "The Booker Prize", "The Mercury Prize", "The BAFTA"], a: [0], e: "The Turner Prize, named after J M W Turner, celebrates contemporary British art at Tate Britain." },
  { i: 1631, base: 122, variant: "exception", c: 4, q: "Which of these is NOT true about the Turner Prize?", o: ["It is awarded for the best novel of the year", "It is named after J M W Turner", "It celebrates contemporary British art", "It is associated with Tate Britain"], a: [0], e: "The Turner Prize celebrates contemporary art, not novels — the prize for the best novel is the Booker Prize." },

  // ---- base i:123 — Christopher Wren designed St Paul's Cathedral ----
  { i: 1632, base: 123, variant: "rephrase", c: 4, q: "Who designed St Paul's Cathedral?", o: ["Sir Christopher Wren", "Inigo Jones", "Robert Adam", "Sir Norman Foster"], a: [0], e: "Wren rebuilt St Paul's after the Great Fire of London in 1666." },
  { i: 1633, base: 123, variant: "truefalse", c: 4, q: "Is this statement TRUE or FALSE? Sir Christopher Wren designed St Paul's Cathedral.", o: ["True", "False"], a: [0], e: "Wren rebuilt St Paul's after the Great Fire of London in 1666." },
  { i: 1634, base: 123, variant: "scenario", c: 4, q: "A friend asks who designed the current St Paul's Cathedral, after the old one burned down in 1666. Who was it?", o: ["Sir Christopher Wren", "Inigo Jones", "Robert Adam", "Sir Norman Foster"], a: [0], e: "Wren designed and rebuilt St Paul's after the Great Fire of London in 1666." },
  { i: 1635, base: 123, variant: "exception", c: 4, q: "Which of these is NOT true about Sir Christopher Wren?", o: ["He designed 'Capability' Brown's landscape gardens", "He designed St Paul's Cathedral", "His work followed the Great Fire of 1666", "He is a famous English architect"], a: [0], e: "Christopher Wren designed St Paul's Cathedral. Landscape gardens were the specialty of a different figure, 'Capability' Brown." },

  // ---- base i:124 — 'Capability' Brown: landscape gardens and parks ----
  { i: 1636, base: 124, variant: "rephrase", c: 4, q: "'Capability' Brown is famous for designing what?", o: ["Landscape gardens and parks", "Cathedrals", "Steam engines", "Furniture"], a: [0], e: "Lancelot 'Capability' Brown designed sweeping natural-looking gardens around country houses." },
  { i: 1637, base: 124, variant: "truefalse", c: 4, q: "Is this statement TRUE or FALSE? 'Capability' Brown is famous for designing landscape gardens and parks.", o: ["True", "False"], a: [0], e: "Lancelot 'Capability' Brown designed sweeping natural-looking gardens around country houses." },
  { i: 1638, base: 124, variant: "scenario", c: 4, q: "A friend asks who designed the sweeping natural-looking gardens seen around many English country houses. Who was it?", o: ["'Capability' Brown", "Sir Christopher Wren", "Inigo Jones", "Robert Adam"], a: [0], e: "Lancelot 'Capability' Brown designed sweeping natural-looking gardens around country houses." },
  { i: 1639, base: 124, variant: "exception", c: 4, q: "Which of these is NOT true about 'Capability' Brown?", o: ["He designed St Paul's Cathedral", "He designed landscape gardens", "His full name was Lancelot Brown", "His gardens were designed around country houses"], a: [0], e: "'Capability' Brown designed landscape gardens, not cathedrals — St Paul's Cathedral was designed by Sir Christopher Wren." },
];
