/* ============================================================
   QUESTION VARIANTS — Chapter 4c (Society: the Booker Prize through
   Welsh and Gaelic, base i:125-138 — the last of BASE_Q's chapter 4
   questions). See chapter1.js for format notes.
   ============================================================ */

export default [
  // ---- base i:125 — the Booker Prize ----
  { i: 1640, base: 125, variant: "rephrase", c: 4, q: "Which prize is awarded each year for the best novel by a writer from the Commonwealth or Ireland?", o: ["The Booker Prize", "The Turner Prize", "The Mercury Prize", "The BAFTA"], a: [0], e: "The Man Booker Prize for Fiction has been awarded since 1968." },
  { i: 1641, base: 125, variant: "truefalse", c: 4, q: "Is this statement TRUE or FALSE? The Booker Prize is awarded for the best novel by a Commonwealth or Irish writer.", o: ["True", "False"], a: [0], e: "The Man Booker Prize for Fiction has been awarded since 1968." },
  { i: 1642, base: 125, variant: "scenario", c: 4, q: "A friend asks which literary prize, awarded since 1968, honours the best novel each year. What is it called?", o: ["The Booker Prize", "The Turner Prize", "The Mercury Prize", "The Costa Book Award"], a: [0], e: "The Man Booker Prize for Fiction has been awarded since 1968." },
  { i: 1643, base: 125, variant: "exception", c: 4, q: "Which of these is NOT true about the Booker Prize?", o: ["It is awarded for the best contemporary art", "It is awarded for the best novel", "It has been awarded since 1968", "It is open to writers from the Commonwealth and Ireland"], a: [0], e: "The Booker Prize honours the best novel of the year, not contemporary art — the art prize is the Turner Prize." },

  // ---- base i:126 — Jane Austen wrote Pride and Prejudice ----
  { i: 1644, base: 126, variant: "rephrase", c: 4, q: "Who wrote Pride and Prejudice?", o: ["Jane Austen", "Charlotte Bronte", "George Eliot", "Mary Shelley"], a: [0], e: "Jane Austen's novels explore marriage and social class in early 19th-century England." },
  { i: 1645, base: 126, variant: "truefalse", c: 4, q: "Is this statement TRUE or FALSE? Jane Austen wrote Pride and Prejudice.", o: ["True", "False"], a: [0], e: "Jane Austen's novels explore marriage and social class in early 19th-century England." },
  { i: 1646, base: 126, variant: "scenario", c: 4, q: "A friend asks who wrote the novel Pride and Prejudice, exploring marriage and class in early 19th-century England. Who was it?", o: ["Jane Austen", "Charlotte Bronte", "George Eliot", "Mary Shelley"], a: [0], e: "Jane Austen's novels, including Pride and Prejudice, explore marriage and social class in early 19th-century England." },
  { i: 1647, base: 126, variant: "exception", c: 4, q: "Which of these is NOT true about Jane Austen?", o: ["She wrote Frankenstein", "She wrote Pride and Prejudice", "Her novels explore marriage and social class", "She wrote in early 19th-century England"], a: [0], e: "Jane Austen wrote Pride and Prejudice. Frankenstein was written by a different novelist, Mary Shelley." },

  // ---- base i:127 — Poets' Corner: Westminster Abbey ----
  { i: 1648, base: 127, variant: "rephrase", c: 4, q: "Where is Poets' Corner?", o: ["Westminster Abbey", "St Paul's Cathedral", "The Tower of London", "Canterbury Cathedral"], a: [0], e: "Many famous poets are buried or commemorated in Poets' Corner in Westminster Abbey." },
  { i: 1649, base: 127, variant: "truefalse", c: 4, q: "Is this statement TRUE or FALSE? Poets' Corner is located in Westminster Abbey.", o: ["True", "False"], a: [0], e: "Many famous poets are buried or commemorated in Poets' Corner in Westminster Abbey." },
  { i: 1650, base: 127, variant: "scenario", c: 4, q: "A friend asks where in London many famous poets are buried or commemorated. Where is it?", o: ["Westminster Abbey, in Poets' Corner", "St Paul's Cathedral", "The Tower of London", "The British Museum"], a: [0], e: "Many famous poets are buried or commemorated in Poets' Corner in Westminster Abbey." },
  { i: 1651, base: 127, variant: "exception", c: 4, q: "Which of these is NOT true about Poets' Corner?", o: ["It is located in St Paul's Cathedral", "It is located in Westminster Abbey", "Famous poets are buried or commemorated there", "It is a well-known literary landmark"], a: [0], e: "Poets' Corner is in Westminster Abbey, not St Paul's Cathedral." },

  // ---- base i:128 — Tim Berners-Lee invented the World Wide Web ----
  { i: 1652, base: 128, variant: "rephrase", c: 4, q: "Who invented the World Wide Web?", o: ["Sir Tim Berners-Lee", "Alan Turing", "John Logie Baird", "Sir Clive Sinclair"], a: [0], e: "Berners-Lee, a British scientist, invented the World Wide Web in 1989-1990." },
  { i: 1653, base: 128, variant: "truefalse", c: 4, q: "Is this statement TRUE or FALSE? Sir Tim Berners-Lee invented the World Wide Web.", o: ["True", "False"], a: [0], e: "Berners-Lee, a British scientist, invented the World Wide Web in 1989-1990." },
  { i: 1654, base: 128, variant: "scenario", c: 4, q: "A friend asks which British scientist invented the World Wide Web around 1989-1990. Who was it?", o: ["Sir Tim Berners-Lee", "Alan Turing", "John Logie Baird", "Sir Clive Sinclair"], a: [0], e: "Berners-Lee, a British scientist, invented the World Wide Web in 1989-1990." },
  { i: 1655, base: 128, variant: "exception", c: 4, q: "Which of these is NOT true about Sir Tim Berners-Lee?", o: ["He invented television", "He invented the World Wide Web", "He made his invention around 1989-1990", "He is a British scientist"], a: [0], e: "Tim Berners-Lee invented the World Wide Web. Television was invented by a different British pioneer, John Logie Baird." },

  // ---- base i:129 — John Logie Baird: television ----
  { i: 1656, base: 129, variant: "rephrase", c: 4, q: "John Logie Baird is known for pioneering what?", o: ["Television", "The telephone", "Radar", "The hovercraft"], a: [0], e: "Baird made the first television transmission in 1926 and the first transatlantic TV transmission in 1928." },
  { i: 1657, base: 129, variant: "truefalse", c: 4, q: "Is this statement TRUE or FALSE? John Logie Baird is known for pioneering television.", o: ["True", "False"], a: [0], e: "Baird made the first television transmission in 1926 and the first transatlantic TV transmission in 1928." },
  { i: 1658, base: 129, variant: "scenario", c: 4, q: "A friend asks who made the first television transmission in 1926. Who was it?", o: ["John Logie Baird", "Sir Tim Berners-Lee", "Alan Turing", "Sir Frank Whittle"], a: [0], e: "Baird made the first television transmission in 1926 and the first transatlantic TV transmission in 1928." },
  { i: 1659, base: 129, variant: "exception", c: 4, q: "Which of these is NOT true about John Logie Baird?", o: ["He invented the World Wide Web", "He pioneered television", "He made the first TV transmission in 1926", "He achieved the first transatlantic TV transmission in 1928"], a: [0], e: "John Logie Baird pioneered television. The World Wide Web was invented much later by Sir Tim Berners-Lee." },

  // ---- base i:130 — Dolly the sheep: cloned from an adult cell ----
  { i: 1660, base: 130, variant: "rephrase", c: 4, q: "Dolly the sheep, cloned in 1996, was the first mammal cloned from what?", o: ["An adult cell", "An embryo", "A plant cell", "A frozen egg"], a: [0], e: "Sir Ian Wilmut and Keith Campbell cloned Dolly at the Roslin Institute in Edinburgh." },
  { i: 1661, base: 130, variant: "truefalse", c: 4, q: "Is this statement TRUE or FALSE? Dolly the sheep was the first mammal cloned from an adult cell.", o: ["True", "False"], a: [0], e: "Sir Ian Wilmut and Keith Campbell cloned Dolly at the Roslin Institute in Edinburgh." },
  { i: 1662, base: 130, variant: "scenario", c: 4, q: "A friend asks what made Dolly the sheep, cloned in 1996 in Edinburgh, scientifically significant. What was it?", o: ["She was the first mammal cloned from an adult cell", "She was the first sheep ever bred in captivity", "She was the first genetically modified animal", "She was the first animal to survive being frozen"], a: [0], e: "Dolly, cloned by Sir Ian Wilmut and Keith Campbell at the Roslin Institute, was the first mammal cloned from an adult cell." },
  { i: 1663, base: 130, variant: "exception", c: 4, q: "Which of these is NOT true about Dolly the sheep?", o: ["She was cloned from a plant cell", "She was cloned in 1996", "She was cloned from an adult cell", "She was cloned at the Roslin Institute in Edinburgh"], a: [0], e: "Dolly was cloned from an adult animal cell, not a plant cell — she was a sheep, produced at the Roslin Institute in 1996." },

  // ---- base i:131 — the Giant's Causeway and Finn McCool ----
  { i: 1664, base: 131, variant: "rephrase", c: 4, q: "Which structure in Northern Ireland is linked to the legend of the giant Finn McCool?", o: ["The Giant's Causeway", "The Eden Project", "Snowdonia", "Loch Lomond"], a: [0], e: "The Giant's Causeway is a natural rock formation on the north-east coast of Northern Ireland." },
  { i: 1665, base: 131, variant: "truefalse", c: 4, q: "Is this statement TRUE or FALSE? The Giant's Causeway is linked to the legend of Finn McCool.", o: ["True", "False"], a: [0], e: "The Giant's Causeway is a natural rock formation on the north-east coast of Northern Ireland." },
  { i: 1666, base: 131, variant: "scenario", c: 4, q: "A friend visiting the north-east coast of Northern Ireland asks about a rock formation linked to a giant of legend. What is it called?", o: ["The Giant's Causeway", "The Eden Project", "Snowdonia", "Loch Lomond"], a: [0], e: "The Giant's Causeway is a natural rock formation on the north-east coast of Northern Ireland, linked to the legend of Finn McCool." },
  { i: 1667, base: 131, variant: "exception", c: 4, q: "Which of these is NOT true about the Giant's Causeway?", o: ["It is located in Scotland", "It is a natural rock formation", "It is on the north-east coast of Northern Ireland", "It is linked to the legend of Finn McCool"], a: [0], e: "The Giant's Causeway is in Northern Ireland, not Scotland." },

  // ---- base i:132 — Ben Nevis: the highest mountain in the UK ----
  { i: 1668, base: 132, variant: "rephrase", c: 4, q: "What is the highest mountain in the UK?", o: ["Ben Nevis", "Snowdon", "Scafell Pike", "Slieve Donard"], a: [0], e: "Ben Nevis in Scotland is the UK's highest mountain; Snowdon is the highest in Wales." },
  { i: 1669, base: 132, variant: "truefalse", c: 4, q: "Is this statement TRUE or FALSE? Ben Nevis is the highest mountain in the UK.", o: ["True", "False"], a: [0], e: "Ben Nevis in Scotland is the UK's highest mountain; Snowdon is the highest in Wales." },
  { i: 1670, base: 132, variant: "scenario", c: 4, q: "A friend planning to climb the UK's highest peak asks which mountain that is. Which one is it?", o: ["Ben Nevis", "Snowdon", "Scafell Pike", "Slieve Donard"], a: [0], e: "Ben Nevis in Scotland is the UK's highest mountain; Snowdon is the highest in Wales." },
  { i: 1671, base: 132, variant: "exception", c: 4, q: "Which of these mountains is NOT the highest point of its UK country?", o: ["Scafell Pike is the highest mountain in Wales", "Ben Nevis is the highest mountain in the UK overall", "Snowdon is the highest mountain in Wales", "Scafell Pike is the highest mountain in England"], a: [0], e: "Scafell Pike is the highest mountain in England, not Wales — Snowdon holds that title in Wales." },

  // ---- base i:133 — the Crown Jewels: kept at the Tower of London ----
  { i: 1672, base: 133, variant: "rephrase", c: 4, q: "Where are the Crown Jewels kept?", o: ["The Tower of London", "Buckingham Palace", "Windsor Castle", "Edinburgh Castle"], a: [0], e: "The Tower of London is guarded by Yeoman Warders, known as Beefeaters." },
  { i: 1673, base: 133, variant: "truefalse", c: 4, q: "Is this statement TRUE or FALSE? The Crown Jewels are kept at the Tower of London.", o: ["True", "False"], a: [0], e: "The Tower of London is guarded by Yeoman Warders, known as Beefeaters." },
  { i: 1674, base: 133, variant: "scenario", c: 4, q: "A friend visiting London asks where they can see the Crown Jewels, guarded by the Beefeaters. Where should they go?", o: ["The Tower of London", "Buckingham Palace", "Windsor Castle", "Westminster Abbey"], a: [0], e: "The Crown Jewels are kept at the Tower of London, guarded by Yeoman Warders, known as Beefeaters." },
  { i: 1675, base: 133, variant: "exception", c: 4, q: "Which of these is NOT true about the Crown Jewels?", o: ["They are kept at Buckingham Palace", "They are kept at the Tower of London", "The Tower of London is guarded by Yeoman Warders", "Yeoman Warders are also known as Beefeaters"], a: [0], e: "The Crown Jewels are kept at the Tower of London, not Buckingham Palace." },

  // ---- base i:134 — the UK's currency: the pound sterling ----
  { i: 1676, base: 134, variant: "rephrase", c: 4, q: "What is the currency of the UK?", o: ["The pound sterling", "The euro", "The dollar", "The guinea"], a: [0], e: "The pound sterling (£) is divided into 100 pence." },
  { i: 1677, base: 134, variant: "truefalse", c: 4, q: "Is this statement TRUE or FALSE? The currency of the UK is the pound sterling.", o: ["True", "False"], a: [0], e: "The pound sterling (£) is divided into 100 pence." },
  { i: 1678, base: 134, variant: "scenario", c: 4, q: "A friend visiting from abroad asks which currency they will need in the UK. Which one is it?", o: ["The pound sterling", "The euro", "The dollar", "The guinea"], a: [0], e: "The pound sterling (£) is the UK's currency, divided into 100 pence." },
  { i: 1679, base: 134, variant: "exception", c: 4, q: "Which of these is NOT true about the pound sterling?", o: ["It is divided into 1,000 pence", "It is the UK's currency", "It is divided into 100 pence", "Its symbol is £"], a: [0], e: "The pound sterling is divided into 100 pence, not 1,000." },

  // ---- base i:135 — the established Church in England ----
  { i: 1680, base: 135, variant: "rephrase", c: 4, q: "Which is the established Church in England?", o: ["The Church of England", "The Church of Scotland", "The Roman Catholic Church", "The Methodist Church"], a: [0], e: "The Church of England is Anglican; the monarch is its head and the Archbishop of Canterbury its spiritual leader." },
  { i: 1681, base: 135, variant: "truefalse", c: 4, q: "Is this statement TRUE or FALSE? The Church of England is the established Church in England.", o: ["True", "False"], a: [0], e: "The Church of England is Anglican; the monarch is its head and the Archbishop of Canterbury its spiritual leader." },
  { i: 1682, base: 135, variant: "scenario", c: 4, q: "A friend asks which church is the established Church in England, headed by the monarch. Which church is it?", o: ["The Church of England", "The Church of Scotland", "The Roman Catholic Church", "The Methodist Church"], a: [0], e: "The Church of England is Anglican; the monarch is its head and the Archbishop of Canterbury its spiritual leader." },
  { i: 1683, base: 135, variant: "exception", c: 4, q: "Which of these is NOT true about the Church of England?", o: ["It is led by a Moderator", "It is the established Church in England", "The monarch is its head", "The Archbishop of Canterbury is its spiritual leader"], a: [0], e: "The Church of England is headed by the monarch, with the Archbishop of Canterbury as spiritual leader — it is the Church of Scotland that is led by a Moderator." },

  // ---- base i:136 — the national church of Scotland ----
  { i: 1684, base: 136, variant: "rephrase", c: 4, q: "What is the national church of Scotland?", o: ["The Church of Scotland, a Presbyterian church", "The Church of England", "The Roman Catholic Church", "There is no national church"], a: [0], e: "The Church of Scotland is governed by its General Assembly, chaired by the Moderator." },
  { i: 1685, base: 136, variant: "truefalse", c: 4, q: "Is this statement TRUE or FALSE? The Church of Scotland, a Presbyterian church, is Scotland's national church.", o: ["True", "False"], a: [0], e: "The Church of Scotland is governed by its General Assembly, chaired by the Moderator." },
  { i: 1686, base: 136, variant: "scenario", c: 4, q: "A friend asks which church, governed by a General Assembly chaired by a Moderator, is Scotland's national church. Which is it?", o: ["The Church of Scotland", "The Church of England", "The Roman Catholic Church", "The Free Church of Scotland"], a: [0], e: "The Church of Scotland, a Presbyterian church, is governed by its General Assembly, chaired by the Moderator." },
  { i: 1687, base: 136, variant: "exception", c: 4, q: "Which of these is NOT true about the Church of Scotland?", o: ["It is headed by the monarch as its spiritual leader", "It is Presbyterian", "It is governed by a General Assembly", "It is chaired by a Moderator"], a: [0], e: "The Church of Scotland is governed by its own General Assembly and Moderator, not headed by the monarch — that arrangement applies to the Church of England instead." },

  // ---- base i:137 — the legal age to buy alcohol in a pub: 18 ----
  { i: 1688, base: 137, variant: "rephrase", c: 4, q: "At what age can you legally buy alcohol in a pub in the UK?", o: ["18", "16", "21", "17"], a: [0], e: "You must be 18 to buy alcohol. Under-18s may enter a pub with an adult in some circumstances but generally cannot drink alcohol." },
  { i: 1689, base: 137, variant: "truefalse", c: 4, q: "Is this statement TRUE or FALSE? You must be 18 to legally buy alcohol in a UK pub.", o: ["True", "False"], a: [0], e: "You must be 18 to buy alcohol. Under-18s may enter a pub with an adult in some circumstances but generally cannot drink alcohol." },
  { i: 1690, base: 137, variant: "scenario", c: 4, q: "A friend turning 17 asks if they can now legally buy a drink in a pub. What do you tell them?", o: ["No — they must wait until they turn 18", "Yes — 17 is the legal age", "Yes, but only with a parent present", "No — the legal age is 21"], a: [0], e: "You must be 18 to buy alcohol in the UK, so a 17-year-old must wait another year." },
  { i: 1691, base: 137, variant: "exception", c: 4, q: "Which of these is NOT the correct legal age for buying alcohol in a UK pub?", o: ["21", "18", "The age at which you can also vote", "The age at which you can also buy a National Lottery ticket"], a: [0], e: "The legal age to buy alcohol in the UK is 18, not 21 — the same age as voting and buying a National Lottery ticket." },

  // ---- base i:138 — two languages besides English: Welsh and Gaelic (choose two) ----
  { i: 1692, base: 138, variant: "rephrase", c: 4, q: "Which TWO are languages spoken in parts of the UK besides English? (Choose two answers)", o: ["Welsh", "Gaelic", "Latin", "Cornish Norse"], a: [0, 1], e: "Welsh is widely spoken in Wales; Gaelic is spoken in parts of Scotland and Northern Ireland." },
  { i: 1693, base: 138, variant: "truefalse", c: 4, q: "Is this statement TRUE or FALSE? Welsh is widely spoken as a language in parts of the UK.", o: ["True", "False"], a: [0], e: "Welsh is widely spoken in Wales; Gaelic is spoken in parts of Scotland and Northern Ireland." },
  { i: 1694, base: 138, variant: "scenario", c: 4, q: "A friend asks which TWO languages, besides English, are spoken in parts of the UK today. Which are they? (Choose two answers)", o: ["Welsh", "Gaelic", "Latin", "Old Norse"], a: [0, 1], e: "Welsh is widely spoken in Wales; Gaelic is spoken in parts of Scotland and Northern Ireland." },
  { i: 1695, base: 138, variant: "exception", c: 4, q: "Which of these is NOT a language still widely spoken in parts of the UK today?", o: ["Latin", "Welsh", "Gaelic", "English"], a: [0], e: "Welsh, Gaelic and English are all spoken in parts of the UK today. Latin is not a living community language, though it survives in some formal and academic use." },
];
