/* ============================================================
   QUESTION VARIANTS — Chapter 4d (Society: Welsh cakes and haggis
   through bank holidays, base i:237-246 — the first part of
   EXTRA_Q's chapter 4 questions). See chapter1.js for format notes.
   ============================================================ */

export default [
  // ---- base i:237 — traditional foods: Welsh cakes + haggis (choose two) ----
  { i: 1696, base: 237, variant: "rephrase", c: 4, q: "Which TWO are traditional foods associated with Wales and Scotland? (Choose two answers)", o: ["Welsh cakes", "Haggis", "Ulster fry", "Cornish pasty"], a: [0, 1], e: "Welsh cakes come from Wales and haggis from Scotland; the Ulster fry is from Northern Ireland." },
  { i: 1697, base: 237, variant: "truefalse", c: 4, q: "Is this statement TRUE or FALSE? Haggis is a traditional Scottish food.", o: ["True", "False"], a: [0], e: "Welsh cakes come from Wales and haggis from Scotland; the Ulster fry is from Northern Ireland." },
  { i: 1698, base: 237, variant: "scenario", c: 4, q: "A friend visiting both Wales and Scotland asks which traditional foods to try in each. Which TWO are correctly matched? (Choose two answers)", o: ["Welsh cakes in Wales", "Haggis in Scotland", "Ulster fry in Wales", "Cornish pasty in Scotland"], a: [0, 1], e: "Welsh cakes come from Wales and haggis from Scotland; the Ulster fry is from Northern Ireland, and the Cornish pasty from Cornwall in England." },
  { i: 1699, base: 237, variant: "exception", c: 4, q: "Which of these is NOT correctly matched with the part of the UK it traditionally comes from?", o: ["Ulster fry — Wales", "Welsh cakes — Wales", "Haggis — Scotland", "Ulster fry — Northern Ireland"], a: [0], e: "The Ulster fry traditionally comes from Northern Ireland, not Wales — Welsh cakes are the traditional Welsh food." },

  // ---- base i:238 — the UK flag: the Union Flag or Union Jack ----
  { i: 1700, base: 238, variant: "rephrase", c: 4, q: "What is the flag of the United Kingdom commonly called?", o: ["The Union Flag or Union Jack", "The Royal Standard", "The Red Ensign", "The Saltire"], a: [0], e: "It combines the crosses of St George, St Andrew and St Patrick." },
  { i: 1701, base: 238, variant: "truefalse", c: 4, q: "Is this statement TRUE or FALSE? The flag of the United Kingdom is commonly called the Union Flag or Union Jack.", o: ["True", "False"], a: [0], e: "It combines the crosses of St George, St Andrew and St Patrick." },
  { i: 1702, base: 238, variant: "scenario", c: 4, q: "A friend asks what the UK's national flag, combining the crosses of St George, St Andrew and St Patrick, is called. What is it?", o: ["The Union Flag or Union Jack", "The Royal Standard", "The Red Ensign", "The Saltire"], a: [0], e: "The Union Flag, or Union Jack, combines the crosses of St George, St Andrew and St Patrick." },
  { i: 1703, base: 238, variant: "exception", c: 4, q: "Which of these is NOT another name for the UK's national flag?", o: ["The Saltire", "The Union Flag", "The Union Jack", "A flag combining three saints' crosses"], a: [0], e: "The Union Flag is also called the Union Jack. The Saltire refers specifically to St Andrew's flag, representing Scotland alone." },

  // ---- base i:239 — Christmas Day: 25 December ----
  { i: 1704, base: 239, variant: "rephrase", c: 4, q: "On which date is Christmas Day celebrated?", o: ["25 December", "24 December", "26 December", "1 January"], a: [0], e: "Boxing Day, 26 December, is also a public holiday." },
  { i: 1705, base: 239, variant: "truefalse", c: 4, q: "Is this statement TRUE or FALSE? Christmas Day is celebrated on 25 December.", o: ["True", "False"], a: [0], e: "Boxing Day, 26 December, is also a public holiday." },
  { i: 1706, base: 239, variant: "scenario", c: 4, q: "A friend new to the UK asks on which date Christmas Day falls, with Boxing Day the day after. Which date is it?", o: ["25 December", "24 December", "26 December", "1 January"], a: [0], e: "Christmas Day falls on 25 December; Boxing Day, 26 December, is also a public holiday." },
  { i: 1707, base: 239, variant: "exception", c: 4, q: "Which of these is NOT true about Christmas Day and Boxing Day?", o: ["Boxing Day comes before Christmas Day", "Christmas Day is 25 December", "Boxing Day is 26 December", "Boxing Day is also a public holiday"], a: [0], e: "Boxing Day, 26 December, comes the day after Christmas Day, 25 December — not before it." },

  // ---- base i:240 — Diwali: celebrated by Hindus and Sikhs ----
  { i: 1708, base: 240, variant: "rephrase", c: 4, q: "Which festival of light is celebrated by Hindus and Sikhs in the UK?", o: ["Diwali", "Eid al-Fitr", "Hanukkah", "Vaisakhi"], a: [0], e: "Diwali normally falls in October or November and lasts for five days." },
  { i: 1709, base: 240, variant: "truefalse", c: 4, q: "Is this statement TRUE or FALSE? Diwali is a festival of light celebrated by Hindus and Sikhs.", o: ["True", "False"], a: [0], e: "Diwali normally falls in October or November and lasts for five days." },
  { i: 1710, base: 240, variant: "scenario", c: 4, q: "A friend asks which five-day festival of light, usually in October or November, is celebrated by Hindus and Sikhs. What is it called?", o: ["Diwali", "Eid al-Fitr", "Hanukkah", "Vaisakhi"], a: [0], e: "Diwali normally falls in October or November and lasts for five days." },
  { i: 1711, base: 240, variant: "exception", c: 4, q: "Which of these is NOT true about Diwali?", o: ["It is a Jewish festival", "It is celebrated by Hindus and Sikhs", "It is a festival of light", "It usually falls in October or November"], a: [0], e: "Diwali is a Hindu and Sikh festival of light — Hanukkah is the Jewish festival of light instead." },

  // ---- base i:241 — Eid al-Fitr: end of Ramadan ----
  { i: 1712, base: 241, variant: "rephrase", c: 4, q: "What is Eid al-Fitr?", o: ["A Muslim festival marking the end of Ramadan", "A Hindu new year festival", "A Sikh harvest festival", "A Jewish festival of light"], a: [0], e: "Muslims thank God for giving them the strength to complete the month of fasting." },
  { i: 1713, base: 241, variant: "truefalse", c: 4, q: "Is this statement TRUE or FALSE? Eid al-Fitr is a Muslim festival marking the end of Ramadan.", o: ["True", "False"], a: [0], e: "Muslims thank God for giving them the strength to complete the month of fasting." },
  { i: 1714, base: 241, variant: "scenario", c: 4, q: "A friend asks what Eid al-Fitr, celebrated at the end of the month of fasting, marks. What is it?", o: ["The end of Ramadan", "The Hindu new year", "A Sikh harvest festival", "A Jewish festival of light"], a: [0], e: "Eid al-Fitr is a Muslim festival marking the end of Ramadan, when Muslims thank God for the strength to complete the month of fasting." },
  { i: 1715, base: 241, variant: "exception", c: 4, q: "Which of these is NOT true about Eid al-Fitr?", o: ["It marks the start of Ramadan", "It marks the end of Ramadan", "It is a Muslim festival", "Muslims give thanks for completing the fast"], a: [0], e: "Eid al-Fitr marks the END of Ramadan, celebrating its completion — not the start." },

  // ---- base i:242 — Lord's cricket ground: cricket ----
  { i: 1716, base: 242, variant: "rephrase", c: 4, q: "Which sport is played at Lord's cricket ground?", o: ["Cricket", "Rugby", "Tennis", "Football"], a: [0], e: "Lord's in London is one of the most famous cricket grounds in the world." },
  { i: 1717, base: 242, variant: "truefalse", c: 4, q: "Is this statement TRUE or FALSE? Cricket is played at Lord's in London.", o: ["True", "False"], a: [0], e: "Lord's in London is one of the most famous cricket grounds in the world." },
  { i: 1718, base: 242, variant: "scenario", c: 4, q: "A friend asks which sport is played at the famous London ground called Lord's. Which sport is it?", o: ["Cricket", "Rugby", "Tennis", "Football"], a: [0], e: "Lord's in London is one of the most famous cricket grounds in the world." },
  { i: 1719, base: 242, variant: "exception", c: 4, q: "Which of these is NOT true about Lord's?", o: ["It is a famous tennis venue", "It is a famous cricket ground", "It is located in London", "It is one of the most famous grounds of its sport in the world"], a: [0], e: "Lord's is a famous cricket ground, not a tennis venue — Wimbledon is London's famous tennis venue instead." },

  // ---- base i:243 — the Six Nations Championship: rugby ----
  { i: 1720, base: 243, variant: "rephrase", c: 4, q: "Which UK-wide competition do the national rugby union teams take part in?", o: ["The Six Nations Championship", "The Ashes", "The Ryder Cup", "The Grand National"], a: [0], e: "England, Scotland, Wales and Ireland play France and Italy each year." },
  { i: 1721, base: 243, variant: "truefalse", c: 4, q: "Is this statement TRUE or FALSE? The UK's national rugby union teams take part in the Six Nations Championship.", o: ["True", "False"], a: [0], e: "England, Scotland, Wales and Ireland play France and Italy each year." },
  { i: 1722, base: 243, variant: "scenario", c: 4, q: "A friend asks which annual competition sees England, Scotland, Wales and Ireland play France and Italy at rugby. What is it called?", o: ["The Six Nations Championship", "The Ashes", "The Ryder Cup", "The World Cup"], a: [0], e: "The Six Nations Championship sees England, Scotland, Wales and Ireland play France and Italy each year at rugby union." },
  { i: 1723, base: 243, variant: "exception", c: 4, q: "Which of these is NOT true about the Six Nations Championship?", o: ["It is a cricket competition", "It involves England, Scotland, Wales and Ireland", "It also involves France and Italy", "It is played annually"], a: [0], e: "The Six Nations Championship is a rugby union competition, not cricket — the Ashes is the famous cricket competition." },

  // ---- base i:244 — Ian Botham: cricket ----
  { i: 1724, base: 244, variant: "rephrase", c: 4, q: "Sir Ian Botham was famous in which sport?", o: ["Cricket", "Football", "Rowing", "Motor racing"], a: [0], e: "Botham held the England record for the number of wickets taken in test cricket." },
  { i: 1725, base: 244, variant: "truefalse", c: 4, q: "Is this statement TRUE or FALSE? Sir Ian Botham was famous as a cricketer.", o: ["True", "False"], a: [0], e: "Botham held the England record for the number of wickets taken in test cricket." },
  { i: 1726, base: 244, variant: "scenario", c: 4, q: "A friend asks which sport Sir Ian Botham, who held England's test wicket-taking record, is famous for. Which sport is it?", o: ["Cricket", "Football", "Rowing", "Motor racing"], a: [0], e: "Botham held the England record for the number of wickets taken in test cricket." },
  { i: 1727, base: 244, variant: "exception", c: 4, q: "Which of these is NOT true about Sir Ian Botham?", o: ["He was a champion rower", "He was a famous cricketer", "He held England's test wicket-taking record", "His achievements were in cricket"], a: [0], e: "Ian Botham is famous as a cricketer. Rowing golds were the achievement of a different sportsman, Sir Steve Redgrave." },

  // ---- base i:245 — Jackie Stewart: three-time F1 world champion ----
  { i: 1728, base: 245, variant: "rephrase", c: 4, q: "Which motor racing driver won the Formula 1 world championship three times in the 1960s and 70s?", o: ["Sir Jackie Stewart", "Damon Hill", "Lewis Hamilton", "Stirling Moss"], a: [0], e: "The Scottish driver Jackie Stewart won three world championships." },
  { i: 1729, base: 245, variant: "truefalse", c: 4, q: "Is this statement TRUE or FALSE? Sir Jackie Stewart won the Formula 1 world championship three times.", o: ["True", "False"], a: [0], e: "The Scottish driver Jackie Stewart won three world championships." },
  { i: 1730, base: 245, variant: "scenario", c: 4, q: "A friend asks which Scottish driver won three Formula 1 world championships in the 1960s and 70s. Who was it?", o: ["Sir Jackie Stewart", "Damon Hill", "Lewis Hamilton", "Nigel Mansell"], a: [0], e: "The Scottish driver Jackie Stewart won three Formula 1 world championships." },
  { i: 1731, base: 245, variant: "exception", c: 4, q: "Which of these is NOT true about Sir Jackie Stewart?", o: ["He is English", "He is Scottish", "He won three Formula 1 world championships", "His titles came in the 1960s and 70s"], a: [0], e: "Jackie Stewart is Scottish, not English." },

  // ---- base i:246 — what is a 'bank holiday' ----
  { i: 1732, base: 246, variant: "rephrase", c: 4, q: "What is a 'bank holiday'?", o: ["A public holiday when most businesses close", "A day when banks charge no fees", "A day when only banks close", "A religious festival"], a: [0], e: "Bank holidays include Christmas Day, Boxing Day, New Year's Day and Easter Monday." },
  { i: 1733, base: 246, variant: "truefalse", c: 4, q: "Is this statement TRUE or FALSE? A bank holiday is a public holiday when most businesses close.", o: ["True", "False"], a: [0], e: "Bank holidays include Christmas Day, Boxing Day, New Year's Day and Easter Monday." },
  { i: 1734, base: 246, variant: "scenario", c: 4, q: "A friend new to the UK asks what a 'bank holiday' actually means, since Christmas Day and Easter Monday are both examples. What is the correct definition?", o: ["A public holiday when most businesses close", "A day when only banks close but shops stay open", "A day when banks charge no fees", "A religious festival only"], a: [0], e: "A bank holiday is a public holiday when most businesses close, including Christmas Day, Boxing Day, New Year's Day and Easter Monday." },
  { i: 1735, base: 246, variant: "exception", c: 4, q: "Which of these is NOT true about a UK bank holiday?", o: ["Only banks are affected, while all other businesses stay open as normal", "Most businesses close", "Christmas Day is one example", "Easter Monday is one example"], a: [0], e: "A bank holiday affects most businesses, not just banks — it is a general public holiday." },
];
