/* ============================================================
   QUESTION VARIANTS — Chapter 5b (Government and law: Hansard
   through the age of criminal responsibility, base i:152-164). See
   chapter1.js for format notes.
   ============================================================ */

export default [
  // ---- base i:152 — Hansard: the record of parliamentary debates ----
  { i: 1824, base: 152, variant: "rephrase", c: 5, q: "What is the record of debates in Parliament called?", o: ["Hansard", "The Domesday Book", "The Gazette", "The Register"], a: [0], e: "Hansard is published daily and is available in large libraries and online." },
  { i: 1825, base: 152, variant: "truefalse", c: 5, q: "Is this statement TRUE or FALSE? The official record of debates in Parliament is called Hansard.", o: ["True", "False"], a: [0], e: "Hansard is published daily and is available in large libraries and online." },
  { i: 1826, base: 152, variant: "scenario", c: 5, q: "A friend wants to read exactly what was said in a Parliamentary debate. Which publication should they look at?", o: ["Hansard", "The Domesday Book", "The Gazette", "The Register"], a: [0], e: "Hansard is the official record of debates in Parliament, published daily and available in large libraries and online." },
  { i: 1827, base: 152, variant: "exception", c: 5, q: "Which of these is NOT true about Hansard?", o: ["It records medieval land ownership", "It records parliamentary debates", "It is published daily", "It is available online"], a: [0], e: "Hansard records parliamentary debates — recording medieval land ownership was the purpose of the much older Domesday Book instead." },

  // ---- base i:153 — the monarch is politically neutral ----
  { i: 1828, base: 153, variant: "rephrase", c: 5, q: "Which of these statements about the monarch is correct?", o: ["The monarch is politically neutral and does not take sides in politics", "The monarch chooses which laws Parliament passes", "The monarch appoints all MPs", "The monarch leads the largest political party"], a: [0], e: "The monarch is head of state but remains above party politics, meeting the Prime Minister regularly to advise and warn." },
  { i: 1829, base: 153, variant: "truefalse", c: 5, q: "Is this statement TRUE or FALSE? The monarch is politically neutral and does not take sides in politics.", o: ["True", "False"], a: [0], e: "The monarch is head of state but remains above party politics, meeting the Prime Minister regularly to advise and warn." },
  { i: 1830, base: 153, variant: "scenario", c: 5, q: "A friend asks whether the monarch is allowed to publicly support one political party over another. What is the answer?", o: ["No — the monarch is politically neutral", "Yes — the monarch leads the largest party", "Yes, but only in private", "No — but the monarch chooses which laws pass"], a: [0], e: "The monarch is politically neutral and remains above party politics, meeting the Prime Minister regularly to advise and warn." },
  { i: 1831, base: 153, variant: "exception", c: 5, q: "Which of these is NOT true about the monarch's role?", o: ["The monarch personally decides which laws are passed", "The monarch is politically neutral", "The monarch meets the Prime Minister regularly", "The monarch can advise and warn the government"], a: [0], e: "The monarch does not personally decide which laws are passed — that is Parliament's role. The monarch stays politically neutral." },

  // ---- base i:154 — the State Opening of Parliament ----
  { i: 1832, base: 154, variant: "rephrase", c: 5, q: "What happens at the State Opening of Parliament each year?", o: ["The monarch reads a speech setting out the government's policies", "MPs elect a new Speaker", "The Budget is announced", "New peers are created"], a: [0], e: "The monarch's speech is written by the government and outlines its plans for the coming year." },
  { i: 1833, base: 154, variant: "truefalse", c: 5, q: "Is this statement TRUE or FALSE? At the State Opening of Parliament, the monarch reads a speech setting out government policy.", o: ["True", "False"], a: [0], e: "The monarch's speech is written by the government and outlines its plans for the coming year." },
  { i: 1834, base: 154, variant: "scenario", c: 5, q: "A friend asks what happens each year when the monarch formally opens a new session of Parliament. What takes place?", o: ["The monarch reads a speech, written by the government, setting out its plans", "MPs elect a new Speaker", "The Budget is announced", "New peers are appointed"], a: [0], e: "At the State Opening of Parliament, the monarch reads a speech, written by the government, setting out its plans for the coming year." },
  { i: 1835, base: 154, variant: "exception", c: 5, q: "Which of these is NOT true about the speech the monarch reads at the State Opening of Parliament?", o: ["The monarch writes it personally", "The government writes it", "It sets out government policy for the year ahead", "It is delivered at the State Opening"], a: [0], e: "The speech the monarch reads at the State Opening is written by the government, not by the monarch personally." },

  // ---- base i:155 — the voting age: 18 ----
  { i: 1836, base: 155, variant: "rephrase", c: 5, q: "At what age can you vote in a UK general election?", o: ["18", "16", "21", "17"], a: [0], e: "You must be 18 or over and on the electoral register to vote in a general election." },
  { i: 1837, base: 155, variant: "truefalse", c: 5, q: "Is this statement TRUE or FALSE? You must be 18 to vote in a UK general election.", o: ["True", "False"], a: [0], e: "You must be 18 or over and on the electoral register to vote in a general election." },
  { i: 1838, base: 155, variant: "scenario", c: 5, q: "A friend turning 17 asks if they can vote in the next general election. What do you tell them?", o: ["No — they must wait until they turn 18", "Yes — 17 is the voting age", "Yes, but only in local elections", "No — the voting age is 21"], a: [0], e: "You must be 18 or over and on the electoral register to vote in a general election." },
  { i: 1839, base: 155, variant: "exception", c: 5, q: "Which of these is NOT the correct minimum voting age for a UK general election?", o: ["21", "18", "The same age as buying alcohol", "The same age as buying a National Lottery ticket"], a: [0], e: "The minimum voting age for a UK general election is 18, the same as buying alcohol or a lottery ticket — not 21." },

  // ---- base i:156 — polling stations open 7am to 10pm ----
  { i: 1840, base: 156, variant: "rephrase", c: 5, q: "On election day, polling stations are open from when to when?", o: ["7am to 10pm", "9am to 5pm", "8am to 8pm", "6am to midnight"], a: [0], e: "Polling stations open at 7am and close at 10pm." },
  { i: 1841, base: 156, variant: "truefalse", c: 5, q: "Is this statement TRUE or FALSE? UK polling stations are open from 7am to 10pm on election day.", o: ["True", "False"], a: [0], e: "Polling stations open at 7am and close at 10pm." },
  { i: 1842, base: 156, variant: "scenario", c: 5, q: "A friend planning to vote after work asks until what time polling stations stay open on election day. What time is that?", o: ["10pm", "5pm", "8pm", "Midnight"], a: [0], e: "Polling stations open at 7am and close at 10pm on election day." },
  { i: 1843, base: 156, variant: "exception", c: 5, q: "Which of these is NOT true about UK polling station opening hours?", o: ["They close at 5pm", "They open at 7am", "They close at 10pm", "They are open for 15 hours on election day"], a: [0], e: "Polling stations close at 10pm, not 5pm — they are open from 7am to 10pm, a 15-hour window." },

  // ---- base i:157 — the Commonwealth: 54 member states ----
  { i: 1844, base: 157, variant: "rephrase", c: 5, q: "How many member states does the Commonwealth have?", o: ["54", "27", "15", "100"], a: [0], e: "The Commonwealth is a voluntary association of 54 countries; the monarch is its head, and it has no power over members." },
  { i: 1845, base: 157, variant: "truefalse", c: 5, q: "Is this statement TRUE or FALSE? The Commonwealth has 54 member states.", o: ["True", "False"], a: [0], e: "The Commonwealth is a voluntary association of 54 countries; the monarch is its head, and it has no power over members." },
  { i: 1846, base: 157, variant: "scenario", c: 5, q: "A friend asks how many countries belong to the voluntary association headed by the monarch, called the Commonwealth. How many is that?", o: ["54", "27", "15", "100"], a: [0], e: "The Commonwealth is a voluntary association of 54 countries; the monarch is its head, and it has no power over members." },
  { i: 1847, base: 157, variant: "exception", c: 5, q: "Which of these is NOT true about the Commonwealth?", o: ["The monarch has direct power to make decisions for all its members", "It has 54 member states", "The monarch is its head", "Membership is voluntary"], a: [0], e: "The monarch is head of the Commonwealth but has no power over its members — membership and cooperation are voluntary." },

  // ---- base i:158 — the UN Security Council: five permanent members ----
  { i: 1848, base: 158, variant: "rephrase", c: 5, q: "The UK is one of how many permanent members of the UN Security Council?", o: ["Five", "Three", "Ten", "Fifteen"], a: [0], e: "The UK is one of five permanent members and can veto proposals." },
  { i: 1849, base: 158, variant: "truefalse", c: 5, q: "Is this statement TRUE or FALSE? The UK is one of five permanent members of the UN Security Council.", o: ["True", "False"], a: [0], e: "The UK is one of five permanent members and can veto proposals." },
  { i: 1850, base: 158, variant: "scenario", c: 5, q: "A friend asks how many permanent, veto-holding members the UN Security Council has, the UK among them. How many is that?", o: ["Five", "Three", "Ten", "Fifteen"], a: [0], e: "The UK is one of five permanent members of the UN Security Council and can veto proposals." },
  { i: 1851, base: 158, variant: "exception", c: 5, q: "Which of these is NOT true about the UK's position on the UN Security Council?", o: ["The UK is only a temporary, rotating member", "The UK is a permanent member", "The UK can veto proposals", "There are five permanent members in total"], a: [0], e: "The UK is a permanent member of the UN Security Council, not a temporary rotating one, and can veto proposals." },

  // ---- base i:159 — NATO: collective defence ----
  { i: 1852, base: 159, variant: "rephrase", c: 5, q: "What is the main purpose of NATO?", o: ["To provide collective defence for member countries", "To set trade rules", "To manage the euro", "To protect human rights in Europe"], a: [0], e: "NATO members agree to help each other if they come under attack." },
  { i: 1853, base: 159, variant: "truefalse", c: 5, q: "Is this statement TRUE or FALSE? NATO's main purpose is to provide collective defence for its member countries.", o: ["True", "False"], a: [0], e: "NATO members agree to help each other if they come under attack." },
  { i: 1854, base: 159, variant: "scenario", c: 5, q: "A friend asks what NATO members commit to doing if one of them comes under attack. What is the answer?", o: ["Helping each other, as part of collective defence", "Setting joint trade rules", "Managing a shared currency", "Nothing — NATO has no defence role"], a: [0], e: "NATO's main purpose is collective defence — members agree to help each other if they come under attack." },
  { i: 1855, base: 159, variant: "exception", c: 5, q: "Which of these is NOT true about NATO?", o: ["It manages a shared European currency", "It provides collective defence", "Members agree to help each other if attacked", "The UK is a member"], a: [0], e: "NATO provides collective defence, not currency management — the euro is managed separately by the European Central Bank, unconnected to NATO." },

  // ---- base i:160 — the Council of Europe: human rights ----
  { i: 1856, base: 160, variant: "rephrase", c: 5, q: "What does the Council of Europe do?", o: ["Protects human rights in member countries", "Sets the EU budget", "Commands European armed forces", "Issues passports"], a: [0], e: "The Council of Europe is responsible for the European Convention on Human Rights and has no law-making power." },
  { i: 1857, base: 160, variant: "truefalse", c: 5, q: "Is this statement TRUE or FALSE? The Council of Europe protects human rights in its member countries.", o: ["True", "False"], a: [0], e: "The Council of Europe is responsible for the European Convention on Human Rights and has no law-making power." },
  { i: 1858, base: 160, variant: "scenario", c: 5, q: "A friend asks what organisation is responsible for the European Convention on Human Rights, with no law-making power of its own. What is it called?", o: ["The Council of Europe", "NATO", "The Commonwealth", "The United Nations"], a: [0], e: "The Council of Europe is responsible for the European Convention on Human Rights and has no law-making power." },
  { i: 1859, base: 160, variant: "exception", c: 5, q: "Which of these is NOT true about the Council of Europe?", o: ["It has the power to pass binding laws for its members", "It protects human rights", "It oversees the European Convention on Human Rights", "It has no law-making power"], a: [0], e: "The Council of Europe explicitly has no law-making power — it protects human rights through the European Convention on Human Rights." },

  // ---- base i:161 — the Magistrates' Court: minor criminal offences ----
  { i: 1860, base: 161, variant: "rephrase", c: 5, q: "Which court deals with minor criminal offences in England and Wales?", o: ["The Magistrates' Court", "The Crown Court", "The County Court", "The High Court"], a: [0], e: "Magistrates, also called Justices of the Peace, are unpaid volunteers who hear minor cases without a jury." },
  { i: 1861, base: 161, variant: "truefalse", c: 5, q: "Is this statement TRUE or FALSE? The Magistrates' Court deals with minor criminal offences in England and Wales.", o: ["True", "False"], a: [0], e: "Magistrates, also called Justices of the Peace, are unpaid volunteers who hear minor cases without a jury." },
  { i: 1862, base: 161, variant: "scenario", c: 5, q: "A friend asks which court, staffed by unpaid volunteers hearing cases without a jury, handles minor criminal offences in England and Wales. Which court is it?", o: ["The Magistrates' Court", "The Crown Court", "The County Court", "The High Court"], a: [0], e: "The Magistrates' Court deals with minor criminal offences in England and Wales; magistrates are unpaid volunteers who hear cases without a jury." },
  { i: 1863, base: 161, variant: "exception", c: 5, q: "Which of these is NOT true about the Magistrates' Court?", o: ["Cases there are always heard by a jury", "It deals with minor criminal offences", "Magistrates are unpaid volunteers", "It operates in England and Wales"], a: [0], e: "Magistrates' Court cases are heard by magistrates alone, without a jury — juries are used in the Crown Court instead." },

  // ---- base i:162 — Scotland: minor offences in the Justice of the Peace Court ----
  { i: 1864, base: 162, variant: "rephrase", c: 5, q: "In Scotland, minor criminal offences are usually heard in which court?", o: ["The Justice of the Peace Court", "The Magistrates' Court", "The County Court", "The Crown Court"], a: [0], e: "Scotland has its own legal system, with Justice of the Peace Courts and Sheriff Courts." },
  { i: 1865, base: 162, variant: "truefalse", c: 5, q: "Is this statement TRUE or FALSE? Minor criminal offences in Scotland are usually heard in the Justice of the Peace Court.", o: ["True", "False"], a: [0], e: "Scotland has its own legal system, with Justice of the Peace Courts and Sheriff Courts." },
  { i: 1866, base: 162, variant: "scenario", c: 5, q: "A friend asks which Scottish court usually hears minor criminal cases, given Scotland's separate legal system. Which court is it?", o: ["The Justice of the Peace Court", "The Magistrates' Court", "The County Court", "The Crown Court"], a: [0], e: "Scotland has its own legal system; minor criminal offences are usually heard in the Justice of the Peace Court." },
  { i: 1867, base: 162, variant: "exception", c: 5, q: "Which of these is NOT true about minor criminal cases in Scotland?", o: ["They are heard in the Magistrates' Court, as in England and Wales", "They are usually heard in the Justice of the Peace Court", "Scotland has its own separate legal system", "Sheriff Courts are also part of the Scottish system"], a: [0], e: "Scotland does not use Magistrates' Courts — that is the English and Welsh system. Scotland instead uses Justice of the Peace Courts and Sheriff Courts." },

  // ---- base i:163 — Crown Court juries: 12 members ----
  { i: 1868, base: 163, variant: "rephrase", c: 5, q: "How many people sit on a jury in a Crown Court in England, Wales and Northern Ireland?", o: ["12", "15", "10", "8"], a: [0], e: "Juries have 12 members in England, Wales and Northern Ireland, and 15 in Scotland." },
  { i: 1869, base: 163, variant: "truefalse", c: 5, q: "Is this statement TRUE or FALSE? A Crown Court jury in England has 12 members.", o: ["True", "False"], a: [0], e: "Juries have 12 members in England, Wales and Northern Ireland, and 15 in Scotland." },
  { i: 1870, base: 163, variant: "scenario", c: 5, q: "A friend asks how many jurors sit on a Crown Court case in England, Wales or Northern Ireland. How many is that?", o: ["12", "15", "10", "8"], a: [0], e: "Juries have 12 members in England, Wales and Northern Ireland, and 15 in Scotland." },
  { i: 1871, base: 163, variant: "exception", c: 5, q: "Which of these is NOT true about jury sizes in the UK?", o: ["Scottish juries have 12 members, the same as England", "English Crown Court juries have 12 members", "Scottish juries have 15 members", "Jury size differs between Scotland and the rest of the UK"], a: [0], e: "Scottish juries have 15 members, not 12 — a larger jury than in England, Wales and Northern Ireland." },

  // ---- base i:164 — age of criminal responsibility: 10 in England, Wales and NI ----
  { i: 1872, base: 164, variant: "rephrase", c: 5, q: "What is the age of criminal responsibility in England, Wales and Northern Ireland?", o: ["10", "12", "16", "18"], a: [0], e: "It is 10 in England, Wales and Northern Ireland, and 12 in Scotland." },
  { i: 1873, base: 164, variant: "truefalse", c: 5, q: "Is this statement TRUE or FALSE? The age of criminal responsibility in England, Wales and Northern Ireland is 10.", o: ["True", "False"], a: [0], e: "It is 10 in England, Wales and Northern Ireland, and 12 in Scotland." },
  { i: 1874, base: 164, variant: "scenario", c: 5, q: "A friend asks at what age a child becomes criminally responsible in England, Wales or Northern Ireland. What age is it?", o: ["10", "12", "16", "18"], a: [0], e: "The age of criminal responsibility is 10 in England, Wales and Northern Ireland, and 12 in Scotland." },
  { i: 1875, base: 164, variant: "exception", c: 5, q: "Which of these is NOT true about the age of criminal responsibility in the UK?", o: ["It is the same across every part of the UK", "It is 10 in England, Wales and Northern Ireland", "It is 12 in Scotland", "It differs between Scotland and the rest of the UK"], a: [0], e: "The age of criminal responsibility differs across the UK — 10 in England, Wales and Northern Ireland, but 12 in Scotland." },
];
